### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by azizLIGHT** [kozec/sc-controller#10]
sc-controller is crashing on start after I updated to 0.1.4 from the repo on Ubuntu 14.04.

```
aziz@LIGHT:~$ sc-controller 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scc/gui/app.py", line 493, in do_startup
    self.setup_widgets()
  File "/usr/lib/python2.7/dist-packages/scc/gui/app.py", line 70, in setup_widgets
    self.builder.add_from_file(os.path.join(self.gladepath, "app.glade"))
gi._glib.GError: /usr/share/scc/app.glade:714:1 <object> requires attribute "id"
aziz@LIGHT:~$ 
```

**Comment by kozec** [comment]
Hmm... My best guess is that Ubuntu had some custom version of GTK in 14.04, because there is no reason for having ID on that required :D

Downloading ISO for 14.04...

**Comment by kozec** [comment]
Ok, I've tested release 0.1.5 on Ubuntu 14.04 and seems to work.

![capture_1461876604](https://cloud.githubusercontent.com/assets/1282500/14901027/ab35d214-0d93-11e6-81a0-d8147d48bf90.png)

**Comment by azizLIGHT** [comment]
Thanks. Confirmed working for me too
