### ISSUE TITLE
Left Stick Controls Cursor

### ISSUE THREAD

**Issue by Suros** [kozec/sc-controller#100]
Title says it all. Anytime I have something mapped to "Left Stick" it moves the mouse/cursor around the screen in a very large oval matching the stick's position. Can't seem to make it stop no matter what I do. Can provide info upon request.

**Comment by kozec** [comment]
Let me guess, you are using ubuntu :)

Try this: https://github.com/kozec/sc-controller/issues/97#issuecomment-252406299

**Comment by Suros** [comment]
Using Antergos actually. (Yeah, I was lazy, don't judge.) The provided fix was exactly what it needed. Thank you much!
