### ISSUE TITLE
Problem with gyro. (inverting y axis) 

### ISSUE THREAD

**Issue by MeDeVILe** [kozec/sc-controller#101]
I am trying to use gyro as mouse with touching right touch pad and inverting y axis doesn't work. Every time I use gyro moving controller down make cursor to go up the screen. It doesn't matter if y axis is inverted or not every time it's working the same way. Is it a bug or do I have to setup something else?

**Comment by kozec** [comment]
Ah, yeah, I can see that sensitivity setting is getting lost when Gyro enable button is used.

As temporal fix, you can paste this to Custom Action:
`mode(RPADTOUCH, sens(1.0, -1.0, mouse(ROLL)), None)`

**Comment by MeDeVILe** [comment]
yes it is a problem solver
