### ISSUE TITLE
[question] Is there a way to set double tap on right touch pad as left mouse button? 

### ISSUE THREAD

**Issue by MeDeVILe** [kozec/sc-controller#102]
Just like it is in touch pad on laptops.

**Comment by kozec** [comment]
Yes, but it's currently not configurable from GUI.

You can edit profile with text editor and add to "buttons" part:

```
    "buttons": {
        "RPADTOUCH": {
            "doubleclick": {
                "action": "button(Keys.BTN_LEFT)"
            }, 
            "time": 0.5
        },
        "A": {
```

But I've never tested this, so I'm not 100% sure how well will it work :)

**Comment by MeDeVILe** [comment]
after adding this to profile sc-conmtroller is keeping to switch to other profile. So it`s not working.

**Comment by kozec** [comment]
Switching to other profile? Maybe you made syntax error there, try pasting entire thing to http://jsonlint.com/ or something similar.

**Comment by MeDeVILe** [comment]
Yeah. I made some mistake. It's working good. Thank you. Valve should pay you. It's working better than with steam big picture :)

**Comment by kozec** [comment]
I'm not 100% sure if they even remember Linux exists anymore :P
