### ISSUE TITLE
Failed to claim USB Device error...

### ISSUE THREAD

**Issue by joekm** [kozec/sc-controller#103]
Tried running .303 today to control my Pandora account while working from home.  After a few minutes the steam controller will time out.  When I was running version .27, I simply restarted the controller and hit the "A" button and I would have control again.  It hasn't been working since that version.  If I walk over to the computer and disable and re-enable the interface (upper left button on your gui), it comes back to life until the steam controller times out again.

Tried running "scc-daemon debug" after last hang and got the following:
D OSD DaemonCtrlr   Connection to daemon lost
E OSD osd.daemon    Connection to daemon lost
debian@pine64:~/sc-controller-0.3.0.3$ scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f847cef10>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f8475fb10>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f84773450>
D SCCDaemon     Created control socket /home/debian/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0.0
E USB           Failed to claim USB device: 28de:1142
E USB           Failed to claim USB device: 28de:1142
D OSD DaemonCtrlr   Connected to daemon, version 0.3
D OSD DaemonCtrlr   Daemon reported profile change: /home/debian/.config/scc/profiles/Desktop.sccprofile
D OSD DaemonCtrlr   Daemon reported error 'Failed to claim USB device: LIBUSB_ERROR_BUSY [-6]'
E USB           Failed to claim USB device: 28de:1142
E USB           Failed to claim USB device: 28de:1142
E USB           Failed to claim USB device: 28de:1142
^^^^ and the last message just periodically repeats ^^^

**Comment by joekm** [comment]
I was just talking about restarting the controller itself after it
"sleeps".  Was a non-issue with ver .27 but has hung since then.  I tried
to capture the terminal screen where it said something like "usb lost".
When I try to restart the controller (by pushing the steam button in the
middle).  It's light won't even come on.  I wind up having to go into your
gui and disable then re-enable it to get it to work again.  So far, it's
100% repeatable behavior.

**Comment by kozec** [comment]
> I triedto capture the terminal screen where it said something like "usb lost".

Getting that exact message may be necessary, because I'm not really sure what are you doing there. How can you even _restart_ Steam Controller?

**Comment by joekm** [comment]
Sorry about the delay getting back.  I've taken a video of the issue so you
can see exactly what I'm doing.  It's two video capture before and after
the  controller goes to sleep.  Would it be OK if I sent them to you?

**Comment by kozec** [comment]
Yeah, no problem.

**Comment by joekm** [comment]
Too big to attach apparently, hopefully you can access the link below:

https://www.dropbox.com/sh/vo3ep4r4jgrmb6n/AAAhDan1BvUqcqJYdhM4lOisa?dl=0

**Comment by kozec** [comment]
Yep, I get what's problem is now. It looks like daemon hangs pretty deep in IO when controller enters sleep mode by itself. I set timeout to lowest possible and now I'm waiting for stuff to die :D

**Comment by kozec** [comment]
Except that's not what's happening here :(

Two more questions:
1. What distro and architecture are you using?
2. Is there any chance that entire machine enters sleep mode, or does anything that could somehow affect USBs?

**Comment by joekm** [comment]
This is PINE 64 SBC with an  ARM 64 bit quad-core (Allwinner BIOS from what
I understand).  Most of the time I use this I'm accessing my Pandora
account while working from home.  So, it goes into screensaver but Pandora
continues to play.  Therefore, I'm thinking it's not going into a "sleep
mode".

The Distro is Debian 8 ("Jessie" I believe) running  the MATE desktop.

**Comment by joekm** [comment]
Actually, that I think of it, my keyboard and mouse are USB and either of
them can wake the computer back up so I'm inclined to say that nothing is
impacting the  USB ports.

**Comment by kozec** [comment]
Ok, so this may be rather hard to reproduce :D

Could you try running daemon in terminal? Disable emulation, close GUI and start `scc-daemon debug` as you already did, just so it displays all output from point when everything works up to the point when it dies.

If you don't feel like waiting, you can edit `scc/drivers/sc_dongle.py`, search for line with `self._idle_timeout = 600` and change it to 10 or even lower.

**Comment by joekm** [comment]
My apologies for taking so long to get back.  Between work ramping up and contractors remodeling my bathroom my down-time has been a bit impacted.  In any event here is the scc-daemon debug output after disabling the controller and closing the GUI.

D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f8fc53f10>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f8fbe4b10>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f8fbf8450>
D SCCDaemon     Created control socket /home/debian/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
D USB           USB device added: 28de:1142
D OSD DaemonCtrlr   Connected to daemon, version 0.3
D OSD DaemonCtrlr   Daemon reported profile change: /home/debian/.config/scc/profiles/Desktop.sccprofile
D OSD DaemonCtrlr   Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon

**Comment by joekm** [comment]
Hold up....got more output as I was typing the above....

D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f8fc53f10>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f8fbe4b10>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f8fbf8450>
D SCCDaemon     Created control socket /home/debian/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
D USB           USB device added: 28de:1142
D OSD DaemonCtrlr   Connected to daemon, version 0.3
D OSD DaemonCtrlr   Daemon reported profile change: /home/debian/.config/scc/profiles/Desktop.sccprofile
D OSD DaemonCtrlr   Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
Traceback (most recent call last):
  File "/usr/local/bin/scc-daemon", line 35, in <module>
    main()
  File "/usr/local/bin/scc-daemon", line 31, in main
    daemon.debug()
  File "/usr/local/lib/python2.7/dist-packages/scc/sccdaemon.py", line 780, in debug
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scc/sccdaemon.py", line 471, in run
    fn()
  File "/usr/local/lib/python2.7/dist-packages/scc/drivers/usb.py", line 278, in mainloop
    d.flush()
  File "/usr/local/lib/python2.7/dist-packages/scc/drivers/usb.py", line 142, in flush
    self.handle.controlWrite(*msg)
  File "/usr/local/lib/python2.7/dist-packages/scc/lib/usb1.py", line 1331, in controlWrite
    sizeof(data), timeout)
  File "/usr/local/lib/python2.7/dist-packages/scc/lib/usb1.py", line 1310, in _controlTransfer
    mayRaiseUSBError(result)
  File "/usr/local/lib/python2.7/dist-packages/scc/lib/usb1.py", line 121, in mayRaiseUSBError
    raiseUSBError(value)
  File "/usr/local/lib/python2.7/dist-packages/scc/lib/usb1.py", line 117, in raiseUSBError
    raise STATUS_TO_EXCEPTION_DICT.get(value, USBError)(value)
scc.lib.usb1.USBErrorPipe: LIBUSB_ERROR_PIPE [-9]
D USB           Releasing devices...
D SCCDaemon     Controller removed: <SCWireless 1>
D OSD DaemonCtrlr   Connection to daemon lost
debian@pine64:~$ E OSD osd.daemon    Connection to daemon lost

**Comment by kozec** [comment]
Ok, this is getting interesting...

LIBUSB_ERROR_PIPE means either that USB device got disconnected (maybe even because connector has loose contact), or that SCC sent request that's not supported. If older version didn't had same problem, it's probably 2nd case.

I should be able to write workaround that will re-grab device automatically, but I'm wondering why would this happen at all. Would it be possible to connect your dongle to PC with Steam and check firmware revision displayed in big screen mode?

**Comment by stengun** [comment]
Can you please try this fix?
Try to move your udev rule for the controller before priority 73.
Doing this fixed a lot of issues for me, and for other users too. This happens because of a special udev rule of systemd that eats uaccess tag and ignores it.

**Comment by stengun** [comment]
ok this does not fix the double grab needed for scc-daemon when pairing a controller. Sorry about this unrelated argument. However, changing priority does make tag+="uaccess" useful (and in fact it should work as expected with mode 0660) inside the udev rule.

**Comment by joekm** [comment]
Steam controller firmware updated as soon as I plugged it into the PC so it's now the latest.  I tried ru-running it on the SBC and there was no change.  As for my configuration, I'm having trouble locating the file but the changes I made to the default setup were as follows:

1)  Track Pad is set to Mouse Wheel Circular

2) Default Left and Right Button actions are moved to the grip buttons (LEFTCNTRL, LEFTALT)

3) Added a simple volume control to the Left and Right Buttons (amixer set Master 5%- ; amixer set Master 5%+)

**Comment by joekm** [comment]
Ok, updating to latest firmware had no impact on the issue.

**Comment by joekm** [comment]
The controller asked my to update it's firmware as soon as I plugged it in
and started STEAM.  Let me try it with your driver now.....got it connected
to my SBC, I'll wait for it to time out and let you know if it works.

**Comment by cjdg** [comment]
Works wired, the onlything is there is any chance to pair it without steam? because if you wire the controller works great the only thing is when you use it wireless

**Comment by kozec** [comment]
> Works wired, the onlything is there is any chance to pair it without steam? because if you wire the controller works great the only thing is when you use it wireless

Not really right now, I'm still trying to figure out how pairing works. But pairing is done to dongle, not to PC, so you connect dongle to machine that can run Steam and pair controller there.

**Comment by joekm** [comment]
Just installed xinput (saw it mentioned on another thread) but no effect on this issue..

What if I purge this install completely, download your .deb package, and install it on my ARM system with dpkg --force-architecture?  Since it's all python, I don't think architecture matters and, this way, I know it's going onto my system exactly the way you intended it to.

Before doing that though, I'll look at the files that were supposed to be installed and see if they are there and in the locations you anticipated.

Do you think this would worth a try?

**Comment by kozec** [comment]
> Since it's all python, I don't think architecture matters and, this way, I know it's going onto my system exactly the way you intended it to.

There is one bit of compiled c code there, but you can use --force-architecture and then recompile that bit with `python2 setup.py build` on source.

Anyway, I'm most likely going to do another release today, so I can add that workaround we talked before. I'm not 100% sure that reconnecting to randomly breaking controller wold help, but it shouldn't break anything.

**Comment by kozec** [comment]
@joekm Sorry, but above plan didn't worked. It looks like controller will no longer talk to me after LIBUSB_ERROR_PIPE occurs, until entire thing is restarted. In such case, crashing is pretty appropriate.

But, I added option that should allow us to see at what message crash occurs. If you run scc-daemon as `SCC_DEBUG_USB_REQUESTS=1 scc-daemon debug`, it will output every message just before it is sent to controller. If you are able to determine which one is causing LIBUSB_ERROR_PIPE to occur, I can add some kind of config setting that would prevent SCC from sending it and deal with missing response.

**Comment by Nazrax** [comment]
I'm getting the same error as @joekm. Here's my output from `SCC_DEBUG_USB_REQUESTS=1 scc-daemon debug`.

I start with the controller off:
```
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7ff609cf2610>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7ff609d00690>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7ff609c8ebd0>
I profile       Converted XY(mouse(Rels.REL_HWHEEL, 1.0), mouse(Rels.REL_WHEEL, 1.0)) to feedback(LEFT, 4096, 16, ball(XY(mouse(Rels.REL_HWHEEL, 1.0), mouse(Rels.REL_WHEEL, 1.0))))
I profile       Converted button(Keys.BTN_RIGHT) to trigger(50, button(Keys.BTN_RIGHT))
I profile       Converted button(Keys.BTN_LEFT) to trigger(50, button(Keys.BTN_LEFT))
D SCCDaemon     Created control socket /home/aabraham/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
D USB           USB device added: 28de:1142
D OSD DaemonCtrlr   Connected to daemon, version 0.3.3
D OSD DaemonCtrlr   Daemon reported profile change: /tmp/sc-controller-0.3.3/default_profiles/Desktop.sccprofile
D OSD DaemonCtrlr   Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
```

I press the Steam button on the controller and immediately get:

```
D USB           controlWrite (33, 9, 768, 1, '\xae\x15\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
[<Keys.BTN_RIGHT: 273>]
(50, 254)
[<Keys.BTN_LEFT: 272>]
(50, 254)
Traceback (most recent call last):
  File "scripts/scc-daemon", line 35, in <module>
    main()
  File "scripts/scc-daemon", line 31, in main
    daemon.debug()
  File "/tmp/sc-controller-0.3.3/scc/sccdaemon.py", line 881, in debug
    self.run()
  File "/tmp/sc-controller-0.3.3/scc/sccdaemon.py", line 524, in run
    fn()
  File "/tmp/sc-controller-0.3.3/scc/drivers/usb.py", line 282, in mainloop
    d.flush()
  File "/tmp/sc-controller-0.3.3/scc/drivers/usb.py", line 146, in flush
    self.handle.controlWrite(*msg)
  File "/tmp/sc-controller-0.3.3/scc/lib/usb1.py", line 1331, in controlWrite
    sizeof(data), timeout)
  File "/tmp/sc-controller-0.3.3/scc/lib/usb1.py", line 1310, in _controlTransfer
    mayRaiseUSBError(result)
  File "/tmp/sc-controller-0.3.3/scc/lib/usb1.py", line 121, in mayRaiseUSBError
    raiseUSBError(value)
  File "/tmp/sc-controller-0.3.3/scc/lib/usb1.py", line 117, in raiseUSBError
    raise STATUS_TO_EXCEPTION_DICT.get(value, USBError)(value)
scc.lib.usb1.USBErrorPipe: LIBUSB_ERROR_PIPE [-9]
D USB           Releasing devices...
D SCCDaemon     Controller removed: <SCWireless 1>
D OSD DaemonCtrlr   Connection to daemon lost
E OSD osd.daemon    Connection to daemon lost
```
And I get dumped back to the prompt.

In order to get the controller working, I have to do a dance of running sc-controller, pressing the Steam button, and disabling/enabling emulation a bunch in different orders until it starts working. At points in the dance, I also get the message about the USB device being in use, but disabling/reenabling seems to take care of it.

This is Ubuntu 14.04, 64-bit.

**Comment by kozec** [comment]
Ok, so it crashes, because controller refuses to send its serial number (`0xae` message is `GET_SERIAL`)
I can simply add config value to disable querying for it and assume some placeholder instead, but I'm really wondering why it does that.

Is there anything unusual on your configuration? Do you have something like 3rd party dongle, one of first controllers ever released, signed by GabeN himself or anything interesting? :)

**Comment by Nazrax** [comment]
Nope, just got it last week, and I used it in BPM a couple of days ago.

**Comment by kozec** [comment]
Ok, this should work. Edit `~/.config/scc/config.json`, find or add `ignore_serials` value right between "gui" and "osd_colors" and set it to true. That way, Steam Controllers are going to be identified by order in which they are connected instead of serial number and that crashing part shouldn't occur.

**Comment by Nazrax** [comment]
It works, but something weird happened that I haven't been able to reproduce. It worked, then it stopped working. I killed all the processes and looked at config.json, and ignore_serials had been set to false! I set it back to true and fired everything back up, and I haven't been able to reproduce it. I'm pretty sure I put that line where you said to.

Also, does it matter that every time the controller reconnects it gets a new ID?

**Comment by kozec** [comment]
> Also, does it matter that every time the controller reconnects it gets a new ID?

It's kinda unavoidable, because there is no longer way to tell if it's same controller. But I'll try to make it so it at least recycles old IDs, so it will work as before if you have only one controller.

If ignore_serials got reset, you most likely had GUI or daemon running and one of them overwrote config. I forgot to say you have to turn off everything before editing config manually :)

**Comment by Jimi-James** [comment]
I'm in a similar boat to @Nazrax (including that error when I use scc-daemon debug, but without the "D USB controlWrite" line). I just got a Steam Controller, used Steam to pair it with its dongle and update its firmware, and got into using this program, first going wired. Now, I'm trying to go wireless, and have run into the same trouble with two differences:

1. I've gotten it working wirelessly before trying the ignore_serials option, and without putting the udev rule before priority 73 (which made no change to the behavior of anything), and I've gotten it down to a science. To get the controller connected to scc-daemon wirelessly, scc-daemon has to be started, then stopped, then started AGAIN--so, ran twice--to get the controller actually working. However, the light comes on as if it's properly connected whenever scc-daemon is running. It just only actually works roughly every other time. There have been some fringe cases in my testing where it worked the first time, or only worked after stopping and starting several times in a row, but it's MOSTLY every other time the daemon is run, starting with the second time since the controller connected to the dongle. The behavior is the same through the sc-controller GUI, with stopping and starting the "Emulation".

2. The ignore_serials option actually doesn't affect this behavior in any way.

On the bright side, I actually do technically have wireless working. It's just too finnicky to have in my automated script, because I have to manually stop and start the daemon a few times, which is a little annoying. Now, I need to figure out if it's possible to get wireless going while the controller is getting power from another USB source, so that I can do away with batteries and buy a rechargeable microUSB charger or something instead.

**Comment by kozec** [comment]
@Jimi-James can you, please, attach output with everything what `SCC_DEBUG_USB_REQUESTS=1 scc-daemon debug` writes before crash on your side?

> Now, I need to figure out if it's possible to get wireless going while the controller is getting power from another USB source, so that I can do away with batteries and buy a rechargeable microUSB charger or something instead.

I'm not sure if this is possible, mine just turns off wireless module when it is on USB.

**Comment by Jimi-James** [comment]
`$ SCC_DEBUG_USB_REQUESTS=1 scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7fb9fdc71750>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7fb9fdc807d0>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7fb9fdc8fcd0>
D SCCDaemon     Created control socket /home/jimi/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0.0

(scc-osd-daemon.py:28083): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(scc-osd-daemon.py:28083): Gtk-WARNING **: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(scc-osd-daemon.py:28083): Gtk-WARNING **: Theme parsing error: gtk.css:115:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(scc-osd-daemon.py:28083): Gtk-WARNING **: Theme parsing error: gtk.css:116:24: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(scc-osd-daemon.py:28083): Gtk-WARNING **: Theme parsing error: gtk.css:145:27: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(scc-osd-daemon.py:28083): Gtk-WARNING **: Theme parsing error: gtk.css:146:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(scc-osd-daemon.py:28083): Gtk-WARNING **: Theme parsing error: gtk.css:166:34: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(scc-osd-daemon.py:28083): Gtk-WARNING **: Theme parsing error: gtk.css:187:34: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.
D OSD DaemonCtrlr   Connected to daemon, version 0.3.3
D OSD DaemonCtrlr   Daemon reported profile change: /home/jimi/.config/scc/profiles/Overwatch.sccprofile
D OSD DaemonCtrlr   Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
D USB           USB device added: 28de:1142
D OSD DaemonCtrlr   Daemon is ready.
D USB           controlWrite (33, 9, 768, 1, '\xae\x15\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
Traceback (most recent call last):
  File "/usr/bin/scc-daemon", line 35, in <module>
    main()
  File "/usr/bin/scc-daemon", line 31, in main
    daemon.debug()
  File "/usr/lib/python2.7/site-packages/scc/sccdaemon.py", line 881, in debug
    self.run()
  File "/usr/lib/python2.7/site-packages/scc/sccdaemon.py", line 524, in run
    fn()
  File "/usr/lib/python2.7/site-packages/scc/drivers/usb.py", line 282, in mainloop
    d.flush()
  File "/usr/lib/python2.7/site-packages/scc/drivers/usb.py", line 146, in flush
    self.handle.controlWrite(*msg)
  File "/usr/lib/python2.7/site-packages/scc/lib/usb1.py", line 1331, in controlWrite
    sizeof(data), timeout)
  File "/usr/lib/python2.7/site-packages/scc/lib/usb1.py", line 1310, in _controlTransfer
    mayRaiseUSBError(result)
  File "/usr/lib/python2.7/site-packages/scc/lib/usb1.py", line 121, in mayRaiseUSBError
    raiseUSBError(value)
  File "/usr/lib/python2.7/site-packages/scc/lib/usb1.py", line 117, in raiseUSBError
    raise STATUS_TO_EXCEPTION_DICT.get(value, USBError)(value)
scc.lib.usb1.USBErrorPipe: LIBUSB_ERROR_PIPE [-9]
D USB           Releasing devices...
D SCCDaemon     Controller removed: <SCWireless 1>
jimi@Death-Tower:~$ D OSD DaemonCtrlr   Connection to daemon lost
E OSD osd.daemon    Connection to daemon lost`

**Comment by kozec** [comment]
Ok, that's same issue as above, controller disconnecting when serial number is requested. Are you using git version or some release?

If you are using git, close everything, make sure there is nothing named _scc-something_ in `ps` output. Then open ~/.config/scc/config.json in editor and find or add ignore_serials value right between "gui" and "osd_colors", and set it to true.

**Comment by Jimi-James** [comment]
I'm using the newest version on Arch Linux's AUR, which is 0.3.3. I downloaded the git version and set ignore_serials, but I couldn't figure out how to launch its version of scc-daemon in debug mode, so here's the output from running sc-controller:

```
$ SCC_DEBUG_USB_REQUESTS=1 ./run.sh

(sc-controller:13062): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :
prelight pseudo-class is deprecated. Use :hover instead.

(sc-controller:13062): Gtk-WARNING **: Theme parsing error: gtk.css:73:35: The :
prelight pseudo-class is deprecated. Use :hover instead.

(sc-controller:13062): Gtk-WARNING **: Theme parsing error: gtk.css:115:31: The 
:insensitive pseudo-class is deprecated. Use :disabled instead.

(sc-controller:13062): Gtk-WARNING **: Theme parsing error: gtk.css:116:24: The 
:insensitive pseudo-class is deprecated. Use :disabled instead.

(sc-controller:13062): Gtk-WARNING **: Theme parsing error: gtk.css:145:27: The 
:insensitive pseudo-class is deprecated. Use :disabled instead.

(sc-controller:13062): Gtk-WARNING **: Theme parsing error: gtk.css:146:29: The 
:insensitive pseudo-class is deprecated. Use :disabled instead.

(sc-controller:13062): Gtk-WARNING **: Theme parsing error: gtk.css:166:34: The 
:insensitive pseudo-class is deprecated. Use :disabled instead.

(sc-controller:13062): Gtk-WARNING **: Theme parsing error: gtk.css:187:34: The 
:inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(sc-controller:13062): Gtk-WARNING **: Failed to get the GNOME session proxy: Th
e name org.gnome.SessionManager is not owned
W UDataManager  enumerate_children_finish for /home/jimi/.config/scc/controller-
icons failed: g-io-error-quark: Error opening directory '/home/jimi/.config/scc/
controller-icons': No such file or directory (1)
W App           Daemon reported unknown profile: '/dev/null'; Overriding.
```

And it worked! I ran numerous tests, and whenever ignore_serials was set to true, it all just worked like a charm, whereas if it was missing or set to false, I had to stop and start the emulation to get it working like I said before.

**Comment by kozec** [comment]
>  I couldn't figure out how to launch its version of scc-daemon in debug mode, so here's the output from running sc-controller:

That reminds me I should probably make release with all those fixes :)

But I'm glad it worked in the end.

**Comment by joekm** [comment]
Since installing latest version, steam controller fails to function at all.  Steam logo blinks for a few seconds then the controller simply shuts down.

**Comment by kozec** [comment]
@joekm have you tried enabling that `ignore_serials` option? You can find it even in GUI, Global settings -> Advanced -> Use Serial Numbers to Identify Controllers (disable that one)

**Comment by joekm** [comment]
I did, in fact, it's disabled by default

Running the above command...

debian@pine64:~$ SCC_DEBUG_USB_REQUESTS=1 scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f8214f9d0>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f821616d0>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f8217d2d0>
D SCCDaemon     Created control socket /home/debian/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
E USB           Failed to claim USB device 28de:1142 : LIBUSB_ERROR_BUSY [-6]
E USB           Failed to claim USB device 28de:1142 : LIBUSB_ERROR_BUSY [-6]
D OSD DaemonCtrlr   Connected to daemon, version 0.3.3
D OSD DaemonCtrlr   Daemon reported profile change: /home/debian/.config/scc/profiles/Desktop.sccprofile
D OSD DaemonCtrlr   Daemon reported error 'Failed to claim USB device: LIBUSB_ERROR_BUSY [-6]'
E USB           Failed to claim USB device 28de:1142 : LIBUSB_ERROR_BUSY [-6]
E USB           Failed to claim USB device 28de:1142 : LIBUSB_ERROR_BUSY [-6]
(repeating the above last line)

**Comment by joekm** [comment]
Oddly, reverting to the previous install doesn't fix the problem.  Nor does deleting /home/debian/.config/scc and letting your software rebuild it.  Next step I would try would be to purge completely and reinstall.

**Comment by kozec** [comment]
> Oddly, reverting to the previous install doesn't fix the problem. Nor does deleting /home/debian/.config/scc and letting your software rebuild it. Next step I would try would be to purge completely and reinstall.


> E USB Failed to claim USB device 28de:1142 : LIBUSB_ERROR_BUSY [-6]

Also please make sure there is no old instance of scc-daemon running, because that's exactly what would happen if it were. `ps |grep scc` should show it.

Basically, what that output shows is that there were no communication with controller, because there is another program with exclusive lock on it.

**Comment by joekm** [comment]
Ok, the issue was not your software.  I recently picked up a Steam Link and the inability for the controller to pair with a PC after being paired with the link is a known issue.  In my case, simply holding down the A button while powering on fixed it.  There's a more complex fix out there involving the Razor drivers if that didn't work.  So, I'll give your latest version a proper test today :)

**Comment by kozec** [comment]
That's great to hear :)
