### ISSUE TITLE
Input doesn't carry over to X(?)

### ISSUE THREAD

**Issue by Freso** [kozec/sc-controller#104]
`sc-controller` registers my controller fine and it seems to take inputs and change profiles fine too (I get different haptic feedback on the right pad across the default "Desktop" profile and a profile I'm putting together myself), and putting `sc-controller` into "test mode" also shows all button presses and left/right pad touches. The OSD is also navigatable.

But the cursor isn't moving, right/left click isn't working, and entering into a text editor, I can't use "WSAD" to enter W's, A's, S's, or D's. In all, the controller seems perfectly responsive within `sc-controller`(/`scc-daemon`), but doesn't seem to do anything outside of the program.

I've tried using `sc-controller 0.3.0.3-1` and `sc-controller-git v0.3.0.3.r6.ca986b7-1` (from AUR) both, with the same results.

Console output from one of the runs: https://gist.github.com/Freso/4b42a810ec97cd672bc405be1ac5e8b5

```
freso@koume ~> uname -a
Linux koume 4.7.6-1-ARCH #1 SMP PREEMPT Fri Sep 30 19:28:42 CEST 2016 x86_64 GNU/Linux
freso@koume ~> python2 --version
Python 2.7.12
```

**Comment by kozec** [comment]
Try disabling emulation from menu, close everything, running `sudo modprobe uinput` and then try running it again. It may be also worth to check `ls -l /dev/uinput` to see if you have access to uinput at all, but only after calling that modprobe.

**Comment by Freso** [comment]
Access might well be it.
```
freso@koume ~> ls -l /dev/uinput 
crw-------+ 1 root root 10, 223 14 okt 11:41 /dev/uinput
```

I have this in `/usr/lib/udev/rules.d/90-sc-controller.rules`:
```sh
# This file allows SC-Controller application and daemon to access Steam Controller or its USB dongle.
# This is done by allowing read/write access to all users. You may want to change this to something like
# MODE="0660", GROUP="games" to allow r/w access only to members of that group.

# Valve USB devices
SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666"
# uinput kernel module write access (allows keyboard, mouse and gamepad emulation)
KERNEL=="uinput", SUBSYSTEM=="misc", , MODE="0660", GROUP="games", TAG+="uaccess", OPTIONS+="static_node=uinput"
```
(A mix of the AUR shipped file as well with added options from https://wiki.archlinux.org/index.php/Gamepad#Steam_Controller_Not_Pairing when the default shipped from AUR wasn't working.)

**Comment by Freso** [comment]
Okay, after a full reboot, the udev rule kicked in:
```
freso@koume ~> ls -l /dev/uinput 
crw-rw----+ 1 root games 10, 223 14 okt 11:59 /dev/uinput
freso@koume ~> groups
lp wheel games video storage users freso
```
And after a some fiddling around (that is, starting and stopping `sc-controller`/`scc-daemon`), `sc-controller` is finally sending inputs through to X.
