### ISSUE TITLE
Key outputs locking up

### ISSUE THREAD

**Issue by toxicwolf** [kozec/sc-controller#106]
Just tried using this for the first time in a while and I'm getting some weirdness with the simulated keypress outputs. The first time an input is pressed, it works fine, but the next press causes the virtual key to be held down until another input is pressed. Then afterwards that input is completely useless until the daemon is restarted.

Both mouse and controller outputs work correctly however.

Is there some log file outputted by the daemon that I can post to help?

**Comment by kozec** [comment]
> Is there some log file outputted by the daemon that I can post to help?

You can run `scc-daemon debug` and check output in stdout.

**Comment by toxicwolf** [comment]
I'm not getting any output aside the initial startup, but I can confirm that the issue only occurs when the actual GUI application is open and has "Enable Input Test Mode" enabled. Therefore the workaround is to either disable this setting or start the daemon without opening the GUI.

Hope that helps.

**Comment by kozec** [comment]
Kind off. What machine are you using? Input test mode draws stuff in pretty dumb way and it's really CPU intensive, so it may cause this kind of stuff. That's also why it is turned off by default.

**Comment by toxicwolf** [comment]
Arch x86_64 Linux 4.7.6-1, i5-6600K, 16GiB RAM

**Comment by kozec** [comment]
Only way I'm able to reproduce that behavior is in virtualbox, with heavy load on normal CPU. I added small fix that shouldn't have anything with that, but I if disabling input test mode is enough to make problem go away, there is good chance this is not really fixable.

**Comment by toxicwolf** [comment]
Odd, I didn't have high CPU load when it was occurring. But as you say, it is just a mode to test the controller so it's not a that much of an issue, I feel. Thanks for your time though.
