### ISSUE TITLE
OSD keyboard settings

### ISSUE THREAD

**Issue by MeDeVILe** [kozec/sc-controller#108]
![osd keyboard bindings_010](https://cloud.githubusercontent.com/assets/6697190/19509941/6cb43810-95e1-11e6-9102-55bbe20fd780.png)

As I setup left mouse button for Y by editing osd profile file could you make it work and could you add possibility to set it like that? It would be easier to navigate using mouse cursor using gyro without turning off osd keyboard.

**Comment by kozec** [comment]
That should be doable, but how are you controlling mouse cursor?

**Comment by MeDeVILe** [comment]
![zaznaczenie_011](https://cloud.githubusercontent.com/assets/6697190/19512153/cab04f04-95ea-11e6-995d-198591db14f7.png)
with right pad touched and gyro ;)

**Comment by MeDeVILe** [comment]
I should work as a tester.

**Comment by kozec** [comment]
Ok, here you are.

One last question. What's that GTK theme you are using? :)

**Comment by MeDeVILe** [comment]
> What's that GTK theme you are using? :)


![zaznaczenie_012](https://cloud.githubusercontent.com/assets/6697190/19597765/d8035194-9796-11e6-8591-7c8b142d0319.png)
And numix circle icons.
