### ISSUE TITLE
Feedback Frequency slider has too many values

### ISSUE THREAD

**Issue by Alzarath** [kozec/sc-controller#109]
The slider goes anywhere between 1 and 9990. The latter is probably unreasonable as a default slider number and makes it very difficult to specify a specific number. If someone wanted a ridiculous number they could always use the custom action. Better yet, I would like to see the ability to click on the number and edit it to a specific number.

I get the feeling this is a bug. Right now, it's impossible to set the frequency to 1.0. When you do, it considers itself 'default', but apparently the default is 4.0 so it's actually set to that.

**Comment by kozec** [comment]
Upper value there is not really limited by anything, but yeah, now when you mention it, I can't really see anyone setting it to anything > 100.

But how's 1.0 getting lost is really bug, I'll check what is causing it.

**Comment by kozec** [comment]
(plus [one before that](https://github.com/kozec/sc-controller/commit/38c454dacfb00aafe23757b6f940d19c20ad2028), lowering max.value in that slider, which's not shown here for whatever reason...)
