### ISSUE TITLE
Inverting Y-axis on gyroscope does not appear to invert Y-axis.

### ISSUE THREAD

**Issue by abrahimladha** [kozec/sc-controller#110]
setting up gyroscope as a mouse pointer, I can get it to move just fine but it appears to be inverted, checking the box does nothing.
`feedback(BOTH, 7182, 2272.0, 6805,
  sens(5.1, -5.1, 5.1,
    mode(
      RPADTOUCH, mouse(YAW),
      None
    )))`
Inserting a `-` for the X and Z params manually does not seem to invert those either. Is it taking an absolute value somewhere?
Running v0.3 on arch. I also do not have steam installed. Controller is plugged in with USB and not using the wireless dongle at all.

**Comment by kozec** [comment]
There is pretty big chance that you are hitting bug fixed in v0.3.1, so it may be worth upgrading.

**Comment by abrahimladha** [comment]
Sorry for the late reply. That fixed it. Thanks.
