### ISSUE TITLE
deb package should depend on xinput

### ISSUE THREAD

**Issue by ajgrf** [kozec/sc-controller#111]
On Debian 8, I ran into issue #105 today because I didn't have xinput installed. So xinput should probably be added to the deb package's dependencies to prevent this.

**Comment by kozec** [comment]
That shouldn't be a problem. What was exact name of package you had to install?

**Comment by ajgrf** [comment]
The package was simply named xinput.

**Comment by kozec** [comment]
Fixed in OBS.
