### ISSUE TITLE
Keyboard Layout

### ISSUE THREAD

**Issue by Biergartenparadoxon** [kozec/sc-controller#112]
When using a different keyboard layout (neo2 in my case) the onscreen keyboard presses the wrong keys.

**Comment by kozec** [comment]
What are you using to select your layout? OSD keyboard should follow what X and GTK believes is your current keymap.

**Comment by Biergartenparadoxon** [comment]
I selected the the layout in the installer of manjaro linux and I'm using MATE. I'm not sure which method it uses but i found the following config: 
/etc/X11/xorg.conf.d/00-keyboard.conf
>Section "InputClass"
>        Identifier "system-keyboard"
>        MatchIsKeyboard "on"
>        Option "XkbLayout" "de"
>        Option "XkbModel" "pc105"
>        Option "XkbVariant" "neo"
>EndSection

On a side note: The TTYs also ignores the keyboard layout but seems to use QWERTZ. The OSD keyboard shows QWERTY pressing the Y (below 5 and 6) on the OSD gets me the key below 6 and 7 (where Y is on a QWERTY keyboard) on my keyboard which is K.

**Comment by kozec** [comment]
Sorry for late answer, I'm kinda occupied this week, but I'll try to replicate problem later.

One question: OSD keyboard shows correct layout (QVLC...), but pressing buttons generates wrong output? Or layout is wrong, but if you press button bellow 1, "x" is typed?

**Comment by Biergartenparadoxon** [comment]
OSD shows QWERTY but types XVLCWK.
(QVLC... is outdated. its XVLC... now as you can see at https://neo-layout.org/)

**Comment by kozec** [comment]
(fun fact: selecting German -> Neo2 layout in XFCE completely breaks your keyboard to the level when one has to logout :D )

**Comment by kozec** [comment]
Ok, so this gonna be fun.

First of all, changing keymap with Xorg settings doesn't seems to be detectable. I'd have to dig out my Mate VM to be sure, but there is good chance if you set it using System -> Settings -> Keyboard -> Layouts menu, it should work.

Bigger issue is that Neo layout seems to use Z and apostrophe keys as modifiers, what's not something I  considered possible when I coded OSD keyboard. It should _work_, but I'm not sure how to display it :(

**Comment by Biergartenparadoxon** [comment]
Ok I think i found something...
using the AUR package still shows shows qwerty no matter what i change in System -> Settings -> Keyboard -> Layouts

But cloning the git and running run.sh respects the layout (but still wrong)
Selecting qwertz shows qwertä (which i don't belive is even a real layout) and types qwertz
Selecting neo2 shows xvlcwy and types xvlcwk
(partly right but some keys are wrong/circulated/double/missing in both cases) (can take a screenshot if it helps)

**Comment by kozec** [comment]
> can take a screenshot if it helps

Please do, I'm getting slightly different behavior here.

**Comment by Biergartenparadoxon** [comment]
https://www.dropbox.com/s/zl84bcpbdgfpqzh/sc-layout.png?dl=0

also the AUR version always defaults to qwerty and the git version defaults to qwerty if there are not two or more layouts in the list (and thus the switcher in the mate-panel). Doesn't matter which one is remaining (qwertz or neo2) when there is only one

**Comment by kozec** [comment]
Thanks.

I've just noticed I'm mistaken about Z being modifier key. If [this](https://neo-layout.org/grafik/flat/tastatur_e1.png) would be US keyboard, what would be placed on "M4" key/

**Comment by Biergartenparadoxon** [comment]
On qwertz there is > and < on qwerty im not sure but i think the same.
maybe a difference in 104 and 105 key keyboards?

**Comment by Biergartenparadoxon** [comment]
Yeah on M3 would be "\" and "|" on a 105 key us layout and "#" and "'" on the standard german layout
so respectively the key between enter and backspace on a 104 key layout iirc

**Comment by kozec** [comment]
Just so it doesn't seems like I forgotten about this, I was finally able to reproduce problem but most likely in wrong way.

@Biergartenparadoxon do you have keyboard indicator anywhere on the panel? If not, can you add it temporary and check if it doesn't show layout being switched to default every time when OSD Keyboard is displayed?

**Comment by Biergartenparadoxon** [comment]
Still like https://github.com/kozec/sc-controller/issues/112#issuecomment-260372636

Also related #123 i guess

**Comment by kozec** [comment]
_(following in 123)_
