### ISSUE TITLE
Unable to select menu option

### ISSUE THREAD

**Issue by Kierek** [kozec/sc-controller#113]
I'm unable to select any option in any menu other than the default one(used for selecting configs). It doesn't matter if I leave the confirm button as A, set another or just check "confirm selection by releasing the button". Either I am stupid or it somehow doesn't work for me.

I have two menus, one for each pad, both configured to activate when RGRIP is pressed. Using latest stable from AUR.

Attaching the mentioned config.

[RetroArch.zip](https://github.com/kozec/sc-controller/files/587718/RetroArch.zip)

**Comment by kozec** [comment]
Ah, that's because menu controls are currently not changeable when menu is put on pad, so main problem is that they are shown when you are configuring modeshift on pad.

**Comment by kozec** [comment]
... and then there was above thing :fearful:

**Comment by Kierek** [comment]
> Just clicking with pad should work.

Nope, it didn't, but now it works perfectly, thank you. I can finally ditch Steam on my Linux installation.
