### ISSUE TITLE
Ubuntu 16.10 packages?

### ISSUE THREAD

**Issue by LiamDawe** [kozec/sc-controller#114]
Could we get some? :)

**Comment by kozec** [comment]
Package for 16.04 should work there, but I'll check if OBS already has support for 16.10.

**Comment by LiamDawe** [comment]
Ah yeah, I just manually went to the URL for the 16.04 packages and downloaded the .deb, but would be ideal to get a repo for 16.10 :)

**Comment by kozec** [comment]
I'm trying right now, but debian has really stupid tendency to break way how packaging works between versions :(

**Comment by kozec** [comment]
Well, [this was painful](http://download.opensuse.org/repositories/home:/kozec/xUbuntu_16.10/) :D
