### ISSUE TITLE
Problem with menus on wayland

### ISSUE THREAD

**Issue by Kierek** [kozec/sc-controller#115]
After switching from X to Wayland (on Gnome), the menus don't seem to work. They rarely appear, always in the left upper corner, but I don't have any control over them, unable to move pointer nor select any option.

Except for this little problem, the sc-controller works impressively well under Wayland.

**Comment by kozec** [comment]
Menus and some other parts of SCC are using Xlib calls to make their windows, so they will not work on Wayland at all. And I don't really think that's fixable, as Walyand, by design, doesn't allow stuff like OSD menus.

**Comment by Kierek** [comment]
>And I don't really think that's fixable, as Walyand, by design, doesn't allow stuff like OSD menus.

And what about osd notifications? I'm no desktop developer, but they do work fine in gnome. 

I don't see any log related to osd. If it's impossible to fix the osd menus, could you make it to work without displaying anything? That would at least be usable.

![zrzut ekranu z 2016-11-22 11-25-51](https://cloud.githubusercontent.com/assets/4080084/20520359/c395dc76-b0a6-11e6-8575-14f5b7c761f6.png)

**Comment by kozec** [comment]
> I don't see any log related to osd.

Sorry, I skipped step there. Click on green top-left icon, disable emulation and run `scc-daemon debug` in another console. That way you'll se messages about what's actually happening.

> And what about osd notifications? I'm no desktop developer, but they do work fine in gnome

Nope. That's not part of wayland and works only with Gnome compositor.

>  If it's impossible to fix the osd menus, could you make it to work without displaying anything? That would at least be usable.

I'm not sure if that can be called usable, but I can give it a try :D

**Comment by Kierek** [comment]
>I'm not sure if that can be called usable, but I can give it a try :D

Well, it would still be more usable than instant freeze after menu showing up :P



> [kierek@kierekDesktop ~]$ scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f9bb89e1610>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f9bb89f3690>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f9bb8a01b50>
D SCCDaemon     Created control socket /home/kierek/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
D USB           USB device added: 28de:1142
D OSD DaemonCtrlr   Connected to daemon, version 0.3.2
D OSD DaemonCtrlr   Daemon reported profile change: /home/kierek/.config/scc/profiles/RetroArch.sccprofile
D OSD DaemonCtrlr   Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
D SCDongle      Got wireless SC with serial FC61125C24
D SCCDaemon     Assigned default_mapper to <SCWireless FC61125C24>
D SCCDaemon     Controller added: <SCWireless FC61125C24>
D OSD DaemonCtrlr   Daemon reported profile change: /home/kierek/.config/scc/profiles/RetroArch.sccprofile
W SCCDaemon     Refused 'Observe' request: Sniffing disabled
W SCCDaemon     Refused 'Observe' request: Sniffing disabled
/usr/lib/python2.7/site-packages/scc/osd/menu.py:195: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if item.widget:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/x11/scc-osd-daemon.py", line 185, in on_unknown_message
    self._window.show()
  File "/usr/lib/python2.7/site-packages/scc/osd/radial_menu.py", line 110, in show
    OSDWindow.show(self)
  File "/usr/lib/python2.7/site-packages/scc/osd/__init__.py", line 207, in show
    self.make_window_clicktrough()
  File "/usr/lib/python2.7/site-packages/scc/osd/__init__.py", line 180, in make_window_clicktrough
    win = X.XID(self.get_window().get_xid())
AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'
D USB           Releasing devices...
D SCCDaemon     Controller removed: <SCWireless FC61125C24>

**Comment by kozec** [comment]
Ok, so this is not gonna work. It's not really possible to create OSD window without initializing window system...

You have two options:
- unset DISPLAY environment variable, so SCC will realize there is no X11 and disable OSD-related stuff. OSD is not going to work, but at least it will not freeze.
- set GDK_BACKEND=x11, to SCC will use XWayland for everything

And, for radial menu that's not visible, I'd suggest DPAD option :)

**Comment by kozec** [comment]
8-way DPAD now uses code that works almost in same way as radial menu. Configuration is little different, but resulting effect should be same.

**Comment by Kierek** [comment]
Thanks for the 8-way DPAD option, but it doesn't seem to work fine for me. When I set it like that 
![zrzut ekranu z 2016-12-12 14-57-07](https://cloud.githubusercontent.com/assets/4080084/21101822/4c1c4d62-c07b-11e6-9271-eba8e2ebc4b5.png)

left and right both seems to send the F6 button(assigned only to right). The same happens with second pad.

**Comment by kozec** [comment]
> left and right both seems to send the F6 button(assigned only to right). The same happens with second pad.

Left direction is overestimated anyway :)
It should be OK now.
