### ISSUE TITLE
Adjustable trackball inertia

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#116]
I've only just started playing with sc-controller, so maybe this is already available and I'm missing it, but the ability to set how long the trackball spins before stopping (if at all) would be very useful.  I can think of two simple ways this function might be presented to the user:

- As an _Inertia_ drop down menu: Infinite/Hi/Med/Lo/No
- As an _Inertia_ slider ranging from 0 (No inertia.  The trackball will not roll further than pushed by user) to 100 (Infinite inertia, trackball spins until stopped, at whatever speed the user swiped the pad)

The ability to "spin-and-stop" the trackball --- at whatever speed and inertia the user chooses --- sets the SC apart from (and perhaps even making it superior to) both joysticks and mice and, I think,  would be a boon to sc-controller user.

**Comment by kozec** [comment]
Slider definitely sounds better.

Code that is used to generate ball rolling effect computes with friction, what's close to opposite, but I believe you should be able to get same effect - friction of 0 would make rolling infinite and high enough value would cause it stop immediately.

How about that? Making it available as setting in UI should be pretty simple.

**Comment by LinuxJoeUser** [comment]
> zero friction would make rolling infinite and high enough value would cause it stop immediately.

Perfect!

**Comment by kozec** [comment]
So, it works with small detail - zero friction causes division by zero, so it's limited to 0.001 for now. I'll check what can be done with it later.
