### ISSUE TITLE
Unable to assign ABS_X to roll axis of gyro

### ISSUE THREAD

**Issue by CarpeNecopinum** [kozec/sc-controller#118]
Setup mostly identical to the closed #117, trying to bind ABS_X to the roll axis of the gyro does not work correctly:

![image](https://cloud.githubusercontent.com/assets/2080713/20493278/6e2853e2-b018-11e6-8294-fc3a24d4983d.png)

Similarly, binding the yaw axis of the gyro to ABS_X, when the roll axis is unbound fails in a similar fashion:

![image](https://cloud.githubusercontent.com/assets/2080713/20493443/17d4964e-b019-11e6-9222-e5448e2398e6.png)

**Comment by kozec** [comment]
True, it was almost same problem :(
