### ISSUE TITLE
Import failed: "Unknown key: 'RIGHT_BRACKET'"

### ISSUE THREAD

**Issue by CarpeNecopinum** [kozec/sc-controller#119]
Importing the "Official ETS2 Bindings" (for Euro Truck Simulator 2; by SCS Software, the developers of the game) fails with the error message

Unknown key: 'RIGHT_BRACKET'
[full error text](https://github.com/kozec/sc-controller/files/604367/error.txt)

**Comment by kozec** [comment]
RIGHT_BRACKET added to list of keys that Steam has weird name for :)
