### ISSUE TITLE
Error with trailing parentheses

### ISSUE THREAD

**Issue by Alzarath** [kozec/sc-controller#12]
An error is detected in the Custom Action editor when there are ) on a standalone line when there is a trailing ')' on the line above it.

The error:
`Excepted action name, got ')'`

This does not work:
```
dpad(
  button(Keys.KEY_UP),
  button(Keys.KEY_DOWN),
  button(Keys.KEY_LEFT),
  button(Keys.KEY_RIGHT)
)
```

Where these do:

```
dpad(
  button(Keys.KEY_UP),
  button(Keys.KEY_DOWN),
  button(Keys.KEY_LEFT),
  button(Keys.KEY_RIGHT))
```

```
dpad(
  button(Keys.KEY_UP),
  button(Keys.KEY_DOWN),
  button(Keys.KEY_LEFT),
  None
)
```

Also I assume you mean 'Expected', not 'Excepted'.

**Comment by kozec** [comment]
> Also I assume you mean 'Expected', not 'Excepted'.

Yes, I did. Thanks :)
