### ISSUE TITLE
Using the left touchpad in dpad-mode triggers wrong buttons.

### ISSUE THREAD

**Issue by CarpeNecopinum** [kozec/sc-controller#120]
Setup: set left touchpad to "Simple DPAD (WASD)"

Results of "typing" into an editor with the controller:
```
Pressing and holding the left edge: assssssssssssssssssssss
Pressing and holding the right edge: dwwwwwwwwwwwwwww
Pressing and holding the upper edge: wwwwwwwwwwwwwwww
Pressing and holding the lower edge: ssssssssssssssssss
```
i.e. the left and right "arrows" (the little ridges) of the left touchpad are detected just fine on the first touch, but repeated events are converted to the up or down actions.

**Comment by kozec** [comment]
Sorry for late answer, I had trouble with replicating reliably this and ended up merging fix with fix for another problem. DPAD should work as expected now.
