### ISSUE TITLE
Invalid Signature, Key Expired

### ISSUE THREAD

**Issue by drohm** [kozec/sc-controller#121]
I started getting this error today in APT:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/kozec/xUbuntu_16.04  Release: The following signatures were invalid: KEYEXPIRED 1480161281
W: Failed to fetch http://download.opensuse.org/repositories/home:/kozec/xUbuntu_16.04/Release.gpg  The following signatures were invalid: KEYEXPIRED 1480161281
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

I wasn't sure if you're aware, but wanted to bring it up.

**Comment by kozec** [comment]
That key is generated by OBS, so it should automatically renew itself in few hours. I hope...

**Comment by drohm** [comment]
Unfortunately, I'm still getting the warning.

**Comment by kozec** [comment]
I had it extended manually and now everything is rebuilding. Hopefully it will help.

**Comment by drohm** [comment]
I'm still getting the warning.  Do I need to pull a new key or something?

**Comment by CreamyCookie** [comment]
Yep, I'm also getting this.

**Comment by kozec** [comment]
> I'm still getting the warning. Do I need to pull a new key or something?

Please, try. I'm not sure how often or even if Ubuntu refreshes keys automatically, but this helped on my testing machine:

```
tom@u1604:~$ sudo apt-key remove 123C1C64
[sudo] password for tom: 
OK
tom@u1604:~$ curl 'http://download.opensuse.org/repositories/home:/kozec/xUbuntu_16.04/Release.key' | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1093  100  1093    0     0  15737      0 --:--:-- --:--:-- --:--:-- 15840
OK
tom@u1604:~$ apt-key list
/etc/apt/trusted.gpg
--------------------
(snip)
pub   2048R/123C1C64 2014-09-18 [expires: 2019-02-07]
uid                  home:kozec OBS Project <home:kozec@build.opensuse.org>

```
Key is listed as expiring on 2019-02-07 after.

**Comment by drohm** [comment]
That worked, thanks @kozec.

**Comment by kozec** [comment]
Great, thanks for confirming :)

**Comment by salamanderrake** [comment]
I now get this message

`Fetched 5,307 kB in 10s (526 kB/s)                                                                                         
Reading package lists... Done
W: The repository 'http://download.opensuse.org/repositories/home:/kozec/xUbuntu_16.04  Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by kozec** [comment]
That's garbled in weird way.

What do you have in your `/etc/apt/sources.list.d/sc-controller.list` file?

**Comment by salamanderrake** [comment]
`deb http://download.opensuse.org/repositories/home:/kozec/xUbuntu_16.04/ /`

**Comment by salamanderrake** [comment]
It seems to be fine now, other issues not related to your repo though.
