### ISSUE TITLE
Stop scc-daemon when closing sc-controller

### ISSUE THREAD

**Issue by CreamyCookie** [kozec/sc-controller#122]
Sometimes I switch between sc-controller and Steam, and it's a bit annoying when you suddenly see the OSD from the scc-daemon popping up and you realize that it's still running. I'm not sure if that's related, but I also remember Steam having problems with recognizing the controller, but this might just be a bug in Steam that appeared at the same time.

**Comment by kozec** [comment]
Steam should recognize Steam Controller as XBox pad while scc-daemon is running.

Anyway, leaving daemon running when GUI is closed is intentional, but you can kill it by unchecking "enable emulation" in menu.

**Comment by CreamyCookie** [comment]
Ah okay.. Didn't know it was intentional. Could you add an option to "always disable emulation when closing" sc-controller?

**Comment by kozec** [comment]
That should be possible, I'll check if there is place to stuff checkbox for it.

**Comment by LinuxJoeUser** [comment]
As a work around to this I've added a "Quit SCC" entry to the default (global) menu that issues the command 
`killall scc-daemon`

I don't have the coding chops to do much more than that, but I see the "Quit" option available on other apps I have that minimize to tray when "closed," so I would suggest that or maybe "Exit" as the label for this "close everything" action.  

As I imagine it, an SCC "Quit" process :

* be started by opening either the _Default_ (global) menu or the _Settings" menu (green/red/grey circle indicator, top left;
* Clicking "Quit" or maybe "Exit" option from the resulting drop-down menu;
* Resulting in 
  * the SCC config UI closing;
  * the SC controller powering off;
  * scc-daemon being killed

**Comment by kozec** [comment]
Sorry @LinuxJoeUser, that was little too over-complicated compared to simple checkbox :) But automatically turning off controller sounds good, I just have to check if it will not freeze if controller is in stand-by mode.

For time being, if this...

![img](https://cloud.githubusercontent.com/assets/1282500/20846059/2474ebda-b8c8-11e6-804e-98b2acc56ace.png)

... is checked, GUI will try to kill daemon before exiting.

**Comment by CreamyCookie** [comment]
@kozec That's great! Thank you very much (again)! :)

**Comment by kozec** [comment]
[Released](https://github.com/kozec/sc-controller/releases/tag/v0.3.3) 8-)
