### ISSUE TITLE
On-screen keyboard is messed up when using Dvorak layout

### ISSUE THREAD

**Issue by Nazrax** [kozec/sc-controller#123]
When my system is in the Dvorak keyboard layout, some (but not all!) of the key labels on the onscreen keyboard are wrong:
![Messed up Dvorak keyboard](http://i.imgur.com/AXjbOXN.png)

For reference, here's the layout:
![Dvorak layout](https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/KB_United_States_Dvorak.svg/1280px-KB_United_States_Dvorak.svg.png)

All keys "send" the correct values. For example, pressing the key labeled "p" in the upper-right-hand corner of the keyboard ends up writing an l - presumably because the keyboard always sends the Qwerty keys and the system translates them into Dvorak.

**Comment by kozec** [comment]
> presumably because the keyboard always sends the Qwerty keys and the system translates them into Dvorak.

It sends keycodes and X translates it according to keymap.
Why it displays QWERTY for _some_ keys is worthy investigation :)

**Comment by kozec** [comment]
Well, this got much more messed up than I anticipated.

@Nazrax , are you able to run code from git? Can you check if this works on your configuration?
And @Biergartenparadoxon , this should fix rest of keys for you as well, this time hopefully all of them :)

**Comment by Nazrax** [comment]
@kozec It works perfectly now - thanks!

**Comment by Biergartenparadoxon** [comment]
Yes seems right now cool thanks
