### ISSUE TITLE
"Preview" setting changes on-the-fly?

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#124]
Would it be possible for changes to settings to be enacted immediately?  Such changes would be temporary until another was chosen or the setting dialogue were "Canceled" or otherwise closed without saving by hitting "Ok."  Hitting "Ok" would save the current setting, exactly as it does now.  

For example, currently getting my mouse sensitivity "just right," involves 6 steps *each time I make an adjustment*: 

1. Open RPad dialogue,
2. click ">More ..."
3. make an adjustment to the sliders, 
4. click "Ok," 
5. try out the results,
6. if not okay, (and it usually isn't) return to 1.

Making changes immediately, as I'm suggesting, would only take 3 steps (3, 4, 5) to make each adjustment after the first:

1. Open RPad dialogue,
2. click ">More ..."
3. make an adjustment to the sliders, 
4. try out the results,
5. if not okay, (and it usually isn't) return to 3, else 6. 
6. click "Ok."

**Comment by kozec** [comment]
I already meditated about something like this, but I can't really think about way to preview anything but mouse and scroll wheel. For these two, I can probably add `[ ] Preview` checkbox in that big space bellow "Output" selection.

**Comment by LinuxJoeUser** [comment]
If we can only preview one output, the mouse (and its related settings such as trackball, etc., if possible) would be it.   It's *sensitivity* (and friction, etc.) where the most "tweaking" is needed to get things "just right."  (Why preview a button click, right?)  

It's times like these that I regret not knowing *any* coding.  (Is this in Python?  If so I can at least begin learning the basics in order to be more useful).  I don't know how these things need to be structured in order to function, but I like that you've already been ruminating on this.  If preview can't be made to work broadly enough, then would it be possible to have an "Apply" button separate from the "Ok" button?  Just keeping the output dialogue box (mouse or trackball, say) open until we're done fiddling with settings would be a huge improvement.  :)

**Comment by kozec** [comment]
So, previewing mouse emulation is now configurable in git, using [this option](https://cloud.githubusercontent.com/assets/1282500/21328638/3df0d11c-c635-11e6-8290-29e29bc32834.png)

But it needs little more testing, especially because I'd like to allow it for stuff like sticks and menus.

**Comment by kozec** [comment]
Tested and works :)
