### ISSUE TITLE
Trackball sensitivity issues.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#125]
With trackball, the sensitivity settings are having no effect, that is: regardless of sensitivity setting, cursor travel remains the same on-screen.  (For comparison, do the same thing on Trackpad (mouse) and see how the sensitivity significantly changes the cursor travel on-screen). 

P.S.  My apologies about including the word "friction" in the title.  It should not be there.  My brain farted and that was the result.  The issue is only with trackball sensitivity. :)

**Comment by kozec** [comment]
Weird, it seems to work for me. Can you post that string displayed on very bottom of editor window? Or just do a screenshot of your settings.

**Comment by LinuxJoeUser** [comment]
Sure thing.  Here's a sample, though it's not particular to this config:

`sens(5.8, 5.8, ball(0.592, mouse()))`

__Slow on the pad, fast on the "roll."__
Now, with that above setting, (Though others will do) when I move my thumb across the pad at a slow to casual speed the cursor moves accordingly, *until* I lift my thumb off the pad, then the cursor takes off like a shot.

__Trackball sensitivity doesn't change cursor travel distance across pad__
This can also be examined by seeing how far a pad swipe moves the cursor at various sensitivities in Mouse mode and Trackball mode.  [I've taken some screen shots to show you what I'm talking about:](http://imgur.com/a/KRSaJ)

In each picture the red line indicates cursor travel created by moving my thumb from one side of RPad to the other.
The first three pix are on mouse at sensitivity = default, 2.0, 3.0., moving from one edge of the RPad to the other.  
The second three pix are Trackball at sensitivity = default, 2.0, 3.0., again, distance is created by moving my thumb from one side of the pad to the other.

I would expect the increased sensitivity on the trackball and pad to be the same, but (for me at any rate) the trackball acts like it stays at default sensitivity on the pad, and simply "rolls" at an increased speed.  

__A funny thing happened when I left the pad__
This all became sorta funny when I set the trackball sensitivity to -2.0.  `sens(-2.0, -2.0, ball(mouse()))` I swipe across the pad right to left, and the cursor moves right to left, but immediately "rolls" backwards when I pull my thumb from the pad. XD

So that's what's happening for me.  :)
