### ISSUE TITLE
Multiple Modeshift issue with Stick, Pads, and Triggers.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#126]
I love the ability to set up multiple mode shifts for each input.  However, once one or more mode shifts are added to the stick, pads, or triggers (SPT) input and "Ok" is selected, then there are two issues that complicate and confound re-setting the outputs of the mode shifts:

1. open the _original_ dialogues for any setting. 
2. change the output setting of any mode shift setting.

__Cannot open original dialogues for any SPT setting, example:__

> If I have Rpad set to Trackpad Mouse, and I add a mode shift to Mouse Wheel (Circular) (it doesn't matter what I need to press to do this) and I select "Ok,"  I will not be able to re-access the original Trackpad Mouse or Mouse Wheel dialogue boxes.  Instead I get a Custom Setting dialogue box for the original setting.  Thus it makes it impossible to adjust sensitivity on the Trackpad, or change the configuration of a Simple DPAD to an 8-way DPAD if additional mode shifts have been added to the input device.

__Cannot change the output setting of any multiple mode shift setting, example__

> In the above example, I cannot change the Rpad's Trackpad or Mouse Wheel outputs to, say DPAD, or anything else without deleting all mode settings past the first (in this case Mouse Wheel)

A final thought after writing this:  It's unclear what to call the initial output that shows up in the Mode Shift dialogue, the one that says "(pressed alone) in front of it."  It's not really a mode *shift,* yet there it is in the Mode Shift dialogue.  And it makes *sense* for it to be there, even though it isn't actually a mode *shift*.  

I'm wondering if the term "_Mode_" wouldn't be less confusing than "Mode *Shift*," and instead of a "Mode Shift"  button in the upper left corner of each input dialogue, it was an "Add Mode" button?  Just a thought.  

:)

**Comment by kozec** [comment]
First problem should be fixed with above, 2nd needs little more deciphering :)

As for terminology, I'd rather keep "Mode Shift" without verb, because it's displayed next to another button named "Macro". With verbs, it would end with "Add Mode" and "Create Macro", what's simply too long to fit there.

But "(pressed alone)" really doesn't make sense with stick and pad. English is not my 1st language, so I'm not sure, but would  be "(default)" more understandable in that case?

**Comment by LinuxJoeUser** [comment]
What you say about "Mode Shift" without a verb makes sense to me.  Sounds good.

And yes, "(default)" is more appropriate than "(pressed alone)", definitely.
