### ISSUE TITLE
Setting Stick to "Hide Keyboard" in OSD Keyboard config doesn't work

### ISSUE THREAD

**Issue by Jimi-James** [kozec/sc-controller#127]
I'd like to be able to toggle the keyboard with the analog stick press, rather than show it and then have to hide it with some other button (like the defaults of the X button and the Steam button). I can set that option in sc-controller just fine, by setting "(pressed alone)" to "Hide Keyboard" in the Advanced OSD Keyboard Bindings, but it doesn't take affect. Pressing the stick while the keyboard is showing seems to do nothing.

Running Arch Linux x64.

**Comment by kozec** [comment]
That's because Stick in that dialog refers to Stick movement, not stick as button.

If I understood correctly, what you are trying to do is that pressing stick would display OSD Keyboard and pressing it again would hide it?

**Comment by Jimi-James** [comment]
Yes.

**Comment by kozec** [comment]
Ok, then. Here, have a button :)
