### ISSUE TITLE
Rotate with Pressed Radial Menu

### ISSUE THREAD

**Issue by Jimi-James** [kozec/sc-controller#128]
For Skyrim, I've made up a radial menu that inputs numbers 1-8 (for favorite item hotkeys), and bound it to when I press and hold the left pad: `radialmenu('Numbers 1-8',LEFT,SAME)`

Trouble is, my left pad seems to be rotated a bit, so that if my finger is at the top end of the + D-pad symbol on the pad, it's actually a little to the left, and if it's at the bottom end, it's actually a little to the right. Center is still center. This leads me to constantly click on the wrong number, because I can't see the radial menu in-game because I can't see any OSD menus above a Steam in-home streaming window (possibly another bug?). The Rotate option for the left pad does nothing, because it can only be applied to mouse emulation, not a radialmenu.

**Comment by kozec** [comment]
> This leads me to constantly click on the wrong number, because I can't see the radial menu in-game because I can't see any OSD menus above a Steam in-home streaming window (possibly another bug?).

Yes, but not bug in SCC :( Steam in-home streaming simply records game window, ignoring all others and OSD is another window with override_redirect flag.

But I can allow rotating input with radialmenu.

**Comment by Jimi-James** [comment]
>Yes, but not bug in SCC :( Steam in-home streaming simply records game window, ignoring all others and OSD is another window with override_redirect flag.

That ended up being my idiocy. Since AMD streaming performance isn't flawless, I like to switch my screen to the HDMI output of the Windows host, and I forgot I was doing that. When I'm actually looking at Linux's screen, I can see the OSD over the game.
