### ISSUE TITLE
Trackball mode hitches

### ISSUE THREAD

**Issue by Ryochan7** [kozec/sc-controller#129]
I pulled a recent version of sc-controller (a70b9483d3efa41d4dfcdf8cdf68bff94e1107e7) and I am now having a problem with trackball mode. It technically works but now there is a problem where mouse movement will stop for a second and then make a massive jump once movement starts up again. I am assuming that a routine is not being called for a period of time and then that routine then makes up the time difference once it is finally called again.

I was hoping to take advantage of some of the most recent features added to sc-controller but I have reverted to an older commit (38dfa5bb20aef3545d8f8505822caf8bc721f329) for now.

**Comment by Jimi-James** [comment]
I was getting this issue ocassionally in 0.3.3, but I have not been able to figure out what reproduces it. I think what's going on is when you flick the pad to "roll" the ball with that whole friction feature, instead of getting a nice smooth mouse movement like usual, the cursor just teleports from point A to point B, where point A is where you started and point B is where that smooth transition would have ended.

**Comment by LinuxJoeUser** [comment]
This sounds a lot like what I reported in [issue #125 **Trackball Sensitivity Issues.**](https://github.com/kozec/sc-controller/issues/125)  Take a look at that and see if that sounds like the same thing, because it may have been fixed. :D

**Comment by Jimi-James** [comment]
I don't think it's the same thing. That issue is about sensitivity acting wonky, whereas this issue is about the "animation" of the mouse flying across the screen not happening, regardless of sensitivity settings.

**Comment by kozec** [comment]
@Ryochan7 Does it happens every time or only if you don't press anything for a while? Can you attach profile where you are having that problem?

**Comment by Ryochan7** [comment]
It happens every time. Regular trackpad mode works fine though. I just pulled the most recent commit and it still happens.

Here is a link to the main profile that I use. Although, I have tried removing my old scc config folder and starting fresh but I still get the same problem.

https://dl.dropboxusercontent.com/u/31073509/fps.sccprofile

**Comment by Ryochan7** [comment]
I looked into it and the last commit that didn't have this problem is 989cb9212b6a08d422d9ea8f51fddb8fb50a37e0. It really seems like the changes made in the multicontroller branch is the source of the problem.

**Comment by kozec** [comment]
Weird thing is that I'm trying that profile, but nothing like that happens. Timing is directed by gamepad and slowed down from 1ms to 1s resolution, when no button is pressed for while, so I originally guessed that may be cause, but mouse stops naturally much sooner with your profile.

@Ryochan7 could you try running `scc-daemon debug`? Just check if there is any error message outputted when mouse stops.

By the way, are you using wired or wireless mode?

**Comment by Ryochan7** [comment]
I am using the controller in wired mode. I had been using sc-controller on the latest version of SteamOS but I just tried it out on Xubuntu 16.04. The same problem occurs on that system as well.

Here is the output that I get when I run the daemon in debug mode.

```
ryochan7@navi:~/Sources/sc-controller$ ./daemon.sh debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f71fce5f590>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f71fce70150>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f71fce80c90>
I profile       Converted XY(mouse(Rels.REL_HWHEEL, 1.0), mouse(Rels.REL_WHEEL, 1.0)) to feedback(LEFT, 4096, 16, ball(XY(mouse(Rels.REL_HWHEEL, 1.0), mouse(Rels.REL_WHEEL, 1.0))))
[<Keys.BTN_RIGHT: 273>]
(50, 254)
I profile       Converted button(Keys.BTN_RIGHT) to trigger(50, button(Keys.BTN_RIGHT))
[<Keys.BTN_LEFT: 272>]
(50, 254)
I profile       Converted button(Keys.BTN_LEFT) to trigger(50, button(Keys.BTN_LEFT))
D SCCDaemon     Created control socket /home/ryochan7/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0.0
D USB           USB device added: 28de:1102
D SCCable       Got wired SC with serial FC54302C5F
D SCCDaemon     Assigned default_mapper to <SCByCable scFC54302C5F>
D SCCDaemon     Controller added: <SCByCable scFC54302C5F>
D OSD DaemonCtrlr   Connected to daemon, version 0.3.3
D OSD DaemonCtrlr   Daemon reported profile change: /home/ryochan7/Sources/sc-controller/default_profiles/Desktop.sccprofile
D OSD DaemonCtrlr   Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
```

**Comment by Ryochan7** [comment]
Looking at the code, it looks like the problem has been acknowledged. In sc_by_cable.py line 56, the comment about the controller only sending an IDLE message once a second seems to affect trackball mode in this case.

```
def _wait_input(self, endpoint, data):
		tup = ControllerInput._make(struct.unpack(TUP_FORMAT, data))
		if not self._ready:
			self.daemon.add_controller(self)
			self.configure()
			self._ready = True
		if tup.status == SCStatus.INPUT:
			self._last_tup = tup
			self.input(tup)
		elif tup.status == SCStatus.IDLE:
			# TODO: Probably use real timer here, wired controller sends IDLE
			# only once per second
			if self.get_mapper():
				# TODO: Also remove run_scheduled at that time
				self.get_mapper().run_scheduled(time.time())
```

Putting a print statement there does show that mouse movement resumes once an IDLE message is seen. Also, making sure the daemon continues to receive input (pressing down the left touchpad) while using the right touchpad for trackball mode makes the cursor behave as expected.

**Comment by kozec** [comment]
Yep, I'm writing those TODOs so I can happily forget about them forever :)

Real timer added.

**Comment by Ryochan7** [comment]
Just pulled the commit and it works. Thank you for the great work that you put into this software.
