### ISSUE TITLE
Set custom sensitivity for pads and stick

### ISSUE THREAD

**Issue by azizLIGHT** [kozec/sc-controller#13]
Is it possible to set sensitivity levels for the pads and the left stick when set as joystick/mouse? 
I'd like to define the rate of travel on a profile basis for the pads/stick, because I have noticed that all of the pads/ sticks movement is slower than what is possible through the steam controller when used with Steam natively on Linux, Windows, as well as keyboard/mouse on both. Either the sensitivity is wrong or the controller under native steam has some kind of programming to go further in a direction, the more the stick/pad is pressed in that direction. Do you know what's going on?

**Comment by kozec** [comment]
> Is it possible to set sensitivity levels for the pads and the left stick when set as joystick/mouse? 

For mouse yes, for joystick no, but I have it in TODO.
