### ISSUE TITLE
OSD appears in incorrect position when primary monitor isn't leftmost

### ISSUE THREAD

**Issue by JoshMedeiros** [kozec/sc-controller#131]
In multimonitor setups, if the primary monitor is not positioned at the bottom left the OSD will not be adjusted for its position, in my case appearing off of the screen when a window on the primary monitor is focused. This is due to it having the id 0, and failing a check as `monitor` will be assigned the value 0.

Removing `if monitor:` at [line 196 in the OSD's init file](https://github.com/kozec/sc-controller/blob/1652e32939e930b787fce033d390a5429d4f604a/scc/osd/__init__.py#L196) fixes the issue.

**Comment by kozec** [comment]
Fixed. Sorry for overlooking this for so long :(
