### ISSUE TITLE
Namespace Rsvg not available

### ISSUE THREAD

**Issue by Sayanel01** [kozec/sc-controller#132]
Hi,

I directly downloaded sc-controller v0.3.4 (without package) then installed it.
When running it, I have :
`me@Deepthought ~/Steam_controller/sc-controller-0.3.4 $ sc-controller`
`Traceback (most recent call last):`
`  File "/usr/local/bin/sc-controller", line 14, in <module>`
`    gi.require_version('Rsvg', '2.0') `
`  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 79, in require_version`
`    raise ValueError('Namespace %s not available' % namespace)`
`ValueError: Namespace Rsvg not available`

And the same error message appears when I directly run ./run.sh

You know what is missing ?

I use mint 17.2, and I had previously installed the steamcontroller driver from ynsta

**Comment by kozec** [comment]
Yep, you missed README or at least 3rd line from bottom :)

#### Dependencies
- [python-gi-cairo](https://packages.debian.org/sid/python-gi-cairo) and [gir1.2-rsvg-2.0](https://packages.debian.org/sid/gir1.2-rsvg-2.0) on debian based distros (included in PyGObject elsewhere)

**Comment by Sayanel01** [comment]
... sorry, I read it too fast....
My bad, it works now, thanks
