### ISSUE TITLE
HatAction type values are inverted

### ISSUE THREAD

**Issue by Ryochan7** [kozec/sc-controller#134]
When using HatAction types to emulate an Xbox 360 DPad, both the X and Y directions are inverted from the assigned directions. This does affect the bundled Xbox Controller and Xbox Controller with High Precision Camera profiles as well as manual assignment.

**Comment by kozec** [comment]
Those should output in same way as steam emulation does, i.e left pad up moves virtual dpad up, axis 7 to negative. Isn't that a case?

But I know of at least one game (Mad Max) that interprets dpad wrong.

**Comment by Ryochan7** [comment]
Using hatup makes axis 7 go positive. I encountered the initial problem when mapping Xbox 360 controls in Euro Truck Simulator 2. Looking at the HatAction types, it seems that the axis max for each is incorrect and STICK_PAD_MAX and STICK_PAD_MIN needs to be swapped for each. However, each dpad direction should max out a +-1 as that is set up as the max and min when creating the virtual Xbox 360 controller. Here is a proposed change for scc/actions.py. evtest shows the expected values now and Euro Truck Simulator 2 detects the proper directions when mapping controls.

```
class HatUpAction(HatAction):
	COMMAND = "hatup"
	def __init__(self, id, *a):
		HatAction.__init__(self, id, 0, -1)
	
class HatDownAction(HatAction):
	COMMAND = "hatdown"
	def __init__(self, id, *a):
		HatAction.__init__(self, id, 0, 1)

class HatLeftAction(HatAction):
	COMMAND = "hatleft"
	def __init__(self, id, *a):
		HatAction.__init__(self, id, 0, -1)
	
class HatRightAction(HatAction):
	COMMAND = "hatright"
	def __init__(self, id, *a):
		HatAction.__init__(self, id, 0, 1)
```

**Comment by kozec** [comment]
> Using hatup makes axis 7 go positive.

Weird thing is it doesn't on my side. This is what I'm getting with default "XBox controller" profile when I press top-right part of left pad.

![pad](https://cloud.githubusercontent.com/assets/1282500/21538141/21036828-cd9a-11e6-9cf4-bbf011721519.png)

Left pad set as `dpad(hatup(Axes.ABS_HAT0Y, 0, 32767), hatdown(Axes.ABS_HAT0Y, 0, -32767), hatleft(Axes.ABS_HAT0X, 0, 32767), hatright(Axes.ABS_HAT0X, 0, -32767))`

If it does something different on your side, it may be much bigger problem than constants being switched-over.

**Comment by Ryochan7** [comment]
Oddly enough, jstest-gtk does show what would normally be expected with the original code. However, the info shown between jstest-gtk and evtest differ where evtest shows that the hat values are inverted. With the proposed change, the info shown in jstest-gtk and evtest match.

**Comment by kozec** [comment]
Hmm... I can see how evtest displays different values, in both cases, but with emulation dobe by Steam, it at least stays in same quadrants. I'll try to replicate that, hopefully it will solve problem with games interpreting DPAD reversed as well.

**Comment by kozec** [comment]
Ok, with above, same values are used in jstest, evtest and in most important testing application, Left4Dead :)

Please, reopen issue if it's still inverted for you.
