### ISSUE TITLE
Setting action for pads/stick press is extremely unobvious

### ISSUE THREAD

**Issue by hxka** [kozec/sc-controller#135]
I actually thought this wasn't implemented yet until I discovered it completely by accident.

It's really unintuitive that pressing a specific area on a button would result in a different action than pressing elsewhere on the button, buttons usually never work this way, even in this app only these 3 buttons behave this way.

**Comment by kozec** [comment]
If you have any better idea, ideally one that wouldn't require stuffing three more buttons into that poor, fatty main window, I'm one big ear :)

**Comment by hxka** [comment]
That's really a discoverability issue. Why not just split each of them into two buttons, making it obvious that there are two possible actions?

I realize that's technically stuffing 3 more buttons, but consider:
- the layout of the window won't change
- the layout of and the amount of the objects user can interact with won't change

**Comment by kozec** [comment]
Problem is that layout would change. By splitting one button, you are adding twice as many borders, paddings, margins, everything.

Plus, it looks weird a.f. :(

![big](https://cloud.githubusercontent.com/assets/1282500/21561973/54794fc6-ce74-11e6-8029-8246059332f7.png)


(i bet it will not even fit this page)

**Comment by Soundtoxin** [comment]
I agree with hxka, but after figuring out how it works, I don't really mind. My idea for additional functionality, add it to the context menu when you right click. Currently it just shows options to copy/paste stuff, but I think adding "Edit blah" and "Edit blah 2" under it would be fine as well.

**Comment by kozec** [comment]
Yep, context menu sounds much less problematic :)

**Comment by kozec** [comment]
... and context menu it is.
