### ISSUE TITLE
Xbox 360 Controller stick emulation "cuts corners"

### ISSUE THREAD

**Issue by hxka** [kozec/sc-controller#136]
I don't know how to better describe it, thus pictures!

Here's me tracing a big circle with a stick when using Steam's emulation:

![](https://i.imgur.com/Ax3G2oQ.png)

Same with SC Controller:

![](https://i.imgur.com/sW77acR.png)

This affects the gameplay! For example, here I try to first walk in squares, then in rhombuses in The Binding of Isaac: https://gfycat.com/IdioticTallGoldeneye

Notice that in the second case the character moves noticeably slower.

This doesn't happen with Steam's emulation: https://gfycat.com/EverySlimyGordonsetter

**Comment by kozec** [comment]
Wouldn't increasing sensitivity achieve same effect?

**Comment by hxka** [comment]
Ah yes, didn't notice it wasn't part of the feedback settings. Nevermind!
