### ISSUE TITLE
Inverting the Y axis for the gyro doesn't work!

### ISSUE THREAD

**Issue by Soundtoxin** [kozec/sc-controller#137]
I'm using the version of your software from the AUR. I was configuring the controller for Minecraft and losing my mind over it never feeling right, when suddenly I realized that whether the box to flip the Y axis was checked or not, pulling up on the controller always moves the mouse down, not up. I want that motion to move it up, but it doesn't no matter if the Y axis is inverted or not. I have the LGRIP as the gyro activator if that matters. Let me know if there's any more info I can give you.

edit: I can clearly see it making one of the numbers at the bottom negative when checked, and it does stay negative after I hit okay and check it again, however it does not change the actual mouse movement.

**Comment by kozec** [comment]
That sounds like issue that was fixed few versions ago and it surely works on my side. What version are you using?

Otherwise, profile where it doesn't works or copied string from bottom of editor window would help.

**Comment by Soundtoxin** [comment]
sc-controller-git v0.2.17.r1.7560b7c-1 from the AUR. Is this not kept up to date anymore? I can switch to the non-git version if that is the case.

As for the profile / text at the bottom, I have since re-worked the profile to not include gyro, so I don't have those anymore, unfortunately.

**Comment by kozec** [comment]
yaourt appears to build sc-controller-git v0.3.4.r17.1ad85a3-1, what seems to be very latest commit. But AUR stuff doesn't update automatically, if you are really on v0.2.17, then that's rather ancient. Try `pacman -Qi sc-controller-git | grep Ver`

Anyway, I really can't reproduce problem in any way, but let me know if you happen to stumble upon it again.

**Comment by Soundtoxin** [comment]
pacman -Qi sc-controller-git | grep Ver returns the following:
Version         : v0.3.4.r17.1ad85a3-1

I'll try to recreate the issue.
