### ISSUE TITLE
Mouse Shaking/Jitter When Thumb is Stationary

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#138]
I've noticed no one else seems to be reporting this issue so this may just be me, but for quite a a while sc-controller suffers from constant mouse shaking when I am touching the pad, regardless of whether my thumb is moving.

Here is a video of it in action, notice when the cursor stops moving it still continues shaking:

https://www.youtube.com/watch?v=IVUPtGRSNag

How much shaking can vary as I move my thumb around the pad to different areas, but I don't notice much consistency in where it happens. This issue does not happen at all under Steam.

Haptic feedback is also firing off while this is happening. Also fires off with pads set to analogue sticks, not sure if it's related e.g. maybe sc-controller is not filtering for really small movements and thus shaking mouse and setting off haptic feedback.

Tested with stable and git versions of sc-controller. Happens under Ubuntu 16.04 and Antergos Arch.

**Comment by kozec** [comment]
Well, thing is that you are _not_ really keeping finger at one exact place. Those touchpads are pretty sensitive :)

Filtering out haptics sounds like good idea, but I'm not sure if I can come with any filtering algorithm that would be able to detect this behavior without stopping small movements when someone is, for example, aiming.

**Comment by GlacialTurtle** [comment]
You are right, even in Steam I do not necessarily get 100% static cursor with my thumb still, but close enough to e.g. snipe with, so I decided to do another check to make sure I wasn't crazy or something else was messed up.

After rebooting into Antergos Arch and trying out Tesseract, I noticed the cursor was moving more similar to Steam. I checked the mouse sensitivity and noticed it was lower than I normally set it in my configs (1.0 default). It seems the issue is when turning the sensitivity up in the config (not advanced settings menu) from 1.0 it causes small movements of the thumb to also be exaggerated so the mouse starts shaking. This sort of happens in Steam, but to a significantly lesser (and much more tolerable) extent.

I did 2 tests, one with Steam set to max sensitivity and smoothing turned all the way down, and the other with sc-controller sensitivity set to 7.0. SC-Controller comes out much more erratic, constantly shaking. Steam does move a little more, but I can still hold it mostly steady, the mouse does not shake constantly.

https://www.youtube.com/watch?v=Pk2WAcNzu-c

I'm not sure what the difference is, as 5.0 - 7.0 feels relatively similar to Steam max sensitivity, but much more erratic mouse movement even with filtering turned down in Steam. Anything above 2.0 in sc-controller seems like it causes more shaking, whilst in Steam 3-5 notches above default is largely still when the thumb is idle whilst having similar sensitivity (at least, to me it feels that way).

**Comment by kozec** [comment]
Ok, let's try this:

Try setting this as custom action:
`filter(6.0, sens(4.0, 4.0, feedback(LEFT, ball(mouse()))))`

filter(*6* ... means that movements for less than ~600 pixels^2 are being ignored, but once input moves that much, everything is used until move speed is not less than 1/3 of that value.

**Comment by GlacialTurtle** [comment]
Tried the new setting, while it does reduce idle thumb movement, there are still occasional sudden jumps. I also tested doing slow movement and it definitely causes a stop/start issue. Here's another video showing it in Tesseract with comparison to Steam BP:

https://www.youtube.com/watch?v=wPBxCBpjNco

**Comment by kozec** [comment]
Ok, here is another, different way to do almost the same. With this one, I'm able to draw straight lines in GIMP, so it may be pretty good 8-)

But it takes ints instead of floats as argument, so try it with something like

`filter(10, feedback(RIGHT, sens(2.0, 2.0, ball(5.534, mouse()))))`

Gonna fix that later.

**Comment by GlacialTurtle** [comment]
This definitely works a lot better, thanks! It also worked well with sensitivity turned up to 7 without modification. There are some rare small "jumps" in movement but they're not really noticeable in  game, only with desktop mouse.

This also fixes the haptics firing with no/very small movements too.

**Comment by kozec** [comment]
Great, thanks for confirming :)

Since it doesn't really filter anything now, I'll rename it to `smooth` and add GUI into next release.

**Comment by Ryochan7** [comment]
Is there any chance that you could implement smoothing using a weighted average? It would mean having to add a variable for a custom weight modifier but having that extra control allows for a more responsive cursor while still allowing for a good amount of smoothing; it does a better job than just playing with the smoothing buffer size.

Also, the way that smoothing is implemented now, the buffer is cleared completely after releasing the pad so less smoothing is being performed when you first touch the pad. I find that filling the smoothing buffer to maxlen upon first touching the touchpad with the first coordinates acting as the zero point feels better than starting with an empty buffer each time.

**Comment by kozec** [comment]
> Is there any chance that you could implement smoothing using a weighted average? It would mean having to add a variable for a custom weight modifier but having that extra control allows for a more responsive cursor while still allowing for a good amount of smoothing; it does a better job than just playing with the smoothing buffer size.

It's not a problem, but I'm not sure how should that modifier be applied. Should first input has more wight than inputs after it?

**Comment by Ryochan7** [comment]
The most recent input would have full weight. Each older input would have a reduced weight based on the modifier value used. When using 0.75 for example, the second value would be multiplied by 0.75, the next by 0.5625, and so on. Using a weight modifier of 1.0 would result in a simple mean value. I am using a weighted average approach for the BallModifier class in my local copy. Right now, I am using a buffer size of 8 with a weight modifier of 0.72 although I had been using 0.70 for a slightly faster cursor. It isn't clean or up to date with the most recent code but here is a diff based on the changes I have made in my copy.

https://gist.github.com/Ryochan7/316a644935f33e4f51ee19058c79777c

**Comment by jrial** [comment]
Wouldn't a simple weighed average formula be easier than using a buffer? It would go like this:
```
current_pos = (1 - weight) * previous_pos + weight * current_measured_pos
```
except for the first measurement, which will "seed" the current_pos value.

It's a standard engineering formula used to smoothen out noisy sensor data. Doesn't require keeping a buffer, doesn't require summing and dividing.

**Comment by Ryochan7** [comment]
Testing the different methods just out of curiosity. The test data is arbitrary and only takes the X+ axis portion of the touchpad coordinates into account. The resulting lists are based on 7 theoretical gamepad polls. A buffer size of 7 was used for the fixed buffer tests. The base weight used for both variants of the weighted average was 0.78; simple weighted used 0.22 to make the results resemble the other approach more.

Poll Data. Most recent data to oldest data

```
[32767, 32767, 24573, 16382, 8191, 4095, 0]
```

When using simple average with changing buffer size

```
[0, 2047, 4095, 7167, 10648, 14334, 16967]
```

When using simple average with fixed buffer size

```
[0, 585, 1755, 4095, 7605, 12286, 16967]
```

When using simple weighted average

```
[0, 900, 2504, 5557, 9740, 14805, 18756]
```

When using weighted average with fixed buffer size

```
[0, 1092, 3038, 6741, 11816, 17961, 22755]
```

**Comment by kozec** [comment]
In third version of same thing, it's used as

`smooth(10, 0.75, ball(mouse()))`

and should work as @Ryochan7 suggested.

GUI is next thing on the plan.

**Comment by GlacialTurtle** [comment]
Just tested and I think it's actually slightly worse. I'm having to set the values a lot higher to try and stop haptics firing when the thumb is idle and keep the mouse steady. Had to set it to 20, 1.0 to try and reach similar behaviour as the previous method got with its default. Even so, this still doesn't stop haptics firing with an idle thumb, with the added detriment of more noticeable drift and lag with the mouse as I move the around pad, particularly on fast movement or when coming to a stop.

**Comment by kozec** [comment]
> Even so, this still doesn't stop haptics firing with an idle thumb, with the added detriment of more noticeable drift and lag with the mouse as I move the around pad, particularly on fast movement or when coming to a stop.

If haptics are main problem, I've already fixed it in 7ecc34cbc2e8df0f3fb7b111db2560a3fb02c5fc. Before, haptics were generated from by moving finger on pad. All movements were accumulated, so that "shaking" on pad accumulated enough distance to trigger click. Now it calculates in way where moving back to original position subtracts from accumulated distance, so steady finger shouldn't click.

About overall results, `smooth(10, 1.0)` should work exactly as `filter(10)`. I've tested it briefly and this...

![shake](https://cloud.githubusercontent.com/assets/1282500/21953499/63e0ee4e-da39-11e6-81de-9808adcfe55a.png)

... are movements generated by idle finger and `filter(8)`, `smooth(8, 1.0)` and `smooth(8, 0.7)` (that's default), all with sensitivity of 10.

Last dot is default `smooth(8, 0.7)` with sensitivity only 2.

**Comment by Ryochan7** [comment]
It looks like the weighted average implementation is correct. The only change that stands out is that the built in dead zone has been reduced significantly. Beforehand, increasing the smoothing buffer size also increased the effective dead zone (level * 2) but it looks like the effective dead zone is now a constant 2. That would explain the haptics firing more and maybe some more jitter but not having additional lag compared to the previous implementation.

**Comment by kozec** [comment]
True, that should have effect, but that part was more like mistake of former implementation... I can add it back, but as additional (optional) parameter, not as function of level.

**Comment by Ryochan7** [comment]
I have pulled the latest commit and the smooth modifier seems to work fine for the most part. It really seems like the idea of using a fixed buffer size is what has affected the initial speed. The dead zone does seem to factor in as well.

**Comment by kozec** [comment]
I've added optional "filter" parameter and with it, both "old" and new behavior can be achieved.

**Comment by Ryochan7** [comment]
One implementation detail regarding Touchpad Mouse mode with the Steam Controller is that there seems to be an initial drag placed on the low end of movement beyond the assigned dead zone; the drag exists regardless of sensitivity or smoothing settings. This happens when using the controller with the Steam client and in Lizard mode. The final output on the low end is too stiff for my liking and that is probably the main reason that a lot of people prefer to use Gyro Mouse mode. I have been testing out adding a small drag zone on the low end of mouse movement and it seems to make the cursor more stable without sacrificing much precision on the low end. I will post a small snippet for the X axis as is. The routine only runs when initial mouse output is under 0.34 pixels.

```
offman = 0.34
throttla = 1.44
if abs(tempx) < (abs(unitx) * offman):
    signx = copysign(1.0, tempx)
    ratioX = abs(tempx) / offman
    tempx = ratioX ** throttla * signx * offman
```

**Comment by pattontim** [comment]
I'm having this problem but it's actually caused by the environment. Vibrations from an overhead speaker or HVAC system cause my pads to intermittently jump, happens on both pads. Must be pushing the limit of the algorithm.
