### ISSUE TITLE
[Request] Set different version number for virtual Xbox 360 controller

### ISSUE THREAD

**Issue by Ryochan7** [kozec/sc-controller#139]
Although vendor and product identifiers can be specified per virtual device, each virtual device uses a version number of 1. Using a different version number would probably only matter for the virtual Xbox 360 controller and only in some cases. The main case that I have seen where the device version number would matter is any application using SDL 2.

The game controller mapping database has the device version number encoded into the GUID which is used to identify a device. Currently, SDL 2 reverts to using the joystick system with the virtual Xbox 360 controller; some games using SDL 2 would likely only use game controller support. The ds4drv project uses the version number 272 (0x110) when it creates a virtual Xbox 360 controller. Using that version number in uinput_init creates a device that SDL 2 sees as a compatible game controller.

It would probably be better to allow a UInput object to specify a custom device version number.

**Comment by kozec** [comment]
Sounds doable, but is there any simple way to test it? Game that outputs used joystick / gamepad GUID system for example?

**Comment by Ryochan7** [comment]
I am not aware of any games that output the GUID anywhere for the user to see. A couple of applications that could be used to test it would be the sdl2 version of sdl-jstest and antimicro. The generated GUID for the virtual Xbox 360 controller currently is `030000005e0400008e02000001000000` while the generated GUID would be `030000005e0400008e02000010010000` with the version number change. The GUID generated using the updated version number is in the game controller mapping database for SDL 2.

One example of a game that I have tried that is affected by this problem is Half-Life 2. Mixed input mode cannot be used because Half-Life 2 cannot detect that an Xbox 360 controller is connected. Using the Xbox Controller with High Precision Camera profile would probably be the best way to play Half-Life 2. Once the version number is changed in uinput.c and the library is recompiled, Half-Life 2 is able to detect the controller and using a mixed mode configuration works.

**Comment by kozec** [comment]
Frankly, that's begins to sound like bug in SDL or games using it, because I can't see reason why should they act differently when there is different controller connected.

But fix is simple, so why not...

**Comment by Ryochan7** [comment]
It looks like there is a fix to this problem in SDL 2.0.4 and later. Based on the source code, it looks like as long as the controller name has the text "Xbox" in it then SDL will attempt to use the included XInput mapping unless there is a dedicated mapping string included in the database.

My main gaming PC is running on SteamOS. SDL 2.0.2 is the version of SDL 2 included in the repositories so I do not have access to that fix for application. Even though the Steam Runtime uses SDL 2.0.4 and Steam BPM actually detects the virtual Xbox 360 controller as an XInput controller, that configuration does not carry over to Half-Life 2; Half-Life 2 bundles its own version of SDL 2. Testing sdl2-jstest on my Xubuntu 16.04 laptop shows that game controller support does work for the version of SDL included (2.0.4).

Besides ds4drv using that device version number for its virtual controller, xboxdrv also uses that device version number when it creates a virtual controller. I guess it would be best to stay consistent with other projects either way. Thank you for including the change.
