### ISSUE TITLE
Randomly stops working

### ISSUE THREAD

**Issue by azizLIGHT** [kozec/sc-controller#14]
While I'm playing, my controller suddenly stops working and the last button pressed is pressed forever. SC-Controller says: "There was an error with enabling emulation: LIBUSB_ERROR_BUSY [-6] Another application (most likely Steam) is using the controller.

The situation is still active, so if you need me to run some commands/debug anything let me know. I've only quit my game. I don't have native Linux Steam on, nor did I start it at any point when this happened, I did not unplug or plug any USB devices either.

**Comment by kozec** [comment]
Can you run `ps ax|grep scc` to check if there isn't another daemon instance running? That's one thing I can imagine taking over input from dongle..

**Comment by kozec** [comment]
Also, if it happens repeatedly, quit everything, make sure daemon is really down (with that `ps ax|grep scc`) and run `scc-daemon null debug` to get output daemon output. You can then choose profile in GUI normally and, if that problem is caused by some exception, it should be printed in console where `scc-daemon null debug` runs.

**Comment by azizLIGHT** [comment]
OK I just got it to fail again. Seems to be random. I verified that there was only one instance of scc and scc-daemon running:

```
aziz@LIGHT:~$ ps ax | grep scc
 8764 pts/17   Sl+   10:13 /usr/bin/python /usr/bin/scc-daemon null debug
32635 pts/8    S+     0:00 grep --color=auto scc
aziz@LIGHT:~$ 
```
I have a screenshot of scc [here](http://i.imgur.com/nhoIe07.png) and the output of the debug log here:
```
aziz@LIGHT:~$ scc-daemon null debug
D Mapper        Creating virtual devices
D Mapper        Gamepad:  <scc.uinput.Gamepad object at 0x7fd5728c3c90>
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7fd5728c3fd0>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7fd5728c3b10>
W SCCDaemon     Failed to load profile. Starting with no mappings.
W SCCDaemon     Reason: [Errno 2] No such file or directory: 'null'
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Created control socket /home/aziz/.config/scc/daemon.socket
D SCCDaemon     Controller turned ON
I SCCDaemon     Loaded profile '/home/aziz/.config/scc/profiles/Rocket League LS High Sensitivity.sccprofile'
I SCCDaemon     Loaded profile '/home/aziz/.config/scc/profiles/Rocket League LS High Sensitivity.sccprofile.mod'
I SCCDaemon     Loaded profile '/home/aziz/.config/scc/profiles/Rocket League LS High Sensitivity.sccprofile.mod'
I SCCDaemon     Loaded profile '/home/aziz/.config/scc/profiles/Rocket League LS High Sensitivity.sccprofile'
I SCCDaemon     Loaded profile '/home/aziz/.config/scc/profiles/Rocket League LS High Sensitivity.sccprofile.mod'
I SCCDaemon     Loaded profile '/home/aziz/.config/scc/profiles/Rocket League LS High Sensitivity.sccprofile.mod'
I SCCDaemon     Loaded profile '/home/aziz/.config/scc/profiles/Rocket League LS High Sensitivity.sccprofile'
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]
E SCCDaemon     LIBUSB_ERROR_BUSY [-6]

```

**Comment by azizLIGHT** [comment]
I have the situation active, in case you need me to run any commands

**Comment by kozec** [comment]
Ok, this is officially weird, LIBUSB_ERROR_BUSY  shouldn't just happen without any reason...

Would it be possible to attach that profile? I'll try to make some stress-test script and run in with it.

**Comment by azizLIGHT** [comment]
Here is "~/.config/scc/profiles/Rocket League LS High Sensitivity.sccprofile"

```
{
    "buttons": {
        "A": {
            "action": "button(Keys.BTN_GAMEPAD)"
        }, 
        "B": {
            "action": "button(Keys.BTN_EAST)"
        }, 
        "BACK": {
            "action": "button(Keys.KEY_TAB)"
        }, 
        "C": {
            "action": "button(Keys.KEY_LEFTSHIFT); button(Keys.KEY_TAB); profile('Desktop')"
        }, 
        "LB": {
            "action": "button(Keys.KEY_LEFTSHIFT)"
        }, 
        "RB": {
            "action": "button(Keys.BTN_TR)"
        }, 
        "RPAD": {
            "action": "button(Keys.BTN_THUMBR)"
        }, 
        "START": {
            "action": "button(Keys.BTN_START)"
        }, 
        "X": {
            "action": "button(Keys.BTN_NORTH)"
        }, 
        "Y": {
            "action": "button(Keys.BTN_WEST)"
        }
    }, 
    "gyro": {}, 
    "left_pad": {
        "action": "dpad(hatup(Axes.ABS_HAT0Y, 0, 32767), hatdown(Axes.ABS_HAT0Y, 0, -32767), hatleft(Axes.ABS_HAT0X, 0, 32767), hatright(Axes.ABS_HAT0X, 0, -32767))", 
        "click": true
    }, 
    "right_pad": {
        "X": {
            "action": "axis(Axes.ABS_RX)"
        }, 
        "Y": {
            "action": "axis(Axes.ABS_RY)"
        }
    }, 
    "stick": {
        "X": {
            "action": "sens(1.4, axis(Axes.ABS_X))"
        }, 
        "Y": {
            "action": "sens(1.4, raxis(Axes.ABS_Y))"
        }
    }, 
    "triggers": {
        "LEFT": {
            "action": "axis(Axes.ABS_Z)"
        }, 
        "RIGHT": {
            "action": "axis(Axes.ABS_RZ)"
        }
    }
}
```

**Comment by kozec** [comment]
Sooo... I had this running literally for three days in a row and absolutely nothing :(

But there is chance I somehow fixed it in meanwhile. Can you confirm if problem still happens with latest release?

**Comment by azizLIGHT** [comment]
I haven't had it happen again since last time. But I'm keeping an eye out for it.

In the meantime I've noticed that the controller gets "twitchy" after some time
Should I create a new issue for this? Is it related to this? I'm not sure.
[Left Stick and Right Trigger twitching](http://i.imgur.com/feHEqJ0.gif)
[X Y A B Buttons twitching](http://i.imgur.com/u2yNk42.gif)
Is this something specific to [my environment](http://i.imgur.com/oT6VPtE.png)?

**Comment by kozec** [comment]
It may be, but probably not with Wine. Check if [jstest-gtk](https://apps.ubuntu.com/cat/applications/jstest-gtk/) (or any other native tester) displays same thing.

But this starting to look like some kind of hw trouble. You have ABXY buttons mapped directly to virtual ABXY buttons and I see no macros anywhere, so there is no way sc-controller would generate 'button pressed' - 'button released' events just out of nothing O.o

How is USB dongle connected? Can you try to connect it to USB port in back (those are usually connected directly to mainboard)

**Comment by azizLIGHT** [comment]
I'm actually connecting the controller directly by a microUSB to USB cable and without the provided USB dongle. Does that matter?

**Comment by kozec** [comment]
Nope, I'm pretty sure that twitching problem is bug in joystick CP in wine. It does same thing with real controller and problem magically disappears when I launch another testing tool in wine or even when I start some game.

Do you have that problem in any actual game, or just in joystick CP?

**Comment by azizLIGHT** [comment]
I've seen the twitching happening in Rocket League in wine-steam a couple of times a week ago. I didn't know about the joystick CP in wine at the time when I experienced it so I don't have any gif of what it looked like in that CP. But basically, my car would steer right (LS to right) and go forward (RT), on a regular interval (much like my first gif) when nothing was being pressed. 

It only stopped when I did one or more of the following: disconnected/reconnected the controller, exited Rocket League, exited Steam, simulated a reboot in wine, stopped emulation in scc, quit and restarted scc, and started wine-steam and Rocket League back up.

**Comment by azizLIGHT** [comment]
I checked out jstest-gtk and I don't see any blinking for the ABXY buttons in there, while I do see twitching in the wine joystick CP, when I hold down all 4 buttons constantly. So you may be right, it might be a wine issue?

**Comment by kozec** [comment]
> So you may be right, it might be a wine issue?

It definitely looks like one. I even tried jstest (that one without -gtk) to print each event as it happened and it didn't logged anything while wine kept twitching.

By the way, no twitching happens as long as I have [this testing tool](http://www.softpedia.com/get/System/System-Miscellaneous/Joystick-Tester.shtml) running (not in joystick CP, not in any game i've tested so far) so it may be related to how is gamepad status queried within wine app.

**Comment by azizLIGHT** [comment]
Yes I'm using xbox360ce. I used [these instructions](https://www.reddit.com/r/linux_gaming/comments/4cbgyx/crossover_linux_with_rocket_league/d1h7k69) to get it working in Crossover

**Comment by kozec** [comment]
Sorry, but this is *definitely* that weird joystick CP problem - [game ignores those nonexisting events](http://kozec.com/lo-5.ogv).

But if'll you find game where it is replicable, I'll may be able to find some workaround.

**Comment by kozec** [comment]
By the way, I managed to reproduce very original problem when I tried to charge two phones from my poor machine. So I'd assume that original thing is really HW related and happens when USB bus can't output enough power to keep dongle alive and can be prevented by using powered USB hub.

Anyway, this ^^ workaround works 8-)

**Comment by azizLIGHT** [comment]
Ah, I was using a USB powered hub to connect the controller via USB cable. Now I'll try directly. Hopefully it was the powered hub's fault, like you say. I will still keep an eye out and run the debug logs to see if it ever acts up while directly connected. Thanks!

**Comment by azizLIGHT** [comment]
I've been using the controller and scc for a while now using the dongle directly attached to my pc and I haven't had the LIBUSB_ERROR_BUSY [-6] problem yet. It seems like the problem was a faulty microUSB cable that would cause a disconnect intermittently? Either way, the newest updates dont seem to be having this problem, while I use the wireless dongle.
Thanks
