### ISSUE TITLE
Battery level indicator ?

### ISSUE THREAD

**Issue by Sayanel01** [kozec/sc-controller#140]
Hi,
Everything is in the title : is there any way to see battery level of the steam controller with sc-controller ?

**Comment by kozec** [comment]
Not right now. I don't know how if it is sent from controller and since it isn't displayed in some numeric format in Steam, it's pretty hard to sniff it from dumps.

**Comment by kozec** [comment]
Hey, silly question. Do you happen to remember where _Steam_ displays indicator? I kinda remember seeing it there, but can't find it anywhere now.

**Comment by Kierek** [comment]
It was always displayed next to the Steam Controller icon under Settings tab, I can confirm that it seems to be gone now.

**Comment by kozec** [comment]
I though so. I did last thing I could, sit down on cable and sniffed everything that controller sends while swapping old and new batteries, but there is no change. There is possibility that Valve removed it from protocol in some fw revision.

So this is most likely unfixable :(
