### ISSUE TITLE
Bumpers not showing Action Name after "ok."

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#144]
The Action Names for the bumpers only change after profile changes are saved, _and_ 
- changing the profile and then changing it back, or 
- closing the SC Controller config UI and re-launching it.

This behaviour isn't consistent with Action Names of any of the other settings.

**Comment by kozec** [comment]
I can't reproduce this at all... By bumpers, you mean "LB" and "RB" buttons?

Try running `sc-controller -d` from console and check if there is any error message printed out when name is not changed.

**Comment by LinuxJoeUser** [comment]
Agh!  Neither can I anymore. Lol!  Whatever was causing this problem seems to *also* have been cleared up by 3.4.1 --- Issue closed. :)
