### ISSUE TITLE
On RPad, Mode Shift resets Trackball & Trackpad (Mouse) sensitivity to default 1.0

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#146]
**Issue:**
On RPad -only-:
- Setting the RPad to **Trackball** works as expected.  Sensitivity of 2.0 moves further than default of 1.0
>>  `sens(2.0, 2.0, rotate(3.8, ball(0.552, mouse())))`

- Setting the RPad to **Trackball** and adding a **Mode Shift** setting, and sensitivity of 2.0 begins acting as if set to default of 1.0.  For example: 
>>  `mode(LB, dpad(button(Keys.KEY_UP), button(Keys.KEY_DOWN), button(Keys.KEY_LEFT), button(Keys.KEY_RIGHT)), rotate(3.8, sens(2.0, 2.0, ball(0.552, mouse()))))`

- Likewise for **Trackpad (Mouse).**  This works as sensitivity 2.0:
>>  `rotate(3.8, sens(2.0, 2.0, mouse()))`

- But a **Trackpad (Mouse)** with a **Mode Shift** and the sensitivity acts as if it's on default 1.0:
>>  `mode(LGRIP, ball(XY(mouse(Rels.REL_HWHEEL), mouse(Rels.REL_WHEEL))), rotate(3.8, sens(2.0, 2.0, mouse())))`

**Variables Tested:**
* A Mode Shift added to either Trackball or Trackpad (Mouse) acts as if set on default 1.0 regardless of initial setting.
* Does NOT happen with other RPAD on Mouse Wheel.
* Does NOT happen on LPad.

**Not Tested:**
- Other initial outputs, including L & R Stick settings.

**Comment by kozec** [comment]
It's hard to explain how much broken this was, but it should work as expected now :)
