### ISSUE TITLE
SC-Controller version number unchanged in GUI?

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#147]
![kozec3-5not3-4-1](https://cloud.githubusercontent.com/assets/23580979/21743196/58999c84-d4cb-11e6-85db-17be73c36dab.jpg)
In GUI > "About" "About SC-Controller" says 3.4.1, but apt-cache show reports
`Filename: ./amd64/sc-controller_0.3.5_amd64.deb`

It seems like a very minor thing, and I wouldn't have caught it if I hadn't taken a look at the "Releases" section of the Github page. (So it was the 3.5 update, not the 3.4.1 that fixed issues #143 and #144 for me. :))

**Comment by kozec** [comment]
That version is taken from python's site-packages, so it should really reflect what's is installed...

Can you check if there is file named `/usr/lib/python2.7/site-packages/sccontroller-0.3.5-py2.7.egg-info` in your system? And, if it is, check if there is line stating `Version: 0.3.5` in it.

**Comment by LinuxJoeUser** [comment]
No.  there's no directory called "site-packages" in `/usr/lib/python2.7`, or anywhere else on the system.  The closest I could come was `/usr/lib/python2.7/dist-packages/sccontroller-0.3.4.1.egg-info`, the contents of which read:

`Metadata-Version: 1.0
Name: sccontroller
Version: 0.3.4.1
Summary: Standalone controller maping tool
Home-page: UNKNOWN
Author: kozec
Author-email: UNKNOWN
License: GPL2
Description: UNKNOWN
Platform: Linux`

**Comment by kozec** [comment]
Yeah, in meantime, I found what most likely caused this. It shouldn't cause any problems as long as that number is larger as number in release before, so I'll fix it with next release.

**Comment by LinuxJoeUser** [comment]
No, worries.  I'm glad to hear it is, in fact, only something minor.  :)
