### ISSUE TITLE
Steam Controller is being "pushed around" by the original Xbox 360 Controller

### ISSUE THREAD

**Issue by Kierek** [kozec/sc-controller#148]
I'm not quite sure if it's a problem with sc-controller, evdev, xpad or generaly something with input stack/my configuration. The problem I experience applies to compatibility issues when using both sc-controller and the original wired Xbox 360 Controller.

I wanted to make some game specific configs for the Dolphin Emulator. In the beggining you have to specify the device for which it should apply and in most of my cases(single player games), Steam Controller is just detected as `evdev/0/Microsoft X-Box 360 pad`. No problem here. 

The problem appeared when I tried to configure some multiplayer games. Steam Controller should always appear as a first players device so I assumed that when I launch sc-controller before connecting wired xbox controller it would work correctly. Nope. No matter what I do, what usb inputs I use, the Xbox Controller always takes the first evdev device and `/dev/input/js0`. 

When the Steam Controller was connected it's just pushed over to `/dev/input/js1` and `evdev/1`.

Would it be possible to allow user to change the name of evdev device as which Steam Controller appears? I assume that it would be the end of my problems since I could make it controller specific, without worrying about ids.

I have no idea what is and how it is doing the sorting. It most certainly isn't the device GUID since the Xbox 360 Controller one is greater.

```
[kierek@kierekDesktop ~]$ sdl2-jstest --list
Found 2 joystick(s)

Joystick Name:     'Microsoft X-Box 360 pad'
Joystick GUID:     030000005e0400008e02000014010000
Joystick Number:    0
Number of Axes:     6
Number of Buttons: 11
Number of Hats:     1
Number of Balls:    0
GameController:
  Name:    'XInput Controller'
  Mapping: '(null)'

Joystick Name:     'Microsoft X-Box 360 pad'
Joystick GUID:     030000005e0400008e02000010010000
Joystick Number:    1
Number of Axes:     6
Number of Buttons: 19
Number of Hats:     1
Number of Balls:    0
GameController:
  Name:    'XInput Controller'
  Mapping: '(null)'
```

**Comment by kozec** [comment]
That's already possible, just not in ui. Disable emulation, open ~/.config/scc/config.json and you can change device name in [output](https://github.com/kozec/sc-controller/blob/master/scc/config.py#L45) node.

**Comment by Kierek** [comment]
Works great, thanks.

**Comment by kozec** [comment]
Np :)

**Comment by kozec** [comment]
Byy the way, I've just noticed...

> Number of Axes:     6
> Number of Buttons: 19

Does your XBox pad really have 19 buttons? Which are responding to IDs 11-18?

**Comment by Kierek** [comment]
That's the Steam Controller, it's reporting 19 buttons on every profile. They don't respond to anything.
