### ISSUE TITLE
UI window top bar enhancement #1: Add separate "App Menu" icon 

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#149]
Currently, its not clear that the "Settings" are opened with the green "enabled" light icon.  Add a separate, recognizable, "Settings" icon (such as a "gear" icon, or the three lined, so called "hamburger.") and add tool tip.
[Picture](http://imgur.com/a/B1Aa4)

**Comment by kozec** [comment]
Dunno about this one, having "App menu" is pretty common thing for GTK applications.

**Comment by LinuxJoeUser** [comment]
Ok, that was partly my fault.  I said "Settings" but I meant what you're calling "App Menu."  I've edited the subject line to reflect that.  


Hmmm.  Maybe I'm missing something.  I can sees nothing on my SC-Controller UI that says "App menu."  Hovering over the Green/Red circle on the top window bar merely says "Emulation is active,"/ "Emulation is inactive,"  respectively.  

As it is, the App Menu is virtually hidden.  It might be that the Green/Red circle is meant to be understood as the method of opening the App Menu as well as indicating the emulation status, but it didn't read that way to me.  It was only after hovering over everything else, even right clicking on the SCC top bar, that I tried clicking on the emulation indicator.

My idea of the gear or hamburger icon for an App Menu was just a suggestion.  I like that the Green/Red indicator light tool-tip explains the indicator's status, so I wouldn't want that replaced with an "App Menu" tool-tip.  I really think an additional icon or a "Menu" button, or something would be better than what SCC has now.  The specific method isn't important, but I feel that the App Menu must be immediately obvious to the user.  

I don't think 

It might be that the Green/Red circle is meant to be understood as the method of opening the dropdown menu

**Comment by kozec** [comment]
> Hmmm. Maybe I'm missing something. I can sees nothing on my SC-Controller UI that says "App menu." Hovering over the Green/Red circle on the top window bar merely says "Emulation is active,"/ "Emulation is inactive," respectively.

I have two questions for that... Do you happen to use more Gnome / GTK apps? Did you never noticed what most of them have in common?

![menus](https://cloud.githubusercontent.com/assets/1282500/21895812/5a99e1fc-d8e4-11e6-80ee-2f326c1fba56.png)

Hamburger menu for options is common thing and I have nothing against it, but there are options that are supposed to be under top-left menu icon and without them, hamburger would have only one or two options to show. So I have to add more features before  :)

**Comment by LinuxJoeUser** [comment]
I use Gnome 3.20 on my Ubuntu 16.04 and on my Ubuntu Gnome 16.04 machines.  Neither has top-left menu icon.  Indeed, poking around online, I couldn't find any distro using Gnome 3.x editions that did have it.

Some of the most popular distros seem to lack this icon, including: 
- Ubuntu Unity 16.04+ 
- Ubuntu Gnome 16.04+
- Linux Mint 18 Cinnamon
- Linux Mint 18 XFCE 
- Linux Mint 18 Mate 
- OpenSUSE 42 Gnome
- Arch Linux Gnome 3.20

I do see little icons like you talk about in the upper left corner of various KDE editions (Kubuntu, LInux Mint, and OpenSUSE among them), and maybe in Ubuntu Mate 16.04.  

I certainly didn't feel that "most of them have in common" a top-left menu icon.  It seems normal for KDE, but _not_ normal for Gnome or Cinnamon, and possibly mixed for Mate and Xfce.  

I think SCC should be distr/desktop agnostic, like Gimp, VLC, Firefox, etc. and not have the green light also be the menu.  The hamburger is a virtually universally recognized icon for "menu," an icon in the upper left corner is not outside of KDE, it seems.  And as I said before, hovering over that little icon in SCC doesn't reveal it to be a menu either.  It only says "Emulator is active/inactive." 

That's my 2 cents. :D

**Comment by dyskette** [comment]
I will chime in here.

Currently what sc-controller has as an appmenu is just a regular menu in the headerbar.

The appmenu in other applications only appear in the headerbar when they are outside of GNOME Shell, this is because GNOME Shell shows the appmenu in the top bar.

See screenshot.

![captura de pantalla de 2017-03-17 12-36-57](https://cloud.githubusercontent.com/assets/6687927/24057842/d3d579be-0b16-11e7-9418-75cb658acde8.png)

I think is explained [here](https://developer.gnome.org/gtk3/stable/GtkApplication.html#gtk-application-prefers-app-menu).

**Comment by kozec** [comment]
@dyskette 
True, I probably never had SCC running under Gnome Shell, so I haven't noticed, but this sounds like bug. I'll try to get it running in VM once again :(
