### ISSUE TITLE
UI window top bar enhancement #2: Change "Enabled" indication.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#150]
Eliminate green "enabled" indicator and add it's "Enable/Disable" functions to each individual controller icon on the left of each profile so:

- Indicator is "lit" when enabled, grey when disabled, and not present when its controller is absent.
- Each controller can be emulated separately, if possible.  (Hopefully, this will allow the user to have one controller available for SCC and another for Steam, or Anti-micro, etc.) 

[Picture](http://imgur.com/a/dVb72)

**Comment by kozec** [comment]
> Each controller can be emulated separately, if possible. (Hopefully, this will allow the user to have one controller available for SCC and another for Steam, or Anti-micro, etc.)

Sadly, nope. Any application talking to Steam Controller is actually communicating with dongle, so disabling just one controller without turning it off is not really possible. And you can't disable wired controller either, there is no way to "cut wire".

So this doesn't sounds possible because of HW limitations.

**Comment by LinuxJoeUser** [comment]
Ok, that makes sense.

Unfortunately, SCC steals control of all dongles, it seems.  

I have two SCs.  I plugged the two dongles into two separate slots on my game machine.  
Beginning with SCC and scc-daemon both off,  I started Steam BPM and turned on Steam Controller #1 (sc1).  Steam saw it and I was able to interact with Steam.

I then turned on SCC and immediately it took control of sc1 away from Steam.  Lol.   Reversing the procedure and Steam was failed to take control of a dongle already "owned" by SCC.

Can SCC tell the difference between two dongles?  If so perhaps something can be done to disable emulation on additional controllers using their own dongles?

**Comment by kozec** [comment]
> Can SCC tell the difference between two dongles? If so perhaps something can be done to disable emulation on additional controllers using their own dongles?

Nope, dongles are, AFAIK, practically identical. I can add some kind of config file-only setting to ignore devices by bus ID, so anything connected to, for example, left-front USB port would be ignored, but that's as far as is technically possible to go with this.

**Comment by LinuxJoeUser** [comment]
> I can add some kind of config-file-only setting to ignore devices by bus ID, so anything connected to, for example, left-front USB port would be ignored, but that's as far as is technically possible to go with this.

That sounds like it would do it, don't you think?  
If I understand what you're saying, could scc check the config file for which SC "belongs" to which bus ID? If so, couldn't SCC arbitrarily assign an arbitrary label (USBx) where x=the order in which the USB port was detected (or something?)  Then if that info was presented somewhere (hovering over the left side SC icon for each SC?) as "USB 1" or  "USB 2," then couldn't an "Ignore this devices USB port" entry be an option added to the right click menu?   :grinning:

**Comment by kozec** [comment]
Soo... I've tried to make this working, but it's pretty-much impossible. Main issue I overlooked is that new, unique device address is generated every time when you connect USB device and since that's only way how to tell difference between two dongles, it's not possible to use it in configuration.

Sorry, but this is not fixable :(

**Comment by LinuxJoeUser** [comment]
No worries, kozec.  Thank you for trying.  I really appreciate all you're doing.  I've been playing with the new build today, and I have to say, I like what you've done *a lot!*  I really like the way you use tabs under "More..." Good design!
