### ISSUE TITLE
UI window top bar enhancement #3: Enhance Undo/Redo icons

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#151]
Enlarge "Undo" and "Redo" icons, and improve their visibility for dark and light themes.
[Picture](http://imgur.com/a/C38gR)

**Comment by kozec** [comment]
Hmm... I believe those icons are dictated by theme.

**Comment by LinuxJoeUser** [comment]
Ah, so they are.  Indeed my particular combination of _Arc-dark_ theme and _Faenza_ icons was about as bad as it could get.  I changed _Faenza_ to _Faenza-Darker_ and all is well. :)

Not an issue after all.  Closed.
