### ISSUE TITLE
UI window profile management #1: Turning off 1 controller, not all.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#152]
Condition: Multiple controller profiles shown as available.

Make it so right clicking on a chosen controller and choosing "Turn off controller" only turns off the controller chosen.  Currently all controllers are turned off regardless of which controller is chosen.

**Comment by kozec** [comment]
Hmm... This is most likely bug, it shouldn't happen. I'll check why it does it.

**Comment by LinuxJoeUser** [comment]
Groovy :)

**Comment by kozec** [comment]
It's not every day that I can fix 4 issues fixed in 4 commits 8-)
