### ISSUE TITLE
UI window profile management #3: Blank "New Profile." 

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#154]
By default, make a "New Profile" blank (except for Default Global Menu, of course).

**Comment by kozec** [comment]
I thought that making copy is feature :) How about checkbox with line like "create empty" in that new profile dialog?

**Comment by LinuxJoeUser** [comment]
Being able to easily  make a copy of a profile is a nice feature. :)

The thing is that the word "New" *means* "unused, just created, fresh."  So the phrase "New Profile" really means an unused, just created, fresh profile --- thus a blank profile.  If you wanted to add a check-box that then said "Create copy of current profile," that would make more sense.

**Comment by kozec** [comment]
Yeah, "Copy current" unchecked by default would probably be best way how to not hide it too well. And menuitem from #155 can just call same window with that value checked.
