### ISSUE TITLE
UI window profile management #5:  Keep copied profiles alphabetical

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#156]
In order to keep copies of profiles listed alphabetically with their profiles, remove "Copy of" from the front of copied profiles, and add "(copy)" to the end.  This becomes more and more useful as a user's list of profiles grows.

**For example:**
- "Copy of My Desktop v1.3"
would become
- "My Desktop v1.3 (copy)"

Thus a list of "My Desktop" versions would list copies as well as originals:

**For Example**
My Desktop v1.0
My Desktop v1.1 
My Desktop v1.1 (copy)
My Desktop v1.2
My Desktop v1.3
My Desktop v1.3 (copy)
etc.

Otherwise (as it is now) all copies of all profiles are lumped together at the very beginning of the Profile List.

**Comment by kozec** [comment]
Sounds possible, but it may turn into hell once I'll enable localisations :D

But for English, why not.

**Comment by LinuxJoeUser** [comment]
Lol, well I and the rest of the English speaking world thank you, to be sure. :)  Out of curiosity, though, what makes it hellish for other languages?  I mean more than changing any other text in the program?  I would have thought that, well, in Spanish, it might look like: 

Mi fondo de escritorio v1.0
Mi fondo de escritorio v1.1
Mi fondo de escritorio v1.0 (copia)
etc.

instead of "Copia de Mi fondo de escritorio v1.0" (etc.)

I'm only curious.  Please don't think I'm arguing for this. :)

**Comment by kozec** [comment]
Well, in my language, "Náhodný profil (kópia)" sounds weird. But I saw worse thing, so np.
