### ISSUE TITLE
UI window profile management #6: Template option

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#157]
Add "New Template" to list of profile options;
Add "Create copy as Template" to right-click profile options, so that any profile can be made into a template. 
A Template would be like any other profile with two exceptions:
1. The word "Template" is automatically added to the front of the profile name;
2. Any changes to a template have a warning "You are about to make changes to this template.  Are you sure?"

Templates are then easily created, alphabetized together, and are (slightly) less easily changed than ordinary profiles.

**Comment by kozec** [comment]
So, it works little differently from what you requested, but this is now done :)

To turn profile into template, choose "Profile Details" from profile options menu and check "Profile is Template". Rest is the same.
