### ISSUE TITLE
Enhancement: Inner / Outer pad settings.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#158]
Like Steam's configuration ability: create the ability to assign an input to an "outer ring" on a pad in addition to the "inner" settins of the pad.  Then allow these to be reversed, so there is one "inner" pad setting and (in the case of a DPad, for example) 4 or 8 outer settings.

See Valve's implementation of this idea as a model BPM > [game] > Manage Game > Controller Configuration > ( R or L pad) Style of Input > Directional Pad > Advanced > Outer ring radius / Outer ring binding / Outer ring invert.  

In some cases this allows for a separate 5th button to be added at the center of a 4 way DPad.

In other cases this allows for two movement speeds to be assigned to a stick or pad.  For example, in Half-Live WASD is sprint by default, needing SHIFT to walk slowly.  I programed WASD to the LPAD and LSHIFT to the outer ring, then inverted it.  The effect is that using the inner pad, I move slowly ... LSHIFT is applied to WASD.

Ideally this ability would be available to any Input that had a deadzone: Pads, Joysticks, etc.

**Comment by kozec** [comment]
_(I'm not ignoring this, it just sounds like good idea and I have nothing to add)_

**Comment by kozec** [comment]
Just a note, this currently works in git and allows choosing all 9 slots in Minecraft, what's making me really happy :)

But only with custom-action. GUI incomming.
