### ISSUE TITLE
Crash when pressing the new button in 0.2.1

### ISSUE THREAD

**Issue by azizLIGHT** [kozec/sc-controller#16]
I think this is another Ubuntu 14.04 specific issue. When pressing [this button](http://i.imgur.com/LQHq8XG.png), sc-controller crashes and my system reports the crash as "sc-controller crashed with GError in load(): /usr/share/scc/glade/ae/gyro.glade:22:1 <object> requires attribute "id"
[Here's some more detail](http://i.imgur.com/KqBLLWi.png)

**Comment by kozec** [comment]
On day I'll meet guy that decided that check is a good idea and I'll end in jail :(
