### ISSUE TITLE
Code formatting is wrong

### ISSUE THREAD

**Issue by jrial** [kozec/sc-controller#160]
Just checked out the code to toy around with, and noticed the majority of the code is indented with tabs instead of spaces.

While I also much prefer tabs rather than spaces wherever possible, Python has made the choice of using spaces (4 spaces per indentation level) for their style guide. This convention is used by every serious Python developer out there. Most Python developers have set up their tools accordingly, and every Python-aware editor uses this style for Python code. Those developers will now have to be very careful when contributing, because their editor will insert spaces. Which leads to mixed tabs/spaces for indentation. Which leads to hard to debug breakage.

```
sc-controller$ echo -ne "Spaces  :  " && ack-grep '^ ' --py |wc -l && echo -ne "Tabs    : " && ack-grep '^\t' --py |wc -l
Spaces  :  3462
Tabs    : 22838
```

**Comment by kozec** [comment]
Only code indented with spaces should be in scc/lib/libusb1.py and that library is included as-is only because it's not available in many distros. Converting it to tabs would only make it harder to update.

Everything else uses tabs "to remain consistent" with everything else :)

**Comment by jrial** [comment]
I think you misunderstood me: the library code is fine. It's all the rest that's wrong. The spaces shouldn't be replaced by tabs, the tabs should be replaced by spaces.

Python is an indentation-based language, so indentation needs to be consistent. Either all tabs, or all spaces. The Python community has chosen to use 4 spaces. You can use whatever you want: tabs, more spaces, less spaces, but in doing so you're going against the style guide for the language that every developer follows. This means that almost nobody will be able to contribute to your project without fiddling with their editors' configurations. This limits the number of people willing to contribute.

As a practical example: I opened your code in my editor, and immediately I'm greeted by an explosion of error messages. Every single line is marked with "wrong indentation". This makes the code harder to read (the red squigglies are very distracting). If I change something, and save, my editor will automatically convert your tabs to spaces, changing your entire file. Even if all I do is add one line of code. So I need to tell it not to do that, but then it's configured wrong for my day job. So after I'm done working on your code, I need to reconfigure my editor again for "real" Python work. The net effect is that I won't bother; too much hassle. Nor will any serious Python developer. This means that you are discouraging the people with the best knowledge about the language from contributing to your project.

If that's your intention, then fine. Your software, your call. Just thought it was worth mentioning.

For the record: I also think Guido made the wrong choice; the unit of indentation should have been the tab, not a fixed number of spaces. But the choice has been made, all Python code follows the convention, and all Python tooling is set up for it.

**Comment by kozec** [comment]
Well, while I'm aware of pep that _suggests_ spaces, I'm not really sure about that community and "real" Python parts, as I have yet to meet anyone who actually indents with spaces :)

But that's not a problem. Problem is that converting 31398 lines of code (and commiting that diff to git) doesn't really sounds like good idea. I would even say that this is something that was already decided, probably even before entire project started, as I reused some code for GUI parts.

So, code formatting works as expected :)

**Comment by jrial** [comment]
> I'm not really sure about that community and "real" Python parts, as I have yet to meet anyone who actually indents with spaces

In other languages, you're right. In Python, take it from a professional Python developer: a lot of people (myself included) start out with this rebellious idea of doing things the "sane" way. And then we need to work with others and realise our code causes nothing but friction. Nearly all Python code out there is indented with 4 spaces because it's just easier to follow the convention than to constantly introduce weird bugs when working on others' code.

But as I said: your code, your call. I'm unsubscribing from this project though, since I don't plan on jumping through hoops in order to contribute the occasional small patch.

**Comment by kozec** [comment]
Frankly, I'm surprised this is problem at all, as I never had issue working with those few space-intended files.

Maybe I just have luck with editors capable of autodetect indentation style.
