### ISSUE TITLE
Error stops daemon when rumble support is enabled

### ISSUE THREAD

**Issue by Ryochan7** [kozec/sc-controller#163]
I wanted to check out the newly added rumble support but I am having a problem with it. I have only tested it with Borderlands: The Pre-Sequel which is a Linux game that does have rumble support when using a physical 360 controller. Whenever rumble support is enabled for the scc-daemon, I keep getting the following error after a short period of time and controller input will get stuck. Also, I never feel any rumble even during events when rumble would be active for a physical 360 controller.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/steam/Sources/sc-controller-vanilla/scc/drivers/sc_by_cable.py", line 90, in _timer
    self.flush()
  File "/home/steam/Sources/sc-controller-vanilla/scc/drivers/usb.py", line 106, in flush
    msg = self._cmsg.pop()
IndexError: pop from empty list
```

No error occurs if rumble support is disabled. I will have to try rumble support in some other programs and see if I run into the same problem.

**Comment by kozec** [comment]
That's pretty weird, as that exception comes from `while len(self._cmsg): msg = self._cmsg.pop()` block. I thought it's some kind of race condition, but it's also called while lock is being held...

Anyway, I'll investigate...

**Comment by Ryochan7** [comment]
Worse scenario. Saints Row 4 won't launch unless rumble support is disabled; it just hangs on startup. I have also tested rumble support with sdl2-jstest and rumble did work with that program.

**Comment by Ryochan7** [comment]
Error received from daemon when attempting to launch Saints Row 4.

```
Traceback (most recent call last):
  File "scripts/scc-daemon", line 35, in <module>
    main()
  File "scripts/scc-daemon", line 31, in main
    daemon.debug()
  File "/home/steam/Sources/sc-controller-vanilla/scc/sccdaemon.py", line 903, in debug
    self.run()
  File "/home/steam/Sources/sc-controller-vanilla/scc/sccdaemon.py", line 537, in run
    fn()
  File "/home/steam/Sources/sc-controller-vanilla/scc/poller.py", line 51, in poll
    self._callbacks[fd](fd, Poller.POLLIN)
  File "/home/steam/Sources/sc-controller-vanilla/scc/mapper.py", line 106, in _rumble_ready
    count = ef.duration * ef.repetitions / 30
  File "/home/steam/Sources/sc-controller-vanilla/scc/controller.py", line 155, in __init__
    raise ValueError("Value out of range")
ValueError: Value out of range
```

Rumble support does work in Saints Row 4 with a physical 360 controller.

**Comment by kozec** [comment]
Ok, that last one is easy enough. But fact that it even tried to generate effect _that_ long is another problem. I have SR4, so I'll check later.

**Comment by kozec** [comment]
Removing threading altogether may sound like weird fix, but it was used to workaround lack of poling that's already implemented. Plus, wireless driver works in main thread and having them different only brings bugs like this one.

**Comment by Ryochan7** [comment]
Thanks for the fix. I found the problem regarding the flush method being called by two threads at the same time. Adding an extra lock worked out but moving the calls to the main thread is a simpler fix. Borderlands: The Pre-Sequel is playable again but no rumble effects happen.

Enabling rumble debugging in uinput.c shows that a lot of the FF events seen from Saints Row 4 are like this.

```
FF_PLAY -> 0 (lvl 16383) reps. 2147483647
```

**Comment by Ryochan7** [comment]
After some playing around, I got rumble to work in Saints Row 4 and Borderlands: TPS. For now, I have the FF_PLAY portion set repetitions to 1 on a non-zero value. Borderlands has a different event flow when it comes to rumble. The game will send an FF_PLAY event with a value of 1 when the game first launches. An FF_PLAY event with a value of 0 is not sent until quitting the game. FF_RUMBLE events are sent regularly. Making sure that feedback is generated on updated FF_RUMBLE events instead of just relying on the FF_PLAY portion is needed.

Also, there is break statement missing in the EV_UINPUT case in uinput.c. Both inner portions in the switch are executed when an EV_UINPUT event is seen. Adding a break at the very end of the EV_UINPUT portion is enough to get around that problem.

**Comment by kozec** [comment]
Wait, so they basically play one never ending effect and just changing its properties on the fly? That's crazy...

But yeah, it should work :(
