### ISSUE TITLE
Touchpad release events sometimes get ignored

### ISSUE THREAD

**Issue by Ryochan7** [kozec/sc-controller#164]
Sometimes when releasing and then pressing the touchpad again, the mouse cursor would appear in a completely different part of the screen as opposed to staying fixed on roughly the spot where the cursor was. Experiments seem to have shown instances when touchpad release events are read by the input thread but then removed by the action thread before it is used.

In sc_by_cable.py, it looks like _last_tup is a shared resource between two threads but no locking is occurring when SCByCable._wait_input is called. I have seen situations when the action thread is in SCByCable._timer and SCByCable._wait_input writes an event to _last_tup followed by SCByCable._timer setting _last_tup to None. Acquiring the lock in the _wait_input method seems to be needed.

**Comment by kozec** [comment]
... okay, that would be that race condition I'm searching for :)

Thanks, I don't have access to my normal PC right now, but I'll try to fix it today.
