### ISSUE TITLE
Macro Binding Constantly Sending Keypress After Activation

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#169]
Found an issue where setting a macro like this:

http://imgur.com/G0q20eN

Instead of pressing Z, waiting, the pressing z again, the second press it instead just keeps spamming z. This happens no matter what the second option is set to (click, press or release).

**Comment by kozec** [comment]
Well, that's what you are telling it to do... Are you trying to do "click Z, delay 500ms, click Z" ?

**Comment by kozec** [comment]
Also, that above fix was bug in UI and has nothing to do with actual problem. That's exactly why I linked it here :)

**Comment by kozec** [comment]
Core problem should be fixed elsewhere and rest works as it is supposed to, so I'm closing this one.
