### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by Zer0t3ch** [kozec/sc-controller#17]
Have you considered managing a package on the AUR for your Arch users? If you'd rather not, I might be able to do that. (It's _relatively_ simple)

**Comment by kozec** [comment]
I'm kinda banned from Arch since I dared to question changes in `makepkg` :D

But feel free to add it yourself, there is even [PKGBUILD](https://github.com/kozec/sc-controller/blob/master/PKGBUILD) that should work in repo.

**Comment by Mocha-Bean** [comment]
I've created an AUR package. Seems to be working.

**Comment by Zer0t3ch** [comment]
@Mocha-Bean You could always automate the version number editing :laughing:

**Comment by kozec** [comment]
> (even if i have to edit the version number myself! *shakes fist angrily*)

That's weird, you have same pkgver() function as I do and it updates version automatically here:

```
$ makepkg
==> Making package: sc-controller-git v0.2.4.r0.6a66907-1 (Mon May 23 07:54:00 CEST 2016)
==> Checking runtime dependencies...

...

==> Extracting sources...
  -> Creating working copy of sc-controller git repo...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 0 (delta 0)
Unpacking objects: 100% (4/4), done.
From /data/tom/Compile/SCC/sc-controller
   e8d4af0..33a7eff  master     -> origin/master
   4f780fa..33a7eff  osd        -> origin/osd
Reset branch 'makepkg'
==> Starting pkgver()...
==> Updated version: sc-controller-git v0.2.4.r1.33a7eff-1
==> Removing existing $pkgdir/ directory...
==> Starting build()...
...
```

(4th line from bottom)

Anyway, thanks for your help :)

**Comment by Mocha-Bean** [comment]
@Zer0t3ch Yeah, I plan to do that, I just need to get good at bash scripting.
