### ISSUE TITLE
Some Configuration Attempts Confuse Macro UI

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#170]
Sometimes the Macro UI can get confused, and end up with weird configs that seem like they shouldn't be valid. For example:

https://imgur.com/a/1F3Jl

Note the "Press | Press Z". When trying to open that first option it jumps straight to the custom editor. I only used the UI to change settings (no manual edit)

This can be caused by:

1. Adding a binding/event
2. Change event to press
3. Switch to click or release then back to press event

The first event will now have " Press | Press Z" as you see above and the config shown also has an extra (unnecessary?) press in it. Tested with stable (0.3.6)

**Comment by kozec** [comment]
There is a good chance I just fixed this in 12b38f868da94bcfbcc623d35191e7a40f028d49, but I'll check just in cause.

**Comment by kozec** [comment]
Yep, definitely fixed in 12b38f8 :)

**Comment by GlacialTurtle** [comment]
I think you did, I got a bit confused between what I was trying to do and the bug it seems and basically reported it twice :/

**Comment by kozec** [comment]
No problem, better that not catching it at all :)
