### ISSUE TITLE
Mouse Region doesn't work with XWayland or Wayland

### ISSUE THREAD

**Issue by Kierek** [kozec/sc-controller#173]
When I try to edit Mouse Region under pure Wayland it simply crashes, but when I move my finger on the the assigned pad my cursor "moves without moving". It only changes back and forth from normal cursor to the writing one.

> [kierek@kierekDesktop ~]$ sc-controller
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/ae/axis_action.py", line 354, in on_cbAxisOutput_changed
    self.update_osd_area(action)
  File "/usr/lib/python2.7/site-packages/scc/gui/ae/axis_action.py", line 95, in update_osd_area
    self.osd_area_instance.show()
  File "/usr/lib/python2.7/site-packages/scc/osd/area.py", line 53, in show
    OSDWindow.show(self)
  File "/usr/lib/python2.7/site-packages/scc/osd/__init__.py", line 207, in show
    self.make_window_clicktrough()
  File "/usr/lib/python2.7/site-packages/scc/osd/__init__.py", line 180, in make_window_clicktrough
    win = X.XID(self.get_window().get_xid())
AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'
Naruszenie ochrony pamięci (zrzut pamięci)

Under XWayland it's more interesting. I can successfully edit settings, it even draws this green rectangle, relative to my coordinates, but after touching right pad it still acts exactly the same as with Wayland. 

Is this another feature that will be impossible to do because of Wayland's design? Or can I still hope that some update to GTK will enable support for osds and whatever is needed for mouse region to work(osds as well?)?

**Comment by kozec** [comment]
> Is this another feature that will be impossible to do because of Wayland's design?

Yep, most likely...

But I'll try to at least stop it from crashing.

**Comment by kozec** [comment]
> Under XWayland it's more interesting. I can successfully edit settings, it even draws this green rectangle, relative to my coordinates, but after touching right pad it still acts exactly the same as with Wayland.

I doubt this will work, but you can try disabling emulation (to stop scc-daemon) and run it with `GDK_BACKEND=x11 scc-daemon debug`. That way it should be able to talk to xwayland and should at least be able to work with screen-relative areas.

But positioning area based on window pos&size is not possible by design.

**Comment by Kierek** [comment]
> I doubt this will work, but you can try disabling emulation (to stop scc-daemon) and run it with GDK_BACKEND=x11 scc-daemon debug. That way it should be able to talk to xwayland and should at least be able to work with screen-relative areas.

Unfortunately it doesn't change anything.

**Comment by kozec** [comment]
> Unfortunately it doesn't change anything.

Is there any error message on from daemon?

**Comment by Kierek** [comment]
It's hard to reproduce, because most of the times it acts and looks exactly the same on Wayland and XWayland, but it seems that I've finally managed to caught something. I'm not sure if it's related to this issue though.

> X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x0
  Serial number of failed request:  1217
  Current serial number in output stream:  1218
D OSD DaemonCtrlr   Connection to daemon lost
E OSD osd.daemon    Connection to daemon lost

**Comment by kozec** [comment]
And with this, I hereby pronounce SCC on Wayland crippled enough to run without crashing :)

**Comment by Kierek** [comment]
Hooray! Wayland is truly the modern experience we all deserve.
