### ISSUE TITLE
Deadzone modes

### ISSUE THREAD

**Issue by kozec** [kozec/sc-controller#174]
Separating this from #168 just so I don't forget about it

Deadzone setting should have multiple modes:
 - `cut` - as it works now, all positions below minimal  **and** above maximal value are translated to 0 and when input values goes over min/max, output value "jumps".
 - `cut below` - positions below minimal value are translated to 0, above maximum are translated to 1 (or maximal value of output), still with "jumping"
 - `linear` - output value is computed as [`out = clamp( ((input - min) / (max - min)) * output_range)`](https://repl.it/FBNY/13), so output value doesn't "jumps" and always covers entire output range.

This is not really issue, just glorified TODO, but comments are welcomed :)

_// edit: removed deadzone scream_

**Comment by LinuxJoeUser** [comment]
I don't understand what you mean by "jumps" in your examples, but the idea of multiple deadzone modes is intriguing.  

(Also, and with the greatest respect for your command of English, I'd like to point out that the word you want is *below,* with one *l* meaning "under, underneath, less than."  *Bellow,*  with a double "l," means ["shout or roar loudly"](https://en.oxforddictionaries.com/definition/bellow).  At first I thought it was a programming term. :D)

**Comment by kozec** [comment]
Wait, you really never heard deadzone shouting? It's pretty nerve-wrecking :D

By "jumping", I mean abrupt change from 0 to some large value. Currently, deadzone generates output like this...

![img1](https://cloud.githubusercontent.com/assets/1282500/22550301/bae1c52c-e94f-11e6-98cd-a412c7542df5.png)
(with code similar to [this one](https://trinket.io/embed/python/4a70840c94))

... what's fine and probably works as expected, but there is also another option that may works better in some cases:

![img2](https://cloud.githubusercontent.com/assets/1282500/22550477/8d47a81a-e950-11e6-9d45-33caa12a5a92.png)
([code](https://trinket.io/embed/python/00363c2d56))
