### ISSUE TITLE
Difficult to reach corners in grid menu

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#175]
Just a small issue with grid menu binding is that it's difficult to hit corner and bottom bindings. With corner buttons I can barely get the cursor within the button area even when the thumb is near the edge of the pad (which sometimes leads to cursor shaking) and bindings at the bottom the cursor tends to stop halfway into the button area, with bottom bindings typically being a little harder to hit without my thumb nearly reaching the end of the pad.

This issue technically applies to list in that it's awkward to reach edges of the menu, but the way it's are laid out means it isn't really an issue for them in practice, only for grid.

**Comment by kozec** [comment]
I can increase limits. Question is, how many items do you have there? Can you add screenshot?

**Comment by GlacialTurtle** [comment]
Here's one with just 9 items for a weapon switch or squad selection (RTS) grid:

http://imgur.com/a/yNc02

When moving my thumb around the pad then trying to hit that bottom right corner that's as far as it will go with my thumb as far as possible in the bottom right without going off the pad. Sometimes just touching immediately to the bottom corner will reach it OK, but any prolonged movement seems to cut off being able to reach the centre of the button.

Here's a second one with list view and my thumb in the bottom right again:

http://imgur.com/a/sufcT 

Similar happens in the bottom left but not quite as bad.
