### ISSUE TITLE
Grid menu vertical/horizontal setting & height/width setting

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#176]
A feature request for the grid menu option I think would be useful would be for a vertical and horizontal setting as well as height/width controls.

My idea would be for it work like this:

In horizontal mode, grid menu fills out left to right as it currently does. This could be combined with a width setting so that with a setting of 5, every 6th button would start a new row below the current one, for example.

In vertical mode, grid menu fills out from top to bottom. A height setting would control when a new column would be started, so that with a setting of 5, every 6th button would start a new column to the right of the current column.

There isn't really anything for the grid menu under the "more" item, so the settings could probably be placed there.

**Comment by kozec** [comment]
Sounds easy, so why not... But I think just "max width" option would be enough, setting it to low value like 2 or 3 would create menu that spans vertically.

**Comment by kozec** [comment]
There is no GUI yet, but with above, using `gridmenu('menuid, 2)` as custom action generates menu that has only two columns and as many rows as needed.

**Comment by GlacialTurtle** [comment]
Just tried it and it works great!

The only issue I noticed was that it was possible to add the option to the other menu types but with no effect or complaint from the UI.

**Comment by kozec** [comment]
> The only issue I noticed was that it was possible to add the option to the other menu types but with no effect or complaint from the UI.

That's intentional, I plan to use same option to limit number of rows (and enable scrolling) in normal menu and probably to specify size with radial menu. It can stay as undocumented feature that does nothing until then :)

**Comment by kozec** [comment]
(this should be done IIRC)
