### ISSUE TITLE
Icons in menu

### ISSUE THREAD

**Issue by kozec** [kozec/sc-controller#177]
... as I forgot about it twice. Biggest issue would be getting some actual graphics.

Just another TODO, but comments are welcomed.

**Comment by GlacialTurtle** [comment]
Here are some icon sets it might be worth looking at for inclusion:

http://opengameart.org/content/grayscale-icons

http://opengameart.org/content/36-free-black-and-white-icons

http://opengameart.org/content/brightmix-icon-set

http://opengameart.org/content/powers-icons - These have a textured background that might have to be removed before they can be used

http://opengameart.org/content/700-rpg-icons

http://opengameart.org/content/some-hud-elements-icons-and-crosshairs

And here is a load more:

http://game-icons.net/

License is CC-BY 3.0 - http://game-icons.net/about.html

Also, I know that Steam right now just lists every icon you stick inside the relevant directory. It's rather hidden so I think it's sort of accidental. It might make sense to make sure Icons are in sub-folders to help keep it organised by set/style.

**Comment by kozec** [comment]
> License is CC-BY 3.0 - http://game-icons.net/about.html

Whoa, this one is great. Maybe I should just add link to that site and allow drag-n-dropping image urls :D

> Also, I know that Steam right now just lists every icon you stick inside the relevant directory. It's rather hidden so I think it's sort of accidental. It might make sense to make sure Icons are in sub-folders to help keep it organised by set/style.

Yeah, I plan to make it in same way as everything else - one default/system directory in /usr and one user directory in ~/.config/scc. Adding subfolders to that shouldn't be a problem.
