### ISSUE TITLE
Broken PID file

### ISSUE THREAD

**Issue by MeDeVILe** [kozec/sc-controller#178]
I've got problem. I have installed sc-controller from github and from distro. Now controller doesn't pair and I don't know how to reinstall it to work correctly. [Linux mitn]

**Comment by kozec** [comment]
Uninstall everything you can, install it again preferably from package and then try running `scc-daemon -d` in terminal, so it displays error messages.

**Comment by MeDeVILe** [comment]
And how to remove it when it was installed by python?

**Comment by kozec** [comment]
With `rm` :)

Running `setup.py install --record record.txt` should generate list of installed files.

**Comment by MeDeVILe** [comment]
I have deleted all of records from both python2.7 and 3.4 
When I use run.sh sc-controller still have my profiles (don't know from where) and still controller doesn't work.
I've installed it from packages and purge it and still nothing.

I FU it so bad. :P

**Comment by kozec** [comment]
Well, if there were any record in python 3.4, you probably FUed more that I imagined :D

Profiles are stored in `~/.config/scc`, you can try move that away just to check but I don't think reason is there.

Anyway, what outputs `scc-daemon -d` when started from terminal?

**Comment by MeDeVILe** [comment]
`Traceback (most recent call last):
  File "/sc-controller-0.3.7/scripts/scc-daemon", line 35, in <module>
    main()
  File "/sc-controller-0.3.7/scripts/scc-daemon", line 29, in main
    daemon.restart()
  File "/sc-controller-0.3.7/scc/lib/daemon.py", line 141, in restart
    self.stop()
  File "/sc-controller-0.3.7/scc/lib/daemon.py", line 114, in stop
    pid = int(pidf.read().strip())
ValueError: invalid literal for int() with base 10: ''
`

**Comment by MeDeVILe** [comment]
scc-daemon -d
`usage: scc-daemon [-h] [--alone]
                  [profile [profile ...]] {start,stop,restart,debug}
scc-daemon: error: too few arguments
`

**Comment by kozec** [comment]
Ok, now I have no idea how this could happen, but try removing `~/.config/scc/daemon.pid`

**Comment by MeDeVILe** [comment]
yes it`s working! Thank you so much. 
I have a talent for creating strange errors

**Comment by kozec** [comment]
No problem :D

I'll add code to ignore broken PID files just in case :)

**Comment by MeDeVILe** [comment]
So I'm a tester now :)

**Comment by kozec** [comment]
Ffixed by cc951efb43043258a9612006e00cc63e6b35ba56, feel free to test it :)
