### ISSUE TITLE
"--Volume" and "+Volume" lables are backwards.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#180]
As you can see below, I chose the "Volume UP" symbol, but scc is labeling it as negative volume, that is, volume down.  (Choosing Volume DOWN gets labled "+Volume" as well).  

Everything *works* as it should, it's just labeled reverse from what it should be.  

http://imgur.com/a/22FYY

**Comment by kozec** [comment]
Yeah, that's done to confuse any eventual enemy :)
