### ISSUE TITLE
Gyro-as-mouse won't "invert Y axis" as Mouse (Desktop)

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#181]
When the "Invert Y axis" box is checked, axis does not invert after clicking "OK".  And although the Y axis *does* change to "--1.0", the X & Y axis are greyed out and cannot be manually adjusted.

**Comment by kozec** [comment]
I'm starting to believe that window is cursed, every time I fix one bug there, something else breaks :D

**Comment by LinuxJoeUser** [comment]
Lol.  That was the only thing keeping me from starting to create proper profiles for games --- and now it's fixed, so I shall procede.  (Btw, I've begun studying Python 3 in the hopes that I might be able to tinker with the code for sc-controller.  It's the first programming language I've studied since I learned BASIC when I was in high school.)

Keep up the great work, kozek!  Sc-controller is awesome!
