### ISSUE TITLE
Inner ring-as-Dpad multi-key setting usage issue

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#184]
__Scenario__
Setting up a profile for an *Halflife 1*, or similar FPS that uses an additional key press to cause movement speed change.  For example:  W moves character forward quickly (running), but W + SHFT moves character forward slowly (walking).  Pad doesn't require click to activate.

__Condition__
Setting the left pad as outer ring = WASD Dpad, inner ring = WASD + SHFT so that touching the outer ring will cause character to "run" and touching the inner ring makes the character "walk"
`ring(0.86,
dpad(
button(Keys.KEY_LEFTSHIFT) and button(Keys.KEY_W),
button(Keys.KEY_LEFTSHIFT) and button(Keys.KEY_S),
button(Keys.KEY_LEFTSHIFT) and button(Keys.KEY_A),
button(Keys.KEY_LEFTSHIFT) and button(Keys.KEY_D)
),
dpad(
button(Keys.KEY_W),
button(Keys.KEY_S),
button(Keys.KEY_A),
button(Keys.KEY_D)
)
)`

__2 (probably related) Issues__
1. Inner ring's diagonals not using the SHFT setting upon initial touch.  For example:  touching the diagonal between W + SHFT and A + SHFT results in running instead of walking forward to the left.
2. While "walking" using the inner ring, any change in direction automatically results in "running" behavior.

**Comment by kozec** [comment]
This most likely happens because "pressing shift" event being generated _before_ "releasing shit", but I'll have to check to make sure.

Meanwhile, you can use something like this:

```
ring(0.84, button(Keys.KEY_LEFTSHIFT)) and dpad(
    button(Keys.KEY_W),
    button(Keys.KEY_S),
    button(Keys.KEY_A),
    button(Keys.KEY_D)
)
```

It generates normal WSAD dpad and one big Shift button, bound at once on inner ring.

**Comment by LinuxJoeUser** [comment]
> It generates normal WSAD dpad and one big Shift button on inner ring, bound at once to same pad.

Excellent!!  This is *exactly* what I was trying to set up.  This absolutely needs to be built into the GUI somehow, though I'm not sure how, just at the moment.  I'll play with it more tomorrow.

**Comment by kozec** [comment]
> This absolutely needs to be built into the GUI somehow, though I'm not sure how, just at the moment.

Yeah, that's why it's not there :) Maybe just adding next row like this...

![pad](https://cloud.githubusercontent.com/assets/1282500/23581998/d8f7804a-0120-11e7-90cb-d4684a6d9c55.png)

... would be enough? Although I'm not sure if "Entire Pad" is clear enough for someone else to guess what's it supposed to do.

**Comment by LinuxJoeUser** [comment]
> I'm not sure if "Entire Pad" is clear enough for someone else to guess what's it supposed to do.

I see your point.  Thinking about it for the last hour or so, I'm inclined to say that Steam's solution may be the way to go, for now at least.  So instead of having "Ring Bindings" in the window's bar, add an "Outer Ring" tab beneath the under the "More..." selection, below "Smoothing."  

Selecting the "Outer Ring" tab, we would see an "Enable Outer Ring" checkbox.  If enabled,  a select button/key binding window opens (the one with the picture of a Controller and a Mouse and "Grab a key" at the bottom) and we ccould then bind a button/key to that ring.  We can then invert the outer ring to become an inner ring, if that's what we want.   

For example, in games like Half-life, where the shift key is "walk" we would map a WASD pad to the LPAD, enable the outer ring, grab the "Shift" key, and invert it and get the "big button" solution you offered above.  If the game were like Payday, where the Shift key makes the character run, then we would do as above, but *not* invert the outer ring.

I feel that there's a better solution, but I'm going to have to do some smore ketching and thinking.

**Comment by kozec** [comment]
> Eat it Steam, SC controller is waayyyy better just for being able to do that! :)

I'm accordingly proud of that :)

> I see your point. What about adding a "Bind Button/Key" option in the "Output" list offered for each ring. If selected the user would be offered the "Action Binding" UI (the one with the gamepad and mouse graphics, and "Grab a Key" at the bottom. The selected key/button could then be mapped to that ring, either inner or outer.

I'm not sure it that allows what are you trying to do. Assigning key to inner/outer ring is not problem even now, what you need is GUI option to add dpad binding to pad as whole.

**Comment by LinuxJoeUser** [comment]
> what you need is GUI option to add dpad binding to pad as whole.
Ok, I think I see what you're saying.  So, we need a setup where the inner & outer ring are separate (like with my awesome mouse wheel around my mouse on Rpad) and a setup where the outer ring *overlaps* or lays "on top of" one big DPad.  

How about a checkbox or dropdown for the Outer Ring that offered two choices:
1.  Overlapping Outer Ring (with one big Dpad button, for example as the Under/Inner ring)
2.  Separate Outer Ring. (As the default GUI now exists).

In both cases, the "Inner Ring" slider would become the "Outer Ring" diameter and work from the right end outward (if possible), otherwise tooltip that the dark area is that covered by the outer ring is all.

> Assigning key to inner/outer ring is not problem even now,

Lol, I can't figure out how.  XD  With the GUI you mean?  I feel stupid, but how do I do that?

**Comment by kozec** [comment]
> Lol, I can't figure out how. XD With the GUI you mean? I feel stupid, but how do I do that?

Sorry, that was my mistake. Binding to buttons is indeed not visible for pad bindings, mainly because this is probably first time it makes any sense to do it. I'll fit it somewhere.

Anyway, Ring relationship (ring overlapping?) sounds good and pretty easy to do. I'll roll with that :D

**Comment by LinuxJoeUser** [comment]
> Joystick -> Output -> Button makes sense.

Agreed!  (There would be a Pad binding as well?)

> Ring relationship (ring overlapping?) sounds good and pretty easy to do. I'll roll with that :D

It makes me feel good to hear you like the idea.  

I think I may like your idea of "Ring Overlapping" instead of "Ring Relationship (though "Ring Overlap" would be stronger, grammatically).  If we go with "Ring Overlap(ping)" instead of "Ring Relationship" then I suggest that instead of __"Keep rings separate"__ we instead use __"No Overlap"__.

**Comment by kozec** [comment]
> Agreed! (There would be a Pad binding as well?)

Yes, same thing for both pads and stick.

> then I suggest that instead of "Keep rings separate" we instead use "No Overlap".

Sounds good to me :)

**Comment by kozec** [comment]
By the way, this is already fixed for some time, I just forgot to close the issue.
