### ISSUE TITLE
Dpad-as-Menu window missing menu "control" and "position" options

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#185]
L/R Pad > Dpad/Menu > Output Type > Menu:  "Control Options..." and "Menu Postition ..." are not available to user.

viewable here:  http://imgur.com/a/braiK

**Comment by kozec** [comment]
Yes, that's intentional, those options are given when menu is bound to dpad. Is there anything that would make sense as option there?

**Comment by LinuxJoeUser** [comment]
> those options are given when menu is bound to dpad.

I guess I'm not understanding something here, because the options clearly *aren'*t available via the method resulting in my last photo at imgur: Photo #1 http://imgur.com/a/braiK 

However, if I choose LPad Press > Special Options > Action = Display menu, the "control" and "menu position" options *are* available as seen in this new photo: Photo #2 http://imgur.com/a/2S9Jz

In the first example I cannot set the control method nor the menu position for the menu, in the second example I can set those options.  I'm thinking adding the control and menu position options shown in photo #2 into the window shown in Photo #1.

See what I'm saying?

**Comment by kozec** [comment]
Sorry, by given I meant hardcoded. When you are assigning menu to button, you can choose what pad/stick should be used to control it and what button should be used to confirm/close menu. But when you are assigning menu to pad, those options are:

- "Control with" - pad you are assigning menu to
- "Confirm button" - option is confimed by pressing that pad
- "Cancel button" - menu is canceled if you lift finger from pad

So there is nothing to configure in that case.

**Comment by LinuxJoeUser** [comment]
> ... by given I meant hardcoded.

Ahhhh.  Damn.  Well, maybe there's a way it could be *faked* for a Pad?

Ok, if it's possible for the user to write a custom action (however complicated), then is it reasonable to assume that same custom action could be written and applied programically?  

If so then a solution might be to create a separate pop-up (like the inner/outer ring pop-up) that offers faux "Control Options" and "Menu Position" entries.  These would mimic the behavior of the hardcoded, real, options available to other buttons, but would "write" and "apply" custom actions for the Pad's menu.

Of course, I'm only guessing whether this is actually possible, seems like it should be.  But so often, what *seems* to be is sooo different from what heartbreakingly *is.* :)

**Comment by kozec** [comment]
Definitely possible. Thing is, entire SCC runs on "custom actions" and editor just generates them in user friendly way :)

But... I'm not really sure what are you trying to achieve here. You indeed can make menu, that shows when you touch left pad, but it's controlled by right one or stick, but wouldn't that be completely useless?

**Comment by LinuxJoeUser** [comment]
> You indeed can make menu that shows when you touch left pad and it's controlled by right one or stick,  but wouldn't that be completely useless?

Granted, it sounds a bit silly and useless to control a RPad touch menu with the stick or LPad.  But that's focusing upon the selection method and ignoring all the other aspects which really aren't silly:  

*  __The Confirm Button.__  I frequently prefer using the Right Trigger for RPad menu selection in games that use the Right Trigger (as Left Mouse) for making selections.  I commonly use the stick for radial menus ... but it is *extremely* awkward to click the stick to make a selection, much easier to use the R. Trigger in these cases.
* __Cancel Button.__  I would always want this to be whatever is acting as my ESC button, which is usually the Start button.
* __Confirm the Selection by Releasing the Button.__  Instead of the Confirm Button ... though here it would happen when the user stopped touching the pad ... the selection would be the last item chosen.
* __Menu Location:__  This should be there for the same reason it is everywhere else, so the user can choose where he or she would like to see the menu appear.
:)

**Comment by kozec** [comment]
I see...

Thing is, it's not a big problem to show those options, what I'm wondering right now is how to make them harmless enough by default :)

Maybe just replacing that checkbox with ...

```
[x] Confirm selection by pressing the pad
[x] Cancel menu when pad is released
```

would be good enough.

**Comment by LinuxJoeUser** [comment]
That sounds good.  And the ability to specify the Menu Location?  :)

**Comment by kozec** [comment]
> And the ability to specify the Menu Location? :)

Yep, that's included as well :)
