### ISSUE TITLE
Void template

### ISSUE THREAD

**Issue by Vintodrimmer** [kozec/sc-controller#186]
Good day,

Can you make a template file for the void distribution, please?

**Comment by kozec** [comment]
I'm not sure if I understand?

**Comment by Vintodrimmer** [comment]
It's similar to the Arch's PKGBUILD, but for Void linux.

Relatively small text-file that tells how to build a package. Like [that one](https://github.com/jaagr/void-packages/blob/polybar/srcpkgs/polybar/template).

I heard they are easy to make, but I've never had experience with them.

Can you make one, please?

It's not very important, so don't feel obligated. Just in case you know how to make them, it will be great to have one.

**Comment by Vintodrimmer** [comment]
Hello once again.

I think, I have created the template.
Is there some post-install required, or just building it is ok?

If it's the second option, please, check the [template](https://github.com/Vintodrimmer/void-packages/blob/sc-controller-branch/srcpkgs/sc-controller/template) and add it to the list of packages, if you like.
I'm not sure, which dependencies are build-time only.

Also, may I PR it into the main Void repo with your permission?

**Comment by kozec** [comment]
> Is there some post-install required, or just building it is ok?

None I'm aware of, just installing it as any other python package should be enough.

> Also, may I PR it into the main Void repo with your permission?

Yeah, but wait hour or so and increase version by one, as I'm trying to get new release out right now :)

**Comment by kozec** [comment]
Also, you are missing pylibacl dependency, which provides [posix1e package](https://github.com/kozec/sc-controller/blob/03063406442c50a566a92815b2ae3d822fdd9ce7/scc/tools.py#L17)

It's actually optional, but try adding it if Void has such package.

**Comment by Vintodrimmer** [comment]
Doesn't look like there is one in the repos yet.

Sure, thanks.

**Comment by kozec** [comment]
[Done.](https://github.com/kozec/sc-controller/releases/tag/v0.3.8)

**Comment by Vintodrimmer** [comment]
Holy smokes, it's working!

I don't know when or even if the PR will be satisfied, so if you can, add template to the list of options for Void users.

**Comment by kozec** [comment]
Yeah, no problem :)

Is it this one? https://github.com/voidlinux/void-packages/pull/5952

**Comment by Vintodrimmer** [comment]
Yep.

But until it's pulled, you just need the template and anyone can build it on their machine.
