### ISSUE TITLE
SC Controller makes Steam not see my Steam Controller

### ISSUE THREAD

**Issue by LiamDawe** [kozec/sc-controller#188]
I never had this issue before on Ubuntu, but on Arch when installing SC Controller, it seems even when the application isn't open and emulation turned off, it somehow still blocks Steam from registering the controller.

Possibly related to https://github.com/kozec/sc-controller/issues/178? I don't seem to have a "daemon.pid" file as noted in that one.

Was installed by the Arch AUR: https://aur.archlinux.org/packages/sc-controller/

Rebooting fixes it, so I think something isn't getting turned off correctly?

**Comment by kozec** [comment]
Sounds possible. Can you, please, check if there is any proces having "scc-daemon" in name left behind and if killing it solves problem?

**Comment by xraynorm** [comment]
Im see this also on ubuntu 16.04 

ps ax|grep scc
30235 pts/17   S+     0:00 grep --color=auto scc

**Comment by Svenare** [comment]
I have the same problem.  scc-daemon stops when closing the application

**Comment by hexc0de** [comment]
try to disable generic xinput controller handling in steam client

**Comment by LinuxJoeUser** [comment]
I've had this problem since installing Arch-based Manjaro, as well.  I've been working around it by pulling the wireless dongle out and then plugging it back in, it's a nuisance but quicker than rebooting.

**Comment by kozec** [comment]
Funny thing is that I'm on Manjaro as well and can't replicate it no matter what.

Can _anyone_ check if that `scc-daemon` process gets terminated?

**Comment by xraynorm** [comment]
Im seeing this also on ubuntu 16.04. 

scc-daemon stop
ps ax|grep scc
5330 pts/2    S+     0:00 grep --color=auto scc

**Comment by kozec** [comment]
Sooo... I'm writing this here mainly because there may be someone around knowing how to fix it :D

What is happening is that when SCC takes over controller, related hidraw nodes are removed by kernel(?) and then they don't appear when controller is released.

I also checked that this was not a problem for Steam until recently (I have old version on my laptop), but it appears to check for those hidraw nodes specifically now. So I'm going to find how to make them reappear again :(

**Comment by kozec** [comment]
By the way, @ynsta, you may be interested in this, as same thing happens with your driver as well.

**Comment by kozec** [comment]
Fixed along with [bugfix release](https://github.com/kozec/sc-controller/releases/tag/v0.3.8.1)

**Comment by LiamDawe** [comment]
Fantastic work, thank you!

**Comment by neuromancer** [comment]
I don't know if it is related with this bug, but the last revision of sc-controller (in ArchLinux) is not closing correctly when I use the "Quit" option. It just hangs. Killing sc-daemon and sc-controller won't work to force Steam to detect my Steam Controllers.

**Comment by kozec** [comment]
Nope, that doesn't really sound related, as "Quit" should not terminate daemon by default. It's pretty-much just call to `exit(0)`

Try running `sc-controller` from console and check if there is any error message displayed when it hangs.

**Comment by neuromancer** [comment]
No errors. Just this:

```
$ sc-controller -v -d
D App           daemon status: unknown
D App           daemon status: unknown
pidfile /home/g/.config/scc/daemon.pid does not exist. Daemon not running?
D DaemonCtrlr   Connected to daemon, version 0.3.8.1
D DaemonCtrlr   Daemon reported profile change: None
D DaemonCtrlr   Daemon is ready.
D App           daemon status: alive
D DaemonCtrlr   Daemon reported profile change: None
W App           Daemon reported unknown profile: 'None'; Overriding.
D DaemonCtrlr   Daemon reported profile change: /usr/share/scc/default_profiles/XBox Controller.sccprofile
D App           Terminating scc-daemon
D App           daemon status: unknown
```

After waiting more than a minute, I sent it "ctrl+c" to close the program:

```
^CTraceback (most recent call last):
  File "/usr/bin/scc-daemon", line 35, in <module>
    main()
  File "/usr/bin/scc-daemon", line 27, in main
    daemon.stop()
  File "/usr/lib/python2.7/site-packages/scc/lib/daemon.py", line 127, in stop
    time.sleep(0.1)
KeyboardInterrupt
```

**Comment by kozec** [comment]
So it appears that daemon doesn't go away when requested. Try running `scc-daemon debug` in another terminal window before starting `sc-controller`, it should say why, but in worst case scenario, I can add timeout there that will kill daemon forcefully when this happens.

**Comment by neuromancer** [comment]
FYI, this is the complete log of scc-daemon using debug mode:

```
$ scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f8e65c7b7d0>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f8e65c7bd50>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f8e65c7bb90>
D SCCDaemon     Created control socket /home/g/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :1.0
D USB           USB device added: 28de:1142
D USB           USB device added: 28de:1142
D USB           USB device added: 28de:1142
D USB           USB device added: 28de:1142
D OSD DaemonCtrlr   Connected to daemon, version 0.3.8.1
D OSD DaemonCtrlr   Daemon reported profile change: /usr/share/scc/default_profiles/XBox Controller.sccprofile
D OSD DaemonCtrlr   Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
D SCDongle      Not requesting serial number for SC 1
D SCDongle      Got wireless SC with serial 1
D SCCDaemon     Assigned default_mapper to <SCWireless 1>
D SCCDaemon     Controller added: <SCWireless 1>
D OSD DaemonCtrlr   Daemon reported profile change: /usr/share/scc/default_profiles/XBox Controller.sccprofile
D USB           Releasing devices...
D USB           Releasing devices...
D SCCDaemon     Controller removed: <SCWireless 1>
D USB           Releasing devices...
```

**Comment by kozec** [comment]
Does it exits after `D USB           Releasing devices...` or it hangs for some time?

**Comment by neuromancer** [comment]
It hangs.
