### ISSUE TITLE
Install in user directory seem looking about files in OS path

### ISSUE THREAD

**Issue by kidburglar** [kozec/sc-controller#189]
Hello,

I install the application from GIT with python setup.py install --user so it install all in $HOME/.local but the application crash when I try to launch it because it search app.glade in /usr/share/scc... in place of $HOME/.local/share/scc/....

Cheers.

**Comment by kozec** [comment]
Frankly, I didn't even know there is `--user` option to install... I can check if there is way to detect such installation, but as workaround, you can use environment variable - set `SCC_SHARED` to `$HOME/.local/share/scc/`

**Comment by kidburglar** [comment]
Ok I will try that when I reboot the computer.

I use that because in Debian the python libraries are not really updated so when I can I store all the libraries / applications in .local like we can do it with pip2 install --user xxx to not broking the distribution.

**Comment by kozec** [comment]
So... I guess it worked? :)

**Comment by kidburglar** [comment]
Sorry I had not much time, but it look ok.
I don't have error message when I launch the application.

I have well a little question, is there a solution to uninstall it properly because I tried in the system path too so I would remove it properly and try again.

**Comment by kozec** [comment]
Not without package manager I'm afraid. You can try `python setup.py uninstall` or just manually remove everything in: `/usr/share/scc` and then

```
/usr/share/pixmaps/sc-controller.svg
/usr/share/mime/packages/scc-mime-types.xml
/usr/share/applications/sc-controller.desktop
/usr/lib/udev/rules.d/90-sc-controller.rules
/usr/bin/sc-controller
/usr/bin/scc-*
/usr/share/icons/hicolor/24x24/status/scc-*.png
```
