### ISSUE TITLE
Controller detected 2 times

### ISSUE THREAD

**Issue by Sayanel01** [kozec/sc-controller#193]
Hi, I've noticed that the controller is sometimes detected 2 times when using sc-controller with steam.

For example:
If playing towerfall ascension, I will always control two player. Like, in character selection, two characters will be selected, and I will play both simultaneously.
If playing Rocket League, everything is fine until I press start: Rocket League understands it as if a second player just joined on a second controller, and I will also control both player with my steam controller.

How did that happened?

**Comment by kozec** [comment]
Steam gained "generic controller support" and xbox pad support recently, so my 1st guess is that it grabs virtual XBox controller created by SCC and emulates another XBox controller on top of it.

Check if you have that option enabled in big screen mode (settings -> controller settings IIRC).

**Comment by Sayanel01** [comment]
You guessed well, that was indeed due to the "xbox configuration support" that I had to deactivate.
Thanks

**Comment by kozec** [comment]
Np. I'm afraid this is not fixable from SCC side as anything I could do to prevent Steam from picking it up would do same for games as well.
