### ISSUE TITLE
Radial Menu - Touch Release Cancel and Click Activate Combination not Working

### ISSUE THREAD

**Issue by ebelsx7** [kozec/sc-controller#194]
For the radial menu the options 'Confirm selection by clicking the pad' & 'Cancel menu when pad is released' can't be set at the same time.
The menu is displayed when the pad is touched but it continues to stay there, clicking the pad does nothing. Instead you have to press the A-Button to activate an entry and B-Button to close the menu.

**Comment by kozec** [comment]
This sounds like bug that I fixed in e5691509833da0a3192a06420e16dddef55b6ddf , but that fix is not yet released. Are you running from git or last released version?

**Comment by ebelsx7** [comment]
I'm running the latest release version available from the AUR. not the git version

**Comment by ebelsx7** [comment]
Will check it after the weekend, dont have acces to the steam controller for now.
Closing the issue if it works or keep you updated if anything went wrong :)
