### ISSUE TITLE
Issue with Left Stick Input

### ISSUE THREAD

**Issue by IronPiston** [kozec/sc-controller#195]
Using the default Xbox controller profile, the left joystick seems to not be registering a full input unless the stick is in a cardinal direction. For instance, having the stick at a 45 degree angle causes a character to move much more slowly than at a 90 or 270 degree angle. This is in comparison to the Valve Steam Controller drivers, which don't have this issue. I have tried adjusting things like dead zone and axis. but the joystick registers a smaller tilt than it should at any angle other than 90, 180, 270, etc.

**Comment by kozec** [comment]
OK, I had to test this, but all what Steam does is setting little higher sensitivity by default.

[This is how far can you reach with Steam emulation by default](https://cloud.githubusercontent.com/assets/1282500/25061521/9fc23f64-21b8-11e7-9a12-2def9fde3c00.png), so to get [same effect with SCC](https://cloud.githubusercontent.com/assets/1282500/25061546/49c71f52-21b9-11e7-88f3-9e87feae8b7e.png), just set sensitivity to 1.2

But I can set it as default.
