### ISSUE TITLE
Daemon crashing if xinput missing

### ISSUE THREAD

**Issue by gamer01** [kozec/sc-controller#196]
`xinput` is a dependency, but if it is missing the software simply crashes without a reasonabe error. I was figuring it out by reading the debug output.

I was connecting the controller by usb cable.

**Comment by kozec** [comment]
Well, stuff is kinda supposed to crash when you don't have all dependencies installed... But I'll check how to detect that and turn it into warning.

**Comment by gamer01** [comment]
I already told the package maintainers at Archlinux AUR.

But as a user i cannot know all the deps :D

Thanks for you fast reply.
