### ISSUE TITLE
Had to purge steam after using sc-controller

### ISSUE THREAD

**Issue by snkiz** [kozec/sc-controller#197]
Got my new steam controller fired up steam, an configured it. It was great. then I tried sc controller. seemed ok until I went back into steam. Now it isn't a steam controller, its an xinput device, the buttons are all screwed and the cursor is gone. Deleted sc-controller and rebooted and Steam sees my controller as a stem controller again but the button mapping is still messed up and the cursor is still gone. So now I have to reinstall steam and hope I don't lose my game saves. I sill don't know if it will fix it. I don't care why it happened just wanted to say thanks for ruining my 60$ purchase.

**Comment by kozec** [comment]
Well, you are welcome :)

Steam recognizing emulated XBox controller is what is supposed to happen, so I'm not entirely sure what problem was, but feel free to let me know if you ever found what caused it.

**Comment by snkiz** [comment]
So your program takes a steam controller and turns it into an Xbox
controller that doesn't work right with steam? I don't know why this was
even nessary. It works fine with steam open, no more overhead than your app.
