### ISSUE TITLE
Is there a way to reduce the size of the menu?

### ISSUE THREAD

**Issue by nstgc** [kozec/sc-controller#200]
Not an issue, but rather a question. The Pie menu is quite large. Is there an option that I'm not seeing to change the size?

**Comment by kozec** [comment]
Not yet, at least not easily, but it's planned feature since menu size was added for grid menu.

But as "hack", you can just scale down `radial-menu.svg` in something that will not break attributes too much.

**Comment by nstgc** [comment]
I'm not sure if I did something wrong or not, but now none of the menus will show. What I did was I `chmod 777 radial-menu.svg`, then used inkscape to chang the canvas size (ctrl+shift+D) to 256x256. I then used the transformation tool (shift+ctrl+M) to shrink to 256x256 px, then shift by (-128x,-128). Saved this. radial-menu.svg is the only file I touched, but the steam button menu isn't showing either. I turned off emulation, exited out of sc-controller, and restarted X. Still not working.

By the way, kudos for making something mostly by yourself that is more functional than what ValvE's in house team managed to do.

**Comment by kozec** [comment]
> edit2: I forgot to mention that there aren't any errors printed when I launched it from terminal with sc-controller.

Try running `scc-daemon debug`, that's part that is most likely crashing right now. What you've done should work unless inkscape managed to break that image, what it shouldn't.

**Comment by nstgc** [comment]
What I'm getting is 

> $scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7fd5fc77b0d0>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7fd5fc77b650>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7fd5fc77b450>
D SCCDaemon     Created control socket /home/briggs5/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
E USB           Failed to claim USB device 28de:1102 : LIBUSB_ERROR_BUSY [-6]
Segmentation fault (core dumped)

I tried restoring the svg from backup, but that didn't work. I tried reinstalling but that didn't help. Also I'm getting some error messages when run in terminal
>$ sc-controller
I StatusIcon    Using backend StatusIconGTK3 (primary)
(sc-controller:12464): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by kozec** [comment]
> E USB Failed to claim USB device 28de:1102 : LIBUSB_ERROR_BUSY [-6]

means that you have either Steam or old instance of scc-daemon running. Check `ps ax|grep scc` and kill everything that looks suspicious.

Why is it segfaulting is another question though...

**Comment by nstgc** [comment]
I have since powered down my computer and now I try again. The menus, both of them, are loading as expected. I turn off emulation and exit out of sc-controller. I retstart the program and am getting
>$ sc-controller
I StatusIcon    Using backend StatusIconGTK3 (primary)
(sc-controller:5526): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
pidfile /home/nstgc5/.config/scc/daemon.pid does not exist. Daemon not running?
W App           Daemon reported unknown profile: 'None'; Overriding.

Steam should not be running, and I expect sc-controller to have exited. In anycase, I turn emulation off and then back on without closing the program again. The menu is working. Again I turn emulation off then exit. Like before I resize the image, but this time I don't mess with the canvas. I restart sc-controller, turn emulation off and then back on again (required to get the menus to work again *shrugs*). It works. The pie itself is the same size as before, but the numbers and what-not are half sized. I run inkscape again and in the canvas menu choose to resize canvas to image. Close Inkscape and load sc-controller. Cycle emulation. Okay. The Steam button menu loads, but the radial one  does not.
[radial-menu.svg.zip](https://github.com/kozec/sc-controller/files/1009486/radial-menu.svg.zip)

**Comment by kozec** [comment]
Sorry for late response, I had to test it. Above fix should prevent crashes, but image still looks weird. I'm not sure if problem is that "arcs" are rotated around wrong point, or if  SVG renderer in GTK just can't deal with scaling...

Anyway, it may be faster to implement what you originally asked for :D I'll check it tonight, at least as option without GUI for now.

**Comment by kozec** [comment]
So, since you mentioned you are running `sc-controller-git` from AUR, you should be able to upgrade and change this...

![shot](https://cloud.githubusercontent.com/assets/1282500/26274362/8edc6868-3d48-11e7-815c-ed6e0a5da738.png)

... option in GUI.
