### ISSUE TITLE
No OSD menu and Keyboard overlay

### ISSUE THREAD

**Issue by corvusd** [kozec/sc-controller#201]
From a few days ago, the OSD menu and Keyboard overlay not work.

**Comment by kozec** [comment]
That's bad to hear. Did anything interesting happened few days ago?

**Comment by corvusd** [comment]
I dont know... It possible, see log for add more data?

**Comment by kozec** [comment]
Disable emulation from menu and then run `scc-daemon debug` in terminal.

Then, copy-paste everything it writes when you are trying to display menu to something like pastebin and include info about your distro and environment :)

**Comment by GlacialTurtle** [comment]
Not sure if it's the same issue, but OSD and menus and have been broken for me too in 0.3.9. with scc-daemon debug I get:

> E OSD osd           Failed to apply css with user settings:
> E OSD osd           gtk-css-provider-error-quark: <data>:45:12'min-width' is not a valid property name (3)
> E OSD osd           Retrying with default values
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/scc/x11/scc-osd-daemon.py", line 256, in <module>
>     d.run()
>   File "/usr/local/lib/python2.7/dist-packages/scc/x11/scc-osd-daemon.py", line 240, in run
>     self._check_colorconfig_change()
>   File "/usr/local/lib/python2.7/dist-packages/scc/x11/scc-osd-daemon.py", line 225, in _check_colorconfig_change
>     OSDWindow._apply_css(self.config)
>   File "/usr/local/lib/python2.7/dist-packages/scc/osd/__init__.py", line 141, in _apply_css
>     OSDWindow.css_provider.load_from_data(str(OSDWindow.CSS % Config.DEFAULTS['osd_colors']))
> GLib.Error: gtk-css-provider-error-quark: <data>:45:12'min-width' is not a valid property name (3)
> 

Which just repeats over and over again.

**Comment by kozec** [comment]
@GlacialTurtle I smell GTK incompatibility which would explain everything :(

Can I ask what version of GTK3 are you using? It should be version of package named "libgtk-3-0" or "gtk3", depending on distro.

**Comment by GlacialTurtle** [comment]
Using Ubuntu 16.04, apt show libgtk-3-0 displays:

> Package: libgtk-3-0
Version: 3.18.9-1ubuntu3.3

**Comment by kozec** [comment]
I'd guess this will break layouts in menus a bit, but Ubuntu seems to [ignore most of layout settings anyway](https://cloud.githubusercontent.com/assets/1282500/26002220/441f94ea-372f-11e7-851f-3eeff81eaef5.png), so this is best it can do :(

**Comment by corvusd** [comment]
Thanks! :)

**Comment by kozec** [comment]
No problem. I'll add release with that fix as soon as build service recovers from whatever keep them down for entire weekend :(
