### ISSUE TITLE
[Suggestion] Allow editable diagonal range used for touchpad dpad mode

### ISSUE THREAD

**Issue by Ryochan7** [kozec/sc-controller#203]
Using the touchpad for character movement has always been something that I never liked and led me to keep reverting back to using the analog stick. In the official Steam Controller software, using the Cross Gate mode for changing the portion of the touchpad that is used for diagonal movement felt better than regular Overlap mode but I still did not like it.

While experimenting, I have found that I do not like the touchpad being divided into equal slices. It takes a little too much movement on the touchpad to activate a diagonal button and the diagonal range doesn't seem big enough. After changing the code to give a larger range for the diagonal portions, movement control improved a lot for me. I am currently testing using a 60 degree range for each diagonal direction and 30 degree range for each cardinal direction.

It might be a good idea to experiment with possibly adding an editable diagonal range for changing the size of the slices used for the touchpad buttons in dpad mode. I am currently testing this playing Half-Life: Source.

**Comment by kozec** [comment]
So, basically, option to change size of "pie slice" that translates to diagonal DPAD buttons at the expense of buttons for left/right/up/down?

That sounds doable.

**Comment by LinuxJoeUser** [comment]
How (im)possible would it be to create a graphic that showed the "pie" and its angles, realtime?  So as overlap angles were adjusted, so too were the graphical "pie's" angles.

**Comment by kozec** [comment]
> How (im)possible would it be to create a graphic that showed the "pie" and its angles, realtime? So as overlap angles were adjusted, so too were the graphical "pie's" angles.

It would be possible but I'm not sure where to fit it in UI. Plus, I'm not sure how useful would it be, as you'd still have to imagine it placed over actual pad...

**Comment by LinuxJoeUser** [comment]
> It would be possible but I'm not sure where to fit it in UI.

Perhaps a separate pop-up opens showing a circle with the pie-slices, the lines moving in response to changing "editable diagonal range" mentioned above by Ryochan7.  Both the circle and "editable diagonal range" (a slider perhaps?).  Similar to the way Steam's UI represents the "rotation" angle (which, now that I mention it, would be great if SCC had as well ;) )

> Plus, I'm not sure how useful would it be, as you'd still have to imagine it placed over actual pad...

With or without a graphic representation, the user would have to imagine variously sized "pie slices"  placed over actual pad.  As it currently stands we already must imagine our current DPad configurations on the Right Pad generally.  A graphic would only improve and clarify what is currently left up to the users' imaginations.  Though you and Ryochan7 may easily visualize such things, alas,--- beyond 90^^o and 45^^o---I cannot, and I imagine many others might find it tricky as well. :)

It seems to me that we've already accepted having to  ... but at least this way users could visualize just what a 80/20 or 25/75, or 60/30 relationship *looks* like.

**Comment by kozec** [comment]
Last problem with this :D

Any idea how to name that option?
