### ISSUE TITLE
Feature request: Windows & Xbox + Arduino + GY 85

### ISSUE THREAD

**Issue by r57zone** [kozec/sc-controller#204]
Support Windows to unbind the controller from the steam platform and enable the use of detailed configuration for xbox controllers.

Support xbox controllers with [custom arduino gyroscope](https://github.com/Razor-AHRS/razor-9dof-ahrs) (on com port).

Thanks.

**Comment by kozec** [comment]
Sorry, but this sounds more out of project scope than I though is possible :)

Any PRs are, of course, welcomed, but as far as I know, doing anything like gamepad emulation through uinput is not possible in Windows.

**Comment by r57zone** [comment]
On Windows there is XInput. Can make the XInput proxy like [this](https://github.com/r57zone/Xbox-contoller-with-gyroscope).
