### ISSUE TITLE
Overhead for smooth modifier

### ISSUE THREAD

**Issue by Ryochan7** [kozec/sc-controller#205]
After migrating to a recent version of sc-controller, I tried to use the smooth modifier to replace the old smoothing buffer code that I had been using. Unfortunately, it felt a bit off compared to what I was used to. I have done some testing and mathematically the code for the smooth modifier and my code produce identical results. However, testing with the timeit module seems to show that the technique used for the smooth modifier runs slower than the version I had been using.

From doing some minor fiddling, even doing something simple like using range instead of xrange when calculating the buffer sums makes a big enough difference to be able to feel when moving the mouse cursor. I figure that I might as well bring this up as something to maybe look into.

**Comment by kozec** [comment]
> From doing some minor fiddling, even doing something simple like using range instead of xrange when calculating the buffer sums

Yeah, if I used range there, it was 100% by mistake. I didn't really considered possibility that code can be slow enough to make difference, but I can check what can be done better :)

**Comment by Ryochan7** [comment]
The timeit module shows on my system that using range instead of xrange is faster. Granted that is over a lot of iterations so feel would be a better metric for testing. Based on feel, using range makes the cursor a bit more snappy. There might be a small increase in memory overhead using range instead of xrange but it does seem like range works out better in this case.

**Comment by Ryochan7** [comment]
Testing again does not show as big of a difference as I had seen before. The max run time value does still favor using range but not by that much. Anyway, here is the small script that I am using for testing. Manual editing has to be done for testing the various routines.

https://gist.github.com/Ryochan7/0ac415934c06d4c868717f1502aa06fd

```
steam@steamos:~$ echo "IN RANGE"
IN RANGE
steam@steamos:~$ python -m smoothtester
2.67388510704
15714.2857143
deque([10000, 20000, 10000, 20000, 10000, 20000, 10000, 20000], maxlen=8)
steam@steamos:~$ python -m smoothtester
2.70377898216
15714.2857143
deque([10000, 20000, 10000, 20000, 10000, 20000, 10000, 20000], maxlen=8)
steam@steamos:~$ python -m smoothtester
2.6331179142
15714.2857143
deque([10000, 20000, 10000, 20000, 10000, 20000, 10000, 20000], maxlen=8)


steam@steamos:~$ echo "IN XRANGE"
IN XRANGE
steam@steamos:~$ python -m smoothtester
2.69991087914
15714.2857143
deque([10000, 20000, 10000, 20000, 10000, 20000, 10000, 20000], maxlen=8)
steam@steamos:~$ python -m smoothtester
2.74785995483
15714.2857143
deque([10000, 20000, 10000, 20000, 10000, 20000, 10000, 20000], maxlen=8)
steam@steamos:~$ python -m smoothtester
2.60054183006
15714.2857143
deque([10000, 20000, 10000, 20000, 10000, 20000, 10000, 20000], maxlen=8)


steam@steamos:~$ echo "IN OLD ROUTINE"
IN OLD ROUTINE
steam@steamos:~$ python -m smoothtester
2.17621207237
15714
deque([20000, 10000, 20000, 10000, 20000, 10000, 20000, 10000], maxlen=8)
steam@steamos:~$ python -m smoothtester
2.15497708321
15714
deque([20000, 10000, 20000, 10000, 20000, 10000, 20000, 10000], maxlen=8)
steam@steamos:~$ python -m smoothtester
2.10389184952
15714
deque([20000, 10000, 20000, 10000, 20000, 10000, 20000, 10000], maxlen=8)
```

Compared to the old code, a little reduction in the smoothing weight seems to be enough to compensate for the difference. I will have to fiddle with the settings. The numbers I have been using with the old routine lately are level 10 and weight 0.71.

**Comment by kozec** [comment]
I've changed it to use one precomputed range and even got rid of dequeue. Numbers are not 100% same, what's most caused by rounding. Frankly, I can't tell the difference at all, but timeit (with [code that runs actual SmoothModifier](https://gist.github.com/kozec/a09cfd69bde13101c8ca4717b4f064af)) shows that computation speed has increased.
