### ISSUE TITLE
[Solved] Radial Menu disable the OSD

### ISSUE THREAD

**Issue by DFOXpro** [kozec/sc-controller#206]
## How to test
With a clean layout set to any trackpad or the joystic add a menu action of your choose ```radialmenu('<anyMeny>',DEFAULT,A)"``` and to other button set any other osd action like scc menu.

## What you want

When you touch the input must show the radial menu (I have never seen this menu)

## What you get

The menu is never displayed and even more the osd maybe crash  trying to launch other osd after the radial dnt works, its necessary to shutdown the controller and restart the sc-controller program (restart the pad or the driver dnt work neither).

side note: other menus like horizontal, grid and vertical works fine.

## HW/SW
Steam controller model 1001
Ubuntu 17.04
OpenSuse's build debs

## What's next?
How can I start the sc-daemon or scc-osd-menu to get a usefull log for this error.

**Comment by kozec** [comment]
> How can I start the sc-daemon or scc-osd-menu to get a usefull log for this error

Uncheck "Emulation enabled" in GUI, make sure there is no proces named `scc-daemon` left behind and then start `scc-daemon debug` from terminal.

**Comment by kozec** [comment]
(in meantime, above will not fix radial menu not showing, but should prevent OSD from disabling itself)

**Comment by DFOXpro** [comment]
Mark this has solve for v0.3.11

**Comment by kozec** [comment]
Good to know :)
