### ISSUE TITLE
[Trivial] Add car actions Icons

### ISSUE THREAD

**Issue by DFOXpro** [kozec/sc-controller#207]
the original steam offers (ugly) car actions Icons, like pedals, turning and others,

I want to add those images (to play eurotruck :v ) how can I add those , which branch should I ask to merge, which list files I need to edit??

**Comment by kozec** [comment]
Make "Racing" directory here - https://github.com/kozec/sc-controller/tree/master/images/menu-icons and dump icons there. But adding icons directly from Steam may be a bad idea, those are most likely copyrighted by Valve.

**Comment by DFOXpro** [comment]
any way I discover an add a custom icon in the GUI so for the moment I'm using copied assets

**Comment by kozec** [comment]
I was not able to find any driving related icons in Steam, but I agree that driving is something that one may use SCC for, so I've added some as defaults.
