### ISSUE TITLE
Application closes automatically (KDE Plasma 5)

### ISSUE THREAD

**Issue by m4df3ll0w** [kozec/sc-controller#209]
Application opens for a split second then automatically closes.
I tried running as root from console and got this message:

(process:5766): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/bin/sc-controller", line 23, in <module>
    Gtk.IconTheme.get_default().append_search_path(images)
AttributeError: 'NoneType' object has no attribute 'append_search_path'

**Comment by m4df3ll0w** [comment]
Add'l information:
sc-controller version: 0.3.10.1-2.1-x86_64
DE: KDE Plasma 5.10.1-1.2

**Comment by kozec** [comment]
That sounds like you don't have any GTK icon theme installed. Does any other GTK application run?

**Comment by m4df3ll0w** [comment]
I've tried both Papirus and Numix GTK themes, and having the same issue. Tested the GTK application geeqie, and that seemed to work fine. Do you have a specific app in mind for me to try? Still getting used to KDE Plasma, and most everything seems to be Qt based. 
Also double-checked that GTK2 and GTK3 dependencies are installed.

**Comment by kozec** [comment]
Ok, I theoretically know how to workaround this, but I'd like to know why is it crashing in 1st place.

What version of OpenSuse and number of bits are you using? Is there any wayland around?

**Comment by m4df3ll0w** [comment]
I was using Opensuse Tumbleweed, so I believe it was 4.11-x86_64. (Since moved back to Fedora 25- Gnome). After switching to Mate, XFCE, and GNOME (Both the Wayland and Xorg versions), sc-controller worked fine. The radial menu did not want to open in GNOME Wayland, but the application itself did function. It was only in KDE Plasma 5 that it did not want to work.

**Comment by kozec** [comment]
> The radial menu did not want to open in GNOME Wayland, but the application itself did function. It was only in KDE Plasma 5 that it did not want to work.

Nothing OSD-related works on GNOME Wayland, but that's kinda by design :(

Anyway, SCC should no longer crash on Opensuse with KDE, but running from source there will probably display placeholder icons.
