### ISSUE TITLE
Tray icon in KDE Plasma

### ISSUE THREAD

**Issue by arshesney** [kozec/sc-controller#210]
The tray icon is not appearing in KDE Plasma (5.10) on Arch, sc-controller version 0.3.10.1 and closing the program

Starting it from command line returns this error:

`I StatusIcon    Using backend StatusIconGTK3 (primary)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/statusicon.py", line 234, in _on_embedded_change
    is_embedded = self._tray.is_embedded() or not self._tray.get_visible() or IS_CINNAMON
NameError: global name 'IS_CINNAMON' is not defined`

Removing the offending value (it is only used in that instance) returns a warning:

`W StatusIcon    StatusIcon: Using backend StatusIconDummy (fallback)`

Yet still no icon and program stays loaded after closing the window

**Comment by arshesney** [comment]
After some messing around installing libappindicator-gtk3 solves the icon missing problem, still returns a warning:

`I StatusIcon    Using backend StatusIconGTK3 (primary)
/usr/lib/python2.7/site-packages/scc/gui/statusicon.py:259: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)`

**Comment by kozec** [comment]
Dunno where IS_CINNAMON gone, but yeah, if you are using desktop without tray support, AppIndicator is best bet. That warning is harmless, you can ignore it.
