### ISSUE TITLE
Add Show/Hide window item to right-click tray menu

### ISSUE THREAD

**Issue by arshesney** [kozec/sc-controller#211]
As per title, using libappindicator with KDE the main window isn't restored by left-clicking or double-clicking the tray icon, it is only possible to open the right-click menu.

I hacked a menu item that uses the function `on_statusicon_clicked`, the patch is attached to this post.
Dunno how to make a pull request, but can make one if preferred.

[restore-window.txt](https://github.com/kozec/sc-controller/files/1081833/restore-window.txt)

**Comment by kozec** [comment]
Thing is, this would add same item to menu in main window, where it makes zero sense.

Is not being able to do left-click on indicator common thing in KDE?

**Comment by arshesney** [comment]
Yeah, I just thrown a quick workaround, probably the best place for this item would be the osd menu.
