### ISSUE TITLE
various circular actions keep diferent input position

### ISSUE THREAD

**Issue by DFOXpro** [kozec/sc-controller#213]
## Setup

Put this text in custom Editor in any of the touchpads and confirm

    ring(0.75,
      feedback(LEFT, 512, 3.0,   sens(1, 1,     circular(axis(Axes.ABS_X)))),
      feedback(LEFT, 256, 6.0,   sens(0.2, 0.2,     circular(axis(Axes.ABS_X))))
    )

## What do you want

After confirm the touchpad must work like a steering wheel with smooth control in the outer ring and fast control in the inner ring, and send a continuous input. This type of input is ideal for car simulation when sometimes you need fine steering (in a highway) and some times you need fast steering(parking).

## What really happen

Each ring keep different cursor input and when you toggle from rings the input sudden jumps (you can test this with jstest-gtk)

## Notes

Maybe each circular actions handle different cursor for the axes, can I set an option like USE_GLOBAL_CURSOR (or something like this?)

**Comment by kozec** [comment]
Sorry for late answer, I had to test it to be sure if I understand.

This may be pretty hard to do, as those rings are completely independent and don't have way to know about each other. But at worse, I can add special condition that's used only when two Circular actions are used with rings...

I'll check what can be done,

**Comment by DFOXpro** [comment]
After some hard testing It looks like the best solution for a variety of crazy configs it's to simply set a  common position for an axis in all configured circular() action; What I mean: All circular actions (independent if it's in separated touchpads or sensibilities or modeshiftings) in the controller that points to <>outputAxis must be sending a continuous point of the axis
