### ISSUE TITLE
[Feature Request] Need equivalent of Gyro Button Behavior - Turns Gyro setting

### ISSUE THREAD

**Issue by Ryochan7** [kozec/sc-controller#214]
Usually, I do not play with the gyro in the Steam Controller but I started playing with it recently. I have settings in the official Steam Controller utility that I like but I cannot duplicate that same functionality in sc-controller. The problem is that there is no way to have the gyro always enabled except while the right touchpad is being touched. There is no Gyro Button Behavior setting in sc-controller. There is also no way to perform a mode shift for the gyro so that cannot be used as an alternative method to disable it while pressing another button.

**Comment by kozec** [comment]
> The problem is that there is no way to have the gyro always enabled except while the right touchpad is being touched.

Maybe you found some bug, but you should be able to select "Always Active" as gyro enable button or just put something like `mouse(ROLL)` as Custom Action.

**Comment by Ryochan7** [comment]
The Gyro Enable Button is working as intended. Always Active works as well as selecting Right Pad Touched. What I would like is to have Gyro mouse always active except while the right pad is being touched. That is done in the Steam client by selecting Right Pad Touch for the Gyro Enable Button option and then selecting Off on the Gyro Button Behavior - Turns Gyro setting. I find that configuration easier to control and more comfortable than keeping the right pad touched to enable mouse movement or using Always Active.

**Comment by kozec** [comment]
Ok, now I understand. You can do that as well, just not with GUI...

`mode(RPADTOUCH, None, mouse(ROLL))` should map gyro to mouse as default action and map gyro to None while rpad is being touched.

But adding GUI should be easy.
