### ISSUE TITLE
Circular -> two buttons mapping

### ISSUE THREAD

**Issue by kozec** [kozec/sc-controller#216]
Feature requested elsewhere;

Option to map circular() modifier to two buttons, one pressed when "wheel" is being rotated clockwise and other when counter-clockwise.

**Comment by LinuxJoeUser** [comment]
Yes!  Yes, yes, yes, yes!  Playing Mad Max would have been sooooo much better if I could have done this!

**Comment by kozec** [comment]
Well, better late than never :)
