### ISSUE TITLE
Triggers range disable axis input (sometimes)

### ISSUE THREAD

**Issue by DFOXpro** [kozec/sc-controller#217]
## Setup

Put this text in custom Editor in any of the triggers and confirm

    trigger(254, 255, button(Keys.BTN_TR)) and trigger(0, 253, axis(Axes.ABS_RZ))

## What do you want

After confirm the trigger must work like a gas pedal with nitro(action) at full pressed.

## What really happen

The axis input became disabled

## Notes

· The driver and the GUI return no error when this setup is active
· There is no deadzone options to edit in the menu

**Comment by kozec** [comment]
There is too many triggers in that :) Was it generated through GUI?

For me, choosing A button as  "fully pressed action" and right stick as analog output generates
`trigger(230, 255, button(Keys.BTN_GAMEPAD)) and axis(Axes.ABS_RY)`
and seems to work.

**Comment by DFOXpro** [comment]
I get the example code via gui, note your code only act over the button action not the axis action

![full size img](https://user-images.githubusercontent.com/5248241/27491047-6380a412-5806-11e7-8930-cd62eec3b77a.png)

Also note the gui everytime change a Fully Pressed Action to a Partially Pressed Action (annother trivial bug)

What I really want it's the trigger at 254(full pressed without the click) return me a full pressed input and at 255 (full pressed with click) return me a full pressed input plus and extra button (kind of a macro), I hope this can be done via deathzone or sensitivity but both are disabled.

The only stable setting it's working is:

    trigger(254, 255, button(Keys.BTN_TR)) and axis(Axes.ABS_RZ)

But when full presset without the click I can't get the full presset input (obviously)
![full size image](https://user-images.githubusercontent.com/5248241/27491307-7471e870-5807-11e7-98ce-b438ae00ae5c.png)

**Comment by DFOXpro** [comment]
![Those  sliders broke the input](https://user-images.githubusercontent.com/5248241/27491406-e18dc622-5807-11e7-888c-327afe1c4a93.png)

**Comment by DFOXpro** [comment]
Thanks to your other bug comment about the docs I accomplish this input via custom editor:
    trigger(254, 255, button(Keys.BTN_TR)) and sens(1.3, axis(Axes.ABS_RZ))

**Comment by kozec** [comment]
Sorry, but I can't replicate this no matter what. Can you describe what you've been clicking and in what order to get that broken action?

**Comment by DFOXpro** [comment]
after many attems looks like this bug appears on random (some times it send the valid input sometime send no input on axis), again the original custom edit line I post in this bug is the one that pops this error

**Comment by DFOXpro** [comment]
Rename the title bug for better testing
