### ISSUE TITLE
[Solved] This project Needs a Wiki doc to handcrafted configs

### ISSUE THREAD

**Issue by DFOXpro** [kozec/sc-controller#218]
For really complex profiles like EuroTruck sea of buttons I always end in the Custom edit options, coping a set of possibles settings then editing in external text editor then pasting within the GUI. It will be nice if there is any docs to do a more precise profile

# Docs like:

# Actions

Anything that you can set to any button/axis of your SC.

### Feedback

Ths SC support haptic feedback this can be set via:

    feedfack(
      [selected_haptic, amplitude, frequency, period, ]
      <action>
    )
[settings] = optional
 \<action\> = mandatory
· selected_haptic: (LEFT, RIGHT, BOTH) witch of the haptic motors will send the feedback
· amplitude: how strong will be the feedback
· frequency: how fast the feedback will repeat
· period: IDK

**Comment by kozec** [comment]
There are actually [kind of docs available](https://github.com/kozec/sc-controller/blob/master/docs/actions.md), but true, converting them to wiki may be good idea, especially for  those examples.

I never really got around to do it, but I should probably check what can github wiki do.

**Comment by kozec** [comment]
> you can enable start the wiki then the community can help you around that

Well, why not. I did exactly that.

It may be even good place to add gui docs once I get around to write them :)

**Comment by DFOXpro** [comment]
Mark has solved
