### ISSUE TITLE
Minimum speed trackball activation.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#219]
At a low or no friction trackball setting, simply lifting one's thumb from the trackpad results in pad registering trackball "rolling," causing unwanted "rolling" or "drift."

I spent some time comparing sc-controller with the Steam driver, and it looks like Steam keeps this from happening by requiring a minimum speed (velocity) be reached for the trackball to continue to "roll" after the trackpad is no longer being touched.

I'm wondering if a simple `if ... else` statement wouldn't fix this.  How it would work would be something like:

```
if speed_on_pad <= 30: 
    free_roll_speed == 0
else:
    free_roll_speed == speed_on_pad:
```

This is meant to suggest how the test would _flow_, not the _literal_ code.  (I'm not even sure if the code is done correctly ... I'm still only beginning to study Python).  And, of course, "30" is just an example, since I don't know what the real values might look like.  If you play with your steam controller under steam, with the trackball friction setting to "None" you'll probably be able to get a good idea what kind of value to use instead of the "30" I used in my example above.

**Comment by kozec** [comment]
Sounds like good idea. ^^ Here, lets see if anyone notices difference :)

**Comment by LinuxJoeUser** [comment]
Yes, that works very well to control drift, but there is a side-effect where the cursor "jumps" to different locations depending upon where the touch-pad is touched.   

The greater the sensitivity setting, the greater the "jump" is.  (It may not be an actual, instant, "jump," but that the cursor is actually traveling very, very fast to the new location.)  The cursor does not need to be in motion, either.  Simply touching around the pad while the cursor is standing still will move the cursor.

This trackball setting makes it more noticeable:

`rotate(16.6, smooth(8, 0.78, 2.0, feedback(RIGHT, 256, sens(2.3, 2.3, ball(0.0, mouse())))))`

And this one is almost uncontrollable:

`smooth(9, 0.9, 1, feedback(RIGHT, 410, 7.0, sens(2.4, 2.4, ball(0.0, mouse())))) `

**Comment by kozec** [comment]
That's probably not side effect, but something caused by smoothing. It appears to produce small "lead in" in position when pad is anywhere but center. It really shouldn't do that, so my math has to be broken somewhere :(

**Comment by LinuxJoeUser** [comment]
It looks like the cursor will still jump with smoothing disabled as well:

`feedback(RIGHT, 410, 7.0, sens(2.4, 2.4, ball(0.029, mouse())))`

I can't remember for certain how it worked in older versions, but touching different locations on the pad didn't cause the cursor to jump from location to location before, did it?

And don't knock your math, it's done a marvelous job creating sc-controller so far!  It'll fix this bit of weirdness too, you'll see! :)

**Comment by kozec** [comment]
(only half fixed yet)

**Comment by LinuxJoeUser** [comment]
DUDE!  This is *perfect!!*  You (and your math) ROCK!!

**Comment by Patola** [comment]
And what's the recipe? I am completely lost here. I have read the wiki, the .md files from the repository, took hours editing .sccprofiles and still can't smooth the gyro input, and every time I try to write a simple action, the sc-controller basically ignores it and writes a different one for me
