### ISSUE TITLE
Deadzones for pads

### ISSUE THREAD

**Issue by azizLIGHT** [kozec/sc-controller#22]
Sometimes when I'm trying to press the Y or B button, my thumb grazes the very edge of the right pad and messes up what I was trying to do. Is it possible to implement some customizable deadzones for the pads, so that touches in specific spots on the pad do nothing?

**Comment by kozec** [comment]
Sounds possible, I'll check on it.

**Comment by kozec** [comment]
(as usual, well hidden here)

![dead](https://cloud.githubusercontent.com/assets/1282500/15575469/5e8b6e76-2353-11e6-9bae-5efc31fa8ae8.png)

**Comment by azizLIGHT** [comment]
I'm not sure how exactly the deadzone settings work? I matched the numbers for lower/upper to axis readings from jstest-gtk where I didn't want the pad to work (outer edges of 6 o clock to 9 o clock position on the pad: Axis 3 -30k and Axis 4: -20k). I entered these into Lower/Upper and tried them in reverse as well, but it seems like input was still recognized. Am I using this wrong?

**Comment by kozec** [comment]
hmm.. -20k? How did you managed to get minus there?

Anyway, sorry if I misunderstood what are you trying to do, but deadzone currently works like this:

![deadzone](https://cloud.githubusercontent.com/assets/1282500/15631347/0b1d7a26-2566-11e6-8cda-7946a9ac258e.png)

Only part between upper and lower deadzone is responsive.
So, if you leave lower deadzone at 0 and set upper at 20000, pretty big part of outer ring will do nothing.

**Comment by azizLIGHT** [comment]
Ah I see. I got it working now. Thanks!

**Comment by kozec** [comment]
I should probably get wiki or something :D
