### ISSUE TITLE
Feedback per scroll step

### ISSUE THREAD

**Issue by GreyAsteroid** [kozec/sc-controller#222]
I'm using the left pad for scrolling in all of my profiles and one thing that I can't quite get the same way as I can through Steam is the feedback. In Steam when I have a circular wheel setup with scrolling, feedback is only given after each step so I can actually feel exactly how much I've scrolled. However I can't quite get it the same using sc-controller. The closest I can get is a feedback frequency of 2 and it still misses every 5th or so step. Is there a way to do this and I'm just missing it or is this something that hasn't been implemented?

**Comment by GreyAsteroid** [comment]
I started fiddling with the custom action field so I could alter the frequency to the decimal places. 1.928 / 1.927 were the closest I could get it, one a bit more one a bit less. Unfortunately I can't set any numbers past the ten-thousandths to make it any more accurate.

**Comment by kozec** [comment]
Allowing more decimal places should be possible, but I'm not sure how much that will help - AFAIK, it's entirely up to application to decide how much should it scroll per wheel movement.

**Comment by GreyAsteroid** [comment]
I've tested native GTK apps, Chrome, Firefox, and a couple games. When using steam there is only ever feedback when a scroll step is taken. Applications seem to move different amounts per scroll step but they still take the same amount of scroll steps.

**Comment by kozec** [comment]
You know, everything you mention uses smooth scrolling on my side :D I can't really tell where scroll step occurs in those applications.

But, what I just did here is that I added code to reset feedback "counter" every time when scroll is started and matched multiplier so, with default frequency of 4, it generates one feedback effect per line scrolled in *Atom*. That's only thing that I can remember scrolling by line on my machine.

Hopefully, it will work same way on your side as well :)

**Comment by GreyAsteroid** [comment]
I'm running with the new commit and it's definitely synced up with the feedback by default now, no need to adjust the frequency. However, I'm having the same issue I was before. No matter what the frequency is, it sometimes becomes "desynced". 

The feedback will start firing early or late while scrolling. The weird thing to me at least is that it even starts desynced sometimes. As soon as I put my thumb on the left pad and move it a little bit sometimes the feedback goes off but the scroll doesn't happen. If I keep scrolling it eventually syncs up but will eventually desync again.

I had to fire up steam again just to make sure I'm not crazy but yeah it's not an issue on Steam. All feedback happens at the scroll step on all applications.

**Comment by GreyAsteroid** [comment]
An issue I just noticed, after clearing the left pad bindings and just running the default circular mouse wheel defaults to test the new commit, I closed the application and reopened it. After doing so the feedback is no longer firing at the same time as the scroll step.

If I either change the feedback frequency to 2 or lower the sensitivity to 0.5 it goes back to firing at the same time.

**Comment by kozec** [comment]
> Restarting the daemon did not fix it. Restarting my computer fixed it until I closed sc-controller and opened it again which caused the issue again.

Ok, now what the hell :D I'll check how this is even possible, but before that, do you have "input test mode" enabled? Meaning, does sc-controller shows buttons as they are pressed?

**Comment by GreyAsteroid** [comment]
Nope, I tried it again after removing all configs and profiles, completely clean and the issue still happened. Just checked and input test mode is not enabled by default and is off. 
This feature has turned into such a mess 😂

**Comment by kozec** [comment]
Few points as I finally understand wtf happens here:

- Problem is is not caused by restarting GUI but by profile being reloaded (what GUI does on start)
- When that happens, all internal counters are restarted as well, but position of wheel on virtual mouse device is not. That's where feedback "desynchronization" happens.
- Steam doesn't seems to have this problem because it doesn't do mouse emulation and uses (most likely) xtest extension to move mouse around.
- I'd rather not do same thing as Steam here, as xtest is not always enabled and works only with X, while mouse emulation SCC uses works with everything, including Wayland.

And now excuse me while I stare to roof thinking about how to solve this unholy mess :)
