### ISSUE TITLE
Installation: scriptlet failure

### ISSUE THREAD

**Issue by KAMiKAZOW** [kozec/sc-controller#223]
Using the Fedora package from your OBS repo (well, actually I forked your package to let it build for Fedora 25 but I touched nothing):

/var/tmp/rpm-tmp.LjZPvX: line 1: fg: no job control
warning: %post(sc-controller-0.3.11-5.1.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package sc-controller
Non-fatal POSTIN scriptlet failure in rpm package sc-controller

**Comment by kozec** [comment]
I'm 100% sure that there is no `fg` anywhere near any installation script. What would it be doing there anyway?

Can you link me to full output of that build?

**Comment by KAMiKAZOW** [comment]
That's the whole output DNF, the package manager!, gives me under Fedora 25. The build process itself looks OK: https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/sc-controller/Fedora_25/x86_64

**Comment by kozec** [comment]
> That's the whole output DNF, the package manager!, gives me under Fedora 25. 

Sorry, I didn't realized that's package manager output.

post-install script should only update desktop database, so nothing really happens if that fails. But code to do that should be actually provided by distro, so I'm not 100% sure if it can be fixed in buildservice.
