### ISSUE TITLE
[Solved] osd/inputdisplay.py fails to run

### ISSUE THREAD

**Issue by DFOXpro** [kozec/sc-controller#225]
## Context
Trying to follow Author's instructions [in this youtube comment](https://www.youtube.com/watch?v=OUuVXHm35Zc&lc=z12etplx5wmlszwtx23eyzfpsyflenfnk.1498078451541126)
I run from installed package this line:

    $ /usr/lib/python2.7/dist-packages/scc/osd/./inputdisplay.py

## Error:

    /usr/lib/python2.7/dist-packages/scc/osd/./inputdisplay.py:10: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
      from gi.repository import Gtk, GLib
    /usr/lib/python2.7/dist-packages/scc/gui/svg_widget.py:11: PyGIWarning: Rsvg was imported without specifying a version first. Use gi.require_version('Rsvg', '2.0') before import to ensure that the right version gets loaded.
      from gi.repository import Gtk, Gdk, GObject, GdkPixbuf, Rsvg

If the ```scc-daemon``` is running the osd launch for half a second then crash with the next console error:

    E osd.InputDisplay Failed to enable test mode: Sniffing disabled.

**Comment by DFOXpro** [comment]
the problem persist with the .pyc file

**Comment by kozec** [comment]
> E osd.InputDisplay Failed to enable test mode: Sniffing disabled.

Open sc-controller (gui), click green icon, settings, advanced, "enable input test mode"

**Comment by DFOXpro** [comment]
Mark as solved

**Comment by kozec** [comment]
I changed that message to 

```
E osd.InputDisplay Failed to enable test mode: Sniffing disabled.
E osd.InputDisplay 
E osd.InputDisplay =================================================================================
E osd.InputDisplay [!!] Please, enable 'Input Test Mode' on 'Advanced' tab in SC-Controller settings
E osd.InputDisplay =================================================================================
```

... just in case someone else will be unable to read my mind in the future :)
