### ISSUE TITLE
Insufficient bus power detection

### ISSUE THREAD

**Issue by TwoD** [kozec/sc-controller#226]
Hi,

I just had problems getting sc-controller to detect when my controller was plugged in over USB. No error/problem indication was shown in the GUI, on stdout or on stderr. The emulation icon was green and everything was apparently fine, but no input was recognized.

A bit of digging in the logs soon made the problem obvious though; I had connected the controller via a port on my keyboard and it apparently did not supply enough power (the controller lit up but did not play the startup sound). Here's the output from my journal in Arch linux when plugging it in:
```
jul 09 11:51:39 Machine kernel: input: SCController Keyboard as /devices/virtual/input/input34
jul 09 11:51:39 Machine kernel: input: SCController Mouse as /devices/virtual/input/input35
jul 09 11:51:39 Machine kernel: input: Microsoft X-Box 360 pad as /devices/virtual/input/input36
jul 09 11:52:13 Machine kernel: usb 1-13.4: USB disconnect, device number 13
jul 09 11:52:22 Machine kernel: usb 1-13.4: new full-speed USB device number 14 using xhci_hcd
jul 09 11:52:23 Machine kernel: usb 1-13.4: rejected 1 configuration due to insufficient available bus power
jul 09 11:52:23 Machine kernel: usb 1-13.4: no configuration chosen from 1 choice
```
It works just fine after switching to another port but it had me scratching my head for a while...
Would it be possible for sc-controller to detect this and display some warning suggesting to use a different port with more power?

**Comment by kozec** [comment]
> Would it be possible for sc-controller to detect this and display some warning suggesting to use a different port with more power?

Not really, this is not something detectable in userspace. And even parsing it out from dmesg would be problematic, because as you probably noticed, there is no info about _what_ got rejected. SCC would end up displaying warning about every USB stick you've (dis)connected.

**Comment by TwoD** [comment]
Figured it may be problematic. Does sc-controller notice [internally] that a controller gets connected at all in this case?

**Comment by kozec** [comment]
> Does sc-controller notice [internally] that a controller gets connected at all in this case?

Nope, AFIK, rejected device is not signalized in any way.
