### ISSUE TITLE
Steam Controller not in /dev/input/by-id (evdev)

### ISSUE THREAD

**Issue by hcorion** [kozec/sc-controller#227]
I'm trying to use my Steam Controller with a custom application that interfaces with controllers via evdev. Does this application support this? It seems to only support the old joystick API.
I would appreciate a evdev implementation.

**Comment by kozec** [comment]
SC-Controller emulates controller as if it were connected to USB, so if evdev node appears depends on evdev configuration. It surely appears as /dev/input/eventXY on mine machine, but I didn't do any specific configuration so I don't really know why :)

**Comment by hcorion** [comment]
OK
So you're right, eventXY does work, however it needs to be symlinked to /dev/input/by-id and /dev/input/by-path.

I know that you can add udev rules to make it symlink like 
`SYMLINK+="input/by-path/steamcontroller-event-joystick"`
but I'm not sure where to add that.

**Comment by kozec** [comment]
> I know that you can add udev rules to make it symlink like
> SYMLINK+="input/by-path/steamcontroller-event-joystick"
> but I'm not sure where to add that.

Here: https://github.com/gentoo/eudev/blob/master/rules/60-persistent-input.rules#L23

But this really _is_ default behavior, including /dev/jsX node, so you should probably check what did you done to _prevent_ their creation from happening :)

**Comment by hcorion** [comment]
Yep, my Arch 60-persistant-input.rules looks like that, 
```
# by-id links
KERNEL=="mouse*|js*", ENV{ID_BUS}=="?*", ENV{.INPUT_CLASS}=="?*", ATTRS{bInterfaceNumber}=="|00", SYMLINK+="input/by-id/$env{ID_BUS}-$env{ID_SERIAL}-$env{.INPUT_CLASS}"
KERNEL=="mouse*|js*", ENV{ID_BUS}=="?*", ENV{.INPUT_CLASS}=="?*", ATTRS{bInterfaceNumber}=="?*", ATTRS{bInterfaceNumber}!="00", SYMLINK+="input/by-id/$env{ID_BUS}-$env{ID_SERIAL}-if$attr{bInterfaceNumber}-$env{.INPUT_CLASS}"
KERNEL=="event*", ENV{ID_BUS}=="?*", ENV{.INPUT_CLASS}=="?*", ATTRS{bInterfaceNumber}=="|00", SYMLINK+="input/by-id/$env{ID_BUS}-$env{ID_SERIAL}-event-$env{.INPUT_CLASS}"
KERNEL=="event*", ENV{ID_BUS}=="?*", ENV{.INPUT_CLASS}=="?*", ATTRS{bInterfaceNumber}=="?*", ATTRS{bInterfaceNumber}!="00", SYMLINK+="input/by-id/$env{ID_BUS}-$env{ID_SERIAL}-if$attr{bInterfaceNumber}-event-$env{.INPUT_CLASS}"
# allow empty class for USB devices, by appending the interface number
SUBSYSTEMS=="usb", ENV{ID_BUS}=="?*", KERNEL=="event*", ENV{.INPUT_CLASS}=="", ATTRS{bInterfaceNumber}=="?*", \
  SYMLINK+="input/by-id/$env{ID_BUS}-$env{ID_SERIAL}-event-if$attr{bInterfaceNumber}"
```

For example, my Xbox 360 controller works properly, showing up in both /dev/input/by-id and /dev/input/by-path
It's just the Steam Controller that doesn't do it automatically.

**Comment by hcorion** [comment]
If you run `ls /dev/input/by-id` @kozec is there an entry for the Steam controller?

**Comment by kozec** [comment]
```
$ udevadm info -q all /dev/input/js0  | grep LINKS
E: DEVLINKS=/dev/input/by-id/-noserial-event-if /dev/input/by-path/-event-joystick
```

Now you are mentioning, those links aren't giving much sense, but they are there.

By the way, what exactly are you trying to do? Because querying  udev devices with `ls /dev/input/by-id` doesn't sounds like good idea...

**Comment by hcorion** [comment]
`/dev/input/js0` is the old joystick API, I'm talking about evdev.
Anyway, I'm trying to use my Steam Controller with RPCS3 (A PlayStation 3 emulator) that uses evdev for connecting to the controllers on Linux. The way it works is by scanning all the files in `/dev/input/by-path` for entries that end in `event-joystick`

My Xbox 360 controller and random flight stick work fine, but for some reason my Steam Controller doesn't symlink, I would assume this is a sc-controller issue.

**Comment by kozec** [comment]
> The way it works is by scanning all the files in /dev/input/by-path for entries that end in event-joystick, and using those.

Then it does it horribly wrong, scanning only those with symlinks is pretty bad idea for reason you just found :)

**Comment by gasinvein** [comment]
It's kinda offtopic here, but I would ask is there any reliable way to enumerate virtual devices created by sc-controller?

**Comment by kozec** [comment]
> It's kinda offtopic here, but I would ask is there any reliable way to enumerate virtual devices created by sc-controller?

Not exactly,  SCC doesn't know what node or id is associated with device it creates.

If keyboard and mouse is enough, you can walk /dev/input and check if name returned by `libevdev_get_name` contains substring '_SCController_'. Emulated gamepad is named '_Microsoft X-Box 360 pad_' by default, but you can change that in config file. But you should be aware that there are games that are not enabling gamepad input unless device with that exact name exists.

**Comment by gasinvein** [comment]
Seems like there is no way to create proper symlinks then. My udev doesn't create symlinks to sc-controller's devices, just as @hcorion's. I'm on openSUSE, and that udev rule is pretty same as Ubuntu's one:
```diff
--- /usr/lib/udev/rules.d/60-persistent-input.rules     2017-08-08 14:18:48.000000000 +0300
+++ /tmp/udev_232-21ubuntu5_amd64/lib/udev/rules.d/60-persistent-input.rules    2017-06-21 18:33:22.000000000 +0300
@@ -3,8 +3,6 @@
 ACTION=="remove", GOTO="persistent_input_end"
 SUBSYSTEM!="input", GOTO="persistent_input_end"
 SUBSYSTEMS=="bluetooth", ENV{ID_BUS}="bluetooth", GOTO="persistent_input_end"
-# Bluetooth devices don't always have the bluetooth subsystem
-ATTRS{id/bustype}=="0005", ENV{ID_BUS}="bluetooth", GOTO="persistent_input_end"
 SUBSYSTEMS=="rmi4", ENV{ID_BUS}="rmi", GOTO="persistent_input_end"
 SUBSYSTEMS=="serio", ENV{ID_BUS}="i8042", GOTO="persistent_input_end"
```

**Comment by kozec** [comment]
You could probably write rule that deals with anything named '_Microsoft X-Box 360 pad_' specifically and assigns some bogus name to it, but that will help only with SCC, not with all other possible drivers that rpcs3 is ignoring right now.

**Comment by hcorion** [comment]
I've got a fix for RPCS3 properly detecting evdev controllers locally, I'll PR it soon, do you mind if I tag you to review it @kozec ?

**Comment by kozec** [comment]
@hcorion yeah, no problem :)
