### ISSUE TITLE
On screen display not working

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [kozec/sc-controller#229]
I receive the message "Cannot show OSD; there is no scc-osd-daemon registered" when attempting to open an OSD. This occurs when running the Arch Linux AUR version of sc-controller, and when running directly from a git repository.

Output of scc-daemon debug
```
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7fcefa3c4c90>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7fcefa11ca10>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7fcefa11c810>
D SCCDaemon     Created control socket /home/abe/.config/scc/daemon.socket
W SCCDaemon     Wayland detected. Disabling X11 support, some functionality will be unavailable
D USB           USB device added: 28de:1142
D SCDongle      Not requesting serial number for SC 1
D SCDongle      Got wireless SC with serial 1
D SCCDaemon     Assigned default_mapper to <SCWireless 1>
D SCCDaemon     Controller added: <SCWireless 1>
W SCCDaemon     Cannot show OSD; there is no scc-osd-daemon registered
```

**Comment by kozec** [comment]
> W SCCDaemon     Wayland detected. Disabling X11 support, some functionality will be unavailable

Here your answer. Wayland lacks functionality needed for OSD.

**Comment by WhiteAbeLincoln** [comment]
Ok. The issue is it wasn't working on XMonad either, which is running under
a pure X server environment. And I launched Gnome on X server, so wayland
shouldn't have been running

**Comment by WhiteAbeLincoln** [comment]
When I disabled gdm and started XMonad using startx instead, the OSD worked. It appears that gdm starts a wayland daemon even if the window manager is running on an x server. I guess I'll have to switch to a different login manager like lightdm

**Comment by kozec** [comment]
On side note, fact that XMonad was able to run and work in Xwayland is kinda amazing :)

**Comment by WhiteAbeLincoln** [comment]
haha, yeah. I didn't even notice. I was using lightdm before, and switched to gdm when I wasn't able to log in after enabling multilib (turns out I just had to recompile my xmonad config). But everything looked like it was working fine while I was using Xwayland
