### ISSUE TITLE
Ubuntu 16.04: No on screen keyboard

### ISSUE THREAD

**Issue by Tinche** [kozec/sc-controller#23]
Hi,

been playing around with this, really loving it so far! However I can't get the on-screen keyboard to show up. I've bound 'Special Action -> Display On-Screen Keyboard' to a button but nothing's happening. Do I need to install anything else?

**Comment by hendricha** [comment]
I seem to have the same issue in 14.04, I've installed the prebuilt package. Runing scc-osd-keyboard and scc-osd-menu in terminal will produce and error, missing libXfixes.so, however libxfixes3 package is installed.

**Comment by kozec** [comment]
> missing libXfixes.so

Sounds like good reason for trouble.
What is `whereis libXfixes.so` output on your machine?

**Comment by Tinche** [comment]
Can confirm, 
```
> scc-osd-keyboard
Traceback (most recent call last):
  File "/usr/bin/scc-osd-keyboard", line 20, in <module>
    from scc.osd.keyboard import Keyboard
  File "/usr/lib/python2.7/dist-packages/scc/osd/__init__.py", line 11, in <module>
    from scc.lib import xwrappers as X
  File "/usr/lib/python2.7/dist-packages/scc/lib/xwrappers.py", line 10, in <module>
    libXFixes = CDLL('libXfixes.so')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libXfixes.so: cannot open shared object file: No such file or directory
```
`libxfixes3` is installed (1:5.0.1-2).

```
> whereis libXfixes.so
libXfixes:
```

Also,

```
> locate libXfixes.so
/usr/lib/i386-linux-gnu/libXfixes.so.3
/usr/lib/i386-linux-gnu/libXfixes.so.3.1.0
/usr/lib/x86_64-linux-gnu/libXfixes.so.3
/usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
```

**Comment by hendricha** [comment]
Same as @Tinche 's response

**Comment by kozec** [comment]
Ah, Ubuntu, Ubuntu...
It's like they do things different especially to break my code :)

I'm firing up VM...

**Comment by kozec** [comment]
Ok, fixed and released in [latest release](http://software.opensuse.org/download.html?project=home%3Akozec&package=sc-controller).

**Comment by Tinche** [comment]
can confirm, writing this with the keyboard :)

**Comment by Tinche** [comment]
Thanks for fixing, that was *really* fast :)

**Comment by kozec** [comment]
Luckily, it was simple as well :)
