### ISSUE TITLE
Editing the 'per axis' settings of gyro doesn't stick when reopening the gyro settings

### ISSUE THREAD

**Issue by Managor** [kozec/sc-controller#230]
Makes configuring the gyro a chore

**Comment by kozec** [comment]
I'm not sure I understand because I was not able to replicate it...

You'll setup per-axis settings, click OK and they are not used?

**Comment by Managor** [comment]
https://my.mixtape.moe/uleitn.webm

Made a short video on it. As you can see it resets to (not set) when I reopen. What I've tried, it saves it and uses the axis, but doesn't fetch the data when you go reconfigure it.

**Comment by kozec** [comment]
Fixed by @MightyPork in #238
