### ISSUE TITLE
Hold Modifier Binding Labelled as "Pressed"

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#234]
I noticed that when using mode shift bindings on pad buttons, hold modifiers are mislabelled as "pressed" rather than hold.

screenshot:
https://imgur.com/a/T5k6t

**Comment by kozec** [comment]
Is that binding for holding pad pressed? :)

**Comment by GlacialTurtle** [comment]
I see what you mean, but with both a press and hold action on the button, press shows on the hold action and not on the normal pressed action, which ends up a little confusing.

**Comment by kozec** [comment]
Yeah, I agree and there shouldn't be problem to add exception so it doesn't shows like that, I was just not 100% sure if I understand when it happens.
