### ISSUE TITLE
Add *Joystick Press* as mode shift method

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#235]
As someone who regularly uses WASD on the LPad, being able to mode shift the RPad or the Buttons with the Stick is a valuable option.  Is this a possibility?

**Comment by kozec** [comment]
Yes, you can do it with custom action, using STICK as modeshift button. But I can add it to GUI as well.

**Comment by LinuxJoeUser** [comment]
Huzzah!  Whilst it's *awesome* to be able to create custom actions via code (I love being able to simply copy the code from one profile to another, for example), as a GUI guy I tend to assume that if it's not in the GUI it's not available.  I'm glad it was a simple fix and appreciate your doing it. :)

**Comment by kozec** [comment]
Well, there will always be stuff and combinations available only as custom actions, because GUI that would allow doing _everything_ would look like Flight Simulator :)
