### ISSUE TITLE
Add option to place OSD menu?

### ISSUE THREAD

**Issue by AccountOneOff** [kozec/sc-controller#239]
Right now the OSD menu overlaps with my panel on Gnome and I was wondering if you could add an option to move that menu in the settings. Kind of like the [Panel OSD extension.](https://github.com/jenslody/gnome-shell-extension-panel-osd) If not it's not that big a deal but it'd be nice.

![OSD Menu](https://i.imgur.com/SFvYGjw.png)

**Comment by kozec** [comment]
You should be able to change where menu pops out here:

![menu-pos](https://user-images.githubusercontent.com/1282500/28954480-f295d9ca-78df-11e7-8ee3-71f7e1ae2f44.png)

Doesn't that work on your side?

**Comment by AccountOneOff** [comment]
Oh snap, yeah that works thank you. I think that should be moved/added to the "OSD & Menu" in Settings as a global setting.

**Comment by kozec** [comment]
> Oh snap, yeah that works thank you. I think that should be moved/added to the "OSD & Menu" in Settings as a global setting.

Well, thing is, that's not global setting, it's per-profile. I can add some kind of "global margins" though, what's exactly are you trying to do?

> Secondary menu (profile switch) and on screen keyboard don't seem affected.

Now that sounds like bug. May I ask what values have you set just so I can replicate it?

**Comment by AccountOneOff** [comment]
position(10, -30, menu('Default.menu'))

https://imgur.com/a/l9VZH

**Comment by kozec** [comment]
That's kinda easier to say than is done :D

But I'm planning smaller OSD overhaul so menus for different controllers will be shown at different places when more than one controller is used, so I'll include option for margins at that time.

**Comment by kozec** [comment]
Closed in favor of #418 as solving that one would include this as well.
