### ISSUE TITLE
Tray icon disappears when gnome shell restarts.

### ISSUE THREAD

**Issue by AccountOneOff** [kozec/sc-controller#240]
The tray icon disappears whenever gnome shell crashes and restarts. Manually restarting makes it disappear as well. SC-Controller is still running but there's no icon in my tray.

Ubuntu 17.04
Gnome 3.24.3
TopIcons Plus
KStatusNotifierItem/AppIndicator Support

https://imgur.com/a/9aXBb

**Comment by kozec** [comment]
I'm afraid this may be bug in gnome shell, AppIndicator icon doesn't have way to hide itself or be manipulated in any way. Application simply creates it and hopes it is displayed somewhere.

**Comment by AccountOneOff** [comment]
Oh that's a shame thank you.
