### ISSUE TITLE
the save button has no icon or tooltip

### ISSUE THREAD

**Issue by MightyPork** [kozec/sc-controller#241]
![screenshot_20170804_075754](https://user-images.githubusercontent.com/2041118/28956027-b145f6de-78ea-11e7-9202-4a4309954200.png)

I'm not actually sure it's a save button, but the (changed) text disappears when I click it, so that's what I assume.

(arch linux, KDE/Plasma)

**Comment by kozec** [comment]
Icon theme you are using is missing "gtk-save" icon. And since you are using KDE, there is good chance you don't have any GTK theme set at all.

**Comment by MightyPork** [comment]
I've installed a couple gtk themes, but nothing happened.

At least I think it should have tooltip or text, if it must use this system icon that sometimes doesn't show.

**Comment by kozec** [comment]
Tooltip is not a problem, but adding text in way so it's shown when image is not available is not possible, AFAIK.

Do you have any icons anywhere? For example, if you click on stick and select gestures, there should be Edit button with icons and two buttons with pictographs for plus / add and minus / remove.
If not, [something like this](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#Themes_not_working_in_GTK.2B_apps) may help

**Comment by MightyPork** [comment]
All other icons work, as far as I can tell

![screenshot_20170804_103818](https://user-images.githubusercontent.com/2041118/28961044-293146b0-7901-11e7-8b71-20b4e6711062.png)
![screenshot_20170804_103849](https://user-images.githubusercontent.com/2041118/28961052-2f8c127e-7901-11e7-898f-d137467f68da.png)

even undo-redo, but they are gray and almost invisible
![screenshot_20170804_103826](https://user-images.githubusercontent.com/2041118/28961047-2c3b9680-7901-11e7-89db-309198baaf20.png)

**Comment by kozec** [comment]
> even undo-redo, but they are gray and almost invisible

Well, that's what you get for dark icon theme on dark background :)

Frankly, there is not much what I can do here, especially because I can see all other gtk-_something_ icons being displayed fine (there is at least gtk-ok, gtk-cancel, gtk-add and gtk-remove on your screenshot). But there are multiple names for "save" icon, so if you happen to know what theme are you using, I can check what names it supports and chose more generic one.

**Comment by MightyPork** [comment]
According to [this document](https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html), the closest standard icon name (ie not gnome specific) is document-save, which indeed works perfectly for me (ie 'document-save', not 'gtk-document-save') in `document_switcher.py:282`. Ideally all gtk-* should be eliminated to make it work outside Gnome.

`Gtk.Button.new_from_icon_name()` [apparently shows "broken image" if the icon can't be found](https://people.gnome.org/~gcampagna/docs/Gtk-3.0/Gtk.Button.new_from_icon_name.html), but I haven't figured out how to check that it happened. If there's a way, then maybe this could be used as a fallback, if it doesn't look OK on Gnome.

**Comment by kozec** [comment]
> `Gtk.Button.new_from_icon_name()` apparently shows "broken image" if the icon can't be found, but I haven't figured out how to detect it had happened. If there's a way, then maybe this could be used as a fallback, if it doesn't look OK on Gnome.

Most of icons are defined in glade files, so there is not much of magic that can be done, but I don't think it will be necessary anyway. Using freedesktop icon names should work fine.

**Comment by MightyPork** [comment]
works great, thanks!
