### ISSUE TITLE
Import steam configs from file

### ISSUE THREAD

**Issue by setzer22** [kozec/sc-controller#242]
When selecting "Import Steam Profile" in the "Import Export Configs" menu, a list is presented to the user with some detected steam configs. However, there is no clear documentation as to which steam configs are on that list, and not all of them are detected. Moreover, some users share steam controller configurations on the internet as text files, which cannot be loaded with the tool.

Because of that, I believe the configurator should offer the possibility to import the steam JSON config from a file. This should probably be a very simple addition, since the tool is already loading files anyway.

I can work on this if you don't have any time, but given my lack of experience with the codebase and with gtk3, it will probably take a lot more than needed. I think this should be a very simple addition which can add a lot of value to this tool. For me, this is the only thing keeping me from using sc-controller instead of the steam client's driver.

**Comment by kozec** [comment]
Steam profiles are readed from `~/.steam/steam/SteamApps/workshop/content` as that's, AFAIK, only place where they are stored by Steam.

You can drag&drop Steam's profile in vdf format on SCC window and it should go straight into last page of Import dialog. You can do same with SCC own profile format and with profile files from steamcontrollerdb.com.

But I never heard about "steam JSON config". Is it something new?

**Comment by setzer22** [comment]
> Steam profiles are readed from ~/.steam/steam/SteamApps/workshop/content as that's, AFAIK, only place where they are stored by Steam.

Oddly enough, some games are not detected for me (but are present in sharedconfig.vdf and have controller configs). Should I file a bug report with more info?

> You can drag&drop Steam's profile in vdf format on SCC window and it should go straight into last page of Import dialog. You can do same with SCC own profile format and with profile files from steamcontrollerdb.com.

My bad! I didn't know this was implemented. To me, it was not obvious at all that I could drag-n-drop a vdf file as well.  May I suggest to change the "You can also drag-n-drop profile file on main application window" to something that explicitly mentions steam vdf profiles? I'd say: "You can also drag-n-drop a sccprofile or Steam vdf profile files on the main application window". 

> But I never heard about "steam JSON config". Is it something new?

I just meant vdf, sorry about that!

**Comment by kozec** [comment]
> Oddly enough, some games are not detected for me (but are present in sharedconfig.vdf and have controller configs). Should I file a bug report with more info?

Please, do, there is always chance that something got changed since importing was implemented.

> You can also drag-n-drop a sccprofile or Steam vdf profile files on the main application window"

I think it would be even better to just move that text to bottom of window, so it's not visibly associated with just one format.

**Comment by setzer22** [comment]
Right, having the text at the bottom should be enough. I probably assumed it was only `.sccprofile` files due to the position in which the label is placed.

Feel free to close this. I'll try to investigate a bit about the missing games and post an issue once I have more info!
