### ISSUE TITLE
Add ability to map multiple keys to GUI

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#244]
Granted, at present it's possible to do this by going into "Custom Action" and adding additional keys via:

`and button(Keys.KEY_`

and whatever key you're looking to add.  It would be a great time saver to have this done in the GUI when we're adding a key.  

Maybe after choosing a key the "Press a key" window a small pop-up window  could open and display two buttons:  [Done] and [Additional key] or something.  The [Done] button would be the default, pre-chosen button, and simply hitting "Enter" would fire it.  The "Additional Key" option would re-open the "Press a key" window and the next setting would be added via:

`and button(Keys.KEY_`

Or whatever.  The main thing is getting the ability to add keys to a single modeshift via the GUI. :)

**Comment by kozec** [comment]
Adding [done] button is bad idea, there is already too much clicking when one tries to map multiple buttons in a row.

Are you trying to map some specific combination, or just ctrl+ or shift+something?

**Comment by LinuxJoeUser** [comment]
> Are you trying to map some specific combination, or just ctrl+ or shift+something?

Nothing specific, but it isn't uncommon when I'm mapping a K & M game to the SC that I might map two contextually dependent keys to one SC input.  For example, in my _Vampire: The Masquerade config_ I've double mapped six inputs:

- **Y** = "Feed (Dialogue 1)" `button(Keys.KEY_F) and button(Keys.KEY_1)`
- **B** = "Attack Mode" (Dialogue 2) `button(Keys.KEY_TAB) and button(Keys.KEY_2)`
- **X** = "Use (Dialogue 4) `button(Keys.KEY_E) and button(Keys.KEY_4)`
- **RGRIP** =  `button(Keys.KEY_SPACE) and button(Keys.KEY_B)`
- **LGRIP** = `button(Keys.KEY_LEFTCTRL) and button(Keys.KEY_V)`

> Adding [done] button is bad idea, there is already too much clicking when one tries to map multiple buttons in a row.

That makes sense.  Ok, I can think of two other ways this could be done without increasing the number of clicks:

1.  Change the name of the  "Grab a Key" button to  "Add a Key" or "Map a Key," and modify  its behaviour so that it adds the button pressed to a previous entry using `and button(Keys.KEY_foo)` instead of overwriting it.  The "Clear" button can be used when it's necessary to overwrite an entry.

2.  Split the existing "Grab a Key" button into two side-by-side buttons: 

- Button One  acts as "Grab a Key" does now, adding  `button(Keys.KEY_foo)` and overwriting previous settings.  It could be called something like "Add a New Key" 
- Button Two _doesn't_ overwrite, but instead adds the new key via `and button(Keys.KEY_foo)` to the previous settings.  It could be called something like "Add Another Key" or "Add More Keys."

I like the second, "two button" method best, as it keeps the current "Grab a key" function but also allows another key to be added without adding any additional clicks to the process. Either method greatly streamlines the multi-button mapping procedure for the average GUI using non-programmer, I think. :)

**Comment by kozec** [comment]
> Split the existing [Grab a Key] button into two side-by-side buttons:

Something like this?
![buttons](https://user-images.githubusercontent.com/1282500/29284054-81108e60-8129-11e7-9fab-8170f1cdd111.png)

Sounds much better :)
