### ISSUE TITLE
OSD Keybord doesn't show

### ISSUE THREAD

**Issue by MeDeVILe** [kozec/sc-controller#245]
I had a problem with Kodi and the solution was to:
`sudo apt-get remove python-openssl python-cryptography python-setuptools python-pkg-resources curl`
`sudo apt-get install kodi`
`sudo apt-get install python-software-properties`

But now the sc-controller doesn't show OSD keyboard.
I have done
`sudo apt reinstall sc-controller`
but it didn't help.

I don't want to screw it more. Please help :)

**Comment by kozec** [comment]
Turn everything off, make sure not process starting in "scc-" runs, start `scc-daemon debug`, try showing OSD menu and check error messages :)

**Comment by MeDeVILe** [comment]
Sorry for trouble.
Everything get back to normal after reboot. 
"Did you try to turn it off and on again?" I didn't :P
