### ISSUE TITLE
Endless "SC-controller was upgraded" notifications

### ISSUE THREAD

**Issue by C0rn3j** [kozec/sc-controller#246]
I get these each time I start up SC-controller.

I'd imagine that once I "X" out of it, it will not appear anymore.

I should be on the latest git version.

**Comment by kozec** [comment]
> I'd imagine that once I "X" out of it, it will not appear anymore.

Yep, that's the idea. Can you, please, check output of `grep last_version ~/.config/scc/config.json` and if it changes once you click on "X"?

**Comment by kozec** [comment]
... so, anyway, yeah, I forgot to add code for that.

ef me -_-

**Comment by kozec** [comment]
Fixed in latest release.
