### ISSUE TITLE
Failed to read release notes

### ISSUE THREAD

**Issue by Vintodrimmer** [kozec/sc-controller#248]
Good morning,

Upon launch `sc-controller` tries to get the release notes and throws a python2 error, also saying that operation is not supported. Here's the complete terminal output:

```
I profile       Converted XY(mouse(Rels.REL_HWHEEL, 1.0), mouse(Rels.REL_WHEEL, 1.0)) to feedback(LEFT, 4096, 16, ball(XY(mouse(Rels.REL_HWHEEL, 1.0), mouse(Rels.REL_WHEEL, 1.0))))
I profile       Converted button(Keys.BTN_RIGHT) to trigger(50, button(Keys.BTN_RIGHT))
I profile       Converted button(Keys.BTN_LEFT) to trigger(50, button(Keys.BTN_LEFT))
pidfile /home/eichhorn/.config/scc/daemon.pid does not exist. Daemon not running?
W App           Failed to read release notes
E App           g-io-error-quark: Operation not supported (15)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/app.py", line 1254, in http_ready
    stream = f.read_finish(task)
Error: g-io-error-quark: Operation not supported (15)
```

Is the error somewhere on my part?

**Comment by kozec** [comment]
Most likely very old GTK/GLib that can't handle http(s) well. It's as non-fatal as it can be, you'll just miss on [messages like this.](http://imgur.com/a/Tgzca)

Anyway, I'd like to know what distro are you using.

**Comment by Vintodrimmer** [comment]
I'm using Void Linux.

My `glib` version is 2.52.3_1 and `gtk+` is 2.24.31 and 3-3.22.18.

**Comment by kozec** [comment]
So, I've ended up installing Void in VM and it kinda displays that message as expected. Library versions are the same and I've installed SCC [from this template](https://github.com/voidlinux/void-packages/pull/5952/files)

My best guess at this point just some kind of temporal network failure.
