### ISSUE TITLE
[important] After +30 mins of constant play, the sc-daemon frezze and worst

### ISSUE THREAD

**Issue by DFOXpro** [kozec/sc-controller#251]
## Setup

Using the attached profile for a long session, it has circular and gyro inputs also 8buttons layout and switchable grips actions.

## What do you want

Playing X hours in any game (Euro truck for my case)

## What really happen

The driver scc-daemon after about 30mins or more of playing freeze (not the driver UI, just the daemon, rendering like the controller became off). Trying to stop/kill the process some time freeze the OS (kernel panic?) or sometimes make the daemon a perfect zombie (unable to kill even with the ```kill -9 pid```, forcing to a hard restart of the PC).

Sadly I don't have any debug info, I did try disabling/enabling debug mode but get the same result, and this behavior start maybe after the 0.3.13 update.

How can I get an useful log?

**Comment by DFOXpro** [comment]
## Current profile
[ets2.sccprofile.zip](https://github.com/kozec/sc-controller/files/1254150/ets2.sccprofile.zip)

**Comment by kozec** [comment]
> How can I get an useful log?

Turn off emulation in gui and start `scc-daemon debug` in console.

Do you have rumble emulation turned on?

**Comment by DFOXpro** [comment]
> Do you have rumble emulation turned on

Yes

**Comment by kozec** [comment]
Ok then, please, try to get that log and then try disabling it and playing without rumble for a while.

Thing is, if game or scc-daemon crashes during rumble effect upload (while game is setting next effect parameters), uinput tends to end up in rather frozen state. But even if that's the cause of your problem, it would really help to know what is causing the crash.

**Comment by DFOXpro** [comment]
while I'm testing, can this be fixed?

**Comment by kozec** [comment]
I surrely hope so :)

**Comment by DFOXpro** [comment]
Using input test (flag+ui) + rumble emu I was able to trigger the bug, the main process of scc-daemon keeps running without any apparent error, but one of the python child process became frozen, now I'm hard restarting my pc T.T

**Comment by kozec** [comment]
> but one of the python child process became frozen, now I'm hard restarting my pc T.T

It would kinda help if you said which one...

What input test are you using?

**Comment by kozec** [comment]
Was you able to capture any logs of this issue?

**Comment by DFOXpro** [comment]
no, just normal game play or total system freeze, something I look at some point there was like 10 "sc controllers" in the js -test at the same time followed by a freeze, no userful log in any case

**Comment by kozec** [comment]
Sorry, but I can't do much without at least that daemon log, I'm not a psychic :)

Anyway, I found bug that _could_ be causing this, although I can't imagine how... Basically, it was but in section that can cause freezing when buggy. Hopefully it will help. If not, feel free to reopen or create new issue.
