### ISSUE TITLE
Info request on how it blocks steam from recognising the controller

### ISSUE THREAD

**Issue by FunnyBunny14** [kozec/sc-controller#252]
I'm trying to create my own program for the steam controller to interface with Elite dangerous as well as generally making the controller more useful for space sims (and sims in general). I want to write it in C++ though, and I'll be using DirectInput to grant full axis controls and I'll be using ED's API to add something akin to native support in conjunction with that.
However, I don't know much about working with USB devices, and while this project has been very helpful, I still don't know how to suppress the controller's input. Would it be possible for someone to help me out in that regard? I also heard about the left stick and left pad essentially being the same entity to the software. Is that still the case?
I'm sorry if this is the wrong section to put this, but I couldn't find anything else and I've already been mulling this idea over in my head for a few days without anything to show for it, and I really want to see it come to life now.

**Comment by kozec** [comment]
> and I'll be using DirectInput

Do you happen to do this on Windows? If so, that may be very 1st thing to note when asking something like this :)

Sadly, I don't really have any idea how this works on Windows. On Linux, there is IOCTL_USBFS_DISCONNECT ioctl, that basically says to _kernel_ "give me exclusive access to this device and forget it ever existed", so you may try searching for Windows alternative of that.

**Comment by FunnyBunny14** [comment]
Hmm, thanks! That's already way more useful than anything I found before. Thanks to that, I've come accross this: https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/specifying-exclusive-access-to-device-objects
Basically, I need to write my own driver and then give that exclusive access... somehow, using the information from microsoft. It'll be annoying, but possible. 
Thank you so much once again, I've now got the beginning of something awesome! 😀

**Comment by FunnyBunny14** [comment]
Well, long story short I found a program (hidguardian) to do what I want, but I'm kinda stuck on the whole input thing. I found this: https://github.com/meh/steamy/tree/master/controller , and I of course also found "Input_Format" in your project https://github.com/kozec/sc-controller/blob/master/scc/drivers/sc_dongle.py
Since I don't really know anything about how enums work, I don't know how to use the info in the first source properly - I can use it for basic tasks like enabling/disabling something just fine, but I wouldn't know how to use it to read data from the touchpad, for example. So I got curious about what you did to connect with the steam controller in the drivers, but "Input_Format" appeared to be the origin, and still was left none the wiser.
Is there anything I'm missing, and if there's not, how would I go about replicating it? The difference in os shouldn't be an issue when it comes to data to/from the controller since that depends on its own firmware, and that is (basically guaranteed to be) consistent across platforms.

**Comment by kozec** [comment]
> but "Input_Format" in the dongle file appeared to be the origin, I still was none the wiser.

Sorry, I can't parse this. It appeared what? Steam Controller starts in "lizard mode", where it emulates mouse and keyboard. You have to [send configuration packet](https://github.com/kozec/sc-controller/blob/master/scc/drivers/sc_dongle.py#L296) to switch it to mode that SCC and Steam uses -

**Comment by FunnyBunny14** [comment]
And after that? How do you get the input from the controller then? 
This was my original question, sorry for not being clear enough - I thought that you used Input_Format for that.

**Comment by kozec** [comment]
I'm afraid that's the part which Windows will do completely different, although libusb should be available for it as well. You can check [docs here](http://libusb.sourceforge.net/api-1.0/io.html).
