### ISSUE TITLE
Controller turns itself back on again when using gyro

### ISSUE THREAD

**Issue by predr** [kozec/sc-controller#253]
Having an issue with a profile I made for DiRT Rally that uses gyro for steering. When I turn off the controller after playing, there is 50/50 chance it will immediately turn itself back on again. With below test profile the issue can be recreated in 3-4 tries.

```
{
    "buttons" : { "C" : { "action": "turnoff()" } },
    "gyro": { "action": "gyroabs(None, Axes.ABS_X, None)" }
}
```

Part of the log when C turnoff() is pressed and it starts up again.
```
W Actions       Action TurnOffAction can't handle button press event
D SCDongle      Turning off the controller...
D SCCDaemon     Controller removed: <SCWireless 1>
D SCDongle      Not requesting serial number for SC 1
D SCDongle      Got wireless SC with serial 1
D SCCDaemon     Assigned default_mapper to <SCWireless 1>
D SCCDaemon     Turning gyrosensor ON
D SCCDaemon     Controller added: <SCWireless 1>
D OSD DaemonCtrl    Daemon reported profile change: /home/myname/.config/scc/profiles/test.sccprofile
```

Log when it turns off correctly without starting again.
```
W Actions       Action TurnOffAction can't handle button press event
D SCDongle      Turning off the controller...
D SCCDaemon     Controller removed: <SCWireless 1>
```

Also tried using "Use Serial Numbers to Identify Controllers" option, issue still happens. Haven't noticed this issue on any other profile, only this one that uses gyro.

**Comment by kozec** [comment]
I don't think SCC (or anything else) can cause controller to turn _on_, so this may be some kind of hw problem...

But I'll check it when I'd get home :D Can you upload your entire profile? It should be located in `~/.config/scc/profiles`.

**Comment by kozec** [comment]
... wait, you are using C / guide button? In that case, that may not be hw bug, but feature.

**Comment by kozec** [comment]
I can't reproduce this at all, so I guess it really relates to hw or firmware revision. But nevertheless, use custom action and add delay before turning controller off:

 `sleep(1); turnoff()` should be long enough for you to release button.

**Comment by predr** [comment]
Happens (to me) regardless of how turnoff() is initiated, it was just easier to test with C set that way.
Ok, thanks for looking into it. Will close if you can't reproduce.

**Comment by kozec** [comment]
So, even with profile you've posted, with two different controllers and with guide button set only to `turnoff()`, I can't replicate the problem. Only way how this could be done is if guide button were somehow short-circuting (because of moisture or some kind of metal piece moving inside).

Oh and just to be clear, can I merge that profile?

**Comment by predr** [comment]
Yes, submitted profile for merging as an example for gyro steering.

Don't waste more time on this until someone else can confirm/replicate this. Just to clarify, issue is not related to guide button. Turning off from the main menu or binding turnoff() to any other button produces same results for me. Issue is in gyro waking controller for some reason. I don't have this problem with other profiles that don't use gyro.
