### ISSUE TITLE
How to add programs to the Games Submenu

### ISSUE THREAD

**Issue by jimgatenby** [kozec/sc-controller#255]
i tried adding the program to the my main menu on my desktop with a .desktop file but scc doesn't recognize the addition. I looked in the wiki for menu items and submenus and see that it is automatically generated, but how? 
Thanks
Jim

**Comment by kozec** [comment]
Application list is cached, so if you've just added new one, it will be shown next time scc-daemon is started. You can disable and re-enable emulation in GUI to restart it.

But I should probably add some kind of filesystem watch there...

**Comment by jimgatenby** [comment]
I've tried that, along with fully restarting the program and the entire system.

**Comment by kozec** [comment]
Ok, that sounds like something is broken. What exactly have you added and where?

**Comment by jimgatenby** [comment]
It is very likely I'm doing something wrong but here's what I did.
I'm running Linux mint 18.2, I right click on the menu -> configure... -> Menu editor -> add new item in the games submenu.
I also tried making the file /usr/share/applications/Broforce.desktop
and filled it with:
[Desktop Entry]
Encoding=UTF-8
Exec=/home/user/GOG\ Games/Broforce/start.sh
Icon=/home/user/GOG\ Games/Broforce/game/Broforce_Data/Resources/UnityPlayer.png
Type=Application
Terminal=false
Comment=Broforce
Name=Broforce
GenericName=Broforce
StartupNotify=false
Categories=Games;

**Comment by kozec** [comment]
> Categories=Games;

Game (singular) is correct name of that category. Is that icon shown under games in your normal menu?

**Comment by jimgatenby** [comment]
So I changed Games to Game, it highlighted red in gedit and appeared in my normal desktop menu. Good start! But now when I open up the OSD menu with sc-controller everything works until I click the games submenu then it freezes.

**Comment by kozec** [comment]
> But now when I open up the OSD menu with sc-controller everything works until I click the games submenu then it freezes.

Interesting progress :( Can you try to run scc-daemon in terminal so it displays error, if there is any? Disable emulation in GUI and start `scc-daemond debug` manually.

**Comment by jimgatenby** [comment]
It was the picture I used for the icon not working correctly. Thanks a lot for your quick responses and walking me through this. Hope I didn't waste too much of your time.

**Comment by kozec** [comment]
Np, but what was up with that picture? I don't like idea of OSD randomly freezing because of that.

Can you upload it somewhere?
