### ISSUE TITLE
Unable to get two steam controllers to work with retroarch

### ISSUE THREAD

**Issue by jphaskins** [kozec/sc-controller#256]
I haven't been able to use my two steam controllers at once in Retroarch. I don't think it's retroarch because I can use one SC and a logitech F310. I've tried with "Use Serial Numbers to Identify Controllers" enabled and disabled. While enabled neither controller works, when disabled I have successfully used them but I get generally crashy behavior and it seems like one gets stuck in desktop mode.

I'm on Fedora 26.

**Comment by kozec** [comment]
Does sc-controller GUI shows two controllers? And what's crashy behavior? Because that doesn't sounds like something I'd like to have :D

Anyway, I'll check what retroarch says on my side, but for start, try checking if jstest-gtk shows two controllers and if both of them react when set to default "xbox controller" mode.

**Comment by jphaskins** [comment]
I do see two controllers, with or without "Use Serial Numbers to Identify Controllers". If i use the overlay to switch profiles on either one they always set to the same controller. The top one I have to change by mouse. I'm not sure, this might be normal behavior (sharing profile in some way).

"Crashy behavior" is for example, pressing a button on controller 1 causes retroarch to force close or getting stuck in desktop mode. Wish I could be more specific I'll do some more tests tomorrow. Also, I'm using the MAME core and sdl2 for input.

**Comment by kozec** [comment]
> "Crashy behavior" is for example, pressing a button on controller 1 causes retroarch to force close or getting stuck in desktop mode.

Ah, retroarch crashing. That's better, at least for scc :)

And yes, overlay works only with first controller. It's feature, but I don't really know what was I thinking back then :) I'll check if it can be fixed in some simple way.

**Comment by Raptus1** [comment]
I'm running Ubuntu 17.04 and have similar behavior with two controllers.

It's not "crashy", but when I change profile it is like both change, or maybe that the controller 2 (if in xbox-mode) becomes controller number one for the profile or something.

Or do I need to duplicate profiles but spesifically as Player 2?

Maybe the feature with the overlay is reason for this also?

**Comment by setzer22** [comment]
I can also confirm having similar issues when two controllers are plugged in on arch linux. It doesn't happen all the time though.

I haven't been able to do proper testing but it is as if the controllers exchanged profiles at some point. One of the two controllers also stopped working completely a couple times (I couldn't even turn off and had to remove batteries).

I'd say the OP is experimenting two separate issues, since the problems with multiple controllers can be replicated outside of retroarch.

**Comment by kozec** [comment]
> It's not "crashy", but when I change profile it is like both change, or maybe that the controller 2 (if in xbox-mode) becomes controller number one for the profile or something.

Basically, on-screen menu keeps no tracking of which controller activated it and so it always changes profile for first one. I'll try to fix that so we can look at problem with retroarch. Are you able to run sc-controller from git?

**Comment by kozec** [comment]
Ok, changing profile with on-screen menu should now work as expected.

**Comment by Raptus1** [comment]
I'm using the ubuntu repo. Will that be updated soon also?

Looking forward to test it.

**Comment by Raptus1** [comment]
Tried it now, and it works very good. Still need to do some more testing though. Also now I can use two controllers on the same plug. Will try a third controller a bit later.

Is it a lot of hassle to add different color codes to the different controllers on-screens menu?

**Comment by kozec** [comment]
> Is it a lot of hassle to add different color codes to the different controllers on-screens menu?

I have it in todolist along with having menus from other controller on other side of screen and allowing display them at once, but yes, it will be rather big change.

**Comment by jphaskins** [comment]
I cloned and ran git. I'm not sure if anything you could have done could have affected retroarch or if I made it all up, but it works great now.

The only thing I noticed is test doesn't work for one controller when "Use Serial Numbers to Identify Controllers" is selected. But it doesn't affect actually playing games. By the way, assuming there are no issues should I leave that option on or off?

**Comment by kozec** [comment]
> By the way, assuming there are no issues should I leave that option on or off?

Nope, serials are used only to save controller configuration. With it, config is "bound" to physical controller, when turned off, it remembers config for first, 2nd, 3rd... in order as they were connected.

**Comment by jphaskins** [comment]
That could be one of my problems. I have an original pre-order.
