### ISSUE TITLE
./run.sh on xbian using Raspberry Pi 3 gives error.

### ISSUE THREAD

**Issue by Raptus1** [kozec/sc-controller#257]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./libuinput.so: cannot open shared object file: No such file or directory
libuinput.so is outdated or missing, building one
Please wait, this should be done only once.

running build
running build_py
running build_ext
building 'libuinput' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c scc/uinput.c -o build/temp.linux-armv7l-2.7/scc/uinput.o
unable to execute 'arm-linux-gnueabihf-gcc': No such file or directory
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```

It's a bit different setup.

 [This site](https://stackoverflow.com/questions/36465212/compileerror-command-arm-linux-gnueabihf-gcc-failed-with-exit-status-1) lead me [here](https://unix.stackexchange.com/questions/119358/create-file-in-folder-permission-denied) where it might be some issues with permission, but I'm not sure how to proceed with it.

The setup is basically for Kodi (running as a service without using X If i'm not mistaken).

**Comment by kozec** [comment]
> unable to execute 'arm-linux-gnueabihf-gcc': No such file or directory

You don't have gcc installed. It should be something like `sudo apt-get install gcc` on debian-based distros.

**Comment by Raptus1** [comment]
Tested it without any controllers added.

It is a somewhat headless node btw. Boots straight into kodi and has no desktop env.

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: ./libuinput.so: cannot open shared object file: No such file or directory
> libuinput.so is outdated or missing, building one
> Please wait, this should be done only once.
> 
> running build
> running build_py
> running build_ext
> building 'libuinput' extension
> arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c scc/uinput.c -o build/temp.linux-armv7l-2.7/scc/uinput.o
> scc/uinput.c:177:11: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
>  const int uinput_module_version() {
>            ^
> arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/scc/uinput.o -o build/lib.linux-armv7l-2.7/libuinput.so
> running build_scripts
> creating build/scripts-2.7
> copying and adjusting scripts/scc-daemon -> build/scripts-2.7
> copying and adjusting scripts/sc-controller -> build/scripts-2.7
> copying and adjusting scripts/scc-osd-dialog -> build/scripts-2.7
> copying and adjusting scripts/scc-osd-keyboard -> build/scripts-2.7
> copying and adjusting scripts/scc-osd-launcher -> build/scripts-2.7
> copying and adjusting scripts/scc-osd-menu -> build/scripts-2.7
> copying and adjusting scripts/scc-osd-message -> build/scripts-2.7
> copying and adjusting scripts/scc-osd-radial-menu -> build/scripts-2.7
> copying and adjusting scripts/scc-osd-show-bindings -> build/scripts-2.7
> changing mode of build/scripts-2.7/scc-daemon from 644 to 755
> changing mode of build/scripts-2.7/sc-controller from 644 to 755
> changing mode of build/scripts-2.7/scc-osd-dialog from 644 to 755
> changing mode of build/scripts-2.7/scc-osd-keyboard from 644 to 755
> changing mode of build/scripts-2.7/scc-osd-launcher from 644 to 755
> changing mode of build/scripts-2.7/scc-osd-menu from 644 to 755
> changing mode of build/scripts-2.7/scc-osd-message from 644 to 755
> changing mode of build/scripts-2.7/scc-osd-radial-menu from 644 to 755
> changing mode of build/scripts-2.7/scc-osd-show-bindings from 644 to 755
> 
> Symlinked libuinput.so -> build/lib.linux-armv7l-2.7/libuinput.so
> 
> Traceback (most recent call last):
>   File "scripts/sc-controller", line 11, in <module>
>     import gi
> ImportError: No module named gi
>

**Comment by kozec** [comment]
You know that you are not get GUI nor overlay if it doesn't use X nor any desktop environment, do you? :) If that's not the case, check [list of dependencies in readme](https://github.com/kozec/sc-controller#dependencies) and install everything.

Or you can run without gui as well, by starting `./daemon.sh debug /path/to/some/profile.json`

**Comment by Raptus1** [comment]
Thanks, but it is ok as long as I can find a way to change the profiles from within kodi., Maybe make a script for each.

But anyways. Have you tested any with suspend and after? The deamon needs to be stopped and then started again on my ubuntu 17.04 cinnamon setup.
