### ISSUE TITLE
gyro smoothing doesn't seem to be working.

### ISSUE THREAD

**Issue by Patola** [kozec/sc-controller#258]
Hi, I am a new user and I looked throughout the wikis, all the .md files from the repository, read a bunch of bug reports and every patreon post visible to non-patrons from this year. But I cannot find out what I am doing wrong, so I am assuming it's a bug. I am using sc-controller 0.13.4.1 on Ubuntu 17.04 64 bits, from the repository on the opensuse site - http://download.opensuse.org/repositories/home:/kozec/xUbuntu_17.04. I have created a few profiles before but I am now trying something more sophisticated with the gyro, activating it with right touchpad touching. However, when I rest my finger on the touchpad, the cursor wriggles nervously, so I thought that employing some smoothing was in place. However:

![gyro_999](https://user-images.githubusercontent.com/2991620/30382805-8551962c-9876-11e7-944d-92c4f1034195.png)

...for some reason, the smoothing tab is disabled. If I select any other output mode, including Mouse (Desktop), nothing changes, it stays disabled all the way. Ok, fine, I am going to try the custom action, it is more complicated but it would do, right?

Now, that is what appears from my previous selection:

![gyro_999 001](https://user-images.githubusercontent.com/2991620/30382967-fbeccad6-9876-11e7-820e-95437181cabf.png)

I try to change it to use the smooth function. According to [this page](https://github.com/kozec/sc-controller/wiki/Custom-Action-Examples-and-Explanations#-smoothbuffer8-multiplier07-filter2--action), smooth has the following format: smooth([buffer=8, [multiplier=0.7, [filter=2, ]]] action)

Well, when I try to change it, it simply does not accept it, and wont' save; at some points where I am typing it says smooth has the wrong number of parameters, but in the end it says nothing and simply refuses to accept my custom action:

![gyro_999 002](https://user-images.githubusercontent.com/2991620/30383294-cb7d9f0a-9877-11e7-8c92-17959a4bb9aa.png)

I even tried to "cheat" by looking at the .sccprofile and locating the gyroscope line:

```
    },
    "gyro": {
        "modes": {
            "RPADTOUCH": {
                "action": "mouse(ROLL)"
            }
        }
    },
    "is_template": false,
```

changing it to:

```
    },
    "gyro": {
        "modes": {
            "RPADTOUCH": {
                "action": "mouse(ROLL)",
                "sensitivity": [5.0, -5.0, 5.0],
                "smoothing": [8.0, 0.7, 2.0]
            }
        }
    },
    "is_template": false,
```

(I tried with "smooth" instead of "smoothing" but then it wouldn't start)
Then, I start sc-controller... And the gyro is working... but not smoothed. I open the configuration and it is like that:

![gyro_999 003](https://user-images.githubusercontent.com/2991620/30383822-f97882b6-9878-11e7-8108-c923ac37e67a.png)

It just stripped the smoothing! What is happening? Why isn't it accepting smoothing? Am I doing something wrong?

**Comment by Patola** [comment]
Also... It doesn't accept me editing that last part with the smooth function!

![gyro_999 004](https://user-images.githubusercontent.com/2991620/30383984-60ab7bfa-9879-11e7-88a8-a2e8c0703d4f.png)

**Comment by Patola** [comment]
Never mind. I am dumb. Just saw a video from #138 and noticed that it is the touchpad that should be smoothed, not the gyro. D'oh!

**Comment by kozec** [comment]
It's possible to allow smoothing with gyro in plain theory, I'm just not sure how should it behave :)

**Comment by LinuxJoeUser** [comment]
> It's possible to allow smoothing with gyro in plain theory, I'm just not sure how should it behave :)

I'd like to see some sort of smoothing for the gyro as well.  In its current state it seems quite jittery to me. ;)
