### ISSUE TITLE
Rebasing on scd?

### ISSUE THREAD

**Issue by shmerl** [kozec/sc-controller#26]
Would you be interested in rebasing the UI on [another driver implementation](https://gitlab.com/dennis-hamester/scd)?

It looks more complete and is actually actively developed further, while your current base rather stale.

**Comment by kozec** [comment]
Not really. sc-controller uses it's own daemon that is only *based* on Ynsta's driver and can do more than it.

And from quick look on scd's page, I think that scc-daemon can do more than it as well, so using scd as backend would mean loosing some features. And that doesn't sound like a good idea.

What *may* be possible to do is some sort of converter between sc-controller profile and scd configuration format. But it will be a lossy one.
