### ISSUE TITLE
Is it possible to combine the left and right analog into single axis?

### ISSUE THREAD

**Issue by parkerlreed** [kozec/sc-controller#260]
Been trying to get this working and have been failing miserably. I have a game that expects the accelerate and brake to be on a single axis (with neutral at 0, left trigger pulls down to -32767, right trigger pulls up to +32767)

Is it possible to do this with the current GUI?

**Comment by kozec** [comment]
Yes, that should't be a problem, as long as you don't press them both at once.

When you are binding trigger to analog axis, you can click at corner of those big arrows to bind just to half of it. Or use custom action and set  `axis(Axes.ABS_RY, 0, 32767)` on left and `axis(Axes.ABS_RY, 0, -32767)` on right trigger.

**Comment by parkerlreed** [comment]
Thanks! It'll be a little bit before I can test but it looks like that'll work great.

**Comment by parkerlreed** [comment]
Odd... `axis(ABS_RY, 0, 32767)` works great but if I try on the Z axis it messes up `axis(Axes.ABS_RZ, 0, 32767)`

**Comment by kozec** [comment]
That's because RZ are triggers and they are read differently from stick. Trigger goes from 0 to 256 and has no center. You can set `axis(Axes.ABS_RZ, 128, 256)` and `axis(Axes.ABS_RZ, 128, 0)` to left and right to get  behavior you are probably expecting, but I'm not sure how actual game will react to that.

**Comment by parkerlreed** [comment]
Ok will give that a shot, thanks. :) Yeah this is a pretty edge case. It's a slightly older game so I can kinda understand but eh. Thanks again for the help.
