### ISSUE TITLE
Minimize to tray icon greyed out

### ISSUE THREAD

**Issue by AccountOneOff** [kozec/sc-controller#263]
The option to minimize to tray is greyed out. 

Ubuntu 17.04
SC Controller v0.3.15

![greyed out](https://i.imgur.com/Fcmsavw.png)

**Comment by AccountOneOff** [comment]
False alarm. I forgot I changed the .desktop file to include `env XDG_CURRENT_DESKTOP=Unity`. It's back now but now I have to use TopIcons Plus instead of AppIndicator. :disappointed:

**Comment by kozec** [comment]
Yeah, Ubuntu 17.04 now uses Gnome and Gnome no longer supports status icons, so extension like that will be needed.

**Comment by AccountOneOff** [comment]
They got rid of them on 3.26 right? My PC is still on 3.24.

I've always used TopIcons Plus and recently with AppIndicator as some programs, like sc-controller, didn't work with the latter. I got rid of TopIcons Plus because I found using `env XDG_CURRENT_DESKTOP=Unity` made them work with AppIndicator. Guess I'll have to start using them in together again.

**Comment by kozec** [comment]
Sorry, when you said AppIndicator, I imagined library and statusicon system from Unity. Are you using gnome-shell extension with same name?

I can check if it is possible to make sc-controller work with it, although changing `XDG_CURRENT_DESKTOP` may be always necessary, as I don't think there is any way to check what _extensions_ is gnome shell using.

**Comment by AccountOneOff** [comment]
I'm using this extension: https://github.com/ubuntu/gnome-shell-extension-appindicator

**Comment by kozec** [comment]
By the way, what's your normal `XDG_CURRENT_DESKTOP` value?

**Comment by kozec** [comment]
I was not able to install any other extension because it's Gnome, so it's not tested with one you linked, but above fixes status icons with appindicator extension bundled with Ubuntu, which is, hopefully the same.

**Comment by AccountOneOff** [comment]
Yup that fixed it. Thank you!

**Comment by AccountOneOff** [comment]
With this update I can't reopen the window unless I launch SC Controller again and that duplicates the tray icon. Clicking and right-clicking the icon behaves the same and just opens the menu.

**Comment by kozec** [comment]
Well, yeah, that's what appindicator does, it can't react to clicking. I should add "show window" to that menu.
