### ISSUE TITLE
Unable to drag and drop profile: UnicodeDecodeError

### ISSUE THREAD

**Issue by gueulderack** [kozec/sc-controller#267]
Hi,
when I try to drag and drop a Steam profile, I had this traceback:
`File "/tmp/.mount_UD6SIc/usr/lib64/python2.7/site-packages/scc/gui/app.py", line 1480, in on_drag_data_received
    filetype = Dialog.determine_type(path)
  File "/tmp/.mount_UD6SIc/usr/lib64/python2.7/site-packages/scc/gui/importexport/dialog.py", line 69, in determine_type
    if filename.endswith(".sccprofile.tar.gz"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
`

To avoid library missing or version problem, I tried the appimage of your application, in version 0.3.99.3 . But it happened also with older versions, and packaging versions.

All vdf files I tried do the same error. I joined here one of them, if you want to try.
[nms config lby_0.zip](https://github.com/kozec/sc-controller/files/1349627/nms.config.lby_0.zip)

My system is a Fedora 26.

Do you have an idea of what happened?

Thank you.

**Comment by kozec** [comment]
Where is file you are dropping located and what kind of non-ascii characters are in the path?

**Comment by gueulderack** [comment]
Your answer triggered me the reason of the problem. My file is locating in a folder that contained french characters (é and è). I did a test, and this time, the vdf file is loaded.
Now, I have also an error message that indicate some game_action binding are ignored. Do you have the same thing? It result that buttons configuration are not loaded at the end.

Thank you, and congratulation for the great performance of your application.

**Comment by kozec** [comment]
Sorry for late answer, I had to test it out. Those ignored actions are Steam Input Actions, stuff that basically requires Steam and is definitely not going to work under wine.
