### ISSUE TITLE
modeshift inverts right pad axes and causes random cursor jump

### ISSUE THREAD

**Issue by cptMikky** [kozec/sc-controller#268]
[modeshift.sccprofile.txt](https://github.com/kozec/sc-controller/files/1353848/modeshift.sccprofile.txt)
Hi, 

when I set up right pad as mouse (trackpad or trackball) and use LT/RT modeshift to decrease sensitivity (i.e. setup new mouse with lower sensitiviy) cursor jumps randomly once and axes get inverted.

Example profile attached.

Tried different approaches but the result was always the same.

-cM.

**Comment by cptMikky** [comment]
Just found out that **any** type of modeshift causes this behaviour, not just soft pulls.

**Comment by kozec** [comment]
You are using negative sensitivity there, what _is_ supposed to invert axis. Lowest sensitivity is 0.01, not -10. Maybe I should write this to that big empty area bellow sliders

As for jumping, I'm still looking at what can be causing it.

**Comment by cptMikky** [comment]
Of course, now it does make sense :) I spent about twenty minutes clicking through all settings to find some kind of "invert axis" switch. 

If I may suggest, instead of tipping out user that negative sensitivity means inverted axis, let the sensitivity slider scale be from 0 to <max> and then put an "invert axis" ticker somewhere else in settings, perhaps in the main settings window part as this is the "usual" approach in most game settings I came across so far.

As for cursor jumping, a theory: when modeshift enables, the pad seems to be reinitialized instead of having just the settings diff applied seamlessly. This makes sense when modeshift changes the logic of the controller completely (like from mouse to a button) but may cause problems when the output is the same and only parameters are adjusted. I can imagine this could be tricky to implement though.

**Comment by kozec** [comment]
> As for cursor jumping, a theory: when modeshift enables, the pad seems to be reinitialized instead of having just the settings diff applied seamlessly. This makes sense when modeshift changes the logic of the controller completely (like from mouse to a button) but may cause problems when the output is the same and only parameters are adjusted. I can imagine this could be tricky to implement though.

Just for the record, you was exactly right :)
