### ISSUE TITLE
"Hold" mode not remaining in "held" state. 

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#269]
#### Version
v 0.3.15

#### Scenario:
I want to create a mode-shift that will occur if I press one button while pressing down and holding another.  _(For example: I wish to enable the on-screen keyboard if I press the left-bumper whilst I am holding down the center button.)_

#### Expected behaviour:  
While pressing _and holding_ a button, (the center button for example), a mode-shift will activate when another assigned button is pressed _at any time after the held button activates and is still being held down._    _(For example, If C is set to fire after the default .2, and player presses at >= .3, the mode shift will activate and the OSKB will display.)_

#### Actual behaviour:
A hold mode-shift will only occur if both buttons are pressed approximately simultaneously.  (For example, pressing the LB at the moment the C button has been held for .2 as indicated by the haptic feedback activates the mode-shift, but pressing LB after that, though still holding the C button, fails to activate the OSKB.)

#### Combinations tested:
Mode*shifted* (held) button | Mode*shifting* (pressed) button | Assigned to Activate
------------------------------------ | ------------------------------------------ | --------------------------
C | LB | OSKB
LB | C | OSKB
LB | RB | OSKB
LB | RB | + Vol
Y | A | OSKB
Y | A | + Vol
Y | A | ctrl + alt + arrow right (workspace right)
LG | RG | + Vol

All the above worked if shift button was pressed at _precisely_ the same time as the held button but not if the shift button was pressed _after_  the held button's delay time.

I tried leaving durations at default and variously changing to .3 and .5.  I also tried turning off haptic delay feedback and waiting longer than the delay.   The results were the same.

**Comment by kozec** [comment]
Do you have holding center button set to OSD menu, as it is by default? Because doing so should prevent OSK from displaying, as there can be only one OSD thing displayed at a time.

Other than that, how long is modeshifting button pressed should have no effect on modeshift, it checks only if button is pressed at moment when it's activated. Please, attach profile you are using, if possible, because if above is not a case, something is broken here :(

**Comment by LinuxJoeUser** [comment]
> Do you have holding center button set to OSD menu, as it is by default?

No, I cleared the Center Button's default "held alone/not set" setting and added the modeshift button "A."  The results were the same.  Results are the same as above, but holding LB and shifting with "A."  These are the settings included with the enclosed profile, but all the "held" buttons and (mode)shift buttons in the table above all failed equally.

> how long is modeshifting button pressed should have no effect on modeshift
Understood, and I made no effort to vary the time I _modeshifting_ button, only the _held_ button (i.e. the modeshifted button, the buttons listed in the first column in the table above).


[Sample_Profile.zip](https://github.com/kozec/sc-controller/files/1368634/Sample_Profile.zip)

**Comment by kozec** [comment]
Ok, I think I understand what you are trying to do and yeah, it's not designed that way :) Right now, "+ Volume" is activated only if A button is pressed right at that 0.2s mark.

But what you are suggesting makes sense, I just have to check how big change it would be to make it working so.

**Comment by LinuxJoeUser** [comment]
Whew!  Ok.  Yeah, being able to modeshift by holding one button and pressing another one at 0.2s mark (or whatever) or after other buttons would be awesome!  Although this came up because I'm trying to replicate Steam's "Chord" profile functions, it would allow any one button to effectively "become" many.  :)

**Comment by LinuxJoeUser** [comment]
Upon reflection, I'm an idiot, and I can do everything I was trying to do ... I was just trying to do it backwards.  Don't fool around with this ... I'm sorry for any time you wasted on this.  I'm gonna mark it closed and then hang my head in shame.
