### ISSUE TITLE
Keyboard selection offset

### ISSUE THREAD

**Issue by NOTtheMessiah** [kozec/sc-controller#27]
Expected behavior: Key under center of cursor is selected.
Actual behavior: Key most recently under top left of cursor image selected.

![selectstuck](https://cloud.githubusercontent.com/assets/2946283/15493384/cb8245f8-2151-11e6-862d-2686868aa642.png)

**Comment by kozec** [comment]
True, I forgot to center that...

**Comment by azizLIGHT** [comment]
How do you open this keyboard?

**Comment by kozec** [comment]
> How do you open this keyboard?

Assign "Show On Screen Keyboard" from "Special Actions" list to any button.

**Comment by parkerlreed** [comment]
Or from the Steam logo menu button.
