### ISSUE TITLE
Cannot change radial menu colours.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#270]
#### Version 
* v 0.3.15

#### Scenario
* Preferring a more subdued menu appearance, I go to Settings > OSD & Menu and choose different colours.

#### Expected behaviour
* All menus will appear in the colours chosen.

#### Actual behaviour
* All menus appear in desired colours *except* radial menus, which appear in their default blue/green/white format.

Please extend menu colours to include radial menus as well.

**Comment by kozec** [comment]
Yeah, this was one of those things I definitely planned to do until I forgot about it...
