### ISSUE TITLE
RPad activated gyro on Mouse (cam. or desk) breaks RP trackball "roll." (UPDATED again)

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#271]
Exactly as before in #182, set to Mouse (camera) press OK, it's Mouse (Desktop).

**Comment by kozec** [comment]
I can't quite replicate... Are you changing any other setting?

**Comment by LinuxJoeUser** [comment]
Edited title after I was unable reproduce problem on a clean, new profile.  (I had thought that whatever was causing "repeat" of #182 might be the cause of the problem as now reported.  It wasn't.)

_To reproduce problem, form 1_ 
1. Create a new, clean profile.
2. Change RP to Trackball (it helps to see problem if you turn friction down, but it's not necessary).  Make no other adjustments for now.  Press OK
3. Change Gyro to Mouse (desktop or camera; the result will be the same).  Press OK
4. Swipe RP quickly with thumb
_Result:_  The cursor does not travel past the moment the thumb leaves the pad.

_To reproduce problem, form 2_

Repeat Steps 1, 3, and 4 the same as above, but change step 2 to read: 

2. Change RP to Trackball (turn down friction or don't, as before).  *Enable Smoothing.*  Press OK

_Result:_  The cursor "jumps" to a new location if RP is touched anywhere but dead center, or "moves" there if thumb moves from center to the new location.  In either case the cursor "snaps back" to it's starting position when RP is released.

This occurs for me in brand new profiles and fully fleshed-out profiles.

**Comment by kozec** [comment]
Sorry but I really can't reproduce anything you report today, so something has to be different here... What version of SCC and on what distro are you using?

**Comment by LinuxJoeUser** [comment]
Ok, my bad.  I left out that the gyro should be set to come on _"when right pad is touched"_ instead of the default "Always Active."  Everything works seems to work fine if gyro activation for everything else *except* "when right pad is touched."   (Please, please, please may it break for you too). ;)

**Comment by LinuxJoeUser** [comment]
My finger's have been crossed since my last post that you were able to reproduce this when Gyro is set to come on with Rpad touched?  The suspense is killing me. 8-\

**Comment by kozec** [comment]
Can you, please, attach profile where this is set up and doesn't work?

**Comment by LinuxJoeUser** [comment]
Sure!  Here you go.  Gyro is set to a frictionless Mouse enabled with the RPad. 


[Borderlands RPad demo.sccprofile.zip](https://github.com/kozec/sc-controller/files/1387400/Borderlands.RPad.demo.sccprofile.zip)

**Comment by kozec** [comment]
Ok, this is almost too dumb to admit, but it seems that specific combination triggered code that wasn't even supposed to be there...

Are you able to test if current git checkout works for you?

**Comment by LinuxJoeUser** [comment]
That's fixed it perfectly!  (And, for what it's worth, my SCC Borderlands profile now functions as well as---if not a little better---than my Steam profile!) :)
