### ISSUE TITLE
Show "Save As" button immediately upon "Select Profile to Export" page.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#272]
Although the "Select Profile ... " window defaults to the current profile, it isn't clear how to export profile unless another profile is chosen first.  This situation could cause confusion (it confused me, anyway :P ) if it's the current profile that's what someone wants to save. 

![](https://i.imgur.com/kLBmgD5.png)

**Comment by kozec** [comment]
I'm not sure if I understand, there should be always either "Save As" or "Next" button visible when anything is selected. How did you managed to get rid of both? :)

**Comment by LinuxJoeUser** [comment]
Ummm ...  magic?  Magic!  No, not really.  I dunno.  "Save As" will show up if I choose another option, but otherwise this is what it looks like when I first arrive.  I'm currently running xfce on top of Ubuntu Gnome (don't ask).  I can't see how that would make a difference, but it's all I can think of.  Lemme know what info you could use at my end (and probs how to get it too).

**Comment by kozec** [comment]
Actially, after loading profile you posted in next issue, I've managed to reproduce the problem. There is code that checks selected profile before continuing and that code crashes with it.
