### ISSUE TITLE
Download links down

### ISSUE THREAD

**Issue by HoellP** [kozec/sc-controller#274]
Hi,

the links for .deb and .rpm packages are dead, i just get a 503. I know it's probably temporary, but is there a way to get the .deb in another way?

Thanks

**Comment by kozec** [comment]
Building them yourself :)

But give it hour or so, buildservice drops down occasionally, but it is always pretty quick to get back.

**Comment by HoellP** [comment]
I tried the prepackaged variant and it's kind of a pain. I made reddit post about it...

**Comment by kozec** [comment]
OBS is up again.
