### ISSUE TITLE
Grab-a-key ctrl/meta + shift/alt + arrows issue

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#275]
When applying a three part combo via grab-a-key that contains either CTRL or META and SHIFT or ALT and an UP/DOWN/LEFT/RIGHT arrow key, the code is recorded in the form of  [CTRL/META] and [ARROW] and [SHIFT/ALT] instead of (the expected?)  [CTRL/META] and [SHIFT/ALT] and [ARROW].

This re-arrangement causes the configured reaction fail to fire unless the button is held @ 1s, and then it rapidly repeats, firing over and over again.

Here's an [example using some pictures](https://imgur.com/a/a0vWl) that I couldn't get github to accept directly.

Notice that ctrl + alt + R.arrow becomes 

`button(Keys.KEY_LEFTALT) and button(Keys.KEY_RIGHT) and button(Keys.KEY_LEFTCTRL)`

(causing the delayed rapid repeat of the action) instead of 

`button(Keys.KEY_LEFTALT) and button(Keys.KEY_LEFTCTRL) and button(Keys.KEY_RIGHT)`

(causing the expected immediate single firing of the action)

For now the workaround is to manually reversing the second and third buttons.  I hope that's enough info, but let me know if you need more. :)

**Comment by kozec** [comment]
I'm not sure if I 100% understand, but `ALT and RIGHT and CTRL` is equivalent to `ALT and CTRL and RIGHT`. Anything combined with "and" fires at once.
