### ISSUE TITLE
Switch to Steam drivers/controls when opening Steam or Big Picture

### ISSUE THREAD

**Issue by yerbestpal** [kozec/sc-controller#279]
I would love to use sc-controller for generic desktop browsing, but sc-controller renders Big Pictures configuration useless until disabled. This is no good when trying to browse configs and play games. As far as I can see there is no solution to this problem but if not, please correct me and point me in the right direction. Thanks.

**Comment by kozec** [comment]
https://github.com/kozec/sc-controller/wiki/Running-SC-Controller-and-Steam ?

**Comment by yerbestpal** [comment]
Great, thanks. I should have researched before posting, apologies.
