### ISSUE TITLE
v0.4 TODOs

### ISSUE THREAD

**Issue by kozec** [kozec/sc-controller#280]
- [x] ~~[This milestone](https://github.com/kozec/sc-controller/milestone/4)~~
- [x] ~~[This PR](https://github.com/kozec/sc-controller/pull/259)~~
- [x] [This wiki page](https://github.com/kozec/sc-controller/wiki/Evdev-and-HID-mode-for-non-Steam-controllers)
- [x] ~~Changing images on GUI buttons~~
- [x] ~~Changing images in "Quick menu"~~
- [x] ~~DS4 touchpad over HID~~
- [x] ~~Hiding / disabling GUI buttons based on controller selected~~
~~Changing entire "Display bindings" image~~ (definitely after v0.4)

**Comment by LinuxJoeUser** [comment]
I seem to remember there being some discussion about creating a sort of "steering wheel" setting that ---as best I can remember---would allow for a two button arrangement on a pad, like maybe A on the left half of the pad and D on the right half?  Was this ever created and I'm missing how to set it up?  Or will this be out with the v.4?

P.S.:  I set up my first multi-profile profile recently so I can switch between foot and vehicle controls in Dead Island DE, and it worked sweeeeet.  Way better than trying to do the same thing in Steam's configurator.   In fact setting up the Dead Island configuration felt quicker and easier than doing it on  Steam (which crashed trying to set up *three* action sets to do what I could do in *two* on SCC!

What you've been doing on SCC is amazing!  Keep on keepin' on!

**Comment by LinuxJoeUser** [comment]
DUDE!  OK, I knew about Joystick > Circular ... but because it ends up saying "Output Axis Mouse Wheel" I expected it to act like a mouse wheel and only accept input when actively scrolled (as in the video), and I never tried to use like two button steering input.  YAY! It is fucking PERFECT!  Shit I wish I had this:
`circular(mouse(Rels.REL_WHEEL) and button(Keys.KEY_A, Keys.KEY_D))`
when I was playing Mad Max!! :P

**Comment by kozec** [comment]
Frankly, I was never able to use that for steering comfortably, but I'm glad it works for you :)

**Comment by LinuxJoeUser** [comment]
It's not ideal, to be sure.   But I don't think keyboard and mouse lend themselves to driving in games anyway.  This method is much closer to being able to rapidly tap between A and D on a keyboard than trying to steer on a four-way DPad using only A and D, leaving W and S blank---or worse:  only using WASD to drive.  Your method let's me put gas and brakes on the triggers, the way God intended. ;)
