### ISSUE TITLE
Start minimized to tray

### ISSUE THREAD

**Issue by jphaskins** [kozec/sc-controller#281]
I have added SC Controller to my startup apps because it's great and obviously should always be running. However, it would be nice if it started up in the tray instead of having to close the window when I reboot my workstation. If a way to do this already exists I couldn't find it. I imagine this feature could work exactly the same as in syncthing-gtk (another awesome app).

**Comment by kozec** [comment]
> I imagine this feature could work exactly the same as in syncthing-gtk (another awesome app).

Yeah, ideal case for copy-paste :)
