### ISSUE TITLE
Tray icon not working on Gnome 3.26 - Locked out

### ISSUE THREAD

**Issue by bisam** [kozec/sc-controller#283]
Hi and thanks for your great software :)

I am running the latest (git) version on Arch with Gnome 3.26.2 and the tray icon is not showing at all. The additional problem is that I set the "Start in tray" option, so it starts but there is no obvious way to get to the UI, and I have to kill it via commandline.
With version 3.26 Gnome started disabling trayicons completely ( see https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/ ) so I am using this extension: https://extensions.gnome.org/extension/495/topicons/ . This generally works pretty well, but not so with sc-controller :'(

I can help with testing and such if you need more information. And can someone help me disable the "start in tray" option so I can use sc-controller again?

**Comment by bisam** [comment]
Thanks a lot for the hint with the config file :)

**Comment by kozec** [comment]
> W StatusIcon    Failed to import AppIndicator3

Sounds like you are missing [libappindicator-gtk3](https://www.archlinux.org/packages/community/x86_64/libappindicator-gtk3/) package. It's not part of dependencies as this is not used by default.

**Comment by kozec** [comment]
By the way, could you, please, post output of `cat /usr/share/gnome/gnome-version.xml` on your machine? I can probably make this default after all, although it's not going to work without extensions installed.

**Comment by bisam** [comment]
Figured it out on my own :) With the package, the extension and the variable it works, thanks a lot.


Also, this warning is now printed, just so you know.

```
/usr/lib/python2.7/site-packages/scc/gui/statusicon.py:266: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
```

**Comment by bisam** [comment]
Sure thing:

```
<?xml version="1.0" encoding="UTF-8"?>
<gnome-version>
 <platform>3</platform>
 <minor>26</minor>
 <micro>2</micro>
 <distributor>Arch Linux</distributor>
 <date>2017-10-31</date>
</gnome-version>
```

**Comment by kozec** [comment]
> You could add a small popup with a link to the extension, or some hint or so.

Yeah, that's the plan :)

**Comment by kozec** [comment]
Ok, so it turns out that file is installed even if you are _not_ using gnome, so it's basically useless.

I don't really think this is fixable - it's how Gnome is _supposed_ to work now. So, until some truly genial solution comes on my mind, just don't use "minimize to tray" option if you have no tray to minimize to :)
