### ISSUE TITLE
Start Steam with Steam button

### ISSUE THREAD

**Issue by Mohandevir** [kozec/sc-controller#284]
It's more a question/feature request than an issue,
Is there a way to map the steam button so that it starts Steam and then turn this driver off?

Thanks!

**Comment by kozec** [comment]
Yes, something like...

```
shell("steam") ; sleep(5); restart
```

... as custom action should do the job.

**Comment by Mohandevir** [comment]
Thanks!
Just tried it but unfortunately it's not working. Steam launches and hangs. Killing it via terminal or with monitoring tool doesn't work. I have to reboot my computer, every time. Just launching Steam with the Steam button works as expected though. Tried removing the pause option... Still the same. There seem to be a conflict between Steam and sc-controller, when it resumes. I tried with the windows switcher too and got the same result.

**Comment by kozec** [comment]
Weird, there shouldn't be any reason for it to hang when started like that. Does it hang even if you start it from terminal?

**Comment by Mohandevir** [comment]
I tried launching it via a script and it failed in the same way.

**Comment by kozec** [comment]
Sorry for late answer, I didn't had controller for a while...

But now I can't replicate problem no matter what. Please, try running _everything_ from terminal and check if there is anything indicating error. Also, I've just realized you forgot to say anything about your environment - what distro, what versions of stuff, what platform are you using?

Other than that, best I can advise is to turn off SC-Controller manually before starting Steam in your specific case.

**Comment by kozec** [comment]
> What command line should I use?

Turn off everything SCC-related and start `scc-daemon debug` in one terminal and `steam` in another.

**Comment by LinuxJoeUser** [comment]
Tried a couple variations:
* __shell("steam") ; sleep(5); restart__ starts steam but scc retakes control of SC after delay, on restart
* __shell('steam'); sleep(5.000); shell('scc-daemon stop')__ starts steam and allows steam to take control of SC, but SCC must be manually re-enabled.

I had no hangs on starting Steam.

**Comment by kitling** [comment]
Issue here may be because of steam forking off and killing off the process you originally start, promoting the script to continue...

What may be more generally useful is to detect when steam is running, and automatically get out of its way.

**Comment by kozec** [comment]
> What may be more generally useful is to detect when steam is running, and automatically get out of its way.

That's possible, [see here](https://github.com/kozec/sc-controller/wiki/Running-SC-Controller-and-Steam#automatically-disable-sc-controller-when-starting-steam)
