### ISSUE TITLE
Radial Menu not Mapping to JStick

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#286]
It's possible to set everything up, but either the actual menu produced is a list or is a Dpad.  I've tried on both new and older profiles, same behaviour.  My version is the latest (`git pull` returns `Already latest version`)
![screenshot_2017-11-17_17-35-02](https://user-images.githubusercontent.com/23580979/32972249-54718072-cbbf-11e7-9b36-06ea4f9f9b10.png)

**Comment by kozec** [comment]
That's what you get from running fresh code from git :)

**Comment by LinuxJoeUser** [comment]
Lol!  Indeed!

**Comment by LinuxJoeUser** [comment]
As long as you know it's happening :)
