### ISSUE TITLE
Replace abbreviated Select Button menu with Full Select Button menu?

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#287]
If it's possible, when setting up _L/RPad > Joystick / Mouse > Single Button > Select Button,_ use the _full_ Select Button menu 

![](http://i.imgur.com/VEo0PLQ.png)

instead of the _abbreviated_ menu

![](http://i.imgur.com/wCaQAT9.png)

because it would be extremely more useful to have access to the Special Actions menu here  (I'm wanting to assign a profile change here, for example).

**Comment by kozec** [comment]
It's possible to change which window is displayed, but it would break a lot - most of special actions are not suitable for pad and setting something like shell there may even bring machine down - moving finger over pad would call incredible amount of shell commands _in paralel_.

I can make change profile action in way so it can be activated by pad, but I believe this kind of use calls for "Custom action" tab :)

**Comment by kozec** [comment]
Here, with this, you can assign `profile('something')` using custom action. Rest of special actions should already work with pad, with exception of keyboard, shell and osd message, to prevent world from burning.

**Comment by LinuxJoeUser** [comment]
> It's possible to change which window is displayed, but it would break a lot ... setting something like shell there may even bring machine down...

Eek!  That sounds like a bad idea then. 

> I can make change profile action in way so it can be activated by pad, but I believe this kind of use calls for "Custom action" tab :)

That's good enough to be sure.  (copy/paste is my friend)  I've spent some time with the wiki since my initial post and have a better grasp of things.  Muy impresivo don Kovek!  Muy bien y gracias! :D
