### ISSUE TITLE
I have just one controller but... (see the screenshot)

### ISSUE THREAD

**Issue by MDIV666** [kozec/sc-controller#292]
I have no idea what have I done
![image](https://user-images.githubusercontent.com/13256985/33598535-755cf220-d9a3-11e7-8d7a-1fc57d2a5f9a.png)

**Comment by kozec** [comment]
Me neither, but at least it looks colorful :)

Try disabling and reenabling emulation using that green top-left icon and if that doesn't help, disable emulation, run `scc-daemon debug` in terminal window and post output, it should show where are they  coming from.

**Comment by MDIV666** [comment]
This is output. I turned on than turn off by holding menu button than turn on and turn off by selecting from osMenu
` scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f583a9ebb90>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f583a9ebfd0>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f583a9f9190>
D SCCDaemon     Created control socket /home/mdiv/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
W SCCDaemon     Refused 'Observe' request: Sniffing disabled
D USB           USB device added: 28de:1142
D SCDongle      Not requesting serial number for SC 1
D SCDongle      Got wireless SC with serial 1
D SCCDaemon     Assigned default_mapper to <SCWireless 1>
D SCCDaemon     Controller added: <SCWireless 1>
D SCDongle      Not requesting serial number for SC 2
D SCDongle      Got wireless SC with serial 2
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f583a9a0450>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f583a9a0bd0>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f583a9a0950>
D SCCDaemon     Controller added: <SCWireless 2>
W SCCDaemon     Refused 'Observe' request: Sniffing disabled
D SCDongle      Not requesting serial number for SC 3
D SCDongle      Got wireless SC with serial 3
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f583a9cd210>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f583a9cd6d0>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f583a9cd510>
D SCCDaemon     Controller added: <SCWireless 3>
D SCDongle      Not requesting serial number for SC 4
D SCDongle      Got wireless SC with serial 4
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f583975a990>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f583975aed0>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f583975ac90>
D SCCDaemon     Controller added: <SCWireless 4>
I SCCDaemon     Loaded profile '/home/mdiv/.config/scc/profiles/chrome.sccprofile'
I SCCDaemon     Loaded profile '/home/mdiv/.config/scc/profiles/chrome.sccprofile'
I SCCDaemon     Loaded profile '/home/mdiv/.config/scc/profiles/chrome.sccprofile'
D OSD DaemonCtrl    Connected to daemon, version 0.3.16
D OSD DaemonCtrl    Daemon reported profile change: /home/mdiv/.config/scc/profiles/chrome.sccprofile
D OSD DaemonCtrl    Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
I XI            Deatached device 13 from its master
I XI            Deatached device 15 from its master
I XI            Deatached device 18 from its master
I XI            Deatached device 20 from its master
D SCCDaemon     STICK locked by <scc.sccdaemon.Client object at 0x7f5839766150>
D SCCDaemon     SCButtons.A locked by <scc.sccdaemon.Client object at 0x7f5839766150>
D SCCDaemon     SCButtons.B locked by <scc.sccdaemon.Client object at 0x7f5839766150>
E OSD osd.menu      Sucessfully locked input
D SCCDaemon     Controller removed: <SCWireless 4>
D SCDongle      Not requesting serial number for SC 4
D SCDongle      Got wireless SC with serial 4
D SCCDaemon     Reused mapper <scc.mapper.Mapper object at 0x7f583975a910> for <SCWireless 4>
D SCCDaemon     Controller added: <SCWireless 4>
D OSD DaemonCtrl    Daemon reported profile change: /home/mdiv/.config/scc/profiles/chrome.sccprofile
D SCCDaemon     SCButtons.A locked by <scc.sccdaemon.Client object at 0x7f5839766150>
D SCCDaemon     STICK locked by <scc.sccdaemon.Client object at 0x7f5839766150>
D SCCDaemon     SCButtons.B locked by <scc.sccdaemon.Client object at 0x7f5839766150>
I SCCDaemon     Loaded profile '/home/mdiv/.config/scc/profiles/chrome.sccprofile'
W OSD osd.daemon    Another OSD is already visible - refusing to show menu
D SCCDaemon     SCButtons.A unlocked
D SCCDaemon     SCButtons.B unlocked
D SCCDaemon     STICK unlocked
W Actions       Action TurnOffAction can't handle button press event
D SCDongle      Turning off the controller...
D SCCDaemon     Controller removed: <SCWireless 4>
^X^CD SCCDaemon     Break
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scc/x11/scc-osd-daemon.py", line 272, in <module>
    d.run()
  File "/usr/lib/python2.7/dist-packages/scc/x11/scc-osd-daemon.py", line 262, in run
D USB           Releasing devices...
    self.mainloop.run()
  File "/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py", line 576, in run
D SCCDaemon     Controller removed: <SCWireless 1>
D SCCDaemon     Reassigned default_mapper to <SCWireless 2>
D SCCDaemon     Controller removed: <SCWireless 2>
D SCCDaemon     Reassigned default_mapper to <SCWireless 3>
D SCCDaemon     Controller removed: <SCWireless 3>
    raise KeyboardInterrupt
KeyboardInterrupt
I SCCDaemon     scc-osd-daemon lost
W SCCDaemon     scc-osd-daemon died; restarting after 5s
`

**Comment by MDIV666** [comment]
Looking back at issues that I posted I think I'm your best tester XD

**Comment by MDIV666** [comment]
And there is something else even though any of profile doesnt have "feedback on", controller is vibrating when I use right pad as trackball

**Comment by kozec** [comment]
> And there is something else even though any of profile doesnt have "feedback on"

That is probably OK, that option turns off feedback generated by applications, not by driver.

Log shows as if there were 4 controllers connected to dongle. Is there any chance dongle is at fault? How are those non-existing controllers behaving? Are all inputs moving at once (you should be able to check that using jstest-gtk or anything similar and switching to xbox profile) What happens when you turn off real controller?

**Comment by MDIV666** [comment]
Getting dongle out and in back to USB helped. I think it had something to do with "Microsoft wireless (keyboard and mouse) 2000" I had to move it out to because after steamcontroller dongle (out/in) keyboard  and mouse hase some pauses.

**Comment by MDIV666** [comment]
Still have a problem with it. When I boot my linux and auto run sc-controller there are 4 controllers. I have to disable and than enable emulation to start only one controller. Please help me to figure it out how to restore it to working setup. :(

**Comment by MDIV666** [comment]
It's random. When I disable and reenable emulation it get's 4 controllers that are connected and next time only one controller that is not connected and than I can really connect steam controller.

**Comment by kozec** [comment]
Can you check if same issue happens with Steam? I can add some config option that simply disables all but 1st controllers, but that may not help if actual problem is with dongle.

**Comment by MDIV666** [comment]
> Can you check if same issue happens with Steam?
I don't get it. How should I check it?

**Comment by kozec** [comment]
> I don't get it. How should I check it?

Does Steam shows 4 controllers as well?
