### ISSUE TITLE
Program will occasionally disable the controller until a restart

### ISSUE THREAD

**Issue by TristanBomb** [kozec/sc-controller#293]
I'm using the controller with a wire, on Debian 9.

I'm sorry to say I don't have solid info on when, why, or how this occurs, but I find that after a while of messing with sc-controller, the controller will completely shut off. From what I can tell, this usually happens when altering settings, enabling/disabling emulation, or starting applications. Unplugging the controller and plugging it back in causes the Steam logo to light up for a *split* second, before shutting off again. The controller will not pair wirelessly.

This will occur with sc-controller open or with it closed. It also tends to freeze Steam, and prevents Steam from restarting, even if the controller is unplugged.

I wish I had more debug info, but here's what I can piece together:

 * When starting sc-controller again, it will output `pidfile /home/<user>/.config/scc/daemon.pid does not exist. Daemon not running?`
 * Running `scc-daemon debug` outputs this:
```
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
```
When sc-controller is started:
```
Exception AttributeError: "'Keyboard' object has no attribute '_fd'" in <bound method Keyboard.__del__ of <scc.uinput.Keyboard object at 0x7f0d3464ef90>> ignored
```
* The program has a gray icon, and states that emulation is enabled. Attempting to disable emulation will cause the menu item to be grayed out. Restarting sc-controller seems to re-enable emulation.

Thankfully, these issues resolve after the host computer is restarted, but I have not found a way to "revive" the controller without restarting the system.

**Comment by kozec** [comment]
Ok, that was very scary use of term brick up there :D

What are you describing is not really controller related, it's bug(?) in uinput kernel module. Under circumstances that I was not yet able to determine, it basically freezes and stop any communication, freezing anything trying to use it. As you already found, reboot helps.

As far as I know, it's linked to rumble support (as that's only part of code that writes _to_ uinput), so if it happens on your machine, you can go to Settings -> Advanced and disable rumble. There are like two games using it on Linux anyway :(

**Comment by TristanBomb** [comment]
You're totally right, that wasn't a good use of the term "brick." Sorry! It was just the first I thought of. 

After disabling rumble, emulation was automatically disabled; but when I enabled it again, emulation would not turn on. The icon stayed gray, and I could not re-disable emulation. Controller inputs also do not show in the GUI.

**Comment by kozec** [comment]
Yeah, disabling _after_ bug triggers is not going to help.

Should it happen again, please, try running `scc-daemon debug` _before_ it get triggered for first time. Output for 1st crash(?) should help determining why it happens.

**Comment by TristanBomb** [comment]
No, I disabled it *before* the bug occurred. Re-enabling emulation afterwards *caused* the bug to occur again.

I'll run `scc-daemon debug` while I'm using it, for now on, and I'll report the output if it happens again. Thanks!

**Comment by DFOXpro** [comment]
I also get this problem, it was since 1.13 version, it looks like a variation of [issue 251](https://github.com/kozec/sc-controller/issues/251)
I can't replicate this bug within the console debug launch BUT it triggers anyway with or without rumble enable (in the gt3 UI and in game UI) and after arround 20 to 40 mins of continuos gameplay.

The game still works only the controller(interface) stop sending data like the control is set power off or something like this.

Unfunny note: also I get this bug in this [video at 8:26](https://youtu.be/53GbD3-9LU4?t=8m10s) in this case I just restart the game/driver and continue (note the cut in 8:49).

**Comment by kozec** [comment]
> it was since 1.13 version

That may help finding cause, there was no 1.13 version...

**Comment by DFOXpro** [comment]
Yeah I pointed to the v0.3.12 not the v?.13 :'(

Anyway testing testing I get [this](https://pastebin.com/e6TyNPC4) error looks like the control disconnect but this was not the case
Then proceed to end the process:

    ^CE AS  AutoSwitcher  break
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/scc/x11/scc-osd-daemon.py", line 273, in <module>
        D SCCDaemon     Break

I then test connecting and disconnecting the controller while playing with the driver but the demon continue sending valid "Controller removed"

**Comment by kozec** [comment]
> Anyway testing testing I get this error looks like the control disconnect but this was not the case
Then proceed to end the process:
> `scc.lib.usb1.USBErrorNoDevice: LIBUSB_ERROR_NO_DEVICE [-4]`

Ok, great, looks like I'm playing with wired controller this evening :)

Anyway, this looks like controller is actually getting disconnected. How sure are you this is not problem with faulty cable or USB not having enough power? Can you check `dmesg` and check if there are any logs of that happening by any chance?

**Comment by DFOXpro** [comment]
I'm testing with your latest update no errors so far, this week I will test with FF options.

**Comment by DFOXpro** [comment]
after long test I get this error with rumble support: https://pastebin.com/MBcGkTrH

**Comment by kozec** [comment]
Ok, LIBUSB_ERROR_IO is basically "something happened" :(

I'll of course add code to handle that so daemon doesn't crash, but I'm not sure what to do with controller. 

I'll try closing everything and ask USB to reset the device, which should make it to reconnect right back and cause, at worst, very short input lag. But that's just theory, because AFAIK, there is no reason for this error to happen in 1st place.
