### ISSUE TITLE
No module named gi

### ISSUE THREAD

**Issue by probonopd** [kozec/sc-controller#295]
```
me@host:~$  Downloads/sc-controller-0-Build126.1.glibc-x86_64.AppImage 
No module named gi
```

**Comment by kozec** [comment]
Install PyGObject package and python-gi-cairo and gir1.2-rsvg-2.0 if you are on anything debian based.

**Comment by probonopd** [comment]
> Install PyGObject package and python-gi-cairo and gir1.2-rsvg-2.0 if you are on anything debian based.

Sure, but the point of an AppImage is to bundle all those dependencies that cannot be assumed to be on every target system...

**Comment by kozec** [comment]
But pygobject & friends should be installed everywhere, or at least on gui-based distros. Plus, packing them along will add ~100MB :(
