### ISSUE TITLE
Ring Bindings do not seem to work properly.

### ISSUE THREAD

**Issue by BlushBerry** [kozec/sc-controller#296]
Set inner ring binding to wasd.
Set outer ring binding to all wasd but with "Shift" added as well.

Transitioning joystick from inner ring to outer ring usually results in player standing still.
Transitioning slowly "SOMETIMES" results in expected result "Running with shift+w,a,s,d"

Am I doing something wrong or is this a legitimate bug?

**Comment by kozec** [comment]
Probably bug, but copy-paste entire thing here so I can check...

Either right-click on that pad in main window and select "copy" or just upload entire profile file somewhere.

**Comment by BlushBerry** [comment]
`ring(dpad(button(Keys.KEY_W), button(Keys.KEY_S), button(Keys.KEY_A), button(Keys.KEY_D)), dpad(button(Keys.KEY_LEFTSHIFT) and button(Keys.KEY_W), button(Keys.KEY_LEFTSHIFT) and button(Keys.KEY_S), button(Keys.KEY_LEFTSHIFT) and button(Keys.KEY_A), button(Keys.KEY_LEFTSHIFT) and button(Keys.KEY_D)))`

**Comment by kozec** [comment]
In this case it looks like it does what you are saying it to do. I think setting mode to "Pad binding with Outer ring" and setting "Outer Ring" to "Joystick/Mouse -> Single button -> Shift" will do better job in your case.

**Comment by BlushBerry** [comment]
I will try this thank you.

**Comment by BlushBerry** [comment]
Not entirely sure if this is done right.. But I tried this and LEFTSHIFT is completely ignored. Also in the gui the deadzone resets upon editing but it seems that the text itself below still reflects the changes? Configuring it this way yeilds same result of not sprinting with shift when outer ring has been reached. Did I configure it wrong? Still sort of new to this program.

dpad(button(Keys.KEY_W), button(Keys.KEY_S), button(Keys.KEY_A), button(Keys.KEY_D)) and ring(0.89, None, button(Keys.KEY_LEFTSHIFT))

**Comment by kozec** [comment]
That's weird, what you've sent works on my side. What version of SCC are you using and what game are you trying to control?

**Comment by BlushBerry** [comment]
I am using V0.3.16 And I am trying to control GZDoom, An OpenGL Sourceport for Doom. I've had this functionality work just fine with Big Picture in the past so it's not the game itself.

**Comment by BlushBerry** [comment]
I've tried to run the git version and it is now indeed latest. However I am now getting the issue `pidfile /home/polygon/.config/scc/daemon.pid does not exist. Daemon not running?`

**Comment by kozec** [comment]
> I did install python2-evdev and then restarted my computer

Yeah, that's new dependency. Sorry, I'm banned from Arch, so I can't really tell them to add it :D

I can see how ring radius is correctly saved, but not loaded back to GUI, I'll check what can be the case.

**Comment by kozec** [comment]
By the way, are you using this on pad or on stick?

**Comment by BlushBerry** [comment]
I'm using the analog stick :3, Also I know off topic but topic within topic.


Why are you banned from Arch? (Also do you mean AUR?)

**Comment by kozec** [comment]
I dared to question some changes in pacman a long time ago :D

Anyway, does above commit fixes your problem?

**Comment by BlushBerry** [comment]
Not sure how I'd test it out. Do I just download this version or something?... like I guess clone from git right now?.. ALSO do you have discord :v? I dunno if theres any sort of private messaging.

**Comment by BlushBerry** [comment]
Nope! That PM Feature was removed apparently! I am putting my discord here if you have one and you'd like to contact me because I Don't care if people know mine BlushBerry#7877 :3

**Comment by kozec** [comment]
Just installing sc-controller-git from AUR (again) should work, as it always pulls latest version possible.

**Comment by BlushBerry** [comment]
I'll try that out one moment kozec!~

**Comment by BlushBerry** [comment]
Yes, the "Outer Ring Starts At" is now saved properly. However the whole shift when outer ring is reached is not working.. Current setup

`dpad(button(Keys.KEY_W), button(Keys.KEY_S), button(Keys.KEY_A), button(Keys.KEY_D)) and ring(0.75, None, button(Keys.KEY_LEFTSHIFT))`

**Comment by kozec** [comment]
> Might I possibly be missing a dependency? For reference could you list all required Arch Dependancies for this to work?

Nope, it wouldn't even start in that case.

But it not working is weird, I just rushed entire e1m1 in gzdoom with that exact configuration. Try restarting emulation using green icon in top-right corner.

**Comment by BlushBerry** [comment]
I will try that one moment.

**Comment by BlushBerry** [comment]
Works perfectly now! Thank you very much for your help. Also thank you for your latest commit. If I find any other issues I'll be sure to create an issue immediately!

**Comment by kozec** [comment]
Np, I'm glad it worked in the end :)
