### ISSUE TITLE
python-evdev require needed for deb package

### ISSUE THREAD

**Issue by Patola** [kozec/sc-controller#297]
Sorry, maybe this is not the right place to file the issue. But the 0.4 package does not require python-evdev -- I hadn't got it installed, and it silently fails to emulate a mouse. Only when using scc-daemon debug I could get an error message.

Also, it seems that when updating from 0.3.16 to 0.4 and running 0.4, it does not automatically create the ~/.config/scc/devices directory.

**Comment by kozec** [comment]
> Also, it seems that when updating from 0.3.16 to 0.4 and running 0.4, it does not automatically create the ~/.config/scc/devices directory.

When I think I checked everything... :(

Anyway, place is right, I've added package to dependency list. And it looks like there will be v0.4.0.1...
