### ISSUE TITLE
Setting Rings via Modeshift is broken upon return

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#298]
### Scenario:
If _Ring Bindings_ are set via _Mode Shift_ menu, the inner and Outer settings will both be on the Inner Ring when you return to the _Ring Bindings_ menu.

### Example:
**RPAD** > modeshift > RPAD press > Ring Bindings > Two Separate Rings > Inner: (example: Single Button) and Outer: (example: DPAD)

		ring(0.7,
		  button(Keys.KEY_E),
		  dpad(12,
		    button(Keys.KEY_C),
		    button(Keys.KEY_V),
		    button(Keys.KEY_R),
		    button(Keys.KEY_Q)
		  )
	)

![sccringissuepd2v2](https://user-images.githubusercontent.com/23580979/34363078-dd01ed14-ea46-11e7-8f2f-339a9adf4eba.png)
### Results and Details:
_"Ring Bindings"_ menu set via _Mode Shift_ t menu "break" in GUI, upon return.
- Ring Bindings shows both inner and outer ring settings as now being on *Inner Ring* only
 - Doesn't seem to matter what is mapped to the  _Inner_ or _Outer_ Ring, _just that it's done _Mode Shift_ menu._ 
- Affects LPAD and RPAD

![sccringissuepd2v2 3](https://user-images.githubusercontent.com/23580979/34363077-dcedf3f4-ea46-11e7-9499-7a7e1bd8bbbd.png)

**Comment by kozec** [comment]
Whoa, that's combination... Does it react as supposed and breakage is only in GUI, or it's broken entirelly?

**Comment by LinuxJoeUser** [comment]
It *functions as configured,* so it seems to be the GUI.  However, the settings *do not display as configured* if the Inner or Outer button is clicked.   The Outer button displays a fresh Action Menu:

![sscringissuepd2v2 4](https://user-images.githubusercontent.com/23580979/34382806-6ede976c-eadf-11e7-802c-c6cfedf6bd7a.png)

and the Inner ring shows an Action Menu at the Custom Editor:

![sscringissuepd2v2 5](https://user-images.githubusercontent.com/23580979/34382918-c8a2ca98-eadf-11e7-95f3-4dfc8f3355a9.png).  

(And playing Payday 2 with SCC is just *better* than Steam's config tool :) ) 

And Merry Christmas, btw!

**Comment by kozec** [comment]
> And Merry Christmas, btw!

Happy new year :)

**Comment by kozec** [comment]
... and by fixed I meant not at all :(
