### ISSUE TITLE
NameError: name 'evdev' is not defined

### ISSUE THREAD

**Issue by Kalabasa** [kozec/sc-controller#299]
Daemon fails to initialize `NameError: name 'evdev' is not defined`

Installed via the deb package.

After installing `python-evdev`, error's gone.

**Comment by kozec** [comment]
What's package version? This should be already fixed...

**Comment by Kalabasa** [comment]
That version is `0.4`.

After upgrading to `0.4.0.1`, attempting to remove `python-evdev` will warn about `sc-controller` dependent. So I guess it's fixed now.
