### ISSUE TITLE
daemon.pid persists after reboot

### ISSUE THREAD

**Issue by dustovich1** [kozec/sc-controller#303]
Hello,
I have written a script that checks every second whether steam is alive and whether the ~/.config/scc/daemon.pid is present. [Gist](https://gist.github.com/dustovich1/4d1ac52dcd1f4f73fc6cd9b155af5dac#file-sc-controller-control-sh)
This works perfectly fine on startup if the daemon.pid is not present and works between cycles of steam being active and closed without issue. The only issue is on reboot the daemon.pid persists and renders the script and 'scc-daemon start' moot.

Is there a preferred way to clean this up? 

I have attempted a few things, but I have a feeling that scc-daemon does not detect the SIGTERM and SIGINT and terminates gracefully with the daemon.pid being deleted on shutdown.

Perhaps there is another preferred way to autostart the scc-daemon that I am not thinking about this that would remedy the situation. I have not tried deleting the daemon.pid file in my script on shutdown as IMHO this should be handled by the program that owns it. Perhaps as a stopgap measure I would try it, but that isn't the permanent solution.

Otherwise this program is pretty sweet. Thanks for making it.
dustovich1

**Comment by kozec** [comment]
scc-daemon definitely should react to SIGTERM ([this handles it](https://github.com/kozec/sc-controller/blob/master/scc/sccdaemon.py#L374)) and there is [handler registered with "atexit"](https://github.com/kozec/sc-controller/blob/master/scc/lib/daemon.py#L73) that should remove PID file.

Of course, there is always chance that whatever handles rebooting or session exit sends SIGKILL instead. What distro, environment and init system are you using?

> Is there a preferred way to clean this up?

If you are talking about checking if scc-daemon is alive, I can think about three options:
 - if PID file exists, check what that PID belongs to
 - try connecting to ~/.config/scc/daemon.socket instead. `nc -NU  ~/.config/scc/daemon.socket` should output some info if scc-daemon is alive and fail with error code if it isn't
 - from next release or if you are running from git, `scc info` command will do the same.

**Comment by dustovich1** [comment]
Ok. I have done some more troubleshooting. If i Ctrl-C my script it runs the scc-daemon stop and the daemon.pid disappears, so the script and your program is handling everything correctly. If I reboot the machine without doing so I get no log entry saying that it has received the shutdown signal so I am guessing it is just terminated. 

But now to figure out why it does this, and also to implement the daemon.pid detection in my script.

I am using Arch with NODM.

**Comment by kozec** [comment]
> I am using Arch with NODM.

If that's case, check if bug with logind killing all user processes on logout doesn't apply to you: https://github.com/systemd/systemd/pull/3005

> Since you are using uinput, this makes the input global, have you thought of running this system wide via a systemd unit instead?

I'm almost sure it will break somehow, but you can be first to try :D Just make sure it runs under your user account.
