### ISSUE TITLE
OSD Menu Timeout

### ISSUE THREAD

**Issue by dustovich1** [kozec/sc-controller#304]
Is there a way to make the OSD menu timeout? If I am just holding the Steam button on the controller down to shut it off, the OSD menu appears, and the controller shuts off leaving me with no way to remove the OSD menu other then by turning on the controller again and selecting controller shut off.

**Comment by kozec** [comment]
OSD menu should automatically exit if controller is removed or shut down, I'll check why it doesn't.

**Comment by LinuxJoeUser** [comment]
Maybe consider setting `Default.menu` to appear on a double click instead of Pressed alone.  I set C  to show its Menu only on a double click, and it avoids all sort of mis-fires (and allows me to make better use of C as a modeshifter across profiles, like Steam's "chord" settings.)
