### ISSUE TITLE
Gyro activated via left grip (which is set to LALT) breaks trackball on right mousepad

### ISSUE THREAD

**Issue by hatani** [kozec/sc-controller#312]
Not sure if this is related to #271, but I am not able to set Gyro active only while I hold left Grip (which is assigned to key LALT, but that hopefully should not interfere).  Once I release the left grip, right mousepad does nothing anymore (does not emulate trackball).

**Comment by kozec** [comment]
I can't replicate problem on my side. Can you send or upload profile you are using somewhere?

**Comment by hatani** [comment]
Hey, for some reason my SC controller is no longer detected when I use
application.  I've modified setup back to 'troublesome' (only change was I
added gyro as mouse(desktop) on left grip).  Now, once you pull left grip,
gyro will correctly work as mouse but when you left it off, right pad no
longer worked as mouse for me.

Link to profile:
https://pastebin.com/ewYSer6z

Thanks!
Miro

**Comment by kozec** [comment]
Weird thing is that it works exactly as it should on my side. What versions of everything (sc-controller, distro, desktop if it is not default...) are you using?

**Comment by hatani** [comment]
I am using Antergos, desktop is Mate, and I think I just now updated to
0.4.0.1 SC-controller.  Read your mail just after noticed SCC got update
and let it update. I'll test after update.

**Comment by kozec** [comment]
I believe this should be already fixed. If not, please reopen this, or create new issue.
