### ISSUE TITLE
SC no longer gets detected after v0.4.0.1 update

### ISSUE THREAD

**Issue by Readek** [kozec/sc-controller#313]
I'm on Manjaro KDE using the AUR package, after the update my controller no longer gets detected and acts like nothing is controlling it (can move cursor, left click and right click). I'm not using steam while using sc-controller. Emulation is enabled. There are no controllers on the controller's settings, and nothing happens when I press the "Registrer New Controller" button. Everything worked fine before the update. Also, [there are missing buttons on the main screen](https://i.imgur.com/Fv0tC8u.png) (but I can click them).

**Comment by kozec** [comment]
> Also, there are missing buttons on the main screen (but I can click them).

That is not a but, but a feature and it's already fixed for next release :)

Can you try disabling emulation, closing gui and run `scc-daemon debug` in terminal? There is a good chance there will be some explanation in output it generates.

**Comment by Readek** [comment]
scc-daemon debug:

`D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
Traceback (most recent call last):
  File "/usr/bin/scc-daemon", line 36, in <module>
    main()
  File "/usr/bin/scc-daemon", line 32, in main
    daemon.debug()
  File "/usr/lib/python2.7/site-packages/scc/sccdaemon.py", line 1038, in debug
    self.run()
  File "/usr/lib/python2.7/site-packages/scc/sccdaemon.py", line 604, in run
    self.init_drivers()
  File "/usr/lib/python2.7/site-packages/scc/sccdaemon.py", line 82, in init_drivers
    mod = getattr(__import__('scc.drivers.%s' % (modname,)).drivers, modname)
  File "/usr/lib/python2.7/site-packages/scc/drivers/ds4drv.py", line 8, in <module>
    from scc.drivers.hiddrv import BUTTON_COUNT, ButtonData, AxisType, AxisData
  File "/usr/lib/python2.7/site-packages/scc/drivers/hiddrv.py", line 15, in <module>
    from scc.drivers.evdevdrv import FIRST_BUTTON, TRIGGERS, parse_axis
  File "/usr/lib/python2.7/site-packages/scc/drivers/evdevdrv.py", line 48, in <module>
    class EvdevController(Controller):
  File "/usr/lib/python2.7/site-packages/scc/drivers/evdevdrv.py", line 55, in EvdevController
    ECODES = evdev.ecodes
NameError: name 'evdev' is not defined
`

**Comment by kozec** [comment]
> NameError: name 'evdev' is not defined

you'll need python-evdev package.

**Comment by Readek** [comment]
Weird thing, I already have it installed.

**Comment by kozec** [comment]
Ok, that's really weird. What gives you`file /usr/lib/python2.7/site-packages/evdev/__init__.py` ?

**Comment by Readek** [comment]
I... don't have the evdev folder. I tried reinstalling both python-evdev and sc-controller.

I have the feeling that this problem is probably not related to sc-controller.

**Comment by feddasch** [comment]
Try `python2-evdev`, Arch has the package names switched since their default interpreter is Python 3

**Comment by Readek** [comment]
That was it! Thank you for your help.

**Comment by kozec** [comment]
Oh, yeah, glorious Arch :D

Glad you solved it :)
