### ISSUE TITLE
Allow daemon to be started without double forking

### ISSUE THREAD

**Issue by kokx** [kozec/sc-controller#315]
To run a daemon under systemd, it is preferred to not double fork, but instead directly run the daemon without any forking.

Hence, it would be nice if there was an option for the daemon such that it doesn't fork. That the daemon can be run nicely by systemd unit files.

**Comment by kozec** [comment]
Don't run daemon under systemd, it will break :)

But you can run it using `scc-daemon debug` to skip demonizing.

**Comment by kokx** [comment]
> Don't run daemon under systemd, it will break :)

Can you explain why / how it should break under systemd? For me it actually works fine so far. With the following unit file:

```ini
[Unit]
Description=SCC Daemon

[Service]
Type=simple
ExecStart=/usr/bin/scc-daemon debug
Restart=on-failure

[Install]
WantedBy=default.target
```

Of course I am running this under my user in systemd, and not as root. Using `systemctl --user start scc-daemon`.

**Comment by kozec** [comment]
> Can you explain why / how it should break under systemd? For me it actually works fine so far. With the following unit file

There may be other issues, as I never tested that, but what's I'm pretty certain is that if you change any setting that requires daemon to be restarted, GUI will be unable to do so and probably break in process of attempting.

**Comment by kokx** [comment]
> There may be other issues, as I never tested that, but what's I'm pretty certain is that if you change any setting that requires daemon to be restarted, GUI will be unable to do so and probably break in process of attempting.

It seems that you are right about that. It works quite well, when you also include and enable a unit file for the OSD daemon. Until it needs to be restarted by itself.

**Comment by kozec** [comment]
> It seems that you are right about that. It works quite well, when you also include and enable a unit file for the OSD daemon.

Interesting, I expected it to be unable to get X11 connection. If you are running osd-daemon and autoswitch-daemon as separate units, you may also add `scc-daemon debug --alone` flag to scc-daemon unit to prevent if from trying to start them by itself.

But that restarting is not going to work :(
