### ISSUE TITLE
Controller auto-turn-off setting [Enhancement]

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#316]
It would be nice to have a setting that shut the controller off after XX minutes of inactivity.  Ideally the time could be either one of several options (5min, 15min, 30min, etc.) or better yet, could be directly input by the user (17.5 minutes, or something).  

I've been running-down my SC's batteries a lot more lately because I've been using it to surf the web and I'll set it down to use the keyboard and won't remember it's on for like half an hour. :)P

**Comment by kozec** [comment]
I thought it already does that by itself, If not, I'll definitely add that option.

**Comment by kozec** [comment]
Right click on controller icon -> configure controller -> slider in middle :)
