### ISSUE TITLE
GUI mapped modes Hold and Double Click failing to map properly

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#317]
Sorry I can't be more specific.  I thought I knew what the pattern was, but the more I tested, the more confused and exhausted I became.  But here's related pieces of what's happening

### GUI created HOLD and DOUBLE CLICK modes fail to map correctly
Using the UI, *Hold* mode and *Double Click* mode settings are being saved as *(pressed alone)*, and function as such.  I've tested this with RB, Y, and Center buttons.

Actions and Keys mapped *__via GUI__* to an input's *Hold* or *Double Click* mode are being written without the mode's modifier.  So, instead of getting `hold(osd('held'))` or `doubleclick(osd('twice'))`, we only get the `osd('hold')` or `osd('hold)` being recorded, respectively.  

If both `hold(osd('held'))` and `doubleclick(osd('twice'))`are mapped (again, via the GUI) only one of them will be mapped, and it will be as the *(pressed alone)* mode setting.

For example, on the RB, I mapped nothing to the *(pressed alone)* setting,

![sccguimode1](https://user-images.githubusercontent.com/23580979/34955393-28f4ddf2-f9f2-11e7-891d-9224614599c3.png)

two *Hold* settings,

![sccguimode2](https://user-images.githubusercontent.com/23580979/34955428-4bce4bec-f9f2-11e7-9928-1e11160ca903.png)

one *Double Click* setting,

![sccguimode3](https://user-images.githubusercontent.com/23580979/34955435-569fb89e-f9f2-11e7-9b1a-ce6b4718758d.png)

And all that actually gets mapped is:

![sccguimode4](https://user-images.githubusercontent.com/23580979/34955452-71387128-f9f2-11e7-983a-35053ef1c262.png)

### Workaround

Manually writing modes with defaults, such as `doubleclick(osd('twice'), hold(osd('held'), osd('solo')))` for example, does work as expected.

**Comment by kozec** [comment]
Interesting, I can't find what's causing this. But as temporal workaround, setting anything to "pressed alone" allows rest to be saved.
