### ISSUE TITLE
Help...About showing incorrect version

### ISSUE THREAD

**Issue by drohm** [kozec/sc-controller#319]
I just installed 0.4.0.2 and when I go to Help...About it's showing 0.3.99.3.

**Comment by Vintodrimmer** [comment]
Strange, mine seems to show the correct version.

![version](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2018-01-22-20%3A08%3A19-screenshot.png)

**Comment by drohm** [comment]
Turns out I had an older AppImage installed.  Removed it and did clean install and all is good.  Apologies for the confusion.

**Comment by kozec** [comment]
I really like self-solving issues :)
