### ISSUE TITLE
Support for any keyboard keys (international layouts?)

### ISSUE THREAD

**Issue by hendricha** [kozec/sc-controller#32]
I have a hungarian QUERTZ keyboard layout. It contains keys that I can not bind in sc-controller, or some that don't bind correctly.

Examples:
- I have the 'Ö' character key on the right of the '9' key. If I press Ö during grab a key, nothing happens, it is not recognised.
- I have the '0' (that's the number zero for clarity) key on the left of the '1' key (it's the place where the '~' key is on QUERTY keyboards I think), if I peress 0 during grab a key, it is recognised as KEY_0. However in action that seem to just send the keycode of the key where the '0' is on QUERTY keyboards, the one on the right of the '9' key, the same one I tried to bind in the previous example unsuccessfully.

**Comment by hendricha** [comment]
(ps. I kind of used xdotool for working around this, for anyone who has the same problem)

**Comment by kozec** [comment]
Sounds interesting...

![huhuhu](https://cloud.githubusercontent.com/assets/1282500/15531961/83de3ed4-225d-11e6-831f-be3965426a5d.png)

Which one?

**Comment by hendricha** [comment]
I'm guessing its 'Hungarian (standard)', silly Ubuntu only lists my current layout as 'Hungarian' (in hungarian :D ). BTW I don't really think this is a hungarian specific issue and more an issue with how you grab the keys. (But that's just a guess, I haven't looked at the code.)

**Comment by kozec** [comment]
Well, it actually grabs keycodes, and keycodes are independent from keyboard map. But there may be some bug in that :)

I have Ubuntu VM at home, so I'll check it tonight.

**Comment by hendricha** [comment]
Not sure it helps, but this is what I see on my ubuntu 14.04: 
('Magyar' means hungarian)
![kepernyokep 2016-05-25 11 59 53](https://cloud.githubusercontent.com/assets/4252659/15536146/6c441af6-2270-11e6-85ed-ff864f423cdc.png)
However when I try to add another and select Hungarian (standard), this happens:
![kepernyokep 2016-05-25 12 01 02](https://cloud.githubusercontent.com/assets/4252659/15536155/7269e8fc-2270-11e6-9eb0-0812cf7a89b8.png)

While "Magyar (szabványos)" (AKA "Hungarian (standard)") is selected I still can not grab 'Ö' in sc-controller.
