### ISSUE TITLE
Frictionless trackball [UPDATE: sometimes] cannot be stopped on L/Rpad mode/profile change. 

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#320]
The title says it all.  To see what I mean you can use the following custom action.  It sets RPad with a circular mouse wheel around a frictionless trackball.  The C modeshift is irrelevant to this issue. 

```
ring(0.75,
  mode(
    C,         dpad(
      button(Keys.KEY_LEFTCTRL) and button(Keys.KEY_LEFTALT) and button(Keys.KEY_UP),
      button(Keys.KEY_LEFTCTRL) and button(Keys.KEY_LEFTALT) and button(Keys.KEY_DOWN),
      button(Keys.KEY_LEFTCTRL) and button(Keys.KEY_LEFT),
      button(Keys.KEY_LEFTCTRL) and button(Keys.KEY_RIGHT)
    ),
    rotate(19.8,   smooth(9, 0.9, 1, feedback(RIGHT, 186, 7.0, sens(2.4, 2.4, ball(2.999, mouse())))))
  ),
  feedback(RIGHT, 149.0,     sens(2.5, 2.5,       circular(mouse(Rels.REL_WHEEL))))
)
```

Now, in one motion, swipe across the trackball center ring into the circular mouse wheel and the cursor will zoom to the side of the screen until `scc-daemon restart.`

This occurs if other inputs are used to shift L/Rpad mode during trackball rolling.

This also occurs if the frictionless trackball is rolling during a profile shift.

For now, I've added an 'scc-daemon restart` entry to my Default(global) menu to regain control.  (I've called it "Failed exorcism,"  because it ends daemonic possession, but the daemon returns. XD)

**Comment by LinuxJoeUser** [comment]
This bug has been a regular and (I had *thought*) predictable issue for me, so I'm going to leave this issue open for a bit even though maddeningly  (pulls hair out) *it's not doing it now.*  

This morning I ran scc in debug to watch for errors (none), but when I tapped RPad, the infinite scroll *stopped.*  I switched back to normal scc, and the problem was no longer there either.  I haven't updated since before I tested and posted yesterday (v0.4.0.2), so I'm not sure what's up.

**Comment by LinuxJoeUser** [comment]
[UPDATE:] This isn't quite as predictable as I initially thought on the mode switch ... but seems to be pretty consistent on the profile change while frictionless ball is rolling.  It may take a few tries to make it happen, but it does happen.

**Comment by kozec** [comment]
It makes sense on profile change, as you are replacing action that should be responsible for stopping that motion. What I'm not sure is whether it is bug or feature...

It shouldn't happen unless you change profile _while_ moving finger on pad at same time. Am I mistaken?

**Comment by LinuxJoeUser** [comment]
> It shouldn't happen unless you change profile while moving finger on pad at same time. Am I right on that?

Almost, but it's not just moving your finger on the pad during a profile change.

It happen if there's a profile change while if you move your finger on the pad and *lift it without stopping on the pad.*

But if you change profiles while moving your finger on the bad, then *stop moving your finger on the pad,* there is no problem.

It's as if the trackball rolling state of *profile_1* needs to be "passed" to *profile_2,*  otherwise it's as if *profile_1* never releases the mouse .

It can happen at any friction level on the trackball, but the less friction, the longer you must wait to regain control again --- or kill `scc-daemon` if there was no friction.

It's extremely easy to do on the desktop, especially,  switching from the desktop to firefox to a game quickly, for example.  Profile changes in games (like having a *On Foot* profile and a *In Vehicle* profile) can be a nightmare.
