### ISSUE TITLE
Add a "Name Only" checkbox so Modeshifters can have Action Names. [Enhancement]

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#321]
For example, if I wanted LPad to become a menu---let's say a Weapon Wheel---when I push the RB, then I want to be name RB "Weapon Wheel," even though it actually has no action assigned to it.

Maybe this can be done with a checkbox called "Name Only"  under the "Action Name" entry?

**Comment by kozec** [comment]
This is basically madness, but why not...

**Comment by LinuxJoeUser** [comment]
> This is basically madness, but why not...

LOL!   You know that's what you love about me XD

**Comment by kozec** [comment]
St. Koze**c** says: No cehckboxes needed, just type name and press save :)
