### ISSUE TITLE
Programmatic control

### ISSUE THREAD

**Issue by IamCarbonMan** [kozec/sc-controller#323]
It would be really nice to see Turing-complete macros added to sc-controller. I think the best possible way to do this would be to add to / document the scc-daemon interface and add a simple command-line client. Example workflow:

- Profile binds button A to `shell("custom-A-button-script")`
- custom-A-button-script does something like
```
#!/bin/bash
case `scc-daemon --read-controller-state | jq .leftGrip`
    true)
        scc-daemon --exec-action 'osd("left grip is being held")'
        ;;
    false)
        scc-daemon --exec-action 'osd("left grip is not being held")'
        ;;
```
Basically, if one can call scc-daemon (or access if via HTTP, FIFO, etc) in order to read the current state of the controller and to execute actions, it's then possible to do any number of custom actions.

**Comment by kozec** [comment]
You can talk to daemon through unix socket and [it can return a lot](https://github.com/kozec/sc-controller/blob/master/docs/protocol.md), adding request for controller state shouldn't be a problem.

My main issue with that is that it's basically keylogger :)

**Comment by IamCarbonMan** [comment]
Actually, the protocol is pretty sweet as it is, I hadn't seen that before. Would it perhaps be possible to add an action similar to the Lock and Unlock messages, but built-in to the GUI? The action would look like `redirect("custom-script", BTN_A, BTN_B)`. This would launch custom-script like the `shell` action but would also automatically lock the A and B buttons to that client.

Another option (more sustainable but harder to program) would be to modularize the communication part of sc-controller as a Python library, and allow a profile option that registers custom Python handlers.

**Comment by IamCarbonMan** [comment]
On the subject of allowing custom Python actions, what about just importing ~/.config/scc/init.py or similar? You could extend the available actions by subclassing scc.actions.Action, and that would probably be enough for most use cases.

**Comment by kozec** [comment]
> Another option (more sustainable but harder to program) would be to modularize the communication part of sc-controller as a Python library, and allow a profile option that registers custom Python handlers.

That's actually easier to do, as there already is [module used by GUI](https://github.com/kozec/sc-controller/blob/master/scc/gui/daemon_manager.py#L25) that fits description. It uses gobject, what is not best thing to use for fast and simple scripting, but separating that shouldn't be a problem.

> On the subject of allowing custom Python actions, what about just importing ~/.config/scc/init.py or similar? 

That sounds OK, but be prepared for it to blow up after every other update :)

**Comment by IamCarbonMan** [comment]
> That sounds possible, but be prepared for it to blow up after every other update :)

Sounds good to me, it's an advanced enough feature that anybody using it should be able to look at the commit log and figure out what needs to be changed.

**Comment by kozec** [comment]
Ok, so with above, you can create ~/.config/custom.py [like this](https://pastebin.com/JG5vKZ32) and have it doing pretty-much anything.

I've also tried to create request for controller state, but I'm not sure how much is it is usable for script, as it would have to understand meaning behind numbers in it...

**Comment by IamCarbonMan** [comment]
> I've also tried to create request for controller state, but I'm not sure how much is it is usable for script, as it would have to understand meaning behind numbers in it...

As long as it's added to the protocol documentation that seems like more than enough for me.

**Comment by kozec** [comment]
That's not problem, problem is that controller state depends on controller hw, even internally. For example, this is for steam controller and DS4...

```
State: ControllerInput(type=1, status=1, seq=60555, buttons=0, ltrig=0, rtrig=0, lpad_x=0, lpad_y=0, rpad_x=0, rpad_y=0, gpitch=0, groll=0, gyaw=0, q1=0, q2=0, q3=0, q4=0)
EvdevControllerInput(buttons=268435456, ltrig=0, rtrig=-32768, stick_x=0, stick_y=0, lpad_x=0, lpad_y=0, rpad_x=0, rpad_y=0, gpitch=-1, groll=-1, gyaw=0, q1=0, q2=0, q3=0, q4=0, cpad_x=0, cpad_y=0)
```

Normalizing it before sending would most likely be slow enough to make client visibly lag.

Using "Lock:" and recieving events when state changes is probably better ideal.

**Comment by IamCarbonMan** [comment]
Are these consistent? Like do 2 DS4s of the same model have the same state across different systems?

**Comment by kozec** [comment]
Nope, it depends on kernel version :D But there are only two versions, I believe. And steam controller is same everywhere, of course.

**Comment by IamCarbonMan** [comment]
Welp, that's about the best I can ask for then. I think we can go ahead and close this.

**Comment by kozec** [comment]
I've ended up adding two commands for command line that may be useful for scripts as well; They just print pressed buttons similarly as `xev` does. With those, you can run something like `scc lock-inputs A B X` and pipe output to something.
```
scripts/scc lock-inputs a b c
A 1
A 0
B 1
B 0
```

It prints `B 1` for button press and `B 0` for release.

**Comment by neuromancer** [comment]
I'm not sure why this issue was closed. Is it possible to send commands to the sc-daemon? (for instance: turn off a controller)

**Comment by kozec** [comment]
@neuromancer 
Yes. `echo "Turnoff." | nc -U ~/.config/scc/daemon.socket`

You'll need bsd-compatibile netcat, most of distros have it either as default one, or as alternative in repository.
