### ISSUE TITLE
Action to move mouse

### ISSUE THREAD

**Issue by IamCarbonMan** [kozec/sc-controller#324]
Would it be possible to have an action that moves the mouse to an absolute (x,y) position onscreen or by a relative (x,y) from its current position?

**Comment by kozec** [comment]
Yes, in theory, but wouldn't `shell("xdotool ...")` do same job?

**Comment by IamCarbonMan** [comment]
Yes, in the same way that quite a bit of sc-controller's functionality could be replaced by xdotool. Currently I do use a shell binding for this, but it's the only thing I have xdotool installed on my system for. If it's not overly difficult to add I think this could be a useful feature.

**Comment by kozec** [comment]
After playing with it a little, I have to say that it is, in fact, overly difficult.

Thing is, SCC controls emulated mouse and doesn't really know how big movement moves cursor by 1px. That depends on sensitivity setting in Xorg, maybe even screen resolution, etc... So while trying to solve all of that in SCC, xdotool is much less error prone :)

As for moving cursor to specific position, you can actually do that using [mose area](https://github.com/kozec/sc-controller/wiki/Custom-Action-Examples-and-Explanations#-areax1-y1-x2-y2--winareax1-y1-x2-y2) feature. Just create small area - `area(20, 150, 20, 150)` moves cursor 20px from left, 150x from top.
