### ISSUE TITLE
OSD&Menus rework

### ISSUE THREAD

**Issue by kozec** [kozec/sc-controller#325]
- [x] SVG based keyboard is slow to render, painting to Gtk.DrawingArea should be much faster
- [ ] Allow multiple menus to be visible, at least one per controller
- [ ] Each controller (or slot?) should display menus on other side of screen, preferably with customizable offsets (#239)
- [ ] Each controller (or slot?) should use different color theme by default
- [ ] Same for keyboard
- [ ] [And everything here](https://github.com/kozec/sc-controller/issues?q=is%3Aissue+is%3Aopen+label%3A%22OSD%26Menus+rework%22)

**Comment by pattontim** [comment]
Keyboard no longer works when using a Steam Controller with the Steam Deck. Related to adding multiple keyboard support, solution may be either to allow each controller to bring up its own keyboard or prioritize the Steam Controller or designate them as priority devices so they can control the same keyboard

**Comment by kozec** [comment]
This is definitelly wrong issue to report that, it's just old, forgotten checklist of mine.

But keyboard should work on deck as it does with everything else. Is the issue with keyboard being controlled by deck touchpads even if it is spawned by controller?
