### ISSUE TITLE
Steam controller joystick press is not working in 4.0.2

### ISSUE THREAD

**Issue by Patola** [kozec/sc-controller#326]
After 4.0.2 update, clicking the joystick does not send a signal anymore. Tested with all my previous configurations, none of them worked. Tested with regular steam configuration/test on steam, worked correctly and shows the stick being pressed. I also enabled Input Test Mode on sc-controller to see if it would show the stick press but it doesn't.

**Comment by Patola** [comment]
Ubuntu 17.10 64 bits
sc-controller from official PPA

**Comment by kozec** [comment]
It was sent to game on my side, but GUI indeed failed to show that.

**Comment by Patola** [comment]
I never cease to be amazed on how quick you are to fix the problems. You've got a big admirer here.

**Comment by Patola** [comment]
Sorry... I've replaced the file you changed in 4.0.2 and that did not fix the issue. The controller still does not seem to be receiving the 'stick press' event. Any way for me to help you debug this?

**Comment by kozec** [comment]
(reopening because of https://github.com/kozec/sc-controller/commit/99d36588a30db33471bc9fefadc5c39fbad5693a#commitcomment-27356138)

> The controller still does not seem to be receiving the 'stick press' event. Any way for me to help you debug this?

Is that issue caused by USB3 you mentioned in 328? I'm almost sure I had no issues with USB3 ports on my side, but I'll check just in case.
