### ISSUE TITLE
SC Controller doesn't recognized saved configurations

### ISSUE THREAD

**Issue by EricxDu** [kozec/sc-controller#327]
SC Controller doesn't seem to recognize any of the profiles saved in its config directory.

When I launch SC Controller, it asks me to name a a new profile (default "New Profile 16", for instance). After that dialog, the drop-down menu contains none of the profiles I have previously saved nor any at all aside from the newly named one and the create "New Profile..." entry.

~/.config/scc/profiles/ contains all of my previously saved profiles. If I try to "import" any of them, SCC forces me to give it a new name. For instance if I import Freedoom.sccprofile the option to Apply is greyed out until I enter "Freedoom(0)". Next time try to import it, I can't do that and must enter "Freedoom(1)" and so on. None of these existing or newly created profiles are shown in the drop-down menu the next time I start SCC.

I'm running sc-controller-0.4.0.2 from the command-line by running run.sh

**Comment by kozec** [comment]
> from the command-line by running run.sh

Is there any output while this happens? It sounds like there is issue reading that directory, and in such case, there should be some error message.

If not, could you post output of `ls ~/.config/scc/profiles/` ?

**Comment by EricxDu** [comment]
There is no relevant output at terminal. Here is the output of `ls ~/.config/scc/profiles/`

```
1.sccprofile                        New Profile 17.sccprofile
  (copy).sccprofile                 New Profile 18.sccprofile
Custom Standard Pad.sccprofile      New Profile 1.sccprofile
Custom Standard Pad.sccprofile.mod  New Profile 2.sccprofile
Freedoom.sccprofile                 New Profile 3.sccprofile
Freedoom.sccprofile.mod             New Profile 4.sccprofile
Minetest1.sccprofile                New Profile 4.sccprofile.mod
Minetest2.sccprofile                New Profile 5.sccprofile
Minetest2.sccprofile.mod            New Profile 5.sccprofile.mod
Minetest3.sccprofile                New Profile 6.sccprofile
Minetest4.sccprofile                New Profile 7.sccprofile
Minetest.sccprofile                 New Profile 8.sccprofile
Minetest.sccprofile.mod             New Profile 8.sccprofile.mod
New Profile 10.sccprofile           New Profile 9.sccprofile
New Profile 11.sccprofile           Steam Generic HID1.sccprofile
New Profile 12.sccprofile           Steam Generic HID1.sccprofile.mod
New Profile 13.sccprofile           Steam Generic HID.sccprofile
New Profile 14.sccprofile           Steam Generic HID.sccprofile.mod
New Profile 15.sccprofile           Steam HID (copy).sccprofile
New Profile 16.sccprofile           Steam HID.sccprofile
New Profile 16.sccprofile.mod       Steam HID.sccprofile.mod
```

**Comment by kozec** [comment]
Just by looking at it, `  (copy).sccprofile` may cause some crazy issue, but I'll test it when I get home.

Just so I can replicate it, what distro, DE and locale are you using?

**Comment by EricxDu** [comment]
I had to strip a character from that output so it would not screw up
markdown. The actual filename is, I think " - (copy).sccprofile" (space,
hyphen, space, open parens, "copy", close parens, period, "sccprofile")

On Feb 7, 2018 10:46 AM, "Eric Duhamel" <ericxdu23@gmail.com> wrote:

Debian 9.n (n=1 I think), GNOME, English

**Comment by kozec** [comment]
Nothing really explains what's happening so far.

What you described happens when GUI fails to load both `share/scc/default_profiles` (from source tree in your case) and `.config/scc/profiles`, so there is nothing to fill menu with. Failing to load `default_profiles` is something that shouldn't never happen and even if that would be case, you'd get messages like this in console:

```
W UDataManager  enumerate_children_finish for /home/user/.config/scc/profiles failed: g-io-error-quark: Error opening directory '/home/user/.config/scc/profiles': No such file or directory (1)
W UDataManager  enumerate_children_finish for /path/to/source/default_profiles failed: g-io-error-quark: Error opening directory '/path/to/source/default_profiles': No such file or directory (1)
```

Try moving entire ~/.config/scc/profiles away, so it gets recreated. Also running `run.sh -d` should give you more logs.

**Comment by EricxDu** [comment]
Thanks. I can confirm no W UDataManager messages show up even when running with -d flag.

After moving ~/.config/scc/profiles and starting sc-controller a dialogue asks me to name "New Profile 1" and when I do so "New Profile 1.sccprofile" appears in the newly-created ~/.config/scc/profiles directory. I can also confirm that inside the present working directory from which I invoke run.py (the root directory as unzipped from release 0.4.0.2) contains default_profiles subfolder and it is populated with non-empty profiles.

**Comment by kozec** [comment]
Ok, this makes zero sense, so I'm going to try installing Debian with Gnome in VM. Is there anything special on your installation? Do you use Wayland, installed Debian 1 and upgraded all way to 9, or installed 9 and never upgraded? :)

**Comment by EricxDu** [comment]
Yeah, this appears to be a very strange problem esp. with no error messages but such an obvious error.

I'm on Debian 9.0 (I can't find a .1 or .2 anywhere and don't remember); it was installed from a live USB and is currently up-to-date for all installed packages. I've tried two different version releases of sc-controller and tried the git clone. I can't imagine whether it has anything to do with how I installed any of sc-controller's dependencies (I used a mix of apt-get and pip install).

**Comment by kozec** [comment]
> I can't imagine whether it has anything to do with how I installed any of sc-controller's dependencies (I used a mix of apt-get and pip install).

At this point, anything passes as possible explanation :( By releases, do you mean installing from .deb package?

**Comment by EricxDu** [comment]
By releases I mean tar zip files of sc-controller releases downloaded from Github as instructed by the readme.

Path to home is pretty simple: `HOME=/home/eric`

`PYTHONPATH=. scripts/scc list-profiles` lists all the profiles ("New Profile 1" thru "New Profile 9" at this point) with no failures or errors

Executing run.sh usually results in no output (just some GLib-GIO-CRITICAL assertion errors and daemon.pid does not exist on first run, not on subsequent runs). Executing run.sh with -d flag results in normal-seeming output:

> D App           daemon status: unknown
> D DaemonCtrl    Connected to daemon, version 0.4.0.2
> D App           Loading release notes from 'https://github.com/kozec/sc-controller/releases/tag/v0.4'
> D DaemonCtrl    Daemon is ready.
> D App           daemon status: alive

I'm willing to get into the nitty-gritty if possible. Inserting a `print` statement somewhere in the Python should be able to show what's going on at different points in sc-controller right?

**Comment by kozec** [comment]
> EDIT: possibly the oddest or most telling thing is that sc-controller can see the available profiles, because it doesn't allow me to name a profile that already exists when creating a new profile or saving an imported profile.

That along with output from `list-profiles` confirms that problem is with GLib. Checking if profile name is available is done with plain `if os.path.exists() ...` as it's quick, but because listing folder can take time, it is done asynchronously, using GLib.

Problem is almost sure in [this method](https://github.com/kozec/sc-controller/blob/master/scc/gui/userdata_manager.py#L72), which [calls enumerate_children_async](https://github.com/kozec/sc-controller/blob/master/scc/gui/userdata_manager.py#L98). And that either never finishes or returns empty list. If you are feeling like placing prints everywhere around those methods, it may give out some idea of what's breaking.

**Comment by EricxDu** [comment]
My first tests inside `load_user_data(self, paths, pattern, category, callback)` show `paths` is a list containing what it ought to `['/home/eric/src/sc-controller/default_profiles', '/home/eric/.config/scc/profiles']`

However when app.py method `on_profiles_loaded(self, profiles)` is called the parameter `profiles` contains `[]`. So it appears `enumerate_children_async` returns an empty list.

**Comment by EricxDu** [comment]
Strange `pdir.enumerate_children_finish` appears to contain `<__gi__.GLocalFileEnumerator object at 0xb6695a04 (GLocalFileEnumerator at 0xb310a700)>` immediately after that line. I used `print(data[i][1]`

**Comment by kozec** [comment]
> Could that still be an empty list? I'm not sure how to print the contents of the object.

Yes, it still can enumerate 0 items. `print list(data[i][1])` should convert it to list and print it in more readable form.

**Comment by EricxDu** [comment]
The return of `pdir.enumerate_children_finish` in fact contains a list of `Gio.FileInfo` objects, so it is not empty. Searching further down in the method I found by line 132 `files` is an empty dictionary. After putting some print statements inside the try block starting on line 120 I found `for finfo in enumerator:` never iterates, so the initialized `files` dictionary is never populated for some reason.

`for pdir, enumerator in data:` loops twice and `enumerator` contains two objects `<__gi__.GLocalFileEnumerator object at 0xb07df4dc (GLocalFileEnumerator at 0xb300a058)>` and `<__gi__.GLocalFileEnumerator object at 0xb665ba04 (GLocalFileEnumerator at 0x172e5f8)>`

**Comment by kozec** [comment]
>  I found `for finfo in enumerator:` never iterates

That means it acts like enumerator was empty, or it never even reaches that line?

By the way, can you check what exact version of gtk and gio package do you have? I can't imagine any reason why it should behave this differently...

**Comment by kozec** [comment]
Ok, it looks like...

> enumerator contains only two __gi__.GLocalFileEnumerator objects each time, and pdir contains only two 

enumerator and pdir containing two items is perfectly fine, that's one for .../default-profiles and one for ~/.config/scc/profiles directories. In such case, "pdir" is not None and thus it absolutely has to reach `for finfo in enumerator` loop. If it doesn't enter it, glib returned empty list and so there is something very broken with it.

I'll go with that using fallback in case like this plan. If you feel like debugging why is glib giving empty list, please, let me know what you found, but at this point, it may not be worth effort to go any deeper :)

**Comment by EricxDu** [comment]
A `print` statement I put inside `for finfo in enumerator` never prints anything, but any `print` statement I put before the loop does print, so it appears it reaches the line but never iterates the loop.

I don't think I want to go any deeper than debugging the Python side of things, but I'll leave my version numbers as requested in case they are relevant to the bug.

libgtk-3-0/stable,stable,now 3.22.11-1 i386
python-gi-cairo/stable,stable,now 3.22.0-2 i386

That should be gtk and gio right?

**Comment by kozec** [comment]
Gio is `gir1.2-glib-2.0`, but you have exactly same GTK as my Debian install and those two are surely updated together, so I'm out of ideas :)

I'll add that fallback.
