### ISSUE TITLE
Most Action Names disappear with profile change or GUI close.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#331]
The only Action names that stay are:  

* LT;  RT
* LG;  RG
* BACK;  START

All other inputs lose their Action names on a profile change or shutting off the GUI.  They are cowards.

**Comment by kozec** [comment]
Looks like fix for #321 broke this :(

**Comment by LinuxJoeUser** [comment]
Hmm, I don't know.  

As far as I can remember, it's *always* been broken.  I hadn't mentioned it yet for two reasons:  1.  I assumed you would know about it, and 2)  I just felt that there were bigger problems than this, basically, cosmetic problem.

**Comment by kozec** [comment]
I'm trying to reproduce this right now but I can't. I've created new profile, set just name on Y button, mapped X button to key and set name on that, saved, switched profile, restarted UI and everything sticks.

Are you doing something different? Can you give me profile where it fails?

**Comment by LinuxJoeUser** [comment]
Ok, glad you described what you did ... it's not input-specific like I thought ... I can make it happen on any input that has more than one mode assigned to it as long as it isn't a Name Only assignment.

Assign X button a name only (e.g. 'Name Only'), save
Assign X button a mode shift LB , a new name, (e.g. 'The Machine Goes') and special action OSD ('Bing!!!), save: 
![image](https://user-images.githubusercontent.com/23580979/36354730-bb53ad12-14a6-11e8-923e-e20fad080443.png)

![image](https://user-images.githubusercontent.com/23580979/36354748-19049138-14a7-11e8-834f-716d256998e1.png)

Change profile and go back, the name only "Name Only," remains, but the OSD name is gone.

![image](https://user-images.githubusercontent.com/23580979/36354780-6661a7f4-14a7-11e8-9724-bc416175e383.png)

**Comment by kozec** [comment]
You were right, this got broken with simplified profile format. This should cover all places where name may not be saved.
