### ISSUE TITLE
OSD memory leak

### ISSUE THREAD

**Issue by Skincanvas** [kozec/sc-controller#333]
I am on Xubuntu, 17.11, open source ATI driver. I do have Steam installed but is closed at the moment. After 10 minutes pressing shift will start to hang the osd (the duration increasing by the minute), and over the course of an hour the osd PID will be upward to a gigabyte in size. Temporary fix is to close the osd occasionally in your task manager

**Comment by kozec** [comment]
Wait, shift on keyboard? OSD should't even read inputs keyboard...

Something sounds horribly broken, can you post exact steps, what are you pressing and what it does / shouldn't?

**Comment by Skincanvas** [comment]
No shift as in left grip, I just go about capitalizing and it slowly but surely hangs longer. Maybe it is hardware related if nobody else experiences it, because it has persisted installs

**Comment by kozec** [comment]
Things that confuses me on your description is that there is no relation between shift and left grip I can think about.

**Comment by Skincanvas** [comment]
In the OSD (maybe this is wrong to say? I mean the onscreen keyboard bundled with sc-controller) when you hold left grip the keys will shift from lowercase to uppercase

**Comment by kozec** [comment]
Ah, ok. Now it makes sense. That keyboard is called, well, keyboard :)

Images drawn there are cached in memory and pressing shift clears the cache, as it changes displayed letters. I'll check if I can do anything about that leak, but I'm actually rewriting entire thing right now in way that doesn't need caching to be fast, so it will be probably faster to ignore it for few days.

**Comment by Skincanvas** [comment]
No problem, thank you
