### ISSUE TITLE
grab_with_size not built into libhiddrv.so

### ISSUE THREAD

**Issue by abrasive** [kozec/sc-controller#334]
Hello! Thanks for the great tool & nicely structured code.

I found the daemon wouldn't start on my machine because symbol `grab_with_size` was not found in libhiddrv.so. Digging in it looks like it was defined as
```
inline int grab_with_size(...
```
In the output .o file (and consequently the .so) the symbol was referenced but no definition was present. I was able to fix it by replacing `inline` with `static`; as far as I understand `static` is the preferred idiom these days.

This is with scc master as of today, on Gentoo, running gcc x86_64-pc-linux-gnu-7.2.0.

I also didn't get any clues until I ran `scc daemon debug` by hand; when running `run.sh` the GUI came up and just... didn't work. Should it barf if the daemon doesn't come up?

**Comment by kozec** [comment]
> Should it barf if the daemon doesn't come up?

Not really, it should just display red or gray icon. There is no detection for daemon simply refusing to start, mainly because that possibility never occurred to me... I should fix that.

But what exact message are you getting? `grab_with_size` is used only in that one c file, there shouldn't be anything requiring it and crashing.

**Comment by abrasive** [comment]
Indeed, it doesn't make sense!
The error is
```
OSError: ./libhiddrv.so: undefined symbol: grab_with_size
```
And inspecting the .so with `readelf` shows that this is an undefined dynamic symbol, with relocations and everything:
```
    41: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND grab_with_size
```

So for some reason when it's declared with `inline` it isn't being referenced by the call site all of 5 lines later :|

**Comment by kozec** [comment]
Ok, that looks weird enough that just going with `static` and letting gcc to optimize (or not) that sounds like good idea :D
