### ISSUE TITLE
Activate OSD keyboard keys with trigger soft pull

### ISSUE THREAD

**Issue by xPMo** [kozec/sc-controller#337]
This is the behaviour of Steam's OSK, and I find it easier and more accurate to clicking the pads since my fingers don't slip to different letters when I push down.

**Comment by xPMo** [comment]
Merge with #325 ?

**Comment by kozec** [comment]
You can already do that, menu -> Settings -> Menus & Keyboard -> Triggers -> "Press Keyboard Buttons"

**Comment by xPMo** [comment]
Oh, neat.  There's a lot in there that I missed.  GTK3 is good at burying things.
