### ISSUE TITLE
Key feedback in GUI

### ISSUE THREAD

**Issue by parkerlreed** [kozec/sc-controller#34]
Since each key already has a highlight when you hover on them maybe have a button test "mode" where the keys light up as you press them. Maybe have a little display above the analog triggers showing potion along with tap points where the fingers are on the touchpads.

**Comment by kozec** [comment]
Hmm... It's not exactly impossible, but would it be good for anything but eye-candy?

**Comment by parkerlreed** [comment]
Probably not :D Maybe to tell if you might possible have something broken but mostly just eye-candy.

**Comment by Alzarath** [comment]
I'd also like to see buttons flash or give some sort of visual feedback when you press them.

**Comment by parkerlreed** [comment]
I see the color options in Settings but pressing keys doesn't seem to have any feedback for me. Started with a fresh config just to make sure.

**Comment by parkerlreed** [comment]
OH wait what... You did this for the OSK. I meant at the main screen, haha.

![1466516056](https://cloud.githubusercontent.com/assets/841440/16231261/7f1a8402-3793-11e6-8c5f-8d4c4a575798.png)

**Comment by parkerlreed** [comment]
Although I I love the highlight for the OSK too. Looks great. My thought for the main screen was how there was already a green highlight, make those react to button presses.

**Comment by kozec** [comment]
By the way, I know I closed this with kinda wrong fix, so I though I should mention that what you originally wanted is now part of latest release.
