### ISSUE TITLE
Debian 9 package requires an inexistant python-evdev dependency

### ISSUE THREAD

**Issue by AlexandreBonneau** [kozec/sc-controller#340]
When using the opensuze repo for installing the Debian package, it fails saying the `python-evdev` is not installable.
And indeed, this does not exists for Stretch (Debian 9).

One workaround is to manually install the package from the testing 'buster' version (see [this link](https://packages.debian.org/buster/amd64/python-evdev/download)), then you are good to use `apt install sc-controller`.

**Comment by kozec** [comment]
I'm not sure if I can do much about it not being packaged in debian, but it should be possible to mark that dependency as optional.

**Comment by kozec** [comment]
python-evdev is now "recommended", not required in debian package.
