### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by trialism** [kozec/sc-controller#342]
Hi,

 I'm on manjaro and I'm using the package from AUR. I've noticed today that the app used 600MB memory after being open for a few hours(it usually starts from 28MB). I tested a few things: switching profiles can consume 1-3MB after each switch but setting a key can be 5-8MB.

**Comment by kozec** [comment]
Which process was one using that much? GUI is partially drawn by modifying SVGs and results are cached. I'm apparently screwing up that somehow :(

**Comment by trialism** [comment]
It was the `/usr/bin/python2 /usr/bin/sc-controller` process. Can you even deallocate things in python?

**Comment by kozec** [comment]
Not really, but I can stop sticking them into memory indefinitely :)

Hopefully above would help without impacting performance too much.
