### ISSUE TITLE
The "Display Current Bindings..." image won't disappear

### ISSUE THREAD

**Issue by trialism** [kozec/sc-controller#344]
Hi,
 I'd expect it to disappear by pressing the menu or by pressing another button(like escape) but I need to kill it from the task manager. It also generates an out.svg in the home dir which is pretty ugly - using `/tmp/sc-controller/out.svg` would be better.

The main menu is also annoying - it should disappear by pressing the menu button again instead of forcing users to choose something.

**Comment by kozec** [comment]
> It also generates an out.svg in the home dir which is pretty ugly - using /tmp/sc-controller/out.svg would be better.

That was used for debugging and I forgotten to remove it. Sorry about that.

> I'd expect it to disappear by pressing the menu or by pressing another button(like escape) but I need to kill it from the task manager.

"B" button on gamepad should work. Doesn't it?

> The main menu is also annoying - it should disappear by pressing the menu button again instead of forcing users to choose something.

That's also done by "B" button. And this may be actually a problem - that button is configurable, and you can choose Menu button for it, but you can't have both B and Menu at once.

**Comment by trialism** [comment]
Thanks! I'd the ESC remapped to another button and I tried that and the menu.
