### ISSUE TITLE
raspberry pi 3  errors

### ISSUE THREAD

**Issue by kodkuce** [kozec/sc-controller#345]
sc-controller

** (sc-controller:12384): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scc/gui/app.py", line 1277, in do_startup
    self.setup_widgets()
  File "/usr/local/lib/python2.7/dist-packages/scc/gui/app.py", line 96, in setup_widgets
    self.builder.add_from_file(os.path.join(self.gladepath, "app.glade"))
GLib.Error: gtk-builder-error-quark: Invalid property: GtkStack.interpolate_size on line 556 (11)

i tryed both whit sudo and without, also i tryed deb armf and builded whit python same error alwies

**Comment by kozec** [comment]
> GLib.Error: gtk-builder-error-quark: Invalid property: GtkStack.interpolate_size on line 556 (11)

Sounds like very old GTK. What are you running and what version it uses?

**Comment by kodkuce** [comment]
pi@raspberrypi:~ $ dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'
ii  libgtk-3-0:armhf        3.14.5-1+deb8u1rpi1rpi1g armhf        GTK+ graphical user interface library
ii  libgtk-3-bin            3.14.5-1+deb8u1rpi1rpi1g armhf        programs for the GTK+ graphical user interface library
ii  libgtk-3-common         3.14.5-1+deb8u1rpi1rpi1g all          common files for the GTK+ graphical user interface library
ii  libgtk2.0-0:armhf       2.24.25-3+deb8u2         armhf        GTK+ graphical user interface library
ii  libgtk2.0-bin           2.24.25-3+deb8u2         armhf        programs for the GTK+ graphical user interface library
ii  libgtk2.0-cil           2.12.10-5.1              armhf        CLI binding for the GTK+ toolkit 2.12
ii  libgtk2.0-common        2.24.25-3+deb8u2         all          common files for the GTK+ graphical user interface library

raspbian updated to latest

**Comment by kozec** [comment]
> raspbian updated to latest , from what i see i have 3.14 gtk , am running steam controler and like i say i tryed both buld an thet debian armf .deb package , does meybe rpi3 appimage exist?

AppImage uses GTK from Steam, so that's not gonna help. But having 3.14 is weird, that has to be at least 5 years old. Are we talking about "Raspbian Stretch"? I'll check if I can get it running in qemu or something.

**Comment by kodkuce** [comment]
hmm i dont think i have streach just checked rpi site it says it got realised in q4 2017 and i think i installed my raspbian before , np will upgrade or reinstall and report back..

**Comment by kodkuce** [comment]
Updated to Raspbian Stretch , got  libgtk-3-0:armnf  3.22.11-1.rpi3 it works :+1:
