### ISSUE TITLE
Pressing on Lstick doesn't work.

### ISSUE THREAD

**Issue by axredneck** [kozec/sc-controller#348]
SC Controller doesn't recognize click of left stick but Steam does.
Antergos, sc-controller 0.4.1 from AUR.

**Comment by kozec** [comment]
Hmm... How sure about it are you? Because I've just tested it and it seems to be mapped correctly.

With default "XBox Controller" profile, It shows as"button 9 in jstest-gtk on my side. Is it any different for you?

**Comment by axredneck** [comment]
I'm absolutely sure. I enabled "input test mode", and SC Controller doesn't paint lstick pink when i press it, and games also don't sense this button.
Sometimes even worse: when i press one of touchpads SC Controller paints lstick pink and it remains pressed until i restart emulation.
Steam doesn't have this issue so i switched from SC Controller to Steam for now.
How can i help to debug this issue?

**Comment by axredneck** [comment]
p.s.2 The same results with jstest-gtk: button 9 doesn't work becomes forever-pressed after pressing one of touchpads.

**Comment by kozec** [comment]
Ok, nothing of that sounds like something that should be happening...

Please, try running scc-daemon in teriminal - disable emulation from menu and then run `scc-daemon debug`  - and check if it outputs any error messages when problem occurs.

**Comment by LinuxJoeUser** [comment]
>  ... try running scc-daemon in teriminal - disable emulation from menu and then run `scc-daemon debug` ...

I was having probs with Jstick press, so I thought I might try this.  But running `scc-daemon` in a terminal gives me:
```
gw@Marianne:~$ scc-daemon
usage: scc-daemon [-h] [--alone] [--once]
                  [profile [profile ...]] {start,stop,restart,debug}
scc-daemon: error: too few arguments```

Did you mean "run `sc-controller` in terminal, disable emulation from settings menu and then run `scc-daemon debug` ... etc. ?

**Comment by kozec** [comment]
@LinuxJoeUser You are missing that ` debug` part of `scc-daemon debug`

**Comment by axredneck** [comment]
[terminal.txt](https://github.com/kozec/sc-controller/files/1799841/terminal.txt)

**Comment by axredneck** [comment]
[the same after installing pyinotify](https://github.com/kozec/sc-controller/files/1799851/terminal.txt)
Stick is still permanently pressed according to SC Controller's GUI.

**Comment by axredneck** [comment]
p.s. I'm unsure if touchpads are involved in this issue. Seems like stick becomes pressed at random condition, usually few seconds after SC Controller's start.

**Comment by kozec** [comment]
Sorry, but I still can't replicate the problem. Can you send me `~/.config/scc/profiles/XBox Controller.sccprofile`, profile that is used according to that log?

Also, I've noticed you have "Use serial numbers" option enabled (menu->settings->advanced). That caused some weird behavior in past, so try disabling it and restart everything.

**Comment by axredneck** [comment]
I already tried to remove ~/.config/scc, the same problem.

**Comment by LinuxJoeUser** [comment]
@kozec Re: "You are missing that `debug` part of `scc-daemon debug`"

* I was following your instruction to[ _"try running scc-daemon in teriminal"_](https://github.com/kozec/sc-controller/issues/348#issuecomment-372033430),* showing you what I got when I ran `scc-daemon` in a terminal,
* and wondering whether you originally meant _"try running ~scc-daemon~ __sc-controller__ in teriminal"_, because running _scc-daemon_ in a terminal only produces an error.

**Comment by LinuxJoeUser** [comment]
@kozec Re: "You are missing that `debug` part of `scc-daemon debug`"

I misunderstood you.  When you wrote

> [Please, try running scc-daemon in teriminal -  ... etc.](https://github.com/kozec/sc-controller/issues/348#issuecomment-372033430),*

I actually tried to run  "scc-daemon" in a terminal as if it were a command.  DOH!

Ok, Here are the outputs from two runnings of `scc-daemon debug,` using my "MyDesktop v2.2" SC profile (not Xbox). Input Test Mode (ITM) is Enabled.

* [The first debug log](https://github.com/kozec/sc-controller/files/1800603/sccStickPressIssueClear.txt):  nothing mapped to the stick press, and pressing the stick doesn't show up with the ITM

* [The second debug log](https://github.com/kozec/sc-controller/files/1800607/sccStickPressIssueOSD.txt): `osd('boink')` is mapped to the stick press.  As soon as debug is run, the ITM marks the stick as being_ pressed  and held down_ even though the stick hasn't been touched.  Clicking on the stick makes no difference.

**Comment by kozec** [comment]
Ok, so LinuxJoeUser is using wireless controller while axredneck wired, axredneck has serials enabled,  LinuxJoeUser doesn't. And you both have same problem and no errors reported. And it doesn't occur for me at all. Now I'm officially confused :(

If you are using Steam as well, have either of you got any firmware updates recently?

@LinuxJoeUser are you using git checkout or some deb package? Can you send me that profile?

**Comment by kozec** [comment]
@axredneck I'm installing Antegros in VM to check this one; Which DE are you using?

**Comment by axredneck** [comment]
I'm using KDE.
About firmware: yes, i received update. I also tried to restore firmware using Steam but bug still presents.
> ... while axredneck wired, axredneck has serials enabled ...
axredneck deleted ~/.config/scc and still has a bug :)

**Comment by LinuxJoeUser** [comment]
I'm using Xfce on Xubuntu 17.10.

I don't remember the last SC firmware update I got from Steam, but I think it's been a while.  If it's any help, here's all the "System Info" I get from Steam about my system:  [steamSystemInfo.txt](https://github.com/kozec/sc-controller/files/1802802/steamSystemInfo.txt)


I don't use `git checkout` or a .deb package.  I cloned __sc-controller__ and update it by `git-pull`, `sudo python2 setup.py build` then `sudo python2 setup.py install`

And finally, here's a copy of my "[My Desktop v2.0.sccprofile.txt](https://github.com/kozec/sc-controller/files/1802817/My.Desktop.v2.0.sccprofile.txt)" that I mentioned and that you requested.

**Comment by kozec** [comment]
So far nothing, I have freshly installed Antegros with KDE and only two additional packages - yarout and sc-controller - and everything works as expected :(

@LinuxJoeUser assuming this is new issue, do you happen to remember last version where it haven't been occuring?

**Comment by LinuxJoeUser** [comment]
I can't be sure.  Definitely sometime since 0.3.7, maybe since .3.10.  I'm going to spend some time today or tomorrow installing old versions of SCC to see if I can figure out exactly which version where it happened.

**Comment by LinuxJoeUser** [comment]
FIXED!  I have no idea how or why it's fixed, but it's fixed.  I have two SCs, one for my Windows box(SCw), and one for my Linux box (SCl).  I plugged SCl into my laptop, which is still on SCC 0.4.02 ... pushed the stick and ... and *it worked!*  Yay!  Ok, so, on a hunch, I plugged my  SCw dongle to my Linux machine, turned on the SCw controller, pushed the stick and ... and *it worked too!*  Yay, but WTF?  Ok, so I put everything back the way it was, with SCl back on my Linux box, pushed the stick and *it worked!*

So fuck my life if that made any sense.  Anyway, it's fixed for me.

**Comment by axredneck** [comment]
I plugged my controller to other USB port and now it works too.

**Comment by axredneck** [comment]
Then i plugged it to USB port it was plugged yesterday and it still works.
So workaround: plug controller to other USB port.

**Comment by LinuxJoeUser** [comment]
["Hello, I.T..  Have you tried turning it off and on again?"](https://www.youtube.com/watch?v=rksCTVFtjM4&index=5&list=RDYhPejfTQfEA)

**Comment by axredneck** [comment]
@LinuxJoeUser i tried but with no result.

**Comment by kozec** [comment]
When weird stuff like this happens and switching ports helps, it usually means that original port was low on power (had too many things connected to same branch).

Anyway, I'm glad that this got solved and I'm going to call it HW problem, because there is no way I can replicate _that_ behavior.
