### ISSUE TITLE
Expand Haptic Feedback candidates

### ISSUE THREAD

**Issue by Alzarath** [kozec/sc-controller#35]
I noticed Haptic Feedback seems to be checked off as 'Done' on your TODO, so I thought I might request it be expanded.

I feel like this should be a priority for the trackball/trackpad, as the pads give little feedback compared to the rest of the controller. I'd also, personally, really like it for the rotating mouse wheel. Adding it as an option for everything possible would be preferred, of course.

On a side note, I'm genuinely impressed with how much work you've been doing on this. It's been quite enjoyable watching it expand from what it was at the beginning to a system that I'd say is even better than the current official software. Thank you for your efforts.

**Comment by kozec** [comment]
Hmm...

Feedback on trackball and trackpad *should* work, but now when you are asking I can see it cannot be enabled in GUI in latest version. It works as it should in v0.2.5, do I'll just check what I broke...

As for rotating mouse wheel, I'll check how hard that would be.

And thanks for your side note, it's always nice to hear that people are actually using my stuff :)

**Comment by kozec** [comment]
Ok, I will deny that this ^^ ever happened, but [latest release](https://github.com/kozec/sc-controller/releases/latest) doesn't have that problem.
