### ISSUE TITLE
SteamOS compatibility 

### ISSUE THREAD

**Issue by Mrcnarine** [kozec/sc-controller#350]
Hello! Iv'e been following this project for almost a year now. I've been eagerly waiting for someone to develop some kind of amazing utility or driver for Windows but I don't think that's happening, so I finally gave in and decided to get Linux just to try sc-controller and Linux ended up really kicking my ass. Nothing worked at all. 

I do plan on trying again in a little bit but I was wondering if I could use sc-controller with SteamOS? I simply want to try one game with sc-controller on Linux without any complications. I know it's based on Debian 8.0 but I wouldn't be surprised if it doesn't work, you can never be too sure with Valve. 

Thanks for reading.

**Comment by kozec** [comment]
Yes, but it's not gonna be entirely straightforward. Only one program can have control of Steam Controller at a time, so sc-controller will fight with Steam on who starts first and calls dips. So you may need to do some modification to make sure that sc-controller (or at least `scc-daemon`) starts before Steam.

Alternatively, you can go to "desktop mode" from power icon in Steam UI and then proceed as on any other distro - start sc-controller, start Steam, continue as usual.
