### ISSUE TITLE
Gyro Tilt sensitivity

### ISSUE THREAD

**Issue by kodkuce** [kozec/sc-controller#351]
Hi i need to lean left and right inGame, wanted to use gyro for that, i tried Tilt but it takes over 45degree in think to activate assigned command. So can i lower it somehow so i don't break my arms :smile: , i didn't saw any settings about it in UI or maybe i am just blind, anyway any help appreciated

**Comment by kozec** [comment]
There is no such option in GUI, mainly because it never occurred to me it may be needed.

But you can use custom action and add sensitivity to tilt - 

```
sens(0, 10,
tilt(
  None,
  None,
  button(Keys.KEY_Z),
  button(Keys.KEY_X)
))
```

\- bigger number where "10" is, less tilting angle is needed.

**Comment by kodkuce** [comment]
thank you :+1:

**Comment by kodkuce** [comment]
Np I am in  no hurry :smile:  
You are probably right I just checked my void-linux package is  4.0.2 so  will build from source to confirm and report back

**Comment by Vintodrimmer** [comment]
Hey, @kodkuce. Here's the [template](https://github.com/Vintodrimmer/void-packages/blob/sc-controller-branch/srcpkgs/sc-controller/template) if you need it.

For some reason, approval process has slowed down again.

**Comment by kodkuce** [comment]
oh i just forked it for nothing, guess will earn my void pull req some other time :sob:
