### ISSUE TITLE
No instructions on how to use sc-controller

### ISSUE THREAD

**Issue by someg33zer** [kozec/sc-controller#352]
When I run it, the controller icon goes green and looks like it should be working but I can't see anything under /dev/input/ and SuperTuxKart doesn't show the controller. The really frustrating problem though, is I don't know what I should be looking for to determine whether it's working because I can't find any information on how to actually use sc-controller.  And I've done lots of searching, using web search engines, github, etc.

**Comment by kozec** [comment]
Well, main goal is that is should "just work" :) Green icon is indication that everything should be ok, so if there is nothing under /dev/input/, something have gone wrong.

Check if `dmesg|tail` shows messages about new input device after icon turns to green and if not, click on that icon, choose "disable emulation" and then run `scc-daemon debug` from console to see if there are any error messages.

And knowing stuff like what distro and DE are you using may be useful :)

**Comment by someg33zer** [comment]
> if there is nothing under /dev/input/, something have gone wrong

Can I suggest adding that sentence to the README?  It would have saved me a lot of time.

**Comment by LinuxJoeUser** [comment]
@someg33zer :  Could you provide some more information, please?  You say that when you run it, the controller icon turns green.  Does that mean [the controller GUI](http://i.imgur.com/OJy9dGx.png) appears?  And if so---and the profile is "Desktop"---does the controller move the pointer on your desktop if you swipe the RPad?



 and looks like it should be working but I can't see anything under /dev/input/ and SuperTuxKart doesn't show the controller.

**Comment by someg33zer** [comment]
@LinuxJoeUser there's two things going on here.  Firstly, I don't understand how sc-controller is supposed to work.  Notice that this is an issue with my head, my memory and with information.  Specifically, lack of information.  I'm asking how sc-controller is supposed to work.  I asked above: "what should be under /dev/input/? Should there be a jsX device?"

Secondly, my Steam Controller doesn't work.  That's a secondary issue though.  The more important issue for me is that I don't understand how sc-controller is supposed to work.  I don't want to go through a process of collaboratively debugging sc-controller over GitHub messages.  I can debug the problem myself and it will be a lot quicker.  However, in order to do that I need to solve the first problem of not understanding what I should be looking for to determine whether sc-controller is working.

**Comment by LinuxJoeUser** [comment]
@someg33zer I'm sorry if you thought I was being unhelpful.  You provided some information in your OP, I was only asking for a bit more to help elucidate your issue.

To answer your question, yes, there should be a `JSx` entry, as well as additional `mousex` entries, a `mice` entry, and a couple `eventx` entries in /dev/input when you run `sc-controller.`

**Comment by someg33zer** [comment]
> yes, there should be a JSx entry, as well as additional mousex entries, a mice entry, and a couple eventx entries in /dev/input when you run sc-controller

Thank you! :-)

**Comment by LinuxJoeUser** [comment]
Additionally, it might help to know that sc-controller will do that whether or not the Steam Controller is on or off, connected or not.

**Comment by kozec** [comment]
Problem with /dev/input/ is that it is kinda distro dependent. But when scc-daemon is started (when icon turns green), it should immediately create at least one set of keyboard, mouse and gamepad devices, no matter if there is steam or any other controller connected.

Now, what's done with those devices may really vary, but typically, you'd something like this in dmesg:

```
[693479.975140] input: SCController Keyboard as /devices/virtual/input/input350
[693479.975990] input: SCController Mouse as /devices/virtual/input/input351
[693479.978083] input: Microsoft X-Box 360 pad as /devices/virtual/input/input352
```

... and appropriate set of /dev/input/js*, mouse* and event* files is created.

**Comment by LinuxJoeUser** [comment]
This doesn't seem like an issue with how `sc-controller` functions, and like you say 

> Problem with /dev/input/ is that it is kinda distro dependent,

so it seems too specific an issue to include in a set of instructions.  

This is the sort of thing someone might post on a forum or ask in irc, but isotherwise  too specific to a particular user.  

Can I suggest calling this issue "fixed?"

**Comment by kozec** [comment]
Yeah, there is no much to fix here, sane for some kind of 1st run welcome message, but I'm not really sure what could be written in it.

I'm closing this, but feel free to ask if there is anything not entirely clear  :)
