### ISSUE TITLE
Trackball (Mouse-like joystick) and dead zone

### ISSUE THREAD

**Issue by rcpoison** [kozec/sc-controller#356]
Hi :)

I'm trying to use the right pad as Mouse-like joystick.

Sadly, the game I want to play has a hard-coded dead zone so it only ever registers the joystick when I move really fast on the touch-pad.

I've played with sc-controllers deadzone configuration, but that seems to only introduce a deadzone itself.

Also played with sensitivity, but that isn't helpful either.

What I need is an option to overcome a games deadzone, so values are at least greater than the configured threshold:
in: 1 -> out: 2001
in: -1 -> out: -2001

Does something like this already exist?

**Comment by kozec** [comment]
Not right now, but it shouldn't be hard to add such mode.

**Comment by kozec** [comment]
Here you are. I've added 'JUMP' mode that basically gives `out = (in / range * (upper - lower)) + lower`.

For that name, I'm open to all suggestions :)

**Comment by rcpoison** [comment]
OK, maybe I'm doing something wrong?
`deadzone(JUMP, 10000, feedback(RIGHT, 281, ball(XY(axis(Axes.ABS_RX), axis(Axes.ABS_RY)))))`

shouldn't output any value between -10000 and +10000?

`Event: type 2, time 1259842, number 4, value 292
Event: type 2, time 1259862, number 3, value 3868
Event: type 2, time 1259862, number 4, value 162
Event: type 2, time 1259890, number 3, value 4163
Event: type 2, time 1259890, number 4, value 173
Event: type 2, time 1259914, number 3, value 3067
Event: type 2, time 1259914, number 4, value 103
Event: type 2, time 1259934, number 3, value 1705
Event: type 2, time 1259934, number 4, value 5
Event: type 2, time 1259962, number 3, value 1393
Event: type 2, time 1259962, number 4, value 0
Event: type 2, time 1259986, number 3, value 356
Event: type 2, time 1260006, number 3, value 0`

**Comment by kozec** [comment]
Hmm... problem is probably that deadzone is applied only to initial movement, not to "ball" effect. I'll check if that's the case.

**Comment by rcpoison** [comment]
Not quite. Values are higher than before but still inside the deadzone range:

```
Event: type 2, time 5629305, number 4, value 0
Event: type 2, time 5629317, number 3, value 9483
Event: type 2, time 5629317, number 4, value -3334
Event: type 2, time 5629325, number 3, value -5404
Event: type 2, time 5629325, number 4, value -8546
Event: type 2, time 5629333, number 3, value 8092
Event: type 2, time 5629333, number 4, value 5841
Event: type 2, time 5629341, number 3, value 3349
Event: type 2, time 5629341, number 4, value 9476
Event: type 2, time 5629353, number 3, value 5443
Event: type 2, time 5629353, number 4, value 8520
Event: type 2, time 5629361, number 3, value 8081
Event: type 2, time 5629361, number 4, value 5857
Event: type 2, time 5629369, number 3, value 6938
Event: type 2, time 5629369, number 4, value -7845
Event: type 2, time 5629377, number 3, value 3505
```

**Comment by kozec** [comment]
That looks right... thing to consider is that deadzone is circular, so for example

```
Event: type 2, time 5629369, number 3, value 6938
Event: type 2, time 5629369, number 4, value -7845
```

means sqrt(6938^2+7845^2)= 10472 distance from center.

Is game you are trying to use doing some kind of rectangular deadzone?

**Comment by rcpoison** [comment]
My bad :) Didn't think of that. Does what it should now.

Thanks a lot!

**Comment by kozec** [comment]
Just small headup, you'll have to change that `JUMP` into `MINIMAL` with next release, but it should work without manually editing custom command.
