### ISSUE TITLE
Editing Custom Actions deletes some actions

### ISSUE THREAD

**Issue by Alzarath** [kozec/sc-controller#36]
When you make any change to the Custom Actions dialog, some actions seem to stop being registered. This appears to affect actions from the 'More...' drop-down, so _click_, _feedback_, and _deadzone_.

They will still show up in the Custom Actions input box, but they will stop showing up at the bottom command preview box. Once you click 'OK', they will not work and you'll have to add them again.

This can currently be worked around by switching from Custom Actions to another Action Type and back.

**Comment by kozec** [comment]
That's by design, entire "More" part should auto-hide itself when you switch to Custom Action.

You can write any combination of anything into Custom Action and I don't think it is possible to add stuff like sensitivity and feedback settings to that automatically.
