### ISSUE TITLE
Enable deadzone to trackpad click

### ISSUE THREAD

**Issue by DFOXpro** [kozec/sc-controller#362]
# What to do

Set in:
**Option A**
- any-trackpad: `click(deadzone(10000, dpad(button(Keys.KEY_W), button(Keys.KEY_X), button(Keys.KEY_A), button(Keys.KEY_D))))`
- same-trackpad-click: `deadzone(0, 9999, button(Keys.KEY_S))`

**Option B**
any-trackpad: `ring(
  click(button(Keys.KEY_1)),
  click(dpad(
  button(Keys.KEY_1),
  button(Keys.KEY_3),
  button(Keys.KEY_4),
  button(Keys.KEY_2)
))
)`

# What to spect

Withing the outCircle of the trackpad use like a clickable DPAD and
withing the innerCircle of the trackpad use like a clickable button

# What happen
With the deadzone approach the centerClick override the DPAD setting
and with the Ring settings the innerClick is disabled
In boot cases some settings are autoremoved (in the trackpadClick the deadzone is reset, and in the other the click action is reset)

# Who affect

- Gamers of complex cameras binding like simulation games or games with 5 sequential bindings like many RTS or FPS

# Notes

The specific use of this feature is to enable some kind of 5 directions clickable DPAD:
- Up
- Down
- Left
- Right
- **Center**

Also this can be a new kind of 5DPAD option in the trackpad list

**Comment by kozec** [comment]
Trackpad clicking is physical button, so making deadzone for it is kinda problem. But that Option B
 should work as you described, I'll check what's the problem.
