### ISSUE TITLE
[Regression][UI] Unable to delete unused profiles

### ISSUE THREAD

**Issue by DFOXpro** [kozec/sc-controller#363]
With the actual UI is no possible to delete unused profiles, time ago it was possible (but I don't remember where we do this).

**Comment by kozec** [comment]
Select profile -> right click on that selector thing -> delete -> "yes".

**Comment by DFOXpro** [comment]
this is like zero intuitive but works, thanks

**Comment by kozec** [comment]
I'm not sure if that's possible with combobox, but I can check on it.

**Comment by kozec** [comment]
After trying it few times, I'm fairly sure that gtk combo can't do that :(
