### ISSUE TITLE
Register New Controller button is always grayed out

### ISSUE THREAD

**Issue by Jimi-James** [kozec/sc-controller#364]
Just, always, no matter what. I successfully connected a DualShock 4 over USB (since Bluetooth isn't working yet for me with it), and I could configure it by right-clicking its icon in the top-left (though the brightness slider never did anything), but in the options menu, I have yet to ever see the Register New Controller button be not grayed out and unclickable. Even when I have the DS4 and the Steam controller connected at the same time, it's still grayed out. In fact, the box above it doesn't ever list any controllers, either. It's always empty. It's as if that entire section of the UI is just completely nonfunctional.

I'm on Arch Linux XFCE if that helps.

**Comment by kozec** [comment]
Sounds like you are missing python-evdev package, which is needed to work with non-steam controllers.

**Comment by Jimi-James** [comment]
I have python-evdev installed. 0.8.1

**Comment by kozec** [comment]
Ok, that's weird. Can you try running `python -c "import evdev; print evdev"` in terminal and copy-paste output?

That "add controller" button is disabled if above import fails.

**Comment by Jimi-James** [comment]
Huh. Why would this be happening? I'm trying to Google for this error in Arch and finding nothing.

```
$ python -c "import evdev; print evdev"
  File "<string>", line 1
    import evdev; print evdev
                            ^
SyntaxError: invalid syntax
$ python2 -c "import evdev; print evdev"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named evdev
```

**Comment by kozec** [comment]
Ah, Arch. Ok, repeat everything with "python2" instead of "python" in package names, then give my regards to only distro that keeps breaking like this :D

**Comment by Jimi-James** [comment]
Ah, I figured it out. It seems whoever maintains the AUR package for sc-controller made a dependency mistake, and I can report this to them. I had python-evdev installed, but not python2-devdev. It seems neither is a dependency of sc-controller at all. It seems like python2-evdev should at least be an optional dependency...

Anyway, I now can actually use this part of the UI. Problem solved.
