### ISSUE TITLE
Allow separate axis and full pull on triggers

### ISSUE THREAD

**Issue by toxicwolf** [kozec/sc-controller#37]
In the controller configurator in Steam I can set both axis output and full pull action on a single trigger. This allows me to, for example, bind LT to the LT axis (brake) and LT full pull to space (parking brake) in the American and Euro Truck Simulators.

Please, if it is possible, allow this in sc-controller (or someone tell me how if it is already possible to do this!), thanks.

**Comment by kozec** [comment]
It should be possible using custom action and writing `axis(Axes.ABS_Z) and button(Keys.KEY_SPACE)` there, but I never tried that combination.

But adding that as option to GUI may be good idea, I'll try to stuff it to that page.

**Comment by toxicwolf** [comment]
Yes that option seems to work as intended! :smiley: One minor issue is that the axis output doesn't reach 100% until you click the trigger down, which doesn't make as much sense when that full pull is mapped to another output.
Again, this may be easily changed using the Custom Action markup, but unfortunately I'm not familiar with it.

**Comment by kozec** [comment]
>  where the grave accent key is used as a dummy key (wasn't sure how to pass 'null' in as a parameter) as I saw this particular method overload when playing with the "Key or Button" page.

Yeah, there is currently no way to make trigger to work only when fully pressed, but it can be added.

> Another minor issue (with the successful configuration) is that the axis output doesn't reach 100% until you click the trigger down, which doesn't make as much sense when that full pull is mapped to another output.

And this could be done using sensitivity setting as well, except that one is not supported so far as well :D

**Comment by toxicwolf** [comment]
No worries, keep up the good work! :D

**Comment by kozec** [comment]
... and by so far I mean until now :)

Something like
`sens(1.3, axis(Axes.ABS_Z)) and button(Keys.KEY_GRAVE, Keys.KEY_SPACE)`
should work now, or rather with next release.

**Comment by toxicwolf** [comment]
Just tested these two commits, works great! :D

Just a note, when attempting to set _only_ a full press action on the trigger "Key or Button" page, it still currently sets it to `button(Keys.SOMETHING)`, but changing this to `button(None, Keys.SOMETHING)` in the "Custom Action" page and re-opening the window correctly displays the "Key or Button" page with just the full press action set.

**Comment by toxicwolf** [comment]
This suffers from the same issue as above, in that the UI actually generates `button(Keys.SOMETHING) and axis(axes.SOMETHING)` instead of `button(None, Keys.SOMETHING) and axis(axes.SOMETHING)` and therefore binds the key to the partial pull instead of the full pull.

Unlike above however, changing this in Custom Action and reopening the window and switching back to the Trigger or Axis page causes the full pull action field to incorrectly report no full pull action set.

**Comment by kozec** [comment]
Ah, yeah, I knew I forgot about something :(
