### ISSUE TITLE
Feature request: an option to choose which controller type to set bindings for

### ISSUE THREAD

**Issue by Jimi-James** [kozec/sc-controller#372]
Maybe I just haven't figured out how yet, but it seems the only way to set bindings for a DualShock 4 (besides memorizing which Steam controller buttons, pads, and sticks correspond to which DS4 ones in a profile file) is to have one connected to a running daemon while I'm setting them?

**Comment by kozec** [comment]
Well, yes, that's basically the idea. I mean, I can add something like context menu to switch images, but only difference is ABXY / XO□△...

**Comment by Jimi-James** [comment]
I think the context menu to switch images would help. Yeah, most of it is obvious, such as ABXY/XO□△, but some not so obvious. For example, of the top of my head right now, I have no idea what corresponds to the DS4's middle touchpad on the SC, or the SC's grip buttons on the DS4.

**Comment by kozec** [comment]
> I have no idea what corresponds to the DS4's middle touchpad on the SC, or the SC's grip buttons on the DS4.

Nothing and nothing :) But changing image is not going to help with button that is physically missing.

**Comment by Jimi-James** [comment]
Oh, I see. In that case, maybe it could change the image *and* which buttons are displayed?
