### ISSUE TITLE
Feature request: control Menu with left D-pad buttons, rather than as a touchpad

### ISSUE THREAD

**Issue by Jimi-James** [kozec/sc-controller#373]
I'm not a fan of navigating menus with an analog stick. I end up going diagonal when I didn't mean to half the time, and it's just a chore to actually get to the menu item I want. When I set the Menu in sc-controller to be controlled by the left pad, I expected it to be a D-pad situation: up, down, left, right. The touchpad situation I got instead is fine, but only for Steam controllers. It's definitely unuseable on a DS4, where the left D-pad is not a touchpad.

**Comment by kozec** [comment]
Here you are.

I've also added option to set default menu controls per controller, which may be useful in your case. You can access it by right-clicking on that small controller icon in main window and selecting "Configure Controller"
