### ISSUE TITLE
Cant start sc-controller

### ISSUE THREAD

**Issue by rinalds14** [kozec/sc-controller#375]
when i run in terminal command ./run.sh this appears:

Traceback (most recent call last):
  File "scripts/sc-controller", line 14, in <module>
    gi.require_version('Rsvg', '2.0') 
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available

**Comment by rinalds14** [comment]
nvm fixed it

**Comment by kozec** [comment]
[Yeah, you most likely had gir1.2-rsvg-2.0 package missing :)](https://xkcd.com/979/)

**Comment by rinalds14** [comment]
yep
