### ISSUE TITLE
I don't see a way to map keyboard to gyro's yaw?  

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#377]
Like if I wanted to map A & D for left and right to steer a vehicle in a game, could it be done?  It would seem like the logical thing to do would be to add a "Yaw" entry to the "Tilt" section (as beautifully rendered below by yours truly).  If it's not possible to enter roll and yaw settings at the same time, then grey one out when the other is chosen.

For example, one could move left/right on Yaw:
`tilt(  button(Keys.KEY_W),  button(Keys.KEY_S),  none,  none,  button(Keys.KEY_A), button(Keys.KEY_D))`

Or on Roll:
`tilt(  button(Keys.KEY_W),  button(Keys.KEY_S), button(Keys.KEY_A), button(Keys.KEY_D, none,  none))`

![image](https://user-images.githubusercontent.com/23580979/40880622-7686a530-6682-11e8-95da-65a1288eb55f.png)

**Comment by kozec** [comment]
Problem is that is not tilting :)

Or, actual problem, adding another row there would not fit to screen :( 

I'll check if it can be at least expressed and done ignoring GUI and think how to fit it later.

**Comment by LinuxJoeUser** [comment]
> Problem is that is not tilting :)

I thought about that before posting and double checked [the definition](https://en.oxforddictionaries.com/definition/tilt) and we can use the word "tilt" to describe this action, no problem.  It's just being tilted from another axis is all. ;)

> Or, actual problem, adding another row there would not fit to screen

Yeah, I figured that might be an issue, but I just went with it because it was the easiest way to show what I was talking about.  The only idea that occurs to me is to make the graphics a bit smaller and move them closer together---but that *might* make everything look crowded.

All the same, I'm glad you see the same need I do!  :)

**Comment by kozec** [comment]
Soo... I've added the thing to GUI, but I'm not sure how useful it is, as I have conceptual problem determining where "forward" is.

![img](https://user-images.githubusercontent.com/1282500/41731915-f5bb6f82-757f-11e8-9793-2340e3a1ab6d.png)

I may have to check how (and if) is this done by Steam.

**Comment by kozec** [comment]
Scrap what I said before, as I was just reminded in #386, there already is way to set where "forward" is. I'll be adding GUI for it.
