### ISSUE TITLE
Tray icon disappearing

### ISSUE THREAD

**Issue by HamishTPB** [kozec/sc-controller#378]
![image](https://user-images.githubusercontent.com/27439242/40943750-3203ae52-684a-11e8-9aa9-59b3e1a1cdb4.png)

After a little while on my system (i3wm) the system tray icon disappears. If I disable emulation it comes back. Not a huge issue, just annoying to not be able to see the emulation status at a glance.

**Comment by kozec** [comment]
Is it that empty slot? What are you using to display tray?

**Comment by HamishTPB** [comment]
Yes, that is the space where the icon reappears when you change the emulation state. The tray is being displayed by i3 itself with the bottom bar rendered using 'i3status' (the default).

**Comment by kozec** [comment]
> I will try to keep an eye on it and see when it disappears to see if it coincides with anything else happening on the system.

Try running GUI in terminal while doing it (`sc-controller -d`), it may display error message with icon file that it fails to load.

**Comment by kozec** [comment]
Just small status report, I've tried to replicate this over weekend and found myself unable to get i3 to display any status icons at all :(

**Comment by HamishTPB** [comment]
The whole time I tried running it from the terminal I have had no problems so far. The computer is taunting me. It still happens from time to time when I restart and it runs without me thinking about it. I will try again this week to see if I can spot anything using the terminal method.

**Comment by legluondunet** [comment]
Same issue on Ubuntu 18.04: icon is not visible in the system tray icon of gnome 3 vanilla.
![capture d ecran de 2018-08-15 00-01-46](https://user-images.githubusercontent.com/325405/44300819-4e65d900-a30d-11e8-8e97-91a35a0f36e6.jpeg)
