### ISSUE TITLE
Registering X360-type controller results in mis-mapped/non-functional inputs.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#379]
I discovered this only because I was wanting to recommend SCC to someone on Reddit who was trying to get some X360 knock-off working.  

I tested both a X360-for-PC wireless controller and a Madkatz X360 wired controller.  Both were properly identified, and after choosing "Two sticks, asymmetrical (x360 pad)" and pressing "Next" SCC shows nothing as being assigned in "USB HID (recommended):

![sccx360issue](https://user-images.githubusercontent.com/23580979/41202558-7d076888-6c98-11e8-8e1a-9f8ae82614ab.png)

None of the buttons/triggers/sticks register as detected by SCC in the gui, and although I can select inputs with the mouse, nothing is detected from the controller.

Choosing "evdev" results in SCC *reporting* all inputs are assigned but nothing flashes blue when controller button etc., is pressed.  

![image](https://user-images.githubusercontent.com/23580979/41203427-b88e7fde-6ca4-11e8-811e-020121fde8d8.png)

Clicking on the gui opens the or "Press a button..." or "Change mapping for Pressing button" etc., but nothing changes.

The Madkatz controller begins in "evdev" instead of "USB HID" but is otherwise the same.

The "Display Raw Data" seems to be for a Steam controller and not the controller being registered, but maybe this is expected?

![image](https://user-images.githubusercontent.com/23580979/41203475-56257b26-6ca5-11e8-819b-4e62dcb98ee2.png)

**Comment by kozec** [comment]
"Display Raw Data" shows how will be controller you are setting up mapped to steam controller, so yeah, that's expected.

Problem here seems to be that HID is always preferred way to access controller if user has rights needed for that, as it should work with everything and allows SCC to take over device completely, so games are not seeing two controllers. But xbox controller is not "everything", it's really weird piece of broken plastic that doesn't support HID :(

Best solution would be add some kind of blacklist, which would say "don't use HID for these, ever". I'll check if I can replicate this with my Logitech pad that can emulate x360 controller, but it would help if you could give me USB IDs for those you were talking about.

**Comment by LinuxJoeUser** [comment]
Sure thing, from `lsusb`
`Bus 003 Device 010: ID 045e:0719 Microsoft Corp. Xbox 360 Wireless Adapter`
and
`Bus 003 Device 011: ID 0738:4716 Mad Catz, Inc.`
