### ISSUE TITLE
On-Screen Keyboard Improvements

### ISSUE THREAD

**Issue by Alzarath** [kozec/sc-controller#38]
I'd like some visual feedback (such as flashing) when pressing a key. Being able to use the left and right trigger to press keys is also preferred to clicking the pads.

It feels like you need to be on the very edge of the pad to be able to reach some keys and it hurts fluidity. This applies to most of the characters on the edges. The numbers, for example, can be reached without too much trouble, but the circle indicators bottom out around the middle of the the keys.

Some characters can barely be reached at all, such as all of the characters on the right and bottom. Some really *can't* be reached, such as the **[**, **'** and **=** keys.

Somehow informing users that X, Y, Start, or Select can be used to close the keyboard seems necessary.

Allowing users to customize the colors of the keys/etc and allowing an alpha on the keyboard as a whole would be nice.

**Comment by kozec** [comment]
> Allowing users to customize the colors of the keys/etc and allowing an alpha on the keyboard as a whole would be nice.

I'm making configuration dialog that will include colors, but alpha may be tricky, because it depends on window manager support. It will include button configuration as well, as requested in #33 

> Some characters can barely be reached at all, such as all of the characters on the right and bottom. Some really can't be reached, such as the [, ' and = keys.

That's weird, I can reach them on my controller. Are you saying that you can't reach bottom row at all?

**Comment by Alzarath** [comment]
> That's weird, I can reach them on my controller. Are you saying that you can't reach bottom row at all?

I can _barely_ reach the ones that I didn't list. Anything I listed I can't reach at all, no matter how far I reach on the pad.

**Comment by kozec** [comment]
Ok, I moved reachable area a little. Are you able to test git version? If not, you can just replace `/usr/share/scc/images/keyboard.svg` with [one from git repo](https://github.com/kozec/sc-controller/blob/master/images/keyboard.svg)

**Comment by Alzarath** [comment]
Sorry for the delay. Yes, I'm able to reach all of the keys now. It'd still be nice if I could reach all of the outter keys a bit more comfortably, though.

Below is an approximation of how far I can reach in each direction when my thumb is as far to the edge of the pad as they can get. I'd like it if all of the edges were about where I can reach on the left side.
![160610064810](https://cloud.githubusercontent.com/assets/1994142/15962192/6420f128-2ed7-11e6-891a-65c0fd662ee8.png)

**Comment by kozec** [comment]
You should be able to reach this far:

![keyboard-v svg](https://cloud.githubusercontent.com/assets/1282500/15962345/ceb5c544-2f0a-11e6-9938-245f43b1d8fc.png)

that's same image as OSD Keyboard uses, but with areas that are used as limits visible.

My question is, what would be point of being able to reach right side of those buttons? It shouldn't matter if you are pressing left or right side.

I'm asking mainly because extending reachable area lowers precision.

**Comment by Alzarath** [comment]
The right side is somewhat acceptable. It's mostly the numbers and the lower area. Needing to reach for them at nearly the very edges of the pad just feels uncomfortable.

**Comment by Alzarath** [comment]
Loving the sensitivity options, 1.2 is quite comfortable for me. Thanks a bunch, @kozec.

One thing, though. The key selection seems to be centered on the left of the circular nubs instead of in the center of them. The harm of this can easily be demonstrated by the resting position of the left nub where, while over 90% of the nub is over the 'd' key, the left side of it is touching 's', causing it to input that instead.

**Comment by kozec** [comment]
Yep, that's because I can't count to 1.0 :)

Should be OK now.
