### ISSUE TITLE
[idea] Use a best fit/sequence alignment algorithm to optionally make gestures easier to use

### ISSUE THREAD

**Issue by DarkArc** [kozec/sc-controller#380]
It should be possible to perform sequence alignment and compare the received motions, with the stored gestures for the current context, then match if off by < "X" score, where "X" is the maximum distance between the given input and the gesture.

For instance if my gesture is up and I give up up, or up left, and there's no exact match for either up left or up up, given an "X" > 0, consider this an up gesture.

Might work on this myself and PR it at some point, just started using this today though, and thought it would be a useful addition to this already awesome software :)

**Comment by kozec** [comment]
I'm not sure if I'd know how to implement it, but I definitely like the idea :)
