### ISSUE TITLE
[FEATURE REQUEST] Implement 3D Mouse Output for SC gyroscope

### ISSUE THREAD

**Issue by Patola** [kozec/sc-controller#381]
Ok... This will be somewhat convoluted to explain, but here is the thing: sc-controller is so powerful and complete that I use it with the steam controller to make 3D modelling in FreeCAD and (sometimes) in Blender.

However, there is a device called a "space navigator" from 3dconnexion that is a "3D Mouse". It generates its own protocol of output, with 3 translation axes and 3 rotation axes. Both FreeCAD and Blender support it. When you use this device, it moves the 3D viewport accordingly, you don't even have to have it in focus.

It would be great if this functionality could be added to sc-controller, so that we could map the gyroscope from the steam controller to the rotation outputs of space navigator.

The driver for the device is free and open-source, implemented through "spacenavd". And both FreeCAD and Blender have python+C++ code to interact with it. I don't think it would be too difficult to use this code to find a way to output the same information as the 3D mouse.

I understand that this is a long shot and it is a feature that is not very useful to many people, since the device is somewhat expensive. However it has been making inroads and even 3D slicing software like Cura have open bug reports to implement 3D viewing using its API. 

I would of course be a volunteer for testing any code, or even help coding if I can get into the protocol.

**Comment by kozec** [comment]
I'm playing with it a little and I'm wondering...

How do you imagine those translation axes? Steam Controller has just  gyros and doesn't know anything about its own position in space, so it can do some kind of touchpad-to-2D space emulation at best.

**Comment by Patola** [comment]
"You can configure SCC to emulate 6-axis device in ~/.config/scc/config.json, key output. You can change device name and USB ids there as well, so spacenavd should pick it up not knowing it's virtual device."

I will try to see if it works.

"How do you imagine those translation axes? Steam Controller has just gyros and doesn't know anything about its own position in space, so it can do some kind of touchpad-to-2D space emulation at best."

I would just map the rotational axes. The translation axes are very comfortable mapped to the stick axes (XZ) and the emulated mouse wheel (zoom in/out - Y axis).

**Comment by Patola** [comment]
These are the space navigator device entries in dmesg:

```
[   11.828447] usb 3-2.3: Product: SpaceNavigator
[   11.828448] usb 3-2.3: Manufacturer: 3Dconnexion
[   11.849100] input: 3Dconnexion SpaceNavigator as /devices/pci0000:00/0000:00:1c.0/0000:02:00.0/usb3/3-2/3-2.3/3-2.3:1.0/0003:046D:C626.0004/input/input19
[   11.849183] logitech 0003:046D:C626.0004: input,hidraw3: USB HID v1.11 Multi-Axis Controller [3Dconnexion SpaceNavigator] on usb-0000:02:00.0-2.3/input0
```

Just as reference for the tests.
