### ISSUE TITLE
SC Analog stick should be available in the list of Gyro (De)Activator inputs

### ISSUE THREAD

**Issue by RomanHargrave** [kozec/sc-controller#385]
What:

The gyro configuration allows for the selection of a gyro en- or disable button/pad. For the same reasoning behind the pads being able to alter gyro state, the stick should be able to do so (when outside of a deadzone, obviously).

Why:

Situations where you want the gyro and stick to share the same output (e.g. steering wheel). Suppose you need to recenter yourself without causing a severe accident ingame, or recenter your vehicle without doing something physically impossible.

Footnote:

Does SC-Controllers gyro support seem clunky/lackluster? It seems to skew towards being off-center and the configuration dialog is very buggy, it would seem. There is no way to set a calibration/skew angle for the gyro axes as there is with the pads.

**Comment by kozec** [comment]
> Does SC-Controllers gyro support seem clunky/lackluster? It seems to skew towards being off-center and the configuration dialog is very buggy, it would seem.

It shouldn't, neither of that, so if you notice something behaving in weird way, please, let me know.

> There is no way to set a calibration/skew angle for the gyro axes as there is with the pads.

Reasoning for that is that while how's "line through center of pad" rotated depends on how is controller being held, center position of gyros is pretty objective and same for everyone. Plus, I'm not sure if it's possible to do anything beyond recentering.

**Comment by RomanHargrave** [comment]
@kozec this is closed but was the issue addressed:

> The gyro configuration allows for the selection of a gyro en- or disable button/pad. For the same reasoning behind the pads being able to alter gyro state, the stick should be able to do so (when outside of a deadzone, obviously).
