### ISSUE TITLE
Gyro needs zero-out/calibration support

### ISSUE THREAD

**Issue by RomanHargrave** [kozec/sc-controller#386]
I've got my gyro set up as an absolute output, and would like to be able to play games while facing the direction that my SC or SCC has decided is 0. 

Having the ability to zero the gyroscope, while in use - as a shortcut, would be appreciated.

**Comment by kozec** [comment]
Funny thing is that [this already exists](https://github.com/kozec/sc-controller/wiki/Custom-Action-Examples-and-Explanations#-resetgyro), it's just so well hidden that even I forgot about it.

I'll add it to GUI somewhere.

> Having the ability to zero the gyroscope, while in use - as a shortcut, would be appreciated.

What's "-" here?

**Comment by RomanHargrave** [comment]
> What's "-" here?
 part of the sentence.

but huh. guess that solves this problem.

**Comment by LinuxJoeUser** [comment]
I know the issue's closed, but being late to a party never stopped me from having a drink.  I added `scc-daemon restart` and `resetgyro()` to my default menu.  Infinitely handy as both have allowed me to fix things in the middle of a game without having to leave. ;)
