### ISSUE TITLE
AppImage on Kubuntu 16.04.4

### ISSUE THREAD

**Issue by alexbrrsclnt** [kozec/sc-controller#388]
When I run the appimage file I get this error, is there some dependencie that I'm missing?

> alex@nina:~/Descargas
|_$ ./sc-controller-0.4.3.glibc-x86_64.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_sc-conEVclwp/usr/bin/sc-controller", line 12, in <module>
    gi.require_version('Gtk', '3.0') 
  File "/tmp/.mount_sc-conEVclwp/usr/lib/python2.7/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

**Comment by alexbrrsclnt** [comment]
Just tried same file on my work laptop with KDE Neon User Edition LTS (ubuntu 16.04) and works well. Don't know if there is something that is needed to install in kubuntu

**Comment by kozec** [comment]
It misses GTK bindings, what's weird, as I'm almost sure I've added them to appimage.

**Comment by kozec** [comment]
I've tried to add GTK directly to appimage, but that just breaks anywhere but on most recent distros, so this doesn't looks solvable in easy way. What you have to do is to install GTK package manually.
