### ISSUE TITLE
Gyro mouse not functioning after July 8th update

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#391]
Noticed this on the 9th, all of my profiles which have a gyro mouse have ceased moving the cursor.  For example `mode(RPADTOUCH, sens(0.5, -0.5, 0.5, mouse(ROLL)), None)` fails to move the cursor on the screen.

I've tried two or three profiles, all with the same result.  I've also tried a clean new profile both with the default Right Pad Pressed and with Always Active, neither worked. :(

I like the UI update, btw. ;)

**Comment by LinuxJoeUser** [comment]
Update:  I'm able to get gyro working in SCC by starting the Steam client before SCC, then when SCC takes over from the Steam client, gyro works with SCC and the Steam client can be exited.

**Comment by kozec** [comment]
I believe we just experienced what's called "regression" :(
