### ISSUE TITLE
Get the right pad to act like Steam's joystick camera

### ISSUE THREAD

**Issue by LiamDawe** [kozec/sc-controller#392]
One issue I've come across with SC Controller, is that the right pad can't hold the position of where your thumb is.

On Steam directly, you can overcome it by setting the right pad to joystick camera.

Is there a way like that, to get it to hold the position until you take your thumb off? Lot's of game need to detect that you're holding that position, which it doesn't seem SC Controller does in many games.

**Comment by kozec** [comment]
Sorry, but I probably don't understand. What do you mean by "holding position of where your thumb is?"

**Comment by LiamDawe** [comment]
Well, the current behaviour seems to act like you've touched it and then removed your thumb. Ideally, we need a way to make it stick to that position when your thumb is there, like an actual stick would be.

In twin-stick shooters for example, then use the held position for continuous firing in the direction of your right thumb.

**Comment by kozec** [comment]
Okay, that doesn't sounds like what it is supposed to do. What profile are you using on what version?

**Comment by FlyingWombat** [comment]
Is this similar to #390 ?

**Comment by kozec** [comment]
I believe this should be already fixed. If not, feel free to reopen or create new issue.
