### ISSUE TITLE
Allow friction on circular mouse wheel?  [Enhancement]

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#398]
Would it be possible to allow the friction setting to be applied to the circular (and maybe other?) mouse wheel output?  It comes in super-handy when scrolling through *long* lists.  Just a thought.

**Comment by kozec** [comment]
Yes, in theory and in non-gui way, otherwise I'd have to find place for additional checkboxes. :)

**Comment by kozec** [comment]
So, with above, you can do

```
feedback(LEFT, 4096, circular(ball(0.5, mouse(Rels.REL_WHEEL))))
```

and get wheel that just rolls and rolls and rolls and rolls and then stops.

**Comment by LinuxJoeUser** [comment]
Thanks for the custom action.  Regarding creating another checkbox, instead of creating a new one, move the "Friction" slider into the "Sensitivity" area.  It makes sense there, because it is the sensitivity of the friction that's being adjusted, and there's *almost* enough room as it is.  Here's a mock-up.  I hope you like it.

![sccfrictionmove](https://user-images.githubusercontent.com/23580979/43004417-b5a972e2-8bfd-11e8-9c34-5cd4ce8fee39.png)

**Comment by kozec** [comment]
That's little too hidden I'm afraid. But I'm trying to reorganize "Basics" to fit it there, as that one is visible by default.

**Comment by LinuxJoeUser** [comment]
Sounds good and makes sense.  I'm looking forward to what you come up with :)

**Comment by LinuxJoeUser** [comment]
A few observations and suggestions about the solution:

The "Setup or disable Trackball Mode" link doesn't seem to do anything (and to my eye, weirdly out of place).  I think it would be better to use the same sort of "Enable" box like the ones used everywhere in the GUI, like in the picture below, with a simple checkbox for the mode right above the Friction slider:

![sccnewfrictionred](https://user-images.githubusercontent.com/23580979/43358195-a949d5a0-925b-11e8-812e-211198520bfa.png)

When Trackball mode is disabled, then the Friction slider becomes greyed out.  Otherwise the slider operates as previously.

This should be just like everything else in the "More..." area, greyed out for some outputs, but available for others.

**Comment by kozec** [comment]
That link is supposed to expand "More..." area and switch to page with trackball setting. So it does nothing if already have it visible. But yeah, I should probably let that part flash red or something, but I kinda understand how not obvious it is now when I'm talking about it.

> This should be just like everything else in the "More..." area, greyed out for some outputs, but available for others.

It works like that, you should be able to see it better if you scroll through items in "Output" combo.

**Comment by kozec** [comment]
> And as a regular user of zero friction, it's a huge difference between the ease of slapping the slider all the way to the left, to zero (easy) and trying to set it to .001 (grrrrrrrrrr). ;)

Okay, okay, I understand, have your combobox :)

**Comment by LinuxJoeUser** [comment]
Thank youuuuuuuuu :)
