### ISSUE TITLE
Issues with Building on latest Fedora versions

### ISSUE THREAD

**Issue by DastardlyVandal** [kozec/sc-controller#40]
I found out that trying to build this doesn't currently work on Fedora 23 or 24. The build scripts try searching for the python libraries, but it isn't able to find them. I ran into this issue when using the steamcontroller package this is based off of.

[Here](https://github.com/ynsta/steamcontroller/issues/36) you can find my mess of an issue report I posted over there, where I give the details on how to make the Stand Alone Steam Controller Driver work on Fedora 23+

The main issue is the build script is looking for a library called either lpython2.7 or lpython3, when in Fedora and other RedHat based distros, the naming convention is instead libpython2.7.so and libpython3.so respectively.

Would it be possible to address the build scripts here as well to provide a more out of the box experience with less fiddling involved?

Great work on this, by the way. I'm thoroughly enjoying this project. :)

**Comment by kozec** [comment]
> The main issue is the build script is looking for a library called either lpython2.7 or lpython3

-**l**anything instructs gcc to use **lib**anything.so on any distro, so that shouldn't be a problem, unless there is something seriously screwed on Fedora. I should have VM with it somewhere, so I'll check whats happening.

**Comment by kozec** [comment]
Ok, [this is output on fresh Fedora 24 install](http://pastebin.com/QcF0ApnV) with `git`, `python`, `python-devel` and `redhat-rpm-config` installed.

I can reproduce your error without `python-devel` package, so that's most likely what you are missing.
