### ISSUE TITLE
Cannot find input.h on android?

### ISSUE THREAD

**Issue by PGFMod** [kozec/sc-controller#403]
When trying to run the file setup.py with parameter "build": it gives me this:
d855:/ $ su
d855:/ # python.sh /sdcard/sc/setup.py build
Traceback (most recent call last):
  File "/sdcard/sc/setup.py", line 3, in <module>
    from scc.constants import DAEMON_VERSION
  File "/storage/emulated/0/sc/scc/constants.py", line 26, in <module>
    from scc.uinput import Axes, Keys
  File "/storage/emulated/0/sc/scc/uinput.py", line 43, in <module>
    raise RuntimeError("Cannot find input.h")
RuntimeError: Cannot find input.h
1|d855:/ #
I don't know if this should even work with android, but if it would have a chance of working I would be very nice. Thank you for your awesome work!

**Comment by KiitoX** [comment]
So yeah, this is shortly addressed in #365. There is a very work in progress branch for android support, but it is nowhere near completion. 

> Android is little bigger issue that I thought originally, pretty-much nothing SCC has right now works there. Different input system, different input emulation, GTK can't work there, python can't work there...

So no, currently it does not support android in any way.

**Comment by kozec** [comment]
You can use [this one from Windows branch](https://github.com/kozec/sc-controller/blob/windows/scc/platform/windows/input.h), but unless you have very special Android device - rooted and uinput module - you are probably not going to get far.
