### ISSUE TITLE
Is there an easy way to install this with dependencies for Raspbian Stretch? 

### ISSUE THREAD

**Issue by Pyroseza** [kozec/sc-controller#405]

**Comment by Pyroseza** [comment]
It looks like I have it installed but it does not seem to work, I do get an error message that /dev/uinput has the wrong perms. when I say fix it it runs but still does not work, If I change the perms manually that also does not fix it. And the perms somehow get reset to crw------- after rebooting...

**Comment by kozec** [comment]
> And the perms somehow get reset to crw------- after rebooting

That's pretty normal, there is [eudev rule](https://github.com/kozec/sc-controller/blob/master/scripts/90-sc-controller.rules) that should give rights to it.

In what way it doesn't work after fixing permissions?

**Comment by Pyroseza** [comment]
As in when I launch the program I can’t see it picking anything up. Is there a log of some sort that I can enable or make more verbose so I can dig around and look for the problem?

**Comment by kozec** [comment]
> Is there a log of some sort that I can enable or make more verbose so I can dig around and look for the problem?

Make sure there is no "scc-_anything_" process running and start `scc-daemon debug`. That's part that does emulation and when steam controller is not recognized, issue is usually with it.

GUI has debug output as well, with `sc-controller -d`

**Comment by Pyroseza** [comment]
thanks, I'll test that and let you know. am I right in assuming when I have the GUI open I should be able to see what I am pressing? 

Also can I use this sc-controller in my scripts to control my robot?

**Comment by kozec** [comment]
> am I right in assuming when I have the GUI open I should be able to see what I am pressing?

You have to enable that in options, it's "enable input test mode" on last tab.

> Also can I use this sc-controller in my scripts to control my robot?

No idea, depends on what exactly you are trying to do :)

But if you are turning PI into single-purpose device that translates Steam Controller inputs to _something_, check [original SteamController](https://github.com/ynsta/steamcontroller) project. It's much simpler and thus better suited to build on. You can just [grab this file](https://github.com/ynsta/steamcontroller/blob/master/scripts/sc-callbacks.py) and add code into callbacks.

**Comment by Pyroseza** [comment]
I’d like something that I can import into my scripts so if I use the analog stick on the controller then I can pick up the input in my scripts and calculate what to output to my motors. I’ve already done this with Ynsta’s sc-controller lib. The only problem is that my steam controller’s adapter broke so I can’t use Ynsta’s lib anymore. I’ve now updated the firmware and switched over to bluetooth and the only lib I can find on github is yours...

**Comment by kozec** [comment]
Well, yeah, I don't think anyone else implemented BT protocol yet.

Although running as library is not what it is sc-controller designed for, but BT driver has [__main__ method](https://github.com/kozec/sc-controller/blob/master/scc/drivers/sc_by_bt.py#L326) that, when it is started as script, simply dumps inputs.

Or you can hijack socket used between GUI and daemon, send [lock command](https://github.com/kozec/sc-controller/blob/master/docs/protocol.md#lock-button1-button2) (with `Lock: STICK` in your case) and then read events using that.

**Comment by Pyroseza** [comment]
thanks, I'll test that and let you know. am I right in assuming when I have the GUI open I should be able to see what I am pressing?

**Comment by kozec** [comment]
Not by default, you have to go to settings and enable "input test mode" on last page.
