### ISSUE TITLE
Hold modeshift needs to be pressed simultaneously

### ISSUE THREAD

**Issue by vinipsmaker** [kozec/sc-controller#406]
Pretty much, it only works reliably if combination is with left/right touch.

Otherwise I have to guess the interval window when I can press the second button.

I cannot press the second button __after__ holding the modeshift button for enough time. I have to press it in the exact time.

Is this the case for every release? I'm using the `git` version and I hope to be a problem of some recent commit. I can attach my controller configuration here if you think it is useful to understand the problem.

**Comment by kozec** [comment]
>  I can attach my controller configuration here if you think it is useful to understand the problem.

Please, do, as I'm not really sure what are you trying to do. Hold modeshift is supposed to activate when you hold button for a while, 0.5s by default.

**Comment by vinipsmaker** [comment]
> Please, do

[Desktop (mode 1).txt](https://github.com/kozec/sc-controller/files/2272134/Desktop.mode.1.txt)

> as I'm not really sure what are you trying to do

My use case is to imitate [Steam Button Chord configuration](https://steamcommunity.com/games/353370/announcements/detail/892098092693507492). I want to hold the Steam Button and, while the buttom is pressed, the keybindings are different.

What SC-Controller forces me to do is to press and hold the Steam Button and then I need to have a good sense of timing (like in music) and press the second button about the time the hold activates (as if I have to press them simultaneously... except that one of the buttons expect a “hold”, not a “press”).

**Comment by kozec** [comment]
I think you are setting it wrong way around.

In SCC, modeshift means "When I press this button, do A, but if I do that _while Steam button is pressed_, do B".

So if you want have pressing stick to do Play/Pause, you configure modeshift on stick, adding normal behavior to "Pressed alone" and Play/Pause button when Steam (C) button is pressed.

**Comment by vinipsmaker** [comment]
It seems I won't have much luck to do what I want :(

![2018-08-13-073930_1366x768_scrot](https://user-images.githubusercontent.com/865914/44027327-72cb2268-9ecc-11e8-9ece-bc6da76b7f7e.png)

Leaving that aside. Can you TL;DR overview how the translation happen?

I assume there's Python code reading the device representing the controller and then how do you generate window events? XTEST? Is there any other major step that should be taken?

**Comment by vinipsmaker** [comment]
Wait. I think I got it. Issue can be closed. Thanks for the patience and help.

**Comment by kozec** [comment]
Np :D

> how do you generate window events? XTEST? Is there any other major step that should be taken?

XTest would be good approach as well, but SCC uses uinput, kernel module that allows creating virtual input devices in userspace. It has nice advantage of working with everything, from VT consoles to wayland.
