### ISSUE TITLE
Kernel driver for Steam Controller

### ISSUE THREAD

**Issue by Vintodrimmer** [kozec/sc-controller#407]
Good day,

There is now a driver for Steam Controller in the kernel itself (from version 4.18).
Will you look into utilizing it or is it worse feature-wise than the userspace one?
As I understand it, one wouldn't need extra uinput rules with native one?

**Comment by kozec** [comment]
I'll check what's possible when my distro upgrades to 4.18. From my understanding it could be possible to replace half of SCC with reading from /dev/hidraw. Question is whether it would help with anything, as that part is actually quite stable.
