### ISSUE TITLE
move and rename config files toward a more intuitive/standard way

### ISSUE THREAD

**Issue by legluondunet** [kozec/sc-controller#409]
Hello,
today sc-controller hangs several times. I didn't know why but I would like to search for the config files to delete them.
I searched for a folder named sc-controller in my .config folder, where all my apps config are stored, and I didn't find it.
After a search in your issues, I did read that the config files are stored directly in the home directory, in a folder named "scc".
Could it be possible, to suit the Linux standard and for a more intuitive way to store your config files in the:
/home/your_home_name/.config 
folder? And to rename scc to sc-controller?

Regards.

**Comment by kozec** [comment]
Weird thing is that configuration folder _should_ be located in /home/your_home_name/.config, unless you have XDG_CONFIG_HOME set to something else. What does `set|grep XDG_CONFIG` say in your terminal?

Renaming it is probably going to break stuff, but I'll take it into consideration.

**Comment by legluondunet** [comment]
This is the result of your command:

```
$ set|grep XDG_CONFIG
XDG_CONFIG_DIRS=/etc/xdg/xdg-gnome-xorg:/etc/xdg
```

**Comment by legluondunet** [comment]
Perhaps Ubuntu does not set the variable XDG_CONFIG_HOME as preconisation Freedesktop.

Here:
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables
you can read:
$XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 

The workaround could be to test if the variable "XDG_CONFIG_HOME" is set, if not set ask sc-controller to use HOME/USERNAME/.config folder?
