### ISSUE TITLE
On-screen keyboard has stopped working

### ISSUE THREAD

**Issue by parkerlreed** [kozec/sc-controller#41]
Pulled latest git. Whenever I activate the keyboard, the touchpads continue to act as mouse and scrolling.

**Comment by kozec** [comment]
Try one after that :D

**Comment by parkerlreed** [comment]
Still doing it https://my.mixtape.moe/fzmtbq.mp4

**Comment by kozec** [comment]
Weird... I mean, there was such bug, but I fixed it right away.

How are you installing? -git package or setup.py install?

**Comment by parkerlreed** [comment]
-git package https://aur.archlinux.org/packages/sc-controller-git/

**Comment by parkerlreed** [comment]
Working now, thanks!
