### ISSUE TITLE
Darksiders/Dark Souls spinning camera bug

### ISSUE THREAD

**Issue by legluondunet** [kozec/sc-controller#410]
Hello,
as you can see in this video:
https://youtu.be/eLFmqih2S3A?t=22s
Dark Souls have a controller bug: the camera spinning around the character.
Darksiders has the same bug.
A workaround is to use x360ce.
I would like to know if your software could help me to correct this bug in place of x360ce.

**Comment by parkerlreed** [comment]
sc-controller isn't for Windows https://github.com/kozec/sc-controller/issues/215

**Comment by legluondunet** [comment]
Oh sorry I forgot to mention my config:
Ubuntu 18.04
Nvidia
I'm using Wine to play Darksiders

**Comment by kozec** [comment]
> I'm using Wine
In that case, this is mainly issue with game expecting xbox controller and doing weird nonsense when "normal" gamepad emulated by wine is connected.

What you are describing is possible, just really clunky to do and probably bad idea :) Turn off everything sc-controller related, open ~/.config/scc/config.json and check `output` node - [it's "documented" here](https://github.com/kozec/sc-controller/blob/master/scc/config.py#L55). You should be able to change those values so they matches what game is expecting, especially those two (0,255) may be reason spinning camera.

But using x360ce or my [dumbxinputemu](https://github.com/kozec/dumbxinputemu/) is probably faster :)

**Comment by Ryochan7** [comment]
ds4drv suffers from a similar problem and I documented that problem on their issue tracker. It really is an issue with the game and its DirectInput support; similar problems can be experienced on Windows if you aren't using an Xbox 360 controller.

**Comment by legluondunet** [comment]
@kozec I will get a try with tweaking config.json.
I already tried dumbxinputemu and it  does well his job: it makes my gamepad visible by the game as it was a true xbox360 gamepad. But I can not modify the way it emulates it to correct the game bug.

**Comment by legluondunet** [comment]
I don't know what they had changed in Wine 3.14 but no more spinning camera in Dark Souls prepare to die or Darksiders. I close this ticket that has no more reason to be. Thanks.
