### ISSUE TITLE
LB & RB swapped when connected over Bluetooth

### ISSUE THREAD

**Issue by simonics** [kozec/sc-controller#411]
On my controller at least, when using Bluetooth, RB & LB buttons are reversed. Mapping is correct over cable, and standard wireless dongle.

https://github.com/kozec/sc-controller/blob/5f0821a147bf17622c976d8e6642ab3eca7afb9d/scc/drivers/sc_by_bt.c#L82-L83

Thanks for the hard work!

**Comment by kozec** [comment]
I'm not ignoring this, but me and my bt-enabled laptop are currently separated by few cities and large river. I should be able to test it tomorow.

**Comment by simonics** [comment]
No worries (or rush) at all, enjoy the long walk & swim!
