### ISSUE TITLE
sc-controller and Steam constantly fighting for control

### ISSUE THREAD

**Issue by 8BitCerberus** [kozec/sc-controller#412]
I followed these directions for having sc-controller automatically disable itself when Steam starts: https://github.com/kozec/sc-controller/wiki/Running-SC-Controller-and-Steam#configure-sc-controller-to-disable-itself-when-steam-is-detected

It seems to work fine initially, but after about 10 seconds sc-controller turns itself back on which causes any controller input to stop for a few seconds while it takes back over from Steam. Then again about 10 seconds later it turns itself back off, which again causes a few seconds of no controller input until Steam reconnects to it. And this just keeps repeating over and over until I either shut down Steam or shut down sc-controller.

This is on Solus. I'm setting up my primary PC today with Ubuntu and will be testing there soon. I don't know if it's a Solus issue, or a Budgie issue, or something else, but I came here to see if anyone else had reported similar behavior or maybe a workaround, and I don't see any others with this issue.

I have not done the bash script method yet, though that should work fine since it's just stopping sc-controller when launching Steam, and restarting it when closing Steam. Would be the same as manually doing it.

**Comment by kozec** [comment]
That's really weird, controller access is exclusive and it shouldn't be any way to take over it until it's released. How's controller connected? Wired or wireless? Are you running Steam in some special way?

Try running it from terminal, it may display some related error message.

**Comment by Jimi-James** [comment]
I haven't actually learned anything about anything mentioned in that wiki link before, mostly because I've never been completely unable to run Steam and sc-controller at the same time. However, our issues might be related.

**Comment by kozec** [comment]
Issue that was most likely cause for this was fixed with latest release. Please, reopen (or report it again) if that's not the case.
