### ISSUE TITLE
Newest `git pull` fails to build, exits with fatal error

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#413]
A couple times a week I do a `git pull` for sc-controller, and the latest one as of 30 August, 2018 results in the following when I try to build it:

```
$ sudo python2 setup.py build 
[sudo] password for gw: 
running build
running build_py
running build_ext
building 'libsc_by_bt' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c scc/drivers/sc_by_bt.c -o build/temp.linux-x86_64-2.7/scc/drivers/sc_by_bt.o
scc/drivers/sc_by_bt.c:2:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

I figure it's gonna be a weirdness with a library or sumpin'.  Just as a reminder, I'm on Xubuntu 18.04, if that helps. :)

**Comment by kozec** [comment]
Missing Python.h would mean that you don't have python headers installed, it will be `python-all-dev` or just `python-dev` on \*ubuntu.

Also, sudo shouldn't be necessary for building.

**Comment by LinuxJoeUser** [comment]
Thanks!  It was `python-dev` that was needed.  (And if I don't use `sudo` to build, I'll  get the error:
```
Assembler messages:
Fatal error: can't create build/temp.linux-x86_64-2.7/scc/drivers/sc_by_bt.o: Permission denied
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

So I'd use `sudo` as a work-around)

**Comment by kozec** [comment]
> And if I don't use sudo to build, I'll get the error:

That's because you used sudo in past and so `build` dir is owned by root :)
