### ISSUE TITLE
Requires root to run d/t permission error

### ISSUE THREAD

**Issue by creed138** [kozec/sc-controller#414]
Running 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

I'm getting error message in bold red LIBUSB_ERROR_ACCESS [-3] when executing "./run.sh".

I've tried: sudo chmod 666 /dev/uinput

And adding a .rules file to either/both /lib/udev/rules.d  or /etc/udev/rules.d directories.  Reloading with the "sudo udevadm control --reload-rules" command does nothing.  Rebooting, I loose my Corsair mouse function and the steam controller still will not allow non-root access.  Renaming the rules files re-enables my mouse to work again.

Any suggestions?

**Comment by kozec** [comment]
> Rebooting, I loose my Corsair mouse function

That sounds suspicious. Do you have any other rule file related to that mouse?

**Comment by creed138** [comment]
Corsair mouse rules file (/etc/udev/rules.d/99-ckb-daemon.rules):

`ACTION=="add|change", SUBSYSTEM=="input", ATTRS{name}=="ckb[0-9]: [A-Za-z0-9]*",
 ENV{ID_INPUT_JOYSTICK}=""
`

**Comment by OvermindDL1** [comment]
For your Corsair mouse, make sure your `ckb` is updated, it moved repo's a few years ago and has had substantial development since:  https://github.com/ckb-next/ckb-next

Reason I mention this is that if that is your full `99-ckb-daemon.rules` file then it is quite out of date.  I'm unsure if this would affect this issue, but couldn't hurt to update that anyway.

**Comment by kozec** [comment]
Looking at @AlexandreBonneau's message in #396, there is chance that there is some issue with how Debian handles udev rules, as you both have basically same issue on Debian.

**Comment by AlexandreBonneau** [comment]
I see that we have 2 locations where udev rules are set:
- `/etc/udev/rules.d/90-sc-controller.rules` comes from the `sc-controller` package, and
- `/lib/udev/rules.d/99-steam-controller-perms.rules` comes from the `steam-devices` one.

In the later location, there are 112 udev rules, while in the former location (`/etc/udev/rules.d/`, there are only the one from `sc-controller`).
Perhaps first sc-controller needs to use the same location than the other Debian packages?

**Comment by AlexandreBonneau** [comment]
Perhaps related : https://github.com/ValveSoftware/steam-for-linux/issues/5169

**Comment by AlexandreBonneau** [comment]
Well it's totally related since installing steam `10.0.0.56` as mentioned in that issue *does* solve the issue where `sc-controller` cannot access the `/dev/uinput` file!

Note: to install that steam version the Debian way, you need to add the unstable repo in your source.list.d directory, then `apt install -t unstable steam steam-devices`.

Also do not forget to pin the unstable repo so that you do not mess your current install;
```sh
cd /etc/apt
mkdir preferences.d && cd preferences.d
cat > 99_unstable
```
Then paste 
```
Package: *
Pin: release o=Debian,a=unstable
Pin-Priority: 99
```
and hit `Ctrl+d`.

**Comment by kozec** [comment]
Interesting issue, one of those that makes me wonder how come it even works for me in 1st place :)

Anyway, it looks like best solution for Debian would be simply to depend on steam-devices package. Can it be installed without Steam?

**Comment by AlexandreBonneau** [comment]
@kozec indeed, having sc-controller depends on the `steam-devices` package would in my opinion be the best way to handle it.

About that commit https://github.com/kozec/sc-controller/commit/c165173458dd9497744fc3a8881d9e1a9c920ed7 , I see that the permissions are set to `666`, while on the official steam-devices's rule those are set to `660`.

`660` is somewhat more secure, and with the `uaccess` option you do not even need to change the `root:root` user/group.
Is there any reason to use the broad `666` permissions?

Right now on my Debian testing with a working sc-controller:
```sh
$ ls -lh /dev/uinput
crw-rw----+ 1 root root 10, 223 sept.  7 09:00 /dev/uinput
```

**Comment by kozec** [comment]
Because relying on uacess tag means relying on undocumented feature of logins, what I would rather not.

Last time I tried it, logind were doing unholy mess with it, including removing access on vt-switch. And losing access in middle of running is something scc can't handle.

**Comment by OvermindDL1** [comment]
Not really a mess, that is what uaccess is designed to do, only give access to the actual local active screen session.  Leaving the access open is *extremely* discouraged.  Here's some various things about it:
https://github.com/systemd/systemd/issues/4288
Example https://cgit.freedesktop.org/systemd/systemd/tree/src/login/70-uaccess.rules

Anything that accesses USB is supposed to assume it's access can be given or removed at any time (with listeners to react to changes as well, you shouldn't poll), that is even a thing without using uaccess.

**Comment by OvermindDL1** [comment]
Including uinput, it has events to listen to for that as well.  :-)

**Comment by kozec** [comment]
Who/what has? Anyway, losing access to uinput is fatal for SCC and can even lead to locking uinput (as in kernel module) if it happens while rumble effect plays, so anything that cause that is basically unsupported and certifiably bad idea to use.

**Comment by kozec** [comment]
I believe this issue is already fixed.
