### ISSUE TITLE
Add "Display Time" and "Display Size" options to OSD

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#416]
There are times when toggling between settings on a button, or switching between multiple profiles in a game, where it would be very useful to know which key was toggled, or which profile was currently active *for the entire time it was active.*  A time slider like the one for the "Hold" mode would be perfect, except that **all the way** to the right would be "always" for a given profile, or button.  

![image](https://user-images.githubusercontent.com/23580979/45254807-3d2c4d00-b34c-11e8-9884-52f49d4c812e.png)

Additionally, allow sizing of the OSD in the same manner as menus:

![image](https://user-images.githubusercontent.com/23580979/45255197-4a980600-b351-11e8-9f3b-9446ac858bed.png)

So for example, if I have a "driver" profile in a game, it will display the entire time it is on.  This is particularly useful if I accidentally switch to the wrong profile.  This feature could immediately alert me.

![sccdeadislandscrshotwosd](https://user-images.githubusercontent.com/23580979/45255246-c5612100-b351-11e8-8cf8-38a02d3562de.png)

**Comment by kozec** [comment]
Ok, so, display time is not a problem, in fact, it was already supported, just not with GUI.

But changing size is a problem. OSD windows are drawn with GTK and GTK can't really do scaling. I can probably get it to display "small font", "large font" and "normal font", but that's as much of customization as one can get here.

**Comment by LinuxJoeUser** [comment]
Lol, okay, I didn't think about there being no real way to turn the osd *off* once called up, except if---and only if--- the profile is changed.  DOH!  Nice job, all the same. 

Hmm, it would be great to have a "Cancel OSD" setting that worked like the "Cancel Menu" setting---so a whole profile change was unnecessary, but that would require a more complicated overhaul of how OSDs work, I bet.  Your call.

And yes, just being able to choose  "small, medium, large" OSD sizes would be great.

**Comment by kozec** [comment]
> Hmm, it would be great to have a "Cancel OSD" setting that worked like the "Cancel Menu" setting---so a whole profile change was unnecessary, but that would require a more complicated overhaul of how OSDs work, I bet.

Not really, it would just call same code as profile change already does.

**Comment by kozec** [comment]
(gui is todo)

**Comment by LinuxJoeUser** [comment]
Has anyone told you this week that you're awesome?  You're awesome, dude. :)

**Comment by kozec** [comment]
Not yet, but it was only Monday :) Thanks.
