### ISSUE TITLE
Right click options for Menus like with Profiles

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#417]
Add the similar right-click options to Menus that exist for Profiles, or replace "Edit" button with a drop-down menu with those options.   So left-click gets the current options:

![image](https://user-images.githubusercontent.com/23580979/45255620-00198800-b357-11e8-99c2-0db2acc7be67.png)

And right-click would open an options menu:

![image](https://user-images.githubusercontent.com/23580979/45255773-065d3380-b35a-11e8-852f-7f9abb75b062.png)

This would greatly streamline creating and using SCC menus by:

* allowing us to create global menus and menu types and then copy them and save the copy as a a profile menu rather than create another "10 key hotkey" menu that's similar, but different from the others we've created, etc.,
* and (easily) delete existing global menus from withing the UI.

(I realize renaming can be done with "Edit" too)  ;)

**Comment by kozec** [comment]
> (I realize renaming can be done with "Edit" too) ;)

In fact, all but delete basically just opens editor :)
