### ISSUE TITLE
**Edit Bindings** changes cannot be saved.

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#419]
When using Edit Profile, profile is grayed out and won't save.  Emulation turns off when Edit profile window is closed.

[Big .gif deleted as promised :)]

**Comment by kozec** [comment]
Profile greyed out is by design, you can't change active profile while in that mode.

Everything else is not. I'll check why saving doesn't work, but I have idea for emulation turning off. Do you have "disable emulation when GUI is closed" option enabled?

**Comment by kozec** [comment]
Well, disabling emulation when "osd gui" is closed is issue, I was just not sure if it's only one.

**Comment by LinuxJoeUser** [comment]
Additional information thats hopefully :helpful to you:

Opening edit profile *without*  "disable emulation when gui closed" and then trying to close the gui without making any changes, results in the Edit Profile Gui to minimize to tray and makes the original profile unavailable until Edit Profile icon is right-clicked and "Quit"
