### ISSUE TITLE
How to `Add Icons` isn't clear or isn't working

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#420]
Clicking on `Add Icons` for a menu opens my File Manager (Thunar) at `/home/me/.config/scc/menu-icons` and there's the .svg file I placed in /items, there ... but how do I then add that to SCC? or the SCC menu I'm working on?

I've been creating a bunch of new icons for scc for my own use as well as the projects if you're interested when I'm done.  I wanted to see how they looked in a menu, but I'm stumped.

**Comment by kozec** [comment]
It has to be png, but I can't remember why. I'll check if it can support svgs.

**Comment by kozec** [comment]
It can :)
