### ISSUE TITLE
Autoswitcher not displaying OSD?

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#422]
I've got the "Display OSD ..." box checked for the option, but it's not working now.  I was monkeying around with OSD using `press` and `release` (which didn't do anything), so maybe I borked my own local install.  I've restarted the daemon, etc, with no change, so it might also be something that happened with the `osd(0.0, [text])` update.

**Comment by kozec** [comment]
Well, it works, but since changing profile clears OSD messages, it gets displayed for something like 10ms :)

I'll have to rethink this one.
