### ISSUE TITLE
Analog triggers don't seem to work

### ISSUE THREAD

**Issue by otaviomad** [kozec/sc-controller#424]
I've configured everything correctly, and when setting up, the triggers light up and get dimmer when I use the triggers, suggesting that it is detecting an analog axis. But it just outputs a digital signal, being either 0 or 255.

I'm using opensuse with the latest version on the official obs repo.

**Comment by kozec** [comment]
It seems to work as expected to me. What are you using to test the output?

**Comment by 0-ks** [comment]
Appears to be the same bug as issue #739

Try [this workaround](https://github.com/kozec/sc-controller/issues/739#issuecomment-2315213259) until the bug is fixed.
