### ISSUE TITLE
If scc-daemon starts after Steam, Steam and the connected controller both lock up

### ISSUE THREAD

**Issue by Jimi-James** [kozec/sc-controller#425]
If scc-daemon is already running when I start Steam, everything's fine. I can use it while using Steam no problem. However, if I start it after Steam is already running, Steam and the controller (whether it be SC or DS4) both completely lock up/hang/freeze until scc-daemon stops (and they both actually will wait and then work fine again after the daemon is stopped).

Right now, a valid workaround is just closing Steam first if you need to launch scc-daemon, then restarting Steam, so this issue isn't a big deal.

This issue first popped up at some point between December and July (sorry I can't get a better estimate). Possibly related to #412.

**Comment by kozec** [comment]
Sorry, I've kinda missed this issue. If this still is a problem, can you try running Steam from terminal and check messages it displays? My guess is that it detects new controller in system and breaks on it _somehow_, but I'm not sure how.

**Comment by Jimi-James** [comment]
And I'm sorry, too, because I have failed to realize this entire time that it was never a bug with sc-controller! I didn't take into account my own workflow for how I manage my controllers. I have a script that constantly polls for whether they're connected, and when I plug in an SC dongle or connect a DS4 over Bluetooth, the script then runs scc-daemon automatically (but not until after it, and therefore my entire system, have noticed those controllers being plugged in). So what was really going on, was scc-daemon was trying to wrestle control over the controller from a Steam that rightfully believed it was supposed to handle the plug-in event, because just like Steam it was running *after* the controller had been plugged in.

On top of that, it looks like even that issue, which was entirely with Steam (I have no idea how you could possibly fix it within sc-controller), has disappeared somewhere along Steam's recent updates. Say Steam is already running. Then, when I start scc-daemon, Steam registers a new blank controller and continues working. When I plug in the SC dongle, Steam registers that, but can't connect to it, and continues working. Try the opposite order. When I plug in the SC dongle, Steam registers that. Before I have a chance to press the button on the SC controller, my script has started scc-daemon, and scc-daemon successfully takes over the dongle (something that wasn't successfully happening before, and nothing relevant has updated since besides Steam). Then the controller can connect to scc-daemon rather than Steam just fine, and Steam still isn't frozen. It all just works now.

**Comment by kozec** [comment]
Issue that was most likely cause for this was fixed with latest release. Please, reopen (or report it again) if that's not the case.
