### ISSUE TITLE
Mouse-like Joystick input is too weak

### ISSUE THREAD

**Issue by blacksparrow123** [kozec/sc-controller#426]
![_2018-10-14_13-03-29](https://user-images.githubusercontent.com/37986014/46915249-945bb800-cfb1-11e8-99b0-1696190d2b60.png)
Hello
The input, that i'm getting in this mode, is so weak that it can't leave red ring(dead zone) and be properly detected by games and emus.
(Antimicro used just to illustrate the problem.)
Any tips?

**Comment by kozec** [comment]
Click on "More", "Sensitivity" and try increasing it until it does.

**Comment by blacksparrow123** [comment]
I tried.
The result is not really playable. Very jittery.
Thanks anyway. :) Your program is awesome.

**Comment by Ryochan7** [comment]
Maybe adding some form of anti-dead zone would help. I guess that would be Minimum Output Value deadzone mode in SC Controller.

**Comment by Ryochan7** [comment]
The input range used is very likely too large to effectively emulate analog stick behavior. The lack of anti-dead zone to start with is another big problem when it comes to mapping a Touchpad or Gyro to a fake analog stick. Even Steam's implementation has some inherent problems.

Going to toot my own horn for a minute. I have tried several different implementations of Mouse-like Joystick for mappers (SC Controller, reWASD, Steam Input, etc.) but none did what I wanted and didn't control well. I cannot remember when I ended up writing my own implementation for DS4Windows but that was the first time Mouse-like Joystick mapping felt playable; I believe I added it in shortly after the initial release of Halo: Master Chief Collection. The screenshot shows a lot of options for that output type but the core portion is mapping a small input range to the output range with an anti-dead zone to compensate for the in-game dead zone.

![ds4win_mouse_joystick_halo_2](https://user-images.githubusercontent.com/581968/136622993-d0a4cf2e-5d7a-4289-be5c-6e42fe6983ac.png)

As it is, SC Controller does not provide all the options that are likely needed. Editing some of the constants used in the code might help.

**Comment by Ryochan7** [comment]
Never mind. Not going to happen. ball and XY being separate kind of ruins the idea of wanting to try to implement something. A new action would probably be required for what I would want. I have a sample online showing what I was playing with. There are some unrelated changes in the source code.

Steam Controller Mouse Joystick Testing - Steam Input vs Custom - Bayonetta
https://www.youtube.com/watch?v=BpKdLFCjfZE

Experiment with Mouse Joystick for Right Touchpad
https://gitlab.com/ryochan7/steam-controller-test/-/commit/d858497c78b2350eaa487b70726f84f9a0adaf31
