### ISSUE TITLE
Settings issues

### ISSUE THREAD

**Issue by Alzarath** [kozec/sc-controller#43]
Clicking the **Edit Button Bindings...** key does not work. It give the following error:
```py
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/global_settings.py", line 87, in on_butEditKeyboardBindings_clicked
    self.osk_binding_editor = OSKBindingEditor(self.app)
  File "/usr/lib/python2.7/site-packages/scc/gui/osk_binding_editor.py", line 37, in __init__
    self.current.load(find_profile(OSKBindingEditor.OSK_PROF_NAME))
  File "/usr/lib/python2.7/site-packages/scc/profile.py", line 65, in load
    data = json.loads(open(filename, "r").read())
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

My guess is it's not generating a default profile.

The Settings dialog appears immediately on startup. The window appears behind the main window, disallowing you to interact with either window without a Window Manager hotkey (i.e. Alt+Click/Drag to move the main window), and the main window can not be closed until the Settings window is closed.

In the **Autoswitcher**, attempting to use **Edit Condition** with a rule that uses **Match exact title** fails with the error:
```py
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/global_settings.py", line 119, in btEdit_clicked_cb
    entTitle.set_text(condition.title)
TypeError: Argument 1 does not allow None as a value
```

In the **Autoswitcher**, when using both a Class and Window Name, the word "and" does not include a space between itself and the title name.

**Comment by kozec** [comment]
Yeah, it's probably related to #41, file that it reads is hidden and I'm afraid its not getting installed for some weird reason.

**Comment by Alzarath** [comment]
Don't forget to the last thing. It's extremely important.

![160612144131](https://cloud.githubusercontent.com/assets/1994142/15993157/73661304-30ab-11e6-9fd7-3f7b640fff65.png)

**Comment by kozec** [comment]
Ah, yeah, that :D
