### ISSUE TITLE
Possible to break GUI by clicking the wrong "OK"

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#430]
To create a sample condition:

Lpad or Rpad > Dpad >Simple Dpad > select a direction > Key/Button > Grab a Key

It's possible to select the "OK" of the Lpad/Rpad window (see picture, below).  Doing so raises the Lpad/Rpad window, covering the Key/Button & Grab Key windows, making them inaccessible.  I've been using `xkill` to kill the gui and just restarting scc.

![sccwrongok2](https://user-images.githubusercontent.com/23580979/47922125-b51a7d80-de8c-11e8-8c12-eff0ae7ccd74.png)

I've had this happen a few times in a few different ways.  I don't remember them, but I can try to figure some of the others out if you need me to.  

This is obviously a type of user error (hitting the wrong "OK") but I'm thinking it shouldn't be possible.

Let me know if there's anything else I can do. :)

**Comment by kozec** [comment]
You can also just alt+drag that window away so you can reach active one, but this was not supposed to happen :)
