### ISSUE TITLE
Just a question about the `shell()` action

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#431]
O' Obi-Kozec, 

On all of my profiles I have the same mode shift on the RBumper to take and save a screenshot:
```
name('Screenshot and Save', pressed(shell('xfce4-screenshooter -fs /home/gw/Pictures/MyScreenshots/SCCAutoScreenshots/')); sleep(0.206); released(button(Keys.KEY_ENTER)))
``` 
and, you know, it *works*, but it's a little slow and involves a big Save window popping up briefly.

I wanted something more elegant and settled on `scrot` and tried the following as a replacement:
```
shell('scrot 'SCCshot_%Y.%m.%d_%R.png' -e 'mv $f /home/gw/Pictures/MyScreenshots/SCCAutoScreenshots/'')
```
Which, of course doesn't work because of `scrot`'s needs to use the apostrophe (') for options.

My question is if you know any way I can work around this issue in SCC as it is?  I've thought of writing a script (will be my first time XD) to call that does all this, but if there's something simpler ... ?

**Comment by kozec** [comment]
Use double-quotes and escape `$`, otherwise it'll get parsed by shell before it gets to scrot:

`shell('scrot "SCCshot_%Y.%m.%d_%R.png" -e "mv \\$f /tmp"')`

**Comment by LinuxJoeUser** [comment]
This!  THIS is why Amazonian Tribes kowtow before an ancient tree carved with the name KOZEC. XD

Thanks mate!
