### ISSUE TITLE
steam play titles are disabling scc-daemon

### ISSUE THREAD

**Issue by Patola** [kozec/sc-controller#435]
This seems to have started a couple days ago.

Steam client (both mainline and beta) seems to be now becoming agressive against sc-controller. If any game under steam play is called, right after the "starting game" frame appears, it seemingly blocks scc-daemon - it stops responding, and steam's own controller configuration also does not work. This happens even if sc-controller and scc-daemon are called as root whilst steam is called as a regular user.
In dmesg, the entries show that there is an USB reset, like this:
```
(...)
[dom dez  9 00:57:54 2018] usb 3-1: reset full-speed USB device number 4 using xhci_hcd
[dom dez  9 00:57:56 2018] input: SCController Keyboard as /devices/virtual/input/input58
[dom dez  9 00:57:56 2018] input: SCController Mouse as /devices/virtual/input/input59
[dom dez  9 00:57:56 2018] input: Microsoft X-Box 360 pad as /devices/virtual/input/input60
[dom dez  9 01:00:38 2018] hid-generic 0003:28DE:1142.0039: hiddev1,hidraw2: USB HID v1.11 Device [Valve Software Steam Controller] on usb-0000:23:00.3-1/input1
[dom dez  9 01:00:38 2018] hid-generic 0003:28DE:1142.003A: hiddev2,hidraw3: USB HID v1.11 Device [Valve Software Steam Controller] on usb-0000:23:00.3-1/input2
[dom dez  9 01:00:38 2018] hid-generic 0003:28DE:1142.003B: hiddev3,hidraw4: USB HID v1.11 Device [Valve Software Steam Controller] on usb-0000:23:00.3-1/input3
[dom dez  9 01:00:38 2018] hid-generic 0003:28DE:1142.003C: hiddev4,hidraw5: USB HID v1.11 Device [Valve Software Steam Controller] on usb-0000:23:00.3-1/input4
[dom dez  9 01:00:38 2018] usb 3-1: reset full-speed USB device number 4 using xhci_hcd
(...)
```
Using Ubuntu 18.04 64 bits, 16 GB RAM, any other data you might need?
Is there any way to prevent this reset? Like, I dunno, an AppArmor profile that prevents steam play/proton from doing that to USB.

**Comment by Patola** [comment]
Tried a few other options, no dice. Tried disabling steam overlay, disabling Desktop Game Theatre, and Steam Input Per-Game Settings to be off, steam play still seizes control of scc-daemon by means of this USB reset. As of today I have 76 different SC-Controller profiles for my games, that is, I stopped using steam's own driver altogether, and some of these I took many hours to create, and have features absent in steam's own configuration possibilities, like left and right grip acting as modifiers for the shoulder and trigger buttons.

**Comment by Patola** [comment]
I could find a workaround, it seems. SC-Controller creates 3 devices: mouse, keyboard and X-Xbox Controller. I thought that maybe steam play "initializes" the X-Box Controller and that leads to the USB reset. I noted down from dmesg that the XBOX device is `/devices/virtual/input/input30`, that is, the directory `/sys/devices/virtual/input/input30` in the Linux filesystem. I chmodded `a-rwx` this directory and all its files: after that, I could normally start and play steam play games with sc-controller.

One solution to prevent this from happening - if you don't use joystick output when configuring your games - would be an option so that sc-controller does not create the X-Box device at all, is that possible? I reckon there are other ways outside of control of sc-controller like running `wine control` and removing/disabling the X-Box device, but these are too difficult for a new user to follow.

**Comment by kozec** [comment]
I _think_ I have this replicated, but just to check we are both talking about same issue: does it disappear if you disable rumble support in advanced settings? (and after restarting daemon / emulation)?

**Comment by Patola** [comment]
Yes. Just tested. Disabling rumble also works.

**Comment by kozec** [comment]
Great. I already _almost_ managed to find what's Steam (or Proton) sending to break rumble that much.

**Comment by Bloodaxe95** [comment]
I have this issue as well. Is this going to be fixed in the next release? I love this tool, and I'm truly looking forward to using it fonwards in place of Steam :smile:

**Comment by kozec** [comment]
Patience, patience, perfection needs time :D
