### ISSUE TITLE
Usign the right stick as mouse fails

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [kozec/sc-controller#437]
When I use the right stick as mouse, it moves the cursor without any problem, but that is not what I need to do when playing games.

I want to use the right stick to look around, and that doesn't happen. When I move the right stick, it moves a little bit and stops and I need to release the stick and push it again to be able to move further to the same direction.

If I am using a real steam controller that will be totally fine because it has a touchpad, but I use Xbox 360 controller, and it has no touchpad.

**Comment by kozec** [comment]
XBox controller is not really supported, but behavior of `mouse` changes when it's bound on controller that has only sticks. At least with DS4 pad, it should work as you are describing.

**Comment by ahmed-elsayed2017** [comment]
Are you going to support Xbox controller or that is not in the future plans at all?

**Comment by kozec** [comment]
Probably not, Xbox controller doesn't support HID standard and grabbing it through evdev would probably cause issues, as virtual gamepad creted by SC Controller is supposed to be indistinguishable from real xbox controller and so SCC configured to handle xbox controller would end in loop of handling its own outputs.

**Comment by ahmed-elsayed2017** [comment]
I just want to use the left stick to look around, and choosing Left stick for the left stick doesn't work. How can I use the left stick to look around? Could you help me @kozec ?
