### ISSUE TITLE
Are you aware of moltengamepad?

### ISSUE THREAD

**Issue by mbenkmann** [kozec/sc-controller#438]
I wonder if you are aware of https://github.com/jgeumlek/MoltenGamepad.
Now that you are reimplementing sc-controller in C, I think there is considerable overlap and both projects could benefit from cooperation.

**Comment by kozec** [comment]
Yes, it's, along with sccd, something I would've used if I knew about them _before_ I wrote my own :)

Right now, dunno, most of code there is over 2 years old, in c++ and Linux-only.
