### ISSUE TITLE
Unable to move the OSD with the left analog stick

### ISSUE THREAD

**Issue by parkerlreed** [kozec/sc-controller#44]
It used to do this, so not sure if regression or just not working with the new OSD code.

**Comment by kozec** [comment]
It's rebound to right grip + stick by default, but you can't change it back in settings.

**Comment by parkerlreed** [comment]
Ahh thanks. Yeah the combo seems to be a little funky with the RG also being alt (Causes the menubar in Firefox to toggle on almost every release) Re: the settings for the OSD keyboard, it tries to change the settings on the system level and not in the user config.

````
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/global_settings.py", line 143, in on_cbStickAction_changed
    self._save_osk_profile(profile)
  File "/usr/lib/python2.7/site-packages/scc/gui/global_settings.py", line 134, in _save_osk_profile
    profile.save(find_profile(OSDKeyboard.OSK_PROF_NAME))
  File "/usr/lib/python2.7/site-packages/scc/profile.py", line 63, in save
    open(filename, "w").write(jstr)
IOError: [Errno 13] Permission denied: u'/usr/share/scc/default_profiles/.scc-osd.keyboard.sccprofile'
````

**Comment by kozec** [comment]
> it tries to change the settings on the system level and not in the user config.

Holly... :(
As temporal workaround, do
`cp /usr/share/scc/default_profiles/.scc-osd.keyboard.sccprofile ~/.config/scc/profiles/`

**Comment by kozec** [comment]
... also fixed in [latest latest release](https://github.com/kozec/sc-controller/releases/tag/v0.2.8.1)

**Comment by parkerlreed** [comment]
Cheers! Hope I'm not annoying you too much with all these issue reports. ;)

**Comment by kozec** [comment]
> Hope I'm not annoying you too much with all these issue reports. ;)

Not at all, thank you for them :)
