### ISSUE TITLE
Quickmenu displays but not inputting menu items

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#441]
Quick menus have never reliably operated for me (going back to at least v0.43, I think, maybe further).  The quick menu would display, but pressing the corresponding button would input whatever was originally mapped to that button, not the mapping in the quick menu.

Today I thought I'd test which games quickmenu worked with and which it didn't ... and it wouldn't even work just on the desktop.  I tried a few games, but same thing.  I tried with the Xfce compositor off as well, same.

Not sure what else you might need from me to fix this.  Let me know.

**Comment by LinuxJoeUser** [comment]
Update:  Issue persists with update to 0.47 ;)

**Comment by kozec** [comment]
... and after GTK update, it stopped working for me as well :(
