### ISSUE TITLE
Appindicator

### ISSUE THREAD

**Issue by FreeTheSmoke** [kozec/sc-controller#448]
Although the icons all seem to work fine, when I launch scc-controller I get the following warning every time.
(Running Ubuntu 18.10 on Kernel v4.20.3)

` /usr/lib/python2.7/dist-packages/scc/gui/statusicon.py:266: PyGIWarning: AppIndicator3 was imported without specifying a version first. 
Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)
...
`

Edit:
If I try and launch the daemon in a separate terminal first I get receive the **Bold** part of the message after GUI launches.
` ~$ scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
W SCCDaemon     Skipping disabled driver 'fake'
W SCCDaemon     Skipping disabled driver 'remotepad'
D USB           Registered USB driver for 054c:09cc
D USB           Registered USB driver for 28de:1102
D USB           Registered USB driver for 28de:1142
D Mapper        Creating virtual devices
`**`Exception AttributeError: "'Keyboard' object has no attribute '_fd'" in <bound method Keyboard.__del__ of <scc.uinput.Keyboard object at 0x7facd1add090>> ignored`**

**Comment by kozec** [comment]
That first warning is harmless and is caused by way how status icon code detects whether it should use AppIndicator or normal XEmbed.

Other one is harmless as well, but it doesn't look good :) I'll check why it happens.

**Comment by kozec** [comment]
> I have some questions/suggestions about the GUI, what is the preferred way to contact you about them?

Just open issue here on github. But I can't promisse I'd get to them as fast as I used to, my IRL job keeps me 100% busy right now.

**Comment by FreeTheSmoke** [comment]
That is no problem, I'll just enjoy my fully functional controller and hopefully get around to finishing and documenting my great hardware mod for the SC!

Anyway, you were right,. I was looking further thorough SysLog and found it contained X's as serial number 
>...kernel: [ 1508.208529] hid-steam 0003:28DE:1142.0004: Steam Controller 'XXXXXXXXXX' connected
 kernel: [ 1508.208589] input input20: parent 0003:28DE:1142.0004 should not be sleeping
 kernel: [ 1508.208643] input: Wireless Steam Controller as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.2/2-1.2:1.3/0003:28DE:1142.0004/input/input20
 kernel: [ 1508.208961] power_supply steam-controller-XXXXXXXXXX-battery: parent 0003:28DE:1142.0004 should not be sleeping
 kernel: [ 1508.209776] hid-steam 0003:28DE:1142.0005: Steam Controller 'XXXXXXXXXX' connected
 kernel: [ 1508.209826] input input21: parent 0003:28DE:1142.0005 should not be sleeping
 kernel: [ 1508.209875] input: Wireless Steam Controller as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.2/2-1.2:1.4/0003:28DE:1142.0005/input/input21
 kernel: [ 1508.210139] sysfs: cannot create duplicate filename '/class/power_supply/steam-controller-XXXXXXXXXX-battery'

This occurred after laptop was in standby for a while... Maybe if the receiver gets queried while the controller is still asleep it provides a wrong/blank serial number.
