### ISSUE TITLE
Release key has expired

### ISSUE THREAD

**Issue by dgelvin** [kozec/sc-controller#450]
It looks like the xUbuntu_16.04 release key expired yesterday so apt is complaining on update.

```
curl -sL https://download.opensuse.org/repositories/home:kozec/xUbuntu_16.04/Release.key|gpg --with-colons
pub:e:2048:1:3B57AE37123C1C64:2014-09-18:2019-02-07::-:home\x3akozec OBS Project <home\x3akozec@build.opensuse.org>:
```

**Comment by Forger125** [comment]
Same issue on Ubuntu 18.04

**Comment by aircave** [comment]
Same issue (mint 19.01/ubuntu18.04) watching this tread

**Comment by kozec** [comment]
I _think_ I managed to get it extended, please let me know if it doesn't work for you.

**Comment by Forger125** [comment]
Adding the new key resolved the issue - thanks so much for the quick turnaround @kozec!

**Comment by dgelvin** [comment]
Looks good.  Thanks.
