### ISSUE TITLE
no systray icon

### ISSUE THREAD

**Issue by legluondunet** [kozec/sc-controller#451]
Hello,
systray icon does not show on Ubuntu 18.0, Gnome DE.
Thank you for your help.

**Comment by PythonicChemist** [comment]
systray icon on GNOME needs an extension to work

**Comment by legluondunet** [comment]
I use one, but as you can see, I have no icon:
![capture d ecran de 2019-02-11 15-12-51](https://user-images.githubusercontent.com/325405/52573592-caebf700-2e1a-11e9-933b-a65f4e6a152c.png)

**Comment by kozec** [comment]
Sorry, but Gnome deprecated icons and I really can't do much about that.

Try running gui in console (`sc-controller -d -v`) and check if it displays any error messages, but if not, your changes are pretty slim.

**Comment by legluondunet** [comment]
```
$ ./run.sh -d -v
.../sc-controller/scc/gui/statusicon.py:266: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)
D App           daemon status: unknown
D DaemonCtrl    Connected to daemon, version 0.4.6
D App           Loading release notes from 'https://github.com/kozec/sc-controller/releases/tag/v0.4.6'
D DaemonCtrl    Daemon is ready.
D App           daemon status: alive

```

**Comment by kozec** [comment]
> $ ./run.sh -d -v

If you are running from git checkout, there is good chance that extension is searching for icons only in /usr/share. Try copying icons from `images/24x24/status` first to `~/.local/share/icons/hicolor/24x24/status` and then to `/usr/share/icons/hicolor/24x24/status` (you'll need root access for later one).

**Comment by legluondunet** [comment]
1) copy `images/24x24/status` to `~/.local/share/icons/hicolor/24x24`, launch sc-controller
--> still no systray icon
2) copy `images/256x256/status` to `~/.local/share/icons/hicolor/256x256`, launch sc-controller
--> it works!

Thanks
