### ISSUE TITLE
Cannot assign two buttons to a single axis

### ISSUE THREAD

**Issue by Electronicks** [kozec/sc-controller#454]
Hello Kozec.

This may not be as much a bug-issue as much as a missing feature, but I thought since the Steam implementation can do it, I would be expecting your software could as well. Basically, I wish to bind two buttons on a scroll wheel. It's easy to bind the pad axis to another axis, such as mouse movement, mouse wheel or triggers, but it's not possible to bind the pad axis to a pair of buttons.

I tried the following Custom Action:
feedback(LEFT, XY( button(Keys.KEEY_LEFT), button(Keys.KEY_DOWN) ))

This kind of works for scrolling left and down to send the key left and down buttons respectively, but I don't know if it's possible, at least in the current state of the software, to bind KEY_RIGHT and KEY_UP to the other directions of the axis.

Steam allows you to bind buttons to the scroll wheel mode and when you scroll a certain distance it triggers the action. What Steam is missing though is the ability to scroll vertically and horizontally at the same time. I can see you have this ability with SCC but not binding digital actions to analog axis. I was hoping to create the use case of a "scrolling DPAD" using your software because that would work great for DPAD centric interfaces where I could use mouse-like movement on the pads.

I can lend a hand with coding, if you're busy with other tasks. If you just point me in the right direction and come up with a design, I should be able to implement it.

Thanks!

**Comment by kozec** [comment]
Wouldn't something like this do?

```
feedback(LEFT,
  relXY(
    button(Keys.KEY_LEFT, Keys.KEY_RIGHT),
    button(Keys.KEY_DOWN, Keys.KEY_UP)
  ))
```

**Comment by Electronicks** [comment]
I stand corrected. Thanks!
