### ISSUE TITLE
Start minimized to tray not working on Plasma5 w/ AppImage

### ISSUE THREAD

**Issue by Bumbadawg** [kozec/sc-controller#456]
Thanks for your software and that Syncthing-based tray icon :)
Start minimized to tray is not working on Plasma5 w/ AppImage.

**Comment by Amathadius** [comment]
It never works with Gnome either on Archlinux.

**Comment by kozec** [comment]
Sorry, I was not able to replicate nor find any reason why it shouldn't work on Plasma. Does icon work when not started from AppImage? Is there anything interesting written in console?

As for Gnome, it dropped support for tray icons. It's not supposed to work there.

**Comment by Bumbadawg** [comment]
@kozec don't be,
for the console, nothing important, just GTK3 warnings

```
(sc-controller:6109): Gtk-WARNING **: 14:23:57.600: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(sc-controller:6109): Gtk-WARNING **: 14:23:57.600: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(sc-controller:6109): Gtk-WARNING **: 14:23:57.600: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
I StatusIcon    Using backend StatusIconGTK3 (primary)
```

Start minimized to tray are well saved but it still popups main GUI when Appimage starts.

**Comment by Amathadius** [comment]
Gnome maybe officially dropped systray, but I do have a sc-controller icon in my topbar (appindicator extension). It's the simplest way to easily stop daemon.

There's other softwares starting successfully "in systray" on gnome. I think that is doable.

**Comment by kozec** [comment]
> There's other softwares starting successfully "in systray" on gnome. I think that is doable.

It may be doable, just not worth doing. If Gnome says they don't want systray, who am I to fight them :)

Plasma is other story, but I'm really not able to replicate issue with it in any way. It may be just some weird combination of library version and/or configuration.

**Comment by Amathadius** [comment]
I don't understand, sc-controller is in "systray" (appindicator) already. It seems to just don't want to save (or something) the option to "start to tray on start". I check the option, I close the settings window and this option is uncheck when I reopen it. "Enable Status (systray)" work, "Minimize to status icons instead of closing" work, but "minimize to tray on start" option don't want to stay check.
