### ISSUE TITLE
"This is seriously bad and means code has to be rewitten"

### ISSUE THREAD

**Issue by Censacrof** [kozec/sc-controller#458]
On windows, when trying to start sc-controller:

```
$ ./scc-daemon.exe
[I] Daemon       Starting SC Controller Daemon v0.4.5...
[E] Poller       Cannot monitor fd #612. This is seriously bad and means code has to be rewitten.
[E] Daemon       sccd_poller_add failed to add listening socket
[E] Daemon       Failed to create control socket.
```

**Comment by kozec** [comment]
Yeah, so much for Windows not generating fd over 256 :) But that code already is rewritten, there just were no release since then. I already got GUI partially working, so I'll try to fix it to somehow usable state and make new release soon.

**Comment by Censacrof** [comment]
Thank you, let me know if there's something i can do to help.

**Comment by kozec** [comment]
Seriously bad code has been rewritten and is now part of new pre-release.
