### ISSUE TITLE
Allow exact values to be entered

### ISSUE THREAD

**Issue by Mar2ck** [kozec/sc-controller#46]
I would like it if you could make the values for sliders be able to be entered exactly. It's really frustrating when I want a value at 2 but the slider increments by 32 numbers with each pixel I slide across so I can only choose between 1 and 33 which are miles apart.

If you could change the text that shows what the slider value is to a text box where a specific number could be entered then that would be greatly appreciated.

**Comment by kozec** [comment]
Which slider?

Most of numbers can be entered manually through Custom Action tab.

**Comment by Mar2ck** [comment]
I'm talking about the sliders in the feedback options. I've already tried using the Custom Action tab but whenever I enter something custom: [[Imgur]](http://i.imgur.com/dXKu02L.jpg) then click ok and go back on it just changes to something else: [[Imgur]](http://i.imgur.com/tQIm52Z.jpg)

**Comment by kozec** [comment]
Ah, ok, that's not supposed to happen :D

As temporal workaround, switch to "Joystick or Mouse" page before clicking OK, it should got remembered that way.

**Comment by Mar2ck** [comment]
Thanks that fixed it :smile:
