### ISSUE TITLE
ds4 not recognized 

### ISSUE THREAD

**Issue by fredwntr1** [kozec/sc-controller#462]
My dualshock 4 isin't being recognized by sc-controller on Ubuntu 19.04, neither usb or bluetooth are recognized. Steam works though. Could it have anything to do with the controller registering as 3 different events?

`May  4 09:31:53 fred-pc kernel: [   22.039275] input: Wireless Controller Touchpad as /devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:11/0005:054C:05C4.0005/input/input26
May  4 09:31:53 fred-pc kernel: [   22.039356] input: Wireless Controller Motion Sensors as /devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:11/0005:054C:05C4.0005/input/input27
May  4 09:31:53 fred-pc kernel: [   22.039479] input: Wireless Controller as /devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-3/1-3:1.0/bluetooth/hci0/hci0:11/0005:054C:05C4.0005/input/input25
`

`/dev/input/event22:	Wireless Controller Touchpad
/dev/input/event23:	Wireless Controller Motion Sensors
/dev/input/event24:	Wireless Controller
`

**Comment by kozec** [comment]
3 different devices are OK, as long as they have correct IDs and numbers of axes. Can you check if it really gets listed as "054C:05C4"? That's weird, it should be "054C:09CC".  One of those three devices should have 8 axes (controller), other two either 6 and 4 or 6 and 6 for gyro sensor and touchpad.

**Comment by fredwntr1** [comment]
> 3 different devices are OK, as long as they have correct IDs and numbers of axes. Can you check if it really gets listed as "054C:05C4"? That's weird, it should be "054C:09CC". One of those three devices should have 8 axes (controller), other two either 6 and 4 or 6 and 6 for gyro sensor and touchpad.

I just checked again and they are "054C:05C4".

**Comment by Ryochan7** [comment]
Looks like SC Controller is only looking for the newer DS4 v.2 controller. Those IDs  are for an older official DS4 v.1 controller. There are only minor differences between the two.

**Comment by kozec** [comment]
Okay, then this is trivial to fix, but next to impossible to test :)

@fredwntr1, are you able to modify source? Changing PRODUCT_ID on [this line in `scc/drivers/ds4drv.py`](https://github.com/kozec/sc-controller/blob/master/scc/drivers/ds4drv.py#L23) (and restarting everything) should be enough to get older DS4 detected, and if you can confirm that it works as expected, I can modify driver so it catches both values.

**Comment by fredwntr1** [comment]
I will check later in the day when I am home from work

**Comment by fredwntr1** [comment]
![Screenshot from 2019-05-06 19-09-48](https://user-images.githubusercontent.com/44382615/57260655-9e6b0400-7032-11e9-912c-648e953e4665.png)



It works now thank you very much.
