### ISSUE TITLE
SCC-DAEMON just. Won't. DIE

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#463]
Once started, any attempt to kill or stop the `scc-daemon` process (including selecting the "Automatically disable emulation when closing the GUI" setting) results in:

* The daemon not being eliminated, but merely becoming a zombie process.
* Breaking mouse/trackpad input in general such that most or all of the screen cannot be interacted with, though the cursor can be moved around.
* Breaking a running instance of Steam and the workspace it occupies, making it inaccessible and impossible to exit or even `kill -9`, each attempt seeming to another instance of Steam.
* Making a `reboot` or shutdown excessively long, around 10 minutes instead of the typical 10-15 seconds.

Attempting to start `sc-controller` after this results in the "CAN'T SUMMON THE DAEMON" error.

This may or may not be related to the possible kernel issue happening after a fresh install, reported in issue #464.  It is possible to workaround these problems by *not* disabling or killing `scc-daemon` once it's been started except with a `reboot`, which will only take the short 15 seconds.

The Steam Controller works as expected with Steam alone, with control passing to the kernel driver when Steam is closed.

I first encountered this in Xubuntu (possibly sometime in 18.10), but have tested and found it on the 19.04 versions of Ubuntu, vanilla Gnome on Ubuntu, and the Ubuntu Mate desktops.

**Comment by kozec** [comment]
Let's hope it's caused by \#464, otherwise I'd have to change way how's daemon terminated when "Automatically disable" is used in way that should prevent this, but may leave daemon running instead.

**Comment by LinuxJoeUser** [comment]
It's because of the issues reported in #464 , so I'm closing this issue.
