### ISSUE TITLE
Possible evdev rules not being set up correctly causing scc-daemon issues

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#464]
Possibly connected to issue #463

Starting up SC-Controller for the first time after a clean install of both Xubuntu 19.04 and Ubuntu Mate 19.04 resulted in the same errors and behaviour:

* Before running SC-Controller for the first time, the SC is controlled wirelessly by the 5.0 kernel.
* The first time running SC-Controller results in the "You don't have permission...Run Steam...Fix Temporarily?" error message (I don't remember the exact wording).
* Stopping and re-starting SC-Controller results in "CAN'T SUMMON THE DAEMON" error.
* After a reboot and starting Steam first, the kernel passed control to the Steam SC driver.  Only then did SC-Controller start correctly and successfully.

**Comment by kozec** [comment]
Well, sounds like that part about never breaking userspace was not precise after all :)

Thanks for detailed report, I'll get Xubuntu into VM and test what's wrong.

**Comment by LinuxJoeUser** [comment]
You're welcome.  Please, let me know if I can be any more help.

**Comment by kozec** [comment]
So, I have xubuntu and can see message, but that one is expected for just running from git checkout.

Just to be sure I'm doing same thing:
- Did you installed sc-controller from package?
- Did you clicked "Fix Temporarily" button?
- Did GUI got into "CAN'T SUMMON THE DAEMON" message by itself, or did you stopped and started daemon manually?

**Comment by LinuxJoeUser** [comment]
>  Did you installed sc-controller from package?

No.  I installed cloning from Github and then

	`python2 setup.py build`
	`python2 setup.py install`
	
	
> Did you clicked "Fix Temporarily" button?

The first time, yes, the second time, no.  No change as I recall.

>Did GUI got into "CAN'T SUMMON THE DAEMON" message by itself, or did you stopped and started daemon manually?

By itself.

**Comment by kozec** [comment]
Ok, so I think this is caused simply by evdev rules not being set up. Because of that, uinput is unavailable and scc-daemon can't access usb devices. Kernel driver is most likely completely innocent in this :)

Quick fix is simply doing `sudo cp scripts/69-sc-controller.rules /etc/udev/rules.d/` and reloading udev rules or rebooting. I'll check if it's possible to make it part of `setup.py install`, but first I'd like to find why starting Steam helps and whether I can copy whatever is Steam doing there.

**Comment by LinuxJoeUser** [comment]
Doing `sudo cp scripts/69-sc-controller.rules /etc/udev/rules.d/` results in the complaint `cp: cannot stat 'scripts/69-sc-controller.rules': No such file or directory`  I went looking in /lib/udev/rules.d and found /69 was occupied by wacom tablet rules:

![image](https://user-images.githubusercontent.com/23580979/57552602-69b0c280-733a-11e9-8911-733776b16ab5.png)

if that's any help for fixing this bug.  Glad the kernel is innocent ;)

**Comment by kozec** [comment]
Sorry, I should have been more specific. That copy should take path to where git checkout placed copy of [this file](https://github.com/kozec/sc-controller/blob/master/scripts/69-sc-controller.rules). AFAIK, those numbers are there just for ordering, it's not problem if there are multiple items at same "level".

**Comment by LinuxJoeUser** [comment]
> Sorry, I should have been more specific.
Naw, *I* should have known better than to tell my file manager to do a search for `/69`.  

Anyway, yes, the quick fix worked like a champ once I did it in the right directory. ;)

**Comment by kozec** [comment]
While trying to add udev rules to setup.py as part of next release, I found that it's already there. setup.py will install `69-sc-controller.rules` to `/usr/lib/udev/rules.d` where udev should be able to find them.
