### ISSUE TITLE
GPG Error when updating apt-get

### ISSUE THREAD

**Issue by bmath1123** [kozec/sc-controller#466]
After adding the kozec repo and using sudo apt-get update I receive the following error message:

W: GPG error: http://download.opensuse.org/repositories/home:/kozec/xUbuntu_18.10  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B57AE37123C1C64
E: The repository 'http://download.opensuse.org/repositories/home:/kozec/xUbuntu_18.10  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

After receiving the error, I tried installing sc-controller anyway but received an Unable to locate package error.My apologies if the solution is simple, I'm new to Linux and I can't find a solution through Google. I'm running Pop OS 18.10.

**Comment by kozec** [comment]
NO_PUBKEY sounds like you skipped [step no.2, adding key.](https://software.opensuse.org/download.html?project=home%3Akozec&package=sc-controller)

You can either do that, or disable signed repository requirement, or download .deb file and install it without adding repository at all.

**Comment by bmath1123** [comment]
That worked and sc-controller is now installed. Thank you
