### ISSUE TITLE
Stick input "hangs" when LPad being touched

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#467]
I've tried this with a completely new profile as well and also on a different computer on the xfce desktop (I'm on Mate now).  In the GIF below, you'll see that by itself, the stick snaps back, but when the LPAD is touched, the stick "hangs" until the LPad is released.  RPad doesn't affect anything.
![Peek 2019-05-10 15-57](https://user-images.githubusercontent.com/23580979/57553619-0ecc9a80-733d-11e9-92d1-55f01498b0fd.gif)

As always, if I can provide any more info, just let me know. :)

**Comment by kozec** [comment]
Yeah, I hoped no one has enough fingers to notice this :)
