### ISSUE TITLE
How to get sc-controller to turn off?

### ISSUE THREAD

**Issue by Dnlaua** [kozec/sc-controller#469]
I'm on Ubuntu 19.04 and I can't get sc-controller to turn off without rebooting. I tried unplugging/replugging dongle, but that didn't work. Also tried pkill sc-controller but no luck. Is there a way to turn off sc-controller without rebooting?

**Comment by kozec** [comment]
You can click "Disable emulation" in menu. pkill is also fine, but process that does all work is called `scc-daemon`

**Comment by Dnlaua** [comment]
Ok, I didn't see an option to disable emulation in the menu. Maybe I need to update to the latest version? Either way, now that I know it's scc-daemon I'll just use pkill. Thanks for your help!

**Comment by kozec** [comment]
It should be here:

![menu](https://user-images.githubusercontent.com/1282500/59381360-766e6f00-8d5b-11e9-802d-ffe3f7727713.png)

... actually called "Emulation Enabled". Sorry for confusing it like that.

**Comment by parkerlreed** [comment]
Ahh the plague of GTK header bars strikes again! :P
