### ISSUE TITLE
Windows 10 - Grab a key mismatch

### ISSUE THREAD

**Issue by FormulaGX** [kozec/sc-controller#472]
I want to open Xbox Game Bar ("Meta"+G) with the Steam button. However, the G key, on its own or not, is picked up as KEY_F5. I have tested many other keys and they're all offset by about 4 rows.

**Comment by kozec** [comment]
> FormulaGX closed this 8 hours ago

Have you resolved the issue? Was it not problem with SC-Controller after all?
