### ISSUE TITLE
osd not working

### ISSUE THREAD

**Issue by edward81** [kozec/sc-controller#48]
Looks like any osd function is not working.
If i try to launch any of the scc-osd util from command line i get this error:
`Traceback (most recent call last):`
`  File "/usr/bin/scc-osd-message", line 21, in <module>  `
`    m = Message()  `
`  File "/usr/lib/python2.7/site-packages/scc/osd/message.py", line 19, in __init__`
`    OSDWindow.__init__(self, "osd-message")`
`  File "/usr/lib/python2.7/site-packages/scc/osd/__init__.py", line 80, in __init__`
`    OSDWindow._apply_css(Config())`
`  File "/usr/lib/python2.7/site-packages/scc/osd/__init__.py", line 106, in _apply_css`
`    OSDWindow.css_provider.load_from_data(str(OSDWindow.CSS % config['osd_colors']))`
`GLib.Error: gtk-css-provider-error-quark: <data>:3:28Junk at end of value (1)`

I run the sc-controller util from kde on arch.

**Comment by kozec** [comment]
Are you running directly from git?
And if yes, can you post output of following command?
`cat ~/.config/scc/config.json`

**Comment by edward81** [comment]
Yes git version, here the output
`edward ~ $ cat ~/.config/scc/config.json`
`{`
`    "autoswitch": [], `
`    "autoswitch_osd": true, `
`    "osd_colors": {`
`        "background": "000000000000", `
`        "border": "00FF00", `
`        "menuitem_border": "004000", `
`        "menuitem_hilight": "000070", `
`        "menuitem_hilight_border": "00FF00", `
`        "menuitem_hilight_text": "FFFFFF", `
`        "menuseparator": "109010", `
`        "text": "00FF00"`
`    }, `
`    "osk_colors": {`
`        "hilight": "00688D"`
`    }, `
`    "recent_max": 10, `
`    "recent_profiles": ["Desktop", "XBox Controller with High Precision Camera", "XBox Controller"]`
`}edward ~ $`

**Comment by kozec** [comment]
Ok, please, edit that file and replace `"background": "000000000000",` with `000000` (6 zeros, rgb for black). I managed to get that value as default with one unlucky commit :(

**Comment by edward81** [comment]
That fixed ! Thanks you :)
