### ISSUE TITLE
daemon and gui

### ISSUE THREAD

**Issue by fiera24** [kozec/sc-controller#488]
errors like it on windows version

![image](https://user-images.githubusercontent.com/53713267/62430338-f2fa4a00-b71b-11e9-9b4e-c3a740f4c8e7.png)

![image](https://user-images.githubusercontent.com/53713267/62430343-fc83b200-b71b-11e9-80f6-6c79327855a2.png)

**Comment by kozec** [comment]
Above error is normal, displayed while daemon is starting. Warning about missing is not and should be fixed in next release.
