### ISSUE TITLE
Mode Shift settings do not work

### ISSUE THREAD

**Issue by Adaephon-GH** [kozec/sc-controller#49]
Hello!

When clicking on the "Mode Shift" button in the settings window of any control, no window comes up. Instead an `AttributeError` exception is thrown:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/scc/gui/action_editor.py", line 395, in on_btModeshift_clicked
        e.set_input(self.id, action, mode=self._mode)
      File "/usr/lib/python2.7/site-packages/scc/gui/modeshift_editor.py", line 318, in set_input
        self.builder.get_object("adjTime").set_value(action.timeout)
    AttributeError: 'ModeModifier' object has no attribute 'timeout'

This seems to be the case for the [latest commit (9b9b712f)](https://github.com/kozec/sc-controller/tree/9b9b712fe936d3646682321fc0dd140c8519ac38) as well as [tag v0.2.9](https://github.com/kozec/sc-controller/tree/v0.2.9).

**Comment by kozec** [comment]
Thanks.
Fixed and released as [new release](https://github.com/kozec/sc-controller/releases)
