### ISSUE TITLE
Ability to disable profile switching

### ISSUE THREAD

**Issue by Revolt64** [kozec/sc-controller#490]
I use the dameon only on Windows so I can use my steam controller as an Xbox controller.

I don't want or need any other functionality, so is it possible to run the daemon without also enabling the profile switcher?

I just want to run the Xbox standard profile locked. No menu popping up when I press the steam button.

Thanks for porting this to windows, it's an excellent program.

**Comment by kozec** [comment]
If by profile switcher you mean on-screen menu that pops up when you press button with Steam logo, there are two options:

1. Delete `scc-osd-menu.exe`. That button will do nothing
2. Open Xbox profile and change action on that button to something else. Setting it to `button(Keys.BTN_MODE)` may be interesting, as that will map it to "Home" button on virtual xbox controller.

**Comment by Revolt64** [comment]
That works. Thank you!
