### ISSUE TITLE
Can't set gestures for DS4

### ISSUE THREAD

**Issue by nstgc** [kozec/sc-controller#493]
I'm trying to get the touch pad to recognize swipe gestures for the arrows keys. This way I don't have to take my thumb off the left stick to use the D-Pad. I know there is a way to use the touch pad as a D-Pad, but my experience with that has been rather poor.

When I go into the gestures menu and click the + button, it brings up a small window in the lower right hand corner of my screen and asks me to draw on the left pad. No matter where I make a gesture, it doesn't register anything.

**Comment by kozec** [comment]
SCC can (and does) take over DS4 touchpad as well, but gesture recognition doesn't really have support for it. Adding it shouldn't be hard, I'm just not sure how useful will it be. DS4 has weird shape and pretty low resolution.

**Comment by kozec** [comment]
Sorry for forgetting to close this. Issue should be already fixed for a while, including new release.
