### ISSUE TITLE
PS3 Logik Controller not working (Bind failed: error 10048)

### ISSUE THREAD

**Issue by robgha01** [kozec/sc-controller#495]
Im trying to get this controller "https://vgcollect.com/item/142839" to work.

I have the latest version of ViGEmBus 1.16.115 using sc controller 0.4.9.6-win32-pre-release
this is what the debug mode throws out.

Using wired cable on a windows 10 Home Edition 64bit.

```
Microsoft Windows [Version 10.0.18362.295]
(c) 2019 Microsoft Corporation. Med ensamrätt.

C:\WINDOWS\system32>cd C:\Users\rober\Downloads\sc-controller-0.4.9.6

C:\Users\rober\Downloads\sc-controller-0.4.9.6>scc-daemon.exe debug
[I] Daemon       Starting SC Controller Daemon v0.4.5...
[I] Daemon       Created control socket C:\Users\rober\AppData\Roaming\scc\daemon.socket
[I] Daemon       Initializing drivers...
[D] Mapper       Creating virtual devices...
[d] Mapper       Gamepad:  <ViGEm x360 Controller 0x001e9fa0>
[d] Mapper       Mouse:    <Winapi mouse device 0x008cd280>
[d] Mapper       keyboard: <Winapi keyboard device 0x008d06a0>
[E] CemuHook     Bind failed: error 10048
[I] Daemon       Activated default profile 'C:\Users\rober\Downloads\sc-controller-0.4.9.6\share\default_profiles\Desktop.sccprofile'
[I] Daemon       Ready.
```
When i test the native windows game settings for the ps3 controller it registers the button clicks and everyting however when i do the same for the emulated 360 controller nothing is being registered.

**Comment by kozec** [comment]
Sorry, but only Steam controllers are currently supported on Windows. I plan to add support for normal controllers as well, it's just not there yet.
