### ISSUE TITLE
Can't build 0.4.9.7

### ISSUE THREAD

**Issue by SolitudeSF** [kozec/sc-controller#496]
Building latest tag fails with
```
../src/virtual-device/uinput/common.c:10:10: fatal error: stropts.h: No such file or directory
   10 | #include <stropts.h>
```

upon further inspection, i found that void linux doesn't contain this header in glibc development files, but arch linux does.

**Comment by kozec** [comment]
> upon further inspection, i found that void linux doesn't contain this header in glibc development files, but arch linux does.

That's pretty weird, can you check where is ioctl defined? Either with `man 3 ioctl` or, if that shows ioctl, just grep for it in /usr/include

**Comment by SolitudeSF** [comment]
yeah, i dont have stropts anywhere. thats void's issue, i think.

**Comment by SolitudeSF** [comment]
Actually, `stropts.h` was removed in latest glibc.
https://sourceware.org/ml/libc-alpha/2019-08/msg00029.html

**Comment by kozec** [comment]
I have to commend void for its speed, but I don't have 2.30 available yet :D

```
$ pacman -Ss glibc
system/glibc 2.29-4 (base) [installed]
    GNU C Library
```

Does replacing that include with `#include <sys/ioctl.h>` works for you?

**Comment by SolitudeSF** [comment]
yep, it works

**Comment by kozec** [comment]
Issue should be fixed with last pre-release.

**Comment by SolitudeSF** [comment]
now it fails when invoking meson with `src/osd/menus/meson.build:37:0: ERROR: File grid_menu.c does not exist.`

**Comment by kozec** [comment]
I don't have any idea how I managed to develop this on 3 machines _without_ adding that file to git, but it should be there now.

**Comment by SolitudeSF** [comment]
yep, everything compiles fine now.
