### ISSUE TITLE
Gyro UI button for pitch down seems sets roll right

### ISSUE THREAD

**Issue by Patola** [kozec/sc-controller#499]
Trying to configure the gyro for Elite: Dangerous. As seen from the screenshots, when I set up KP2 as pitch down, it's the roll right button that receives the label. However configuration seems ok on the custom action and it also behaves correctly.

![Gyro_195](https://user-images.githubusercontent.com/2991620/65931566-9ac08b00-e3e0-11e9-93ed-c5feaa481ee4.png)
![1 Press_199](https://user-images.githubusercontent.com/2991620/65931588-b3c93c00-e3e0-11e9-809f-cc8f0c969454.png)
![Gyro_197](https://user-images.githubusercontent.com/2991620/65931593-ba57b380-e3e0-11e9-83d0-853baffe35a2.png)
![Gyro_198](https://user-images.githubusercontent.com/2991620/65931600-bfb4fe00-e3e0-11e9-878e-c9c3add07d85.png)

**Comment by Patola** [comment]
Created pull report #500 to fix this issue.

**Comment by kozec** [comment]
Good catch. Thanks for PR :)
