### ISSUE TITLE
How to use the input OSD?

### ISSUE THREAD

**Issue by Leeo97one** [kozec/sc-controller#501]
Maybe I'm stupid, but I don't really know how to use the input OSD feature of sc-controller and I didn't find any documentation. Is it supposed to be straightforward?

**Comment by Leeo97one** [comment]
OK, so we have to Enable Input Test Mode in the Advanced tab of Settings, then run the Python file `scc/osd/inputdisplay.py`. Is that the best (and only) way to do it?

**Comment by kozec** [comment]
It's not really supposed to be straightforward, `inputdisplay.py` is just script I hacked together when I needed to demonstrate something in video. I didn't really expected anyone else to find it useful.

But I'm glad you managed to find way around it and sorry for not answering sooner.

**Comment by Leeo97one** [comment]
Oh OK! But it could be great to have something like VSCView.
