### ISSUE TITLE
"C-branch" Analog output in pads wrap around

### ISSUE THREAD

**Issue by ren2r** [kozec/sc-controller#502]
Setting sensitivity above 1.0 for LStick or RStick in pads or in analog stick causes the output wraps around.. It goes to maximum and instead of maintaining in max output, it reverts to reverse direction.

![image](https://user-images.githubusercontent.com/1781248/66359075-f85a5780-e94b-11e9-9899-5362967e4ce8.png)
![Peek 07-10-2019 21-43](https://user-images.githubusercontent.com/1781248/66359041-d6f96b80-e94b-11e9-99a0-0e50bdda7daa.gif)

**Comment by kozec** [comment]
Fixed by 894f529ec818f8158ff5fb6ada5fb1fe2c66faed
