### ISSUE TITLE
"C-branch under windows" Grabbing a wrong key

### ISSUE THREAD

**Issue by ren2r** [kozec/sc-controller#507]
The action "Grab a key" in action binding window is getting different keys when pressed (pressing "Esc" in my keyboard results in "KEY_R")

**Comment by ren2r** [comment]
I tested values from https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes on "gtk_to_key" dict inside the file with the same name in "python/scc/gui" folder and got the right keys in my pc (windows 10), maybe it should check if is windows system then use these keycodes.

**Comment by kozec** [comment]
Issue should be fixed in [latest release](https://github.com/kozec/sc-controller/releases)
