### ISSUE TITLE
Can't change settings on right touchpad setting right pad to mouse controls. 

### ISSUE THREAD

**Issue by Beardmang** [kozec/sc-controller#509]
Once I program the right touchpad to mouse controls and save it I can no longer click on the Right Touchpad in SC Controller GUI and edit these controls.

Also, Thanks! keep up the great work!

**Comment by Beardmang** [comment]
Oh I should have added I'm using Windows 10 and v0.4.9.8

**Comment by kozec** [comment]
Which exact option have you set? It should be possible to right-click on Right Touchpad and select "copy" to get configuration you can paste here.

**Comment by Beardmang** [comment]
Okay I right-clicked on the trackpad at the bottom and copied this:
smooth(10, 1, 33, feedback(RIGHT, 210, sens(3, 3, ball(5.534, mouse()))))

I did some testing just now, here my steps to get the same result:
_New profile>Click Right Trackpad> Joystick/mouse>Output: Mouse (Trackpad or Trackball)> Basics: *Check* Trackball Mode> Smoothing Enabled_

**smooth(mouse())**

I also find that this gets the same result

_New profile>Click Right Trackpad> Joystick/mouse>Output: Mouse (Trackpad or Trackball)> Basics: *Check* Trackball Mode> Smoothing Enabled_

**deadzone(0, 32768, mouse())**

after doing that I am no longer able to access settings for that trackpad again. 

![Can't Click here](https://user-images.githubusercontent.com/55560127/68429955-1bf80400-017d-11ea-8abe-f193c4c74942.jpg)
![I can Click here still](https://user-images.githubusercontent.com/55560127/68429956-1bf80400-017d-11ea-857f-347350e10cf6.jpg)

**Comment by Beardmang** [comment]
To be clear, I realize in my second image that that is just for programing what happens when you click the trackpad. I was just trying to show that I can still click there BUT obviously it doesn't help lol.

**Comment by kozec** [comment]
Ok, I believe that I fixed it along with #507. I've one more issue I'd like to tackle tomorrow and I'll try to make another prerelease with all fixes over the weekend.

**Comment by Beardmang** [comment]
Wow that was fast, thanks. Keep up the great work. I'll try to donate to the cause when I get paid.

**Comment by kozec** [comment]
Issue should be fixed in [latest release](https://github.com/kozec/sc-controller/releases)
