### ISSUE TITLE
No repository listing for Debian 10 (buster)

### ISSUE THREAD

**Issue by llirium** [kozec/sc-controller#512]
There isn't an option for a Debian 10 (buster) repository on this page, only Debian 9 and Debian 8.

https://software.opensuse.org/download.html?project=home%3Akozec&package=sc-controller#manualDebian

Please create one for Debian 10, thank you. :)

**Comment by kozec** [comment]
Debian 10 added.

**Comment by llirium** [comment]
Much appreciated!
