### ISSUE TITLE
Is there any way to fully or temporally disable the OSD so it doesn't collide with Steam Chord? (Windows)

### ISSUE THREAD

**Issue by notNSANE** [kozec/sc-controller#515]
So SCC is great but there are many cases where I can actually use the Steam Input Xbox 360 Steam Chords. Right now the SCC OSD is preventing Steam Chords from being recognized.

Maybe there's some command line argument? I haven't researched extensively yet.

**Comment by kozec** [comment]
Opening OSD is just part of profile, you can edit profile and remap that button to Guide button on Xbox.
