### ISSUE TITLE
Extreme lag and dpad hangs when using xinput/x360 Emulation and bluetooth

### ISSUE THREAD

**Issue by clst** [kozec/sc-controller#518]
The mouse mode and debug mode (the highlights on the main window) and the OSD work fine. But as soon as I start pcsx2 or a wine xinput game inputs repeat or lag for about 500ms to 2s.

When I plug in the cable everything instantly works perfectly.

Is this a known issue or do you need more info?

**Comment by kozec** [comment]
I'd definitely need more info and 1st thing to check would be CPU utilization.

**Comment by clst** [comment]
This seems to have solved itself. No more troubles. Maybe it was the drivers or a kernel update that fixed this issue.
