### ISSUE TITLE
button behaviour when key is already pressed

### ISSUE THREAD

**Issue by TiloWiklund** [kozec/sc-controller#52]
With the current setup having two controller events mapped to the same button action (i.e. the same key on the keyboard) generates a release event as soon as one of them is released and a press press event only if the other is not already pressed. 

I see why this is a natural behaviour in terms of implementation but it might not always generate expected behaviour in terms of game controls (examples below). I am unsure what would be the natural configuration options here, but all situations I can think of where the current behaviour is problematic could be solved in a somewhat ad-hoc fashion by being able to specify an action (a "button tap") which generates: a release event *if they key is already pressed*, followed by a key press event, a key release event, and finally another key press event *if the key was originally pressed*. 

I realise this might seem like a niche situation, but it does appear in situations where some set of keys serve both for movements and as part of a combo. If the combo is triggered by some other controller event the movement is interrupted until the relevant keys/axes are released and pressed again. 

In my case the situation arose when experimenting with different controller configurations for Mount & Blade. The controller stick was bound to a WASD-dpad action and the controller right pad to a dpad action generating a mouse click with the corresponding WASD-direction pressed. Currently this means that swinging (using the right pad) in the direction of ones current movement (controlled by the stick) interrupts the movement until the stick is released and reactivated.

**Comment by kozec** [comment]
>  (a "button tap") which generates: a release event if they key is already pressed, followed by a key press event, a key release event, and finally another key press event if the key was originally pressed.

That actually sounds pretty simple to do, but I'm not sure where to stick it in UI. Would be having it accessible only as custom action too complicated?

As custom action, even something more generic like "do this if simulated button is pressed, do something else otherwise" should be possible.

**Comment by TiloWiklund** [comment]
If it's done via a new type of action I think a custom-only action would do fine (as with press and release now). If going via an option in "More" one should perhaps be a little more explicit, something like "tap button if already pressed" or something like that?

Either approach sounds reasonable to me.

**Comment by kozec** [comment]
Just to check if I understood correctly, what you need is:
- tapping that virtual button, i.e. pressing it for short while and automatically releasing it
- or keeping it pressed while you keep finger on dpad and then having it released and pressed again to keep character in move?

**Comment by TiloWiklund** [comment]
The latter, if I understand you correctly. I a controller button to be able to generate a press/release event for a key, such that the the state of the key (pressed/not pressed) from before the event is preserved after the controller button is released.

**Comment by kozec** [comment]
Ok, after some meditation I changed how all button events are generated. Currently, in your example, it should do following:

- You move stick to left, key A is pressed.
- You press swinging button, key A is released and immediately pressed again along with mouse button.
- key A is released only after both swinging button and stick is released.

**Comment by TiloWiklund** [comment]
Fantastic! Thanks for a great piece of software.
