### ISSUE TITLE
Double click speed very slow

### ISSUE THREAD

**Issue by TRPB** [kozec/sc-controller#520]
I have RT bound to mouse left, but double clicking anything requires a very long pause to register a double click. It seems to prevent the second click from being registered for some time after the first click. Using Steam it's fine, but with SC Controller there is quite a delay. Is there any way to configure this?

**Comment by Tsudico** [comment]
What does it show for the text at the bottom of the input dialog for RT Trigger? My RT Trigger shows up like this:
`button(BTN_LEFT)`

But I can double click fast enough that in Mouse Properties on Windows 10 I can have the double click activate the folder test at the fastest speed.

**Comment by TRPB** [comment]
Mine's also set to ` button(BTN_LEFT)`. With a bit of trial and error I figured it out. It seems to be an issue with it detecting fully released whether I'm just not used to releasing the trigger all the way I'm not sure but changing it to "Full pressed action" instead of "partially pressed" has the same behaviour as Steam.
