### ISSUE TITLE
dpad with mouse wheel action makes key events

### ISSUE THREAD

**Issue by miezebieze** [kozec/sc-controller#53]
i tried to make an 'inverted' mouse wheel on the left track pad, so i tried this:
`dpad(`
`  button(Rels.REL_WHEEL, 1),`
`  button(Rels.REL_WHEEL, -1),`
`  button(Rels.REL_HWHEEL, 1),`
`  button(Rels.REL_HWHEEL, -1)`
`)`
it does not work and with xev i can see that it sends keyboard key '5' and '7'

**Comment by kozec** [comment]
`button` works only with buttons, but you can use normal `mouse` with negative sensitivity:

```
sens(-1.0,
  XY(mouse(Rels.REL_HWHEEL), mouse(Rels.REL_WHEEL))
)
```
