### ISSUE TITLE
[Feature Request]Turn off Steam controller via cli / on SC-Controller quit

### ISSUE THREAD

**Issue by FrankyB** [kozec/sc-controller#531]
I have aproblem that drives me mad. My PC is keeping rebooting on shutdown as soon as one of my two steam controllers is turned on.
I tried allI could find about quirks in the kernel, tried to shut down the receiver of the controller via /sys/usb...., I disabled it via /proc/acpi/wake without any luck. The PC goes down, the controller realizes that and turns itself off, and in exact this moment the PC starts up again :-/
So.... I love your work and all thank you so much for this lovely piece of software... and could you please add a cli switch to turn the controller off, or turn it off when sc-controller is shut down?
If not, I can always turn off the controller, then turn off the TV (with Pulse-Eight's little box the PC is shut down) - but you see, I am really interested in a user friendly setup...

Thanks again for the sc-controller software, I ever since use it and it helps me getting steam, kodi and vdr on one PC in one living room "wife-acceptable" - and of course friendly to use for me :-)

**Comment by kozec** [comment]
> The PC goes down, the controller realizes that and turns itself off, and in exact this moment the PC starts up again :-/

Check anything related to "USB wake up" in BIOS :)

> and could you please add a cli switch to turn the controller off, or turn it off when sc-controller is shut down?

That should be possible even now, although not in entirely intuitive way. You can send commands to daemon that runs on the background using netcat:

```
echo -n 'Turnoff.' | nc -w1 -U ~/.config/scc/daemon.socket
```

... should turn controller off.

**Comment by FrankyB** [comment]
Wow, that works! I cannot turn off USB wakeup because the Pulse-Eight CEC adapter should turn on my PC when the TV is turned on ;-) 
Now, I will turn the netcat into a systemd service!
