### ISSUE TITLE
[Feature Request] Rotational gesture option for pads

### ISSUE THREAD

**Issue by seylerius** [kozec/sc-controller#532]
The official driver in the Steam client has a rather efficient rotating gesture as the default for mouse wheel mode on the pads. It functions by running a finger clockwise on the pad to scroll down, and counterclockwise to scroll up. I find it preferable to the normal touchpad mousewheel mode because it can be used indefinitely without picking up one's thumb. Unfortunately I can't figure out how to build it compactly in the gesture tool, not without either requiring much longer circuits to scroll at all, or running into conflicts and ambiguity about which direction you mean. 
The gesture display while recording a gesture suggests that this driver is sensitive enough to do it, but the config files seem to be recording gestures exclusively in two-axis terms. Would including a degree of region detail in the gesture language be possible? If the notation supported something like that, I could reliably and unambiguously describe the gestures I want, and wouldn't need it to be compact. The most straightforward thing I can think of is numbering the nine regions and allowing gesture notation to be either numbers or arrows (or both?). Then I could have `12`, `23`, `36`, `69`, `98`, `87`, `74`, `41` as `Scroll Down` and the reversed ones as `Scroll Up`.

**Comment by kozec** [comment]
Wouldn't [circular mode](https://user-images.githubusercontent.com/1282500/73134441-da1d8200-4036-11ea-8bce-6874ad1b0c80.png) work for what are you trying to do?

**Comment by seylerius** [comment]
How did I miss that?I feel silly. 

Thank you very much for pointing it out.
