### ISSUE TITLE
No outputs are passed to system

### ISSUE THREAD

**Issue by CommunistWitchDoctor** [kozec/sc-controller#536]
The controller connects perfectly, inputs are recognized perfectly, but none of sc-controller's configured outputs are passed through to the system.

For example, the gui will recognize that I am pressing the "A" button or moving on the right trackpad, but I can not control the mouse or input any keypresses. Steam is not running, so there should be no other connections to the controller. Menus of all sorts work, and can be navigated with the controller, but their outputs are also not passed to the system. For example, I can bring up the on screen keyboard and navigate it just fine, however no keys I press will be sent to anything else.

**Comment by kozec** [comment]
Check if you have uinput (kernel module) available, loaded and whether you have read _and_ write access to `/dev/uinput` file.

**Comment by CommunistWitchDoctor** [comment]
Confirmed in /proc/modules and with modinfo that uinput is loaded. Also confirmed that /dev/uinput has read/write access

**Comment by kozec** [comment]
Okay, that sounds wrong. What os/distro/de/everything are you using? Try disabling emulation in GUI (through that big ball-icon on top-left), starting `scc-daemon debug` from console and check whether it displays any error.

**Comment by CommunistWitchDoctor** [comment]
I'm using Arch with the 5.5.3 Linux Zen kernel, runnning on an Nvidia Optimus laptop using Optimus Manager, using KDE Plasma 5 as my desktop

Here's the full log output from scc-daemon debug

mitchell@bishop ~ % scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
W SCCDaemon     Skipping disabled driver 'fake'
W SCCDaemon     Skipping disabled driver 'remotepad'
D USB           Registered USB driver for 054c:09cc
D USB           Registered USB driver for 28de:1102
D USB           Registered USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f357f28b310>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f357f103d50>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f357f103c90>
D SCCDaemon     Created control socket /home/mitchell/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
D USB           USB device added: 28de:1142
Exception TypeError: TypeError('super() takes at least 1 argument (0 given)',) in <bound method InputDevice.__del__ of InputDevice('/dev/input/event275')> ignored
D SCDongle      Not requesting serial number for SC sc1
D SCDongle      Got wireless SC with serial sc1
D SCCDaemon     Assigned default_mapper to <SCWireless sc1>
D SCCDaemon     Turning gyrosensor ON
D SCCDaemon     Controller added: <SCWireless sc1>
Exception TypeError: TypeError('super() takes at least 1 argument (0 given)',) in <bound method InputDevice.__del__ of InputDevice('/dev/input/event275')> ignored
I CemuHook      Created CemuHookUDP Motion Provider

(scc-osd-daemon.py:2158): Gtk-WARNING **: 17:12:14.559: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(scc-osd-daemon.py:2158): Gtk-WARNING **: 17:12:14.559: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(scc-osd-daemon.py:2158): Gtk-WARNING **: 17:12:14.560: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
D OSD DaemonCtrl    Connected to daemon, version 0.4.7
D OSD DaemonCtrl    Daemon reported profile change for sc1: /home/mitchell/.config/scc/profiles/Desktop.sccprofile
D OSD DaemonCtrl    Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
D SCCDaemon     SCButtons.A on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.B on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.C on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.X on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.Y on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.START on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.BACK on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.LB on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.RB on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.LPAD on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.RPAD on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.LGRIP on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.RGRIP on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.LT on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.RT on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     LEFT on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     RIGHT on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     STICK on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.STICKPRESS on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.X on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.LT on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.Y on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.RB on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.BACK on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     STICK on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.A on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     LEFT on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.LPAD on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.C on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.RT on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.B on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.STICKPRESS on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.RPAD on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.START on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.LGRIP on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.RGRIP on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     RIGHT on <SCWireless sc1> observed by 7f357d8538d
D SCCDaemon     SCButtons.LB on <SCWireless sc1> observed by 7f357d8538d
I SCCDaemon     Loaded profile '/home/mitchell/.config/scc/profiles/Desktop.sccprofile'
D OSD DaemonCtrl    Daemon reported profile change for sc1: /home/mitchell/.config/scc/profiles/Desktop.sccprofile

As you can see, it's getting the appropriate buttons from the Steam controller. But nothing is passed to the system. I should note the same problems occur with a generic USB Playstation style controller and SC Controller, so the issue does not seem to be unique to the Steam controller.

**Comment by kozec** [comment]
Sorry but I can't see anything wrong there and I haven't be able to reproduce issue with Plasma in VM.

How about `xinput test-xi2` ? Are sc-controller related devices, `SCController Mouse` and `SCController Keyboard` shown there? Does it show any output from them?

**Comment by CommunistWitchDoctor** [comment]
Welp, I tried to run "xinput test-xi2" to find that xinput was not installed on my system at all. After installing xorg-xinput, it became unnecessary to run the command to check if the devices are shown because scc-controller is working now. There is still some trouble with the OSK, are there any other required low level packages that would usually be expected to have by default like xinput that could be causing that?

I'll make a comment on the aur package to add xorg-xinput as a dependency for scc-controller.

**Comment by CommunistWitchDoctor** [comment]
Reopening since I've discovered the problem isn't as solved as I thought it was. Mouse functionality is perfect, but keyboard functionality is not. Keyboard actions assigned to controller buttons or menus behave do not pass to system, but mouse movement and presses do. Which had initilly had me thinking the problem was mostly resolved.

xinput shows SCController Mouse, but not SCController Keyboard

**Comment by kozec** [comment]
Ok, now that's something I haven't seen before O.o

Based on your description, this sounds more like issue with your Xorg configuration as it seems to be unable to handle "hotpluging" of virtual devices that SCC creates. So maybe `/var/log/Xorg.0.log` or `dmesg` and check for evdev messages?

**Comment by kozec** [comment]
I've noticed similar error message as in [#539](https://github.com/kozec/sc-controller/issues/539#issuecomment-589992316) :

> Exception TypeError: TypeError('super() takes at least 1 argument (0 given)',) in <bound method InputDevice.del of InputDevice('/dev/input/event275')> ignored

It looks like bug in `python-evdev` package but I'm not sure if it's causing your problem.

**Comment by CommunistWitchDoctor** [comment]
I haven't had problems with any of my other devices (physical or virtual), so I want to suspected you're onto something with python-evdev. Following that suspicion, I've installed xf86-input-evdev, which seems to be improving things greatly. I can now use the on screen keyboard, as well as both keyboard and mouse actions bound to the controller. The only thing not functioning is media keys (play/pause/volume/etc).

Is there a full list of dependencies somewhere? It would appear that the dependencies for the AUR package are missing some critical packages. I'd like to submit the full list of missing packages to be added as dependencies so that others don't encounter the same issue.

Since xf86-input-evdev has fixed the main issue for me, I'll mark this closed.
