### ISSUE TITLE
OSK and Wayland

### ISSUE THREAD

**Issue by jumpinggoofballs** [kozec/sc-controller#537]
I'm looking to buy a Steam Controller. I don't suppose I could use the OSK under wayland, right?

**Comment by kozec** [comment]
Nope, Wayland still lacks support for anything even remotely similar.

**Comment by jumpinggoofballs** [comment]
Bummer. 

I expected as much based on the previous issues on wayland and OSD stuff - but did not find a specific reference to the keyboard, which is what I was most interested in with the Steam Controller. 

So for future readers: the on screen keyboard will not work under wayland. 

(still awesome project though!)
