### ISSUE TITLE
Request for I/O documentation.

### ISSUE THREAD

**Issue by FancyBanana** [kozec/sc-controller#54]
Hi,  
I'm passively developing a wrapper for steam controller on windows and i would like to ask you if you could provide me with a little bit of documentation on communication with the controller.
I'm mainly interested in packet structure (disabling feedback, toggling gyro, packet structure).
It would really help me with development because python is not my forte.
Thanks a bunch

**Comment by kozec** [comment]
[Scraw](https://dennis-hamester.gitlab.io/scraw/protocol/) has pretty nice documentation about controller protocol.

**Comment by kozec** [comment]
By the way, @FancyBanana , if I may ask, how are you planning doing actual gamepad / keyboard / mouse emulation in Windows? I was under impression that Windows doesn't have libraries for user-space input drivers.

**Comment by FancyBanana** [comment]
For joystick emulation i am planning on using (vJoy)[http://vjoystick.sourceforge.net/site/] which is virtual jostick driver. As for mouse and keyboard, windows has some functions in User32.dll that ca be used to send input events to programs, but it not might work for some programs.
