### ISSUE TITLE
Arm build for rasbperry pi

### ISSUE THREAD

**Issue by TheVetter** [kozec/sc-controller#545]
I think this would be a great project to integrate with [plasma bigscreen](https://plasma-bigscreen.org/) but there needs to be an ARM build, atleast for the rpi version right now. 
Even though this is a python based project it should be just updating how the debs are built. I'd love to learn how to do it if some one pointed me in the right direction

**Comment by kozec** [comment]
Just downloading source and running `python setup.py build` should work, there is nothing x86-dependent in code at all.
