### ISSUE TITLE
Error when enabling emulation... I don't know if this thread is still supported but I'll try Nevermind Solved Because I am an idiot

### ISSUE THREAD

**Issue by MASmax1000** [kozec/sc-controller#546]
![This is a picture of the entire application menu when I load into SC Controller](https://user-images.githubusercontent.com/62804236/77826861-8c7dce00-70e8-11ea-9a84-330b20f7f2b2.png)
I am using the Windows version, on Windows 10. Is there any way to get around this issue?

**Comment by SolitudeSF** [comment]
if it's solved, you can close it.

**Comment by kozec** [comment]
There should be `scc-daemon.exe` next to `sc-controller.exe` you are starting. Try running that one and look for any errors it prints out.
