### ISSUE TITLE
PS4

### ISSUE THREAD

**Issue by essorblood** [kozec/sc-controller#547]
Will OpenStreamController be installed on Raspberry Pi and not be able to use the steam controller for ps4?

Can we use the steam controller for various platforms?

**Comment by kozec** [comment]
Sounds like you are asking at wrong place, but if you meant sc-controller, then yes, it works on Pi and no, it can't make PS4 to accept Steam Controller. Consoles are closed platforms, you can do only what manufacturer specifically allowed.
