### ISSUE TITLE
Allow pads to still operate as OSD menu control when menu display is set to a button

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#55]
I've been experimenting with the OSD menu options and have noticed that pads cannot seem to control the radial menu when any other button is assigned to show the menu nor when it is assigned to clicking/pressing down the pads themselves. Instead it always seems to default to using the analogue stick.

For example, I want to have the right pad act as mouse control when touched like normal, but when pressed it will show the radial menu. While still pressed down, moving the thumb across the pad should control the selection. Releasing the button (even if still touching the pad) should then select the highlighted option and hide the menu.

Instead, no matter which configuration options I try (setting click to display menu, using a modeshift or using a macro) clicking the pad or any other button always results in the left analogue stick being used to control the menu, instead of the pad.

Assigning another button being held down to modeshift the pad so that on touch it shows and controls the menu doesn't work either. Instead holding the button simply displays the menu only if you touch the pad at the exact "Hold Time" value, with the menu again relying on analogue stick control.

**Comment by kozec** [comment]
What you asking is partially possible with [custom action options](https://github.com/kozec/sc-controller/blob/master/docs/actions.md#-menumenu--confirm_buttona--cancel_buttonb--show_with_releasefalse), but setting which pad controlls menu is currently not possible.

I can add it as another custom action option, but I'm afraid I can't imagine any way how to stuff all those options into GUI.
How about that?

**Comment by GlacialTurtle** [comment]
Adding a custom action option would be great. As for the UI, I attempted a mockup in GIMP just to show what I mean:

https://imgur.com/vKqMo3U

Note the Menu Control option, which would only contain left pad, right pad and analogue stick options. I'm not sure if you'd only want to show it when in the modeshift settings seeing as enabling it would temporarily override the original binding, but at least to me the mockup above makes sense and would be fairly straightforward (assuming it would be possible). It would go like:

1. Set right pad press (or any other button) to show menu
2. Set menu control to one of the pads or analogue stick
3. Set other options normally

Then when pressing the show menu button, the menu control binding would cause the OSD menu to temporarily override the original binding you had until it goes away.

**Comment by kozec** [comment]
> Adding a custom action option would be great. As for the UI, I attempted a mockup in GIMP just to show what I mean:
> 
> https://imgur.com/vKqMo3U

Frankly, my main problem with this is that it will make that window stupidly big and empty when anything else is selected. But it's probably better to have big windows *and* options :)

> Then when pressing the show menu button, the menu control binding would cause the OSD menu to temporarily override the original binding you had until it goes away.

This is done always anyway, OSD menu runs in separate process that takes over inputs as long as it runs.

**Comment by kozec** [comment]
So, I ended up putting it to revealer, because... Well, with all options show, that window no longer fits my 10" laptop screen :)

![mooore](https://cloud.githubusercontent.com/assets/1282500/16894038/81781230-4b4a-11e6-9783-c1790ca31afe.png)

**Comment by GlacialTurtle** [comment]
Thank you so much for this!

Just tested it, only 2 issues left is that it seems to block the Clear/OK buttons from functioning in certain weird configs (thanks to my previous experimenting), clearing the offending/conflicting ones seemed to fix it. 

The  second is that the mouse is also suddenly moved to its new position after exiting the menu e.g. in Quake I switch to weapon 3 on the menu by moving moving cursor down, then after release the view suddenly jumps down.

**Comment by kozec** [comment]
> e.g. in Quake I switch to weapon 3 on the menu by moving moving cursor down, then after release the view suddenly jumps down.

Can you attach profile that you are using?

**Comment by GlacialTurtle** [comment]
This should be it:

http://www.pastebin.ca/3661437

**Comment by kozec** [comment]
I need to keep this open, I forgot about it yesterday :(
