### ISSUE TITLE
Smoothing not working in lower half of right pad

### ISSUE THREAD

**Issue by NameDevRandom** [kozec/sc-controller#552]
Mouse smoothing **does work** using left pad and in the upper half of right pad. Smoothing **does not work** in the lower half of the right pad. There I always observe the same level of mouse jitter no matter what smoothing configuration values I choose.
Note: the issue is limited to the lower half of the right pad, on the upper half of the same pad smoothing works as expected.

A fix would be highly appreciated.

Bug is reproducible with versions 0.4.9.4 - 0.4.9.10 using Windows 10 64-bit.

**Comment by kozec** [comment]
Should be fixed in source and in next release.

**Comment by NameDevRandom** [comment]
Great! I will test next release and provide feedback.

**Comment by kozec** [comment]
Fixed in [latest prerelease.](https://github.com/kozec/sc-controller/releases/tag/v0.4.9.11)

**Comment by NameDevRandom** [comment]
Confirmed to work. Thank you for fixing!
