### ISSUE TITLE
New install, onscreen keyboard does not work

### ISSUE THREAD

**Issue by japrogramer** [kozec/sc-controller#56]
i installed sc-controller from aur with yaurt.
0.2.9.1-1  
Everything else is working.

also doesn't work in the git version of the package.

im using arch with xmonad. I do not know how the key presses are implemented
but if they depend on the window manager that may be why .. if changes could be made to make it WM agnostic it would be better for everyone using it.

**Comment by kozec** [comment]
OSD Keyboard creates new virtual keyboard device and sends keypresses through it. It should be equivalent of connecting USB keyboard on the fly and it works even in VTs.

Now, how much it doesn't work? Is keyboard shown and can you control it?

**Comment by japrogramer** [comment]
it works now, after iwoke the machine from a sleep. maybe it had failed too create the virtual device, on a related note can the keyboard be moved?

**Comment by japrogramer** [comment]
i tried the joystick, like the settings seem to indicate, but it does not move,

**Comment by japrogramer** [comment]
also, i can see that the keyboard uses an image to generate the background, it would be nice if we could set which image that is, for customization reasons.

**Comment by kozec** [comment]
> also, i can see that the keyboard uses an image to generate the background, it would be nice if we could set which image that is, for customization reasons.

It's either `~/.config/scc/keyboard.svg` or `/usr/share/scc/images/keyboard.svg`, whatever exists in that order of preference.

> maybe it had failed too create the virtual device, on a related note can the keyboard be moved?

It creates them only once, so it's more like something suspended them and failed to resume them later

> i tried the joystick, like the settings seem to indicate, but it does not move,

Sorry, but I really have to ask you to check it with some other window manager, from what I grasped about xmonad, there is pretty good chance that it ignores override-redirect flag.

**Comment by kozec** [comment]
So, any chance this is *not* related to xmonad?
