### ISSUE TITLE
Could you please build an arm version for debian 10 for the raspberrypi 4?

### ISSUE THREAD

**Issue by ranomier** [kozec/sc-controller#560]
It is available for debian 9, but not for 10

![image](https://user-images.githubusercontent.com/7649949/82250078-21fc4800-994b-11ea-9174-bcfb2c3c341a.png)

Pretty please?

**Comment by kozec** [comment]
I've added same as for debian 9, lets see whether it builds.

**Comment by ranomier** [comment]
seems like it thank you!
