### ISSUE TITLE
SC-Controller wont work using xpadneo.

### ISSUE THREAD

**Issue by DaiKaiser93** [kozec/sc-controller#561]
Benn having some issues getting this to work with my Cyberpunk gamepad, jstest shows that after opening SC-Controller it does make a 360 input device but the controller keeps sending the inputs from the Xbox One Wireless device.
![Screenshot from 2020-05-18 14-32-36](https://user-images.githubusercontent.com/25765658/82261334-a9c66000-9913-11ea-89d3-4b773a136143.png)

**Comment by kozec** [comment]
> from the Xbox One Wireless device

This may be your problem. Since SC Controller emulates xbox controller, it also explicitly ignores any input device that looks like xbox controller to avoid hooking into itself.
