### ISSUE TITLE
Haptic feedback on Windows

### ISSUE THREAD

**Issue by loafofpiecrust** [kozec/sc-controller#568]
I'm trying out sc-controller on Windows, and I love the flexibility but it doesn't seem like `feedback` is working on any inputs. I don't get any response on the haptics. Is there something I have to configure for this to work?

**Comment by kozec** [comment]
Fixed in source, should work in next pre-release. I blame weirdness of Windows handling of HID on this :)

**Comment by loafofpiecrust** [comment]
Awesome, I'll make sure to try it. Then this might beat out the steam configurator for me. Thanks!

**Comment by kozec** [comment]
Fixed in [latest prerelease.](https://github.com/kozec/sc-controller/releases/tag/v0.4.9.11)
