### ISSUE TITLE
Can't open action editor if rotation is set

### ISSUE THREAD

**Issue by joao678** [kozec/sc-controller#570]
I tried changing some of the variables around, but I don't have too much experience with Python so I couldn't figure out what's inside the action variable anyway here's a screenshot
OS: Windows 10

![image](https://user-images.githubusercontent.com/8322552/87253350-dd73c100-c450-11ea-8770-797db848fefd.png)
The configuration file looks like this:
![image](https://user-images.githubusercontent.com/8322552/87253449-b669bf00-c451-11ea-815a-a1e34b0c89f5.png)
The gui looks like this
![image](https://user-images.githubusercontent.com/8322552/87253457-c1245400-c451-11ea-9e89-dc153bb43948.png)

**Comment by kozec** [comment]
No python could help with this, it was not yet implemented. It is now and will be available in next Windows pre-release.

**Comment by kozec** [comment]
Fixed in [latest prerelease.](https://github.com/kozec/sc-controller/releases/tag/v0.4.9.11)
