### ISSUE TITLE
Extreme start/stop mouse jitter when holding in one direction with joystick.

### ISSUE THREAD

**Issue by mpach388** [kozec/sc-controller#576]
Its happening on Windows across multiple steam controllers. When setting the left joystick to mouse output I will get intense jittering almost like the output signal from the controller is being randomly dropped. Its marginally better when rotating the stick around in a circle, but still kind of laggy. When I move the joystick to 100% and hold its not uncommon for the mouse output to stop completely until the stick is moved again. It feels like inputs aren't being registered fully unless the stick is constantly in motion (for example when rotating it around). Everything else works smoothly so it doesn't seem to be input lag and I have tried it with two separate brand new SCs so it doesn't seem to be hardware.

**Comment by kozec** [comment]
Fixed in [latest pre-release](https://github.com/kozec/sc-controller/releases/tag/v0.4.9.12)
