### ISSUE TITLE
Menu: Confirm Selection by "touching" the pad

### ISSUE THREAD

**Issue by ryancordin** [kozec/sc-controller#578]
Is there a way to activate menu items while touching, instead of pressing the pad? In Steam OSD, I've found that selecting menu items with touch saves on hand fatigue, especially for those menu selections that I use often. I've also reserved the clicking action for other events, such as toggling other key presses (like toggling shift that toggles off after touch-release), or for switching to a different touch menu. After switching to touch-based menu selections, I've completely eliminated hand fatigue, which is useful not only for long sessions of gaming, but also while working.

**Comment by ryancordin** [comment]
In Steam’s Controller Configuration menu, the options that are possible for activating menu items on the touchpad are, "click", "button release", "touch release/modeshift end", and "always". The activation styles that I'm describing are the last two. In "touch release/modeshift end", when the user withdraws the thumb from touching the pad, the menu item that was last highlighted is activated. This is useful for menu items that require hesitation before one is certain it is desired (such as choosing the correct sculpt tool in a 3d modeling program). The "always" activation style is similar, but instead of activating on touch release, the menu item is constantly triggered as long as it is highlighted. This last option is useful for complex button mappings, or for holding a modifier key (such as panning the canvas in a 2d graphics program).

An example of a complex button mapping that utilized the "always" activation style, is one from a game I've been playing. In diablo 2, a key press is used to display items on the ground. Instead of binding this to a regular button, I have bound this to a touchpad menu item that “always” activates.  In addition, I have assigned the click action of the touchpad to a modeshift that maps the touchpad to a different menu (also set to “always” activate). This menu is used by keyboard buttons 1-4 that will cause my game character to drink a health or mana potion correlated to the number/quadrant of the touchpad. Since I don’t want to drink all my potions on a single press, I have second action that is fired in sequence that causes the modeshift mapping to end and to revert to the last menu selection. The effect of this mapping is that one button click equals one button pressed, and the key fired depends on the placement of my thumb before pressing but touchpad button.

**Comment by kozec** [comment]
"touch release/modeshift end" was already implemented but little buggy. Next pre-release should have it fixed along with added  "always active" mode,

**Comment by ryancordin** [comment]
Awesome, thank you.

**Comment by kozec** [comment]
Fixed in [latest pre-release](https://github.com/kozec/sc-controller/releases/tag/v0.4.9.12)

**Comment by ryancordin** [comment]
The confirm selection when pad is released seems to be working well on the Appimage for Linux. Thanks for adding this feature. Although there doesn't seem to be an" always active" mode available. I thought that maybe the "cancel menu when pad is released" might be it, but it doesn't appear to be working if it is. Thanks for your work on this. I appreciate being able to use my controller for more than what steam allows.
