### ISSUE TITLE
Feature request: Rotate PAD input, invert axis

### ISSUE THREAD

**Issue by japrogramer** [kozec/sc-controller#58]
I think it would be useful to have the option to invert the pads in either x or y axis. or maybe even rotate the axis, so i could just swipe my thumb left and right, so that it passes across the left pad diagonally and that action is interpreted as up and down, less strain on my thumb.

**Comment by kozec** [comment]
If I understood correctly, you can use negative sensitivity for that.

**Comment by japrogramer** [comment]
i can't seem to set it from the gui.

**Comment by japrogramer** [comment]
oh, i was able to edit the profile from a text editor, it works . thanks

**Comment by kozec** [comment]
> might be useful to let the sliders, have negative values for the pads sensitivity

I don't know about any way how to make slider going to negative value, but skip zero and setting zero there may lead to crash, so this feature really belongs to advanced / custom action editor :)

**Comment by japrogramer** [comment]
or maybe a check box that multiplies the sensitivity by -1

**Comment by kozec** [comment]
> or maybe a check box that multiplies the sensitivity by -1

Just out of curiosity, what's actual use-case for reverting axis?

But I somehow skipped over that rotating axis part, that sounds interesting. I'll reopen this as TODO :)

**Comment by japrogramer** [comment]
lets say that its easier for me to use if up wasn't directly up but of by a few % in the z axis, so that up is now pointing slightly to left or right. I would find this useful especially in applications where the pads up and down action would be required often, like scrolling a page or in an mame game
