### ISSUE TITLE
Input validation for repeat a little off [C / Windows branch] [4.9.11]

### ISSUE THREAD

**Issue by mtwomey** [kozec/sc-controller#580]
This following works fine if I edit it straight into the profile file. However, in the UI, the input validation is in a weird state and won't let me save it.

![image](https://user-images.githubusercontent.com/7715262/91641667-8d928e80-e9eb-11ea-96ca-80826d92a4c0.png)

**Comment by kozec** [comment]
Fixed in [latest pre-release](https://github.com/kozec/sc-controller/releases/tag/v0.4.9.12)
