### ISSUE TITLE
OSD Custom Actions don't fire [4.9.11]

### ISSUE THREAD

**Issue by mtwomey** [kozec/sc-controller#582]
I've created a custom menu - but the items don't fire for some reason. First I tried creating with the inbuilt generator (via the GUI):

```
[{
    "name": "Choose", 
    "separator": true
}, {
    "action": "name('Say Hello', type('hello'))", 
    "icon": "system/keyboard", 
    "id": "item2", 
    "name": "Say Hello"
}, {
    "action": "name('Say Goodbye', type('goodbye'))", 
    "icon": "system/keyboard", 
    "id": "item3", 
    "name": "Say Goodbye"
}, {
    "action": "name('Test', button(KEY_T))", 
    "icon": "weapons/baseball-bat", 
    "id": "item4", 
    "name": "Test"
}]
```

Then I noticed that the default menus don't wrap the action in a `name` clause. So I hand build one:

```
[{
    "name": "Choose", 
    "separator": true
}, {
    "action": "type('hello')", 
    "icon": "system/keyboard", 
    "id": "item2", 
    "name": "Say Hello"
}, {
    "action": "type('goodbye')", 
    "icon": "system/keyboard", 
    "id": "item3", 
    "name": "Say Goodbye"
}, {
    "action": "button(KEY_T)", 
    "icon": "weapons/baseball-bat", 
    "id": "item4", 
    "name": "Test"
}]
```

In either case, nothing outputs when I make a menu selection.

**Comment by mtwomey** [comment]
Additional note, actions like "Turn off controller" do work, but it seems that actions the involved pressing a button on the controller or keyboard (or "type"ing) don't work.

**Comment by kozec** [comment]
Fixed in [latest pre-release](https://github.com/kozec/sc-controller/releases/tag/v0.4.9.12)
