### ISSUE TITLE
Modshift buttons missing (Branch C)

### ISSUE THREAD

**Issue by ren2r** [kozec/sc-controller#585]
I was trying to set some modshift for certain buttons, and could not set the modshift to activate with the buttons "BACK", "STICKPRESS", "RPADPRESS" and "LPADPRESS", looking in the code I could notice that those variables is missing in the file "./src/conversions/string_constants.c" and by puting then there I could get the daemon to recognize these modshift. 
I would submit a pull request, but as the python code has some Pad actions mapped with the words without "PRESS", I thought I could break something.
Would you kindly take a look at this?

**Comment by kozec** [comment]
Fixed in c branch.

**Comment by kozec** [comment]
Fixed in [latest pre-release](https://github.com/kozec/sc-controller/releases/tag/v0.4.9.12)
