### ISSUE TITLE
Radial menu is clipped, if display scaling is greater than 100%

### ISSUE THREAD

**Issue by DrPepperBianco** [kozec/sc-controller#587]
I tested in Ubuntu 20.04. My display resolution is 3000x2000 and scaling is 200%, because the display is not that big. The menu is scaled too much. The circle, where the menu should be is scaled correctly. The content seems to have been scaled like 400% instead. Anything  that doesn't fit in  the circle is clipped.
It is not possible to use it.
If I change display scaling to 100% everything works perfectly.
The list menu is working correctly.

**Comment by kozec** [comment]
Fixed in git, I'm going to make release with fix, but I have to figure how to get it running on Ubuntu 20.xx first.
