### ISSUE TITLE
Comfirm menu selection when pad is released doesn't work

### ISSUE THREAD

**Issue by Kojlax** [kozec/sc-controller#589]
Tested on Manjaro 20.1.2 on budgie desktop, with the sc-controller package off of AUR, 
When touching a pad is set to a menu, and "Confirm selection when pad is released", releasing the pad will close the menu, but not activate the action. This is true on all versions of the menu, list, grid, radial, and horizontal menu, and with both default menus, as well as my own custom menu.

**Comment by Kojlax** [comment]
apparently the AUR version of sc-controller has been changed to Ryochan7's python3 branch, but I've checked on the latest AppImage release, and this is still an issue

**Comment by kozec** [comment]
I was able to fix the issue but I dont think I'll be able to get it to AUR.
