### ISSUE TITLE
Deleting user profiles

### ISSUE THREAD

**Issue by tcarrio** [kozec/sc-controller#59]
I haven't noticed any way to delete profiles created by the user so far (through the program). 

This would be an excellent addition to the application, and I've already forked the project and looked over the code to get started on the process. I'm hoping to get to this sometime this week and conduct testing. 

**The scope includes a button beside the profile dropdown, which would be enabled when on user-generated profiles that would delete the profile from the ~/.config/scc/profiles/ directory. System profile will not be affected by this change, unless you would prefer that.**

Let me know if this is something that interests you

**Comment by kozec** [comment]
Sounds good, I had something like that in very-long-term todo list. But as I don't think that option will be used too often, context menu may fit better than button.

> System profile will not be affected by this change, unless you would prefer that.

System profile (file in /usr/share) cannot by deleted by user anyway, but removing modified version from  ~/.config... can be used as way to reset it to default version.

**Comment by tcarrio** [comment]
I mostly meant the option to delete would be disabled on system profiles, although they wouldn't be able to even if the application tried. 

I can throw up a mockup later, but I was thinking just a button alongside the `cbProfile` dropdown, which would be disabled if it is a system profile. 

It may not seem like an option that would be used often, but within an hour I already wanted to delete a profile I'd created and saw there wasn't any way to go about that. Oops. 

Anyway, I'm glad to hear you've though about this before. If I can get to it this evening I will post back here with the change to the GUI just to show you what I'm thinking!

**Comment by tcarrio** [comment]
![Screenshot](http://i.imgur.com/k0AV6ZQ.png)

This is the idea that I had for a delete option. Simple and would show up similar to the Save button when a non-system profile is selected.

**Comment by kozec** [comment]
:+1: that looks good. Maybe just that padding can be smaller.

**Comment by tcarrio** [comment]
Ah yes of course, didn't notice I'd left that in there. Oops :laughing: 

I'll have it flush with the right border. I'll have time later to work on logic to show it only on user-generated profiles.

**Comment by kozec** [comment]
>  I'll have time later to work on logic to show it only on user-generated profiles.

Basically, if
<pre>"%s/%s.sccprofile" % (<a href="https://github.com/kozec/sc-controller/blob/master/scc/paths.py#L35">get_default_profiles_path()</a>, profile_name) </pre>
file exists, profile is not user-generated.

**Comment by tcarrio** [comment]
I like it :smile: it's the exact opposite of what I would have done, calling on [`get_config_path()`](https://github.com/kozec/sc-controller/blob/dd7cb613b399e700d28d6529874de34f9b38c1d9/scc/paths.py#L16) instead, so I'm glad I had the right idea.

**Comment by kozec** [comment]
By the way, are you working on this in any way?

If not, I'm planning to add context menu with delete and rename options as next small thing.

**Comment by tcarrio** [comment]
A context menu is a better solution than mine, if you're thinking of doing that, I'll let you take that one 😁
