### ISSUE TITLE
[BUG] DPAD Locking if LStick pressed

### ISSUE THREAD

**Issue by PowerUser64** [kozec/sc-controller#598]
If you move the Left Stick in a direction, then press a direction on the DPAD down, **the left stick's button (L3) and the direction you pressed on the DPAD get spammed**. Then, if you let up on the DPAD, L3 stops getting spammed, but the DPAD still gets spammed until pressed and released in the direction that is getting spammed.

I discovered this when I tried to whistle sprint in Breath of the Wild in the Cemu Emulator. If my explanation was confusing, there's a 16-second demonstration of this motion at the 0:20 timestamp in this video.
https://www.youtube.com/watch?v=Wn4aa8bY8ZQ&t=20s

**Comment by kozec** [comment]
Just in case, which controller are we talking about? Playstation / Dualshock 4?

**Comment by PowerUser64** [comment]
Steam Controller

**Comment by PowerUser64** [comment]
The latest release didn't seem to fix the issue. Here is a demo I made of it:
https://www.youtube.com/watch?v=YTKDohw8XMM
I put some notes detailing the parts of the bug and what I am doing in the description
