### ISSUE TITLE
Unable to set Left Stick sensitivity

### ISSUE THREAD

**Issue by azizLIGHT** [kozec/sc-controller#6]
The left stick (Joystick/Mouse Action type) sensitivity setting isn't getting recorded for some reason. If I set it to anything and hit OK, then if I check it again, it will have reverted back to 0.01.

**Comment by kozec** [comment]
Ah, yes, that sensitivity slider works only for mouse emulation, stick is always mapped 1:1.
Would any other mapping make any sense?

**Comment by azizLIGHT** [comment]
Hmm, I was getting the feeling that it's not mapped 1:1 and might be a bit slower. I noticed that my turn radius is much bigger in Rocket League.

**Comment by kozec** [comment]
Fixed by 387e12e535425f8d57c2b60ac105083eb7490896

**Comment by kozec** [comment]
By the way, I'm still not sure it this does what one would expect... 

Now if stick sensitivity is set to, let's say, 8.0, slightest touch of physical stick throws virtual stick off limits and when set to 0.4, I can only do circle around this large:

![circle](https://cloud.githubusercontent.com/assets/1282500/15079936/c117e04e-13bb-11e6-915b-d5bd5f60f785.png)


It makes perfect sense for mouse, but not so much for sticks, imho.

**Comment by azizLIGHT** [comment]
This seems to be helping believe it or not. I have the sensitivity set to 1.5 and get more range out of the sticks.

I found[ this thread on reddit](https://www.reddit.com/r/RocketLeague/comments/4dvcym/issue_using_a_ps4_controller_puts_you_at_a/d1uw66j) that details the difference in sensitivity/range between the DS3 and DS4 controllers. At 1.0 sensitivity, the steam controller felt like the DS4, but at 1.5 sensitivity I'm more closer the the DS3 now and it feels a bit better.

**Comment by azizLIGHT** [comment]
[This post](https://www.reddit.com/r/RocketLeague/comments/4dvcym/issue_using_a_ps4_controller_puts_you_at_a/d1uqf2h) distills the issue down quite nice.

**Comment by kozec** [comment]
> This post distills the issue down quite nice.

Interesting problems... Thanks, I think I understand now.
