### ISSUE TITLE
Travis-CI testing

### ISSUE THREAD

**Issue by tcarrio** [kozec/sc-controller#60]
This isn't anything particularly wrong with your application, but if you were to include Travis-CI testing on this you could have continuous testing on any proposed pull requests and commits in the future, allowing for more elaborate testing and confirmation that your changes haven't broken anything. 

At the very least, you would know if a proposed pull request broke Gtk by including your `run.sh` in the test script, which faults if there are any issues in the Glade files or GUI logic. 

I was thinking I might make a `.travis.yml` test script as an example in another branch to see how well it works, but I know several projects with successful Gtk testing through Travis-CI. 

If you're interested, [this is what I'm talking about](https://travis-ci.org/). I'll put together a small build script later on with my own fork.

**Comment by kozec** [comment]
I have some tests made with pytest, including one that test if glade file will fail to load on Ubuntu. But I cannot quite imagine how would Travis test GUI part...

**Comment by tcarrio** [comment]
Whatever tests you can run with pytest can be utilized in Travis-CI as well.

**Comment by tcarrio** [comment]
It would be helpful since it integrates into Github projects, and when someone submits a PR, it will tell you if those tests have been passed.

**Comment by kozec** [comment]
Do you happen to know about any GTK-based application that uses Travis?

**Comment by kozec** [comment]
Woo, it actually works 8-)

At least for non-gui part.

**Comment by tcarrio** [comment]
Yeah it's pretty useful and it'll run every time a PR or commit is pushed, you can also reference the status in the README so on the Github page it will show the status of the latest build. 

[![Build Status](https://travis-ci.org/kozec/sc-controller.svg?branch=master)](https://travis-ci.org/kozec/sc-controller)

That one is yours: 
`[![Build Status](https://travis-ci.org/kozec/sc-controller.svg?branch=master)](https://travis-ci.org/kozec/sc-controller)`

**Comment by kozec** [comment]
You mean like one that's in README.md file?

**Comment by tcarrio** [comment]
Yes, oops :fearful:

**Comment by kozec** [comment]
:laughing: No problem, I just found it in tutorial.

Anyway, I'll close this after I figure how to add tests to that GTK part. That's part that has breaking tendencies.

**Comment by kozec** [comment]
I'll just close it, I have test for most frequent case that broke GUI and running GUI tests without X never worked reliably.
