### ISSUE TITLE
Using two steam controllers at the same time?

### ISSUE THREAD

**Issue by jose1711** [kozec/sc-controller#609]
Not sure if this is unsupported or I am doing something wrong. I have two SCs registered to one wireless receiver. `sc-controller` sees both: one indicated by green icon, the other by blue one. If I run the first controller I am presented with an OSD menu where I can select one of the profiles, starting up the second controller also brings up a menu but navigation is impossible and OSD is simply stuck.

When the 2nd controller is turned on the following message appears in debug log:
```
Daemon reported unknown profile: 'None'; Overriding.
```

Also I tried to set different profiles for each controller but that does not work either. Or maybe I need to have one receiver per controller for this to work?

**Comment by jose1711** [comment]
FWIW connecting via USB makes no difference - the first controller connected always wins. Input from the second controller is ignored. Independent controller configuration is possible and working with [qjoypad](https://github.com/panzi/qjoypad).

**Comment by kozec** [comment]
Thats definitelly something that shouldn't happen. Which version of SCC are we talking about?

**Comment by jose1711** [comment]
> Thats definitelly something that shouldn't happen. Which version of SCC are we talking about?

`sc-controller 0.4.8.2`. if you want me I can try couple other versions (or git revisions)

**Comment by FrankyB** [comment]
Just wanted to chime in that I have the same problem since some versions (nut sure since when as I dont play often" At first I though the controller was broken. But its definitely sc-controller because in Steam they work both nicely.

I used them together maybe two months ago (using arch, so I had no idea when it updated sc-controller)

If I should help I will be there :-)

**Comment by jose1711** [comment]
Thank you for sharing, if you're convinced this is a regression it should be fairly easy to find using git bisect.

**Comment by jose1711** [comment]
Oh, I just discovered I am not using this fork/branch but instead https://github.com/Ryochan7/sc-controller/releases/tag/v0.4.8.2. Sorry about that. @FrankyB running Arch Linux by any chance?

**Comment by jose1711** [comment]
@kozec Any chance you could transfer this to Ryochan7's fork (default branch: `python3`)?

**Comment by FrankyB** [comment]
> Oh, I just discovered I am not using this fork/branch but instead https://github.com/Ryochan7/sc-controller/releases/tag/v0.4.8.2. Sorry about that. @FrankyB running Arch Linux by any chance?

@jose1711 Actually, yes I run on Arch. Also v0.4.8.2 and I am sure it worked. I doubt my coding knowledge is good enough for using bisect, though

**Comment by jose1711** [comment]
@FrankyB if you check the comment at https://aur.archlinux.org/packages/sc-controller/ you'll find:

> The package is now based on Ryochan7's Python 3 fork.

From October 26th, 2020. Up until that day it was using kozec's fork. Maybe that explains it?

**Comment by FrankyB** [comment]
@jose1711 actually it does. I built Ryochan7's fork and it has that exact bug using two controllers.

**Comment by jose1711** [comment]
Closing as invalid (wrong fork)
