### ISSUE TITLE
[Question] Is there a way to simulate button smashing/holding by only clicking a button once?

### ISSUE THREAD

**Issue by Toadfield** [kozec/sc-controller#619]
In many games,there is that nasty button pressing or button holding that you have to do.
So is there a way to set that you enable that by pressing a button once and it gets disabled if you press that button again?

**Comment by SolitudeSF** [comment]
![image](https://user-images.githubusercontent.com/10168645/105644373-edf40200-5e9d-11eb-80fc-479cb16d0f92.png)

**Comment by Toadfield** [comment]
thanks
