### ISSUE TITLE
Disable when steam is active.

### ISSUE THREAD

**Issue by xraynorm** [kozec/sc-controller#62]
Hi.

Thanks for working on this.

Is there away for sc-controller to detect if steam is running and if it is let steam take over, and when steam exits enable sc-controller again?

**Comment by kozec** [comment]
That's not *entirely* impossible in SC-Controller, but still pretty complicated.
Doing something like `alias steam="scc-daemon none stop ; steam"` would be probably much faster :)

**Comment by xraynorm** [comment]
Thanks for your reply. 

Any ideas how I would get steam to start SC-controller when it exits?

**Comment by kozec** [comment]
Well, adding command to start daemon at end of that alias should be enough, but you'd need to set profile to load there.

```
alias steam="scc-daemon none stop ; steam ; scc-daemon ~/.config/scc/profiles/Desktop.sccprofile start"
```

I definitely should add some way to simplify that command :)

But, I got the idea. I can add option for SC-Controller to release controller device for while. Steam is quite pushy and grabs it in 5s or so, so if you bind that to menu, or make it as action to be executed when Steam window is active, it would basically do what you want. Then, when you exit steam, SC-Controller will regrab device automatically when it became available again.

Which option sounds less crazy?

**Comment by xraynorm** [comment]
Thank you.

This information have has been very useful. I have a script now that starts steam when I exit kodi, and vice versa. The steam controller works now when switching between the two, by starting and stopping the daemon. This is great for HTPCs.

Thanks again.

**Comment by kozec** [comment]
Np, I'm glad it worked for you after all :)
