### ISSUE TITLE
Gyro's Y axis is inverted

### ISSUE THREAD

**Issue by Xodetaetl** [kozec/sc-controller#63]
Setting the gyro as "Joystick or Mouse", I expect to see my cursor go up when I point up with the SC, but it goes down instead. It's perhaps the expected behavior when emulating a joystick, but not a mouse. There is no option to revert this.

**Comment by kozec** [comment]
> There is no option to revert this.

Click on "more" and set Y sensitivity to -1. But I can probably fit checkbox there as well.

**Comment by Xodetaetl** [comment]
Oh, well yeah, that's not intuitive.

Ideally Mouse mode would be separate from Joystick mode and have the expected defaults (yaw for X and inverted Y, as well as more sensibility and activate only when right-pad touched).

**Comment by kozec** [comment]
Changing how it behaves by default is not good idea at this point, that would invert Y axis for everyone who is already using gyro-to-mouse mapping. But pre-setting activation by right pad sounds good, after some playing with gyro I too don't think that anyone leaves it always active.

**Comment by Xodetaetl** [comment]
> Changing how it behaves by default is not good idea at this point

Then what about a "presets" menu that switches between joystick and mouse defaults when activating one or the other option?

**Comment by kozec** [comment]
True, I can probably make that Invert Y checkbox flipping itself when mode goes from joystick to mouse or vice-versa...

**Comment by kozec** [comment]
Soo... I found that in fact, I already *did* changed how default gyro-to-mouse behavior works and inverted Y axis by mistake :(

I'm ofc going to fix it and add code to old profile format loader to convert old settings, what basically means that when I'm on it, I can fix that mouse sensitivity as well.

Question is, by "more sensibility" for mouse, you mean that mouse should move slower by default, when controlled by gyros?

**Comment by Xodetaetl** [comment]
Sorry I meant sensitivity, not sensibility. :p 
So I mean it should move faster. At sensitivity 1 it feels very sluggish: To get accross my screen horizontally I have to drop the mouse, move back and grab it again two times so I can travel the whole distance. Isn't it the same for you? What feels right for me is a sensitivity between 4 and 6. But I like it pretty responsive. I'd set it to 3 or 4 by default.

In fact it looks like you're never really used the gyro as a mouse, have you? If not, you really should, it's the best thing in the controller! After a couple dozen minutes of training, you get 95% as fast and accurate as with a mouse, it's so much better than using the pad! (Though the pad is still useful for some moves like large swipes.)

**Comment by Xodetaetl** [comment]
PS: same with the trackpad as mouse actually, default sensitivity is waaay too slow.
But maybe that's just me.

**Comment by kozec** [comment]
I'm using gyro only for aiming in game, where slow movements are much better. But I think I know how to do this:

"Mouse (camera)" will be split to two modes:
- "Mouse", where sensitivity will default to values comfortable for moving mouse around screen
- "Mouse (aim)", where sensitivity will be as it is now.

That's also UI-only change, so it would not affect anyone who already has profiles set up.

**Comment by Xodetaetl** [comment]
Sounds good!
