### ISSUE TITLE
Python Error On Arch Linux

### ISSUE THREAD

**Issue by HurricanePootis** [kozec/sc-controller#646]
Whenever the scc daemon starts to run, I recieve this error in the stdout of the `sc-controller` process

```
pidfile /home/borowski/.config/scc/daemon.pid does not exist. Daemon not running? 
W App           Failed to read release notes 
E App           g-io-error-quark: Operation not supported (15) 
Traceback (most recent call last):   
    File "/usr/lib/python3.9/site-packages/scc/gui/app.py", line 1516, in http_ready     
    stream = f.read_finish(task) 
gi.repository.GLib.GError: g-io-error-quark: Operation not supported (15) 
W App           (above error is not fatal and can be ignored) 
```

Here are all of the python packages installed on my Arch Linux install:
```
borowski@TheCloutPC ~ $ paru -Q | grep python
python 3.9.6-1
python-appdirs 1.4.4-3
python-avalon_framework 1.8.2-1
python-cairo 1.20.0-3
python-chardet 4.0.0-2
python-colorama 0.4.4-3
python-dnspython 1:1.16.0-3
python-evdev 1.4.0-1
python-gobject 3.40.1-1
python-greenlet 1.1.0-1
python-idna 3.2-1
python-lxml 4.6.3-1
python-magic 5.40-1
python-markdown 3.3.4-1
python-more-itertools 8.7.0-1
python-msgpack 1.0.2-2
python-numpy 1.20.3-1
python-ordered-set 4.0.2-3
python-packaging 20.9-1
python-pidfile 3.0.0-2
python-pillow 8.3.1-1
python-ply 3.11-7
python-psutil 5.8.0-1
python-py-cpuinfo 8.0.0-1
python-pyaml 20.4.0-4
python-pyelftools 0.27-1
python-pygments 2.9.0-1
python-pylibacl 0.5.4-5
python-pynvim 0.4.3-1
python-pyparsing 2.4.7-3
python-pyqt5 5.15.4-1
python-pyqt5-sip 12.9.0-1
python-requests 2.25.1-1
python-setuptools 1:57.4.0-1
python-six 1.16.0-1
python-tqdm 4.61.2-1
python-urllib3 1.26.6-1
python-vdf 3.4-1
python-yaml 5.4.1.1-2
python2 2.7.18-3
python2-appdirs 1.4.4-3
python2-ordered-set 3.1.1-3
python2-packaging 20.9-1
python2-pyparsing 2.4.7-3
python2-setuptools 2:44.1.1-1
python2-six 1.16.0-1
```

**Comment by HurricanePootis** [comment]
Never mind. I figured out the problem was that the Arch package doesn't listen the package `gvfs` as a requirement, which is required for one the dependencies. I am pretty sure Gnome and XFCE come with `gvfs` automatically, so maybe that's why the never noticed a need to add it to the dependencies list on the PKGBUILD.

**Comment by parkerlreed** [comment]
I maintain the sc-controller-git AUR PKGBUILD. I am running KDE without gvfs installed at all and sc-controller works fine (FWIW we are using the Python 3 fork in both stable and git PKGBUILDs) https://github.com/Ryochan7/sc-controller

**Comment by rah2501** [comment]
> the Python 3 fork

Why is there a fork rather than a merge request to add Python 3 support to the main project?

**Comment by Ryochan7** [comment]
> > the Python 3 fork
> 
> Why is there a fork rather than a merge request to add Python 3 support to the main project?

Maybe because this has been an active topic for over 2 years now and Kozec has expressed his opinion several times over. If that is what he wanted, it would have been done. Read past posts.

**Comment by Ryochan7** [comment]
https://github.com/kozec/sc-controller/issues/367
https://github.com/kozec/sc-controller/issues/498

**Comment by rah2501** [comment]
> because this has been an active topic for over 2 years now and Kozec has expressed his opinion several times over

If the python 3 fork is intended to be permanent then why hasn't the project's name been changed?  Why is it still called sc-controller?
