### ISSUE TITLE
Mouse axes are not clickable in Select Axis dialog (gyro)

### ISSUE THREAD

**Issue by Xodetaetl** [kozec/sc-controller#65]
When setting up the gyro in Per Axis mode, I can choose the axis to emulate for pitch/yaw/roll but the mouse axes are not responsive, can't select them.

**Comment by kozec** [comment]
Gyro currently can't control ony one mouse axis, but it's probably possible to stitch it there. But is there any game or other case where such setup could be used?

**Comment by Xodetaetl** [comment]
Forget about it then, it was just a way for me to workaround the inverted Y axis issue.
