### ISSUE TITLE
Add link to Patreon

### ISSUE THREAD

**Issue by Xodetaetl** [kozec/sc-controller#66]
I've encouraged people to support you [on Reddit](https://www.reddit.com/r/linux_gaming/comments/4u85ax/libre_steam_controller_gui_drivers_developer_is/), but if you really want to one day be able to work full time on your libre projects, you should integrate payment options in your app(s).

If you're doing this seriously, avoid calling it "donations" or even "support". It's better to say "pay what you want", "name your price" or the like.

I'd have a bar that says something like "SC-Controller is a Pay What You Want application. If you like it, please consider backing us on Patreon". With a "Not now / Already done!" button to hide it.

Edit: Some people will surely prefer making a one-time payment, so you should have a paypal button too.

Edit 2: The "Not now / Already done!" button should actually better be separated into two buttons, with the "Not now" one hiding the bar for a couple months (for example) and the second one hiding it permanently.

**Comment by kozec** [comment]
Wow, thanks, I was wondering what in the world happened :D

I'm not big fan of bars with sole purpose of money gathering, but I was thinking of some kind of ["Did you know dialog"](https://docs.gimp.org/en/images/menus/help/tip-of-the-day.png) or infobar that would inform about non-immediately clear options that SC-Controller has and I definitely could add "Did you know you can pay for this" to that list, or as separate button.

But one-time paypal button sounds like good idea, I'll check how can I add that.

**Comment by C0rn3j** [comment]
@kozec  Afaik you get more money through Paypal, is this right?

If I try to donate 1 USD on patreon, I have to pay 1.21 USD because VAT, and then Patreon takes a cut.

Instead if I try to donate 1 EUR through Paypal however I actually get charged 1 EUR. 

The question is, from which option do you get more money, percentage wise?

**Comment by kozec** [comment]
I believe PayPal takes ~3%, what's definitely less than Patreon does.
