### ISSUE TITLE
Add profiles import from Steam

### ISSUE THREAD

**Issue by Xodetaetl** [kozec/sc-controller#67]
[Partially from discussion [on reddit](https://www.reddit.com/r/linux_gaming/comments/4u85ax/libre_steam_controller_gui_drivers_developer_is/d5ok6ww)]

Useful information to implement this:

A list of profiles for each user lies at the bottom of `~/.steam/steam/userdata/<user_ID>/7/remote/sharedconfig.vdf`

The list contains:
* The game's Steam ID, used to retrieve the game's name from the Steam API: either this [list of all Steam games](http://api.steampowered.com/ISteamApps/GetAppList/v0001) (fat!) or this [detail of a game](http://store.steampowered.com/api/appdetails?appids=504360).
* The workshop game ID, to retrieve the full profile file: `~/.steam/steam/steamapps/workshop/content/<workshop_user_ID>/<workshop_game_ID>/controller_configuration.vdf`
* Or if not the workshop ID, it can be the template used (from `~/.steam/controller_base/templates/`)

The user's name can be found in the friends list in `~/.steam/steam/userdata/<user_ID>/config/localconfig.vdf`

And workshop_user_ID can be found in `~/.steam/steam/userdata/<user_ID>/ugc/consumed.vdf`

**Comment by kozec** [comment]
Just so it doesn't looks like I'm ignoring this:
- I'm currently trying to figure differences between vdf "version 2", vdf  "version 3" and when is which version used.

**Comment by kozec** [comment]
Sooo... [Latest release](https://github.com/kozec/sc-controller/releases) has kinda experimental Steam profile import. Experimental means that it works for me and now I'll need few people to check if it works for them as well :)

**Comment by richese** [comment]
Hi,
the import works only for games which are installed in in the default steam library folder located at `.local/share/Steam/steamapps`.
If a game is located in different steam library folder it fails since its app manifest and workshop data seem to be part of the steam library the game is installed in.
There seems to be a list of all library folders in `.local/share/Steam/steamapps/libraryfolders.vdf`.

P.S. Well it seems steam also downloads all(?) controller configs to the default folder but it does not do so until you install at least one game to that folder (steamapps folder is empty until you install something). :confused:

**Comment by kozec** [comment]
> There seems to be a list of all library folders in .local/share/Steam/steamapps/libraryfolders.vdf.

Good to know, reading that and iterating over all libraries shouldn't be a problem.

**Comment by mulark** [comment]
For what it's worth, opening the Import Steam Profile window doesn't actually populate the list with any titles. Relevant console output below:
`(sc-controller:19867): Gtk-CRITICAL **: gtk_assistant_set_page_has_padding: assertion 'child != NULL' failed
E ImportDialog  u'userroamingconfigstore'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/import_dialog.py", line 58, in _load_profiles
    i = self._parse_profile_list(i, sharedconfig)
  File "/usr/lib/python2.7/site-packages/scc/gui/import_dialog.py", line 76, in _parse_profile_list
    cc = data["userroamingconfigstore"]["controller_config"]
KeyError: u'userroamingconfigstore'
`

Dragging and dropping .vdf directly onto the application seems to more or less work. Stick clicks seem to not be preserved though.


mouse_region seems to cause import to fail, if present. Output from log attached.

[import_fail_mouse_region.txt](https://github.com/kozec/sc-controller/files/400768/import_fail_mouse_region.txt)

**Comment by kozec** [comment]
@mulark Two questions:

1. Do you have more than one user directory in `~/.steam/steam/userdata/` ?
2. Can you check if there actually is any 'controller_config' in `~/.steam/steam/userdata/<your_id>/7/remote/sharedconfig.vdf` ?

**Comment by mulark** [comment]
1. Only one directory
2. `{"selected"		"usercloud://controller_config/c078c7cea8b984145d46d9a5b1410bace12a4099/gamecube .vdf"}`
Exists, but it's non-steam game, and curiously the only case of controller_config. There is a lot of template://x.vdf which I would expect should be importable.

**Comment by kozec** [comment]
> There is a lot of template://x.vdf which I would expect should be importable.

Why? That would import one of Steam default profiles for which SC-Controller already has equivalent.

```
[tom@silver remote]$ grep template sharedconfig.vdf | sort | uniq -c
      8 			"selected"		"template://gamepad_fps.vdf"
      5 			"selected"		"template://gamepad_joystick.vdf"
      1 			"selected"		"template://gamepad+mouse.vdf"
      7 			"selected"		"template://wasd.vdf"
```

**Comment by mulark** [comment]
It may be an artifact of some of my past meddling but: 
`     14 			"selected"		"template://Woodsies Dolphin GameCube.vdf"`
~~Where does steam normally put exported user template?~~ Looks like it's actually a template I downloaded from steamcontrollerdb.com that's now set as a global template. Probably not expected use case.

**Comment by kozec** [comment]
> Probably not expected use case.

Not really, but I plan to make steamcontrollerdb.com format importable by doubleclicking, so that should be covered as well.

**Comment by kozec** [comment]
With above fix, I'm pronouncing this feature done.
