### ISSUE TITLE
Is there any way to use two USB devices on one "virtual controller"

### ISSUE THREAD

**Issue by EzequielBruni** [kozec/sc-controller#679]
Hey there,

I like to use my HOTAS setup (A Logitech x56 throttle and a VKB Gladiator Pro stick) for games that don't necessarily support them, e.g. No Man's Sky. On Windows I would use x360ce or Virtual Controller to combine the two devices into one virtual Xbox 360 game pad.

On Linux, Steam itself recognizes my stick, but not the throttle (which HOTAS-supporting games recognize just fine), so using Steam's own mapping option isn't going to work. In SC Controller, I've tried mapping both of my devices to one profile or another, but nothing really seems to work, and I'm not entirely sure if what I'm attempting is possible. If it is, could I get a guide on how to assign two controller devices to one virtual controller, and how to make Steam see it?

P.S. Other things I've tried: I got AntiMicroX to emulate keyboard and mouse movement successfully, but I'd rather emulate controller inputs.

**Comment by kozec** [comment]
Not right now, at least not wihout some level of hacking. For every real gamepad connected, new virtual gamepad is created and linked with it.

**Comment by EzequielBruni** [comment]
@kozec Thanks for the info. Closing this one out then.
