### ISSUE TITLE
[Question] Need help for combining right-pad trackball/mouse with holding a button

### ISSUE THREAD

**Issue by michaelbutler** [kozec/sc-controller#681]
Hi I have spent hours trying various configurations but still haven't arrived at a solution (specifically for the game Final Fantasy XIV) so I decided to open this GitHub issue :-)

Unlike many games, FFXIV requires holding a mouse button to move the camera. The way this is done with the Steam Controller in normal Steam API is to set the right track pad as trackball mouse movements, but to hold a specific button down (Right Mouse BTN) for as long as the virtual trackball is "active".

In sc-controller, I have gotten close to this but it's not playable yet. Here are things I have tried:

```
press(button(Keys.BTN_RIGHT)) and rotate(4.5, smooth(6, 0.56, 2, feedback(RIGHT, sens(1.2, 1.2, ball(1.995, mouse())))))
```

```
press(button(Keys.BTN_RIGHT)); rotate(4.5, smooth(6, 0.56, 2, feedback(RIGHT, sens(1.2, 1.2, ball(1.995, mouse())))))
```

In the first example I used `and` and in the second I used `;` . The first one has the best results so far, but the problem is, as soon as your finger leaves the touchpad, it stops pressing BTN_RIGHT, meaning the camera stops moving but the mouse cursor flies across until the trackball motion comes to a complete stop.

**Is there a way to have a mouse button held down for the complete duration of a trackball swipe until the trackball stops moving?**  e.g. something like: `PRESS_RIGHT_BTN; do_trackball(); on_trackball_end(): RELEASE_RIGHT_BTN`

**Comment by kozec** [comment]
It's not really possible to detect that trackball has stopped 'rolling', but wouldn't simple timer work?

```
touched(  press(button(Keys.BTN_RIGHT)); sleep(2.000); release(button(Keys.BTN_RIGHT))  ) 
rotate(4.5, smooth(6, 0.56, 2, feedback(RIGHT, sens(1.2, 1.2, ball(1.995, mouse())))))
```

Adding detection for trackball stopping wouldn't be too hard, it would be basically just else branch [here](https://github.com/kozec/sc-controller/blob/master/scc/modifiers.py#L492), but I'm not sure how would one express it in configuration.

**Comment by michaelbutler** [comment]
@kozec thanks a lot, I didn't know about the `touched(...)` syntax and was trying other macros to no avail. It looks like this might solve it if I can find the right delay that covers most cases without being too long. Unfortunately now FFXIV isn't seeing the gamepad as an Xbox 360 controller... no idea what happened but maybe I was installing/uninstalling too many packages. 

The right pad works as the mouse trackball but none of the buttons are registering as Xbox 360 pad presses.

**Comment by michaelbutler** [comment]
I'm going to close this as solved since it's a good solution for the mouse button being held WHILE trackballing. I think my new issue about the controller not being seen is specific to that game.
