### ISSUE TITLE
Edit window won't open

### ISSUE THREAD

**Issue by Brunfunstudios** [kozec/sc-controller#7]
First of all this is an awesome program (can finally play Rocket League on wine with the SC :D),
but unfortunately I can't edit the config with the client.
Every time I click on a widget I get the following error:

```
(sc-controller:13693): Gtk-WARNING **: Theme parsing error: gtk.css:701:22: 'text-decoration-line' is not a valid property name
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scc/gui/controller_widget.py", line 52, in on_click
    self.app.show_editor(self.id)
  File "/usr/lib/python2.7/dist-packages/scc/gui/app.py", line 119, in show_editor
    ae = ActionEditor(self, self.on_action_chosen)
  File "/usr/lib/python2.7/dist-packages/scc/gui/action_editor.py", line 55, in __init__
    ButtonChooser.__init__(self, app, self.on_button_chooser_callback)
  File "/usr/lib/python2.7/dist-packages/scc/gui/button_chooser.py", line 45, in __init__
    self.setup_widgets()
  File "/usr/lib/python2.7/dist-packages/scc/gui/action_editor.py", line 73, in setup_widgets
    ButtonChooser.setup_widgets(self)
  File "/usr/lib/python2.7/dist-packages/scc/gui/button_chooser.py", line 51, in setup_widgets
    self.builder.add_from_file(os.path.join(self.app.gladepath, self.GLADE))
GLib.Error: gtk-builder-error-quark: invalid property: GtkStack.interpolate_size in line 163 (11)
```

I am using the deb file and also tried out the git zip.
Same issue.

Everything else seems to work fine.
Thanks for making it.

**Comment by kozec** [comment]
> GLib.Error: gtk-builder-error-quark: invalid property: GtkStack.interpolate_size in line 163 (11)

Sounds like you have old version of GTK.
What distro are you using?
Can you, please, run this in terminal and paste output?
```
$ python2

from gi.repository import Gtk, GLib
print GLib.glib_version
print Gtk.get_major_version(), Gtk.get_minor_version()
```

**Comment by kozec** [comment]
By the way, as quick and dirty fix, you can try editing `/usr/share/scc/action_editor.glade` as root. Search for line
```
<property name="interpolate_size">True</property>
```
and delete it.

**Comment by Brunfunstudios** [comment]
Thanks for the quick answer.
```
>>> from gi.repository import Gtk, GLib

(.:1707): Gtk-WARNING **: Theme parsing error: gtk.css:701:22: 'text-decoration-line' is not a valid property name
>>> print GLib.glib_version
(2, 45, 1)
>>> print Gtk.get_major_version(), Gtk.get_minor_version()
3 16
>>> 
```

I'm on Ubuntu 15.10 Gnome

**Comment by Brunfunstudios** [comment]
After deleting this line I also needed to delete bottom_margin in the same file.
Now it seems to work fine (but still need to test further).

**Comment by xPMo** [comment]
On Debian Jessie, using Cinnamon 2.2.16, same issue: 

`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scc/gui/controller_widget.py", line 60, in on_click
    self.app.show_editor(self.id)
  File "/usr/lib/python2.7/dist-packages/scc/gui/app.py", line 169, in show_editor
    ae.set_button(id, self.current.buttons[id])
  File "/usr/lib/python2.7/dist-packages/scc/gui/action_editor.py", line 492, in set_button
    self._set_mode(action, Action.AC_BUTTON)
  File "/usr/lib/python2.7/dist-packages/scc/gui/action_editor.py", line 479, in _set_mode
    component.load()
  File "/usr/lib/python2.7/dist-packages/scc/gui/ae/special_action.py", line 41, in load
    AEComponent.load(self)
  File "/usr/lib/python2.7/dist-packages/scc/gui/ae/__init__.py", line 45, in load
    self.builder.add_from_file(os.path.join(self.app.gladepath, self.GLADE))
GLib.Error: gtk-builder-error-quark: Invalid property: GtkStack.interpolate_size on line 97 (11)`


`>>> from gi.repository import Gtk, GLib
>>> print GLib.glib_version
(2, 42, 0)
>>> print Gtk.get_major_version(), Gtk.get_minor_version()
3 14`

Deleting the same line from `ae/special_action.glade` didn't fix, led to this:

`GLib.Error: gtk-builder-error-quark: Invalid property: GtkTextView.monospace on line 45 (11)`

Deleting the monospace line from `ae/custom.glade` allows the window to pop up.

Also, it keeps giving the warning (sc-controller:26791): `Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtkcontainer.c:1174: child property `position' of container class `GtkHeaderBar' is not writable`

**Comment by kozec** [comment]
> GLib.Error: gtk-builder-error-quark: Invalid property: GtkTextView.monospace on line 45 (11)

Those properties are rather important there. I guess there is no way to update GTK on Raspbian?

**Comment by xPMo** [comment]
> What exactly is a problem on Debian Jessie?

Same thing.  The edit window wasn't opening on either Debian Jessie or Raspian Jessie.  (Sorry if I wasn't clear originally).

Same GLib and Gtk versions for both systems.

Removing the "interpolate" and "monospace" property lines allows the edit window to open on both systems.

(I'm not sure if that warning has anything to do with this, but it is sent at the same time any of the windows are drawn.)

**Comment by kozec** [comment]
Ok, this ^^ should be compatible with Debian's version of GTK. I mean, it will not use monospace font where it belongs, but it will not crash :)
