### ISSUE TITLE
Port to GTK4

### ISSUE THREAD

**Issue by orowith2os** [kozec/sc-controller#706]
Currently sc-controller uses GTK3, however this can leave a lot to be desired as GTK4 has improved lots of things like performance. I'll be using this issue to track the steps needed to port this to GTK4.

Sidenote: Maybe libadwaita can be done too, but GTK4 itself will be fine.

Porting to something other than Glade will also be required:
https://gitlab.gnome.org/GNOME/glade
> It is not being actively developed or maintained anymore. If you are interested in becoming a maintainer please contact us on gitlab.

- [ ] Port to GTK UI files, cleanup
- [ ] Port to GTK4
- [ ] (optional, might be interesting to try) Port to libadwaita
- [ ] (optional, might be good to try) Follow GNOME HIG if porting to libadwaita

Will be working on it over at https://github.com/orowith2os/sc-controller/tree/gtk4-port

**Comment by HurricanePootis** [comment]
swag

**Comment by orowith2os** [comment]
Turns out @kozec is rewriting in C, which I'm not comfortable with. I'll close this as not panned for now, but can try to help out later if some form of contact (like Matrix) is provided so I can have some assistance with the C side of things ;)

https://www.patreon.com/posts/future-of-sc-22941064

**Comment by C0rn3j** [comment]
@orowith2os if you'd still possibly be interested in this, we've a Python 3 fork as this repository isn't active recently and the C rewrite hasn't really happened.

https://github.com/C0rn3j/sc-controller
