### ISSUE TITLE
[HELP] sc-controller won't hide originals on the host when streaming using Sunshine & Moonlight

### ISSUE THREAD

**Issue by Barina** [kozec/sc-controller#718]
Pretty sure I'm doing something incorrectly..
My setups are:
- Host - Win11 PC with Sunshine server installed, basic USB kb & mouse and without any controller attached
- Client - Linux (LMDE) with sc-controller (0.4.8 appimage) and Moonlight installed, mini kb+touchpad connected through single dongle and with two Nintendo gamepads connected and mapped as an XBOX controllers

To make my remote games playable, I have to use sc-controller because otherwise, the buttons are all wrong..
The issue is, as soon as I connect to the host from the Moonlight client, the host detects 4 XBOX controllers instead of 2.
If I launch Moonlight without sc-controller, then the host detect only two. but of-course they're not usable like so..
So I assumed sc-controller didn't managed to "hide" original inputs or Moonlight\Sunshine force detect ALL input devices... 

Is that a known issue? how can one overcome this?

**Comment by kozec** [comment]
I'm sorry, but if I'm understanding your question correctly, sc-controller is not supposed to hide original devices. They should appear frozen, but not disconnected.

Maybe this can help? https://github.com/moonlight-stream/moonlight-docs/wiki/Gamepad-Mapping

**Comment by Barina** [comment]
Thank for replying!

> sc-controller is not supposed to hide original devices. They should appear frozen, but not disconnected.
There isn't any way to ignore them..? oof


> Maybe this can help? https://github.com/moonlight-stream/moonlight-docs/wiki/Gamepad-Mapping

Yea I did earlier, it doesn't work for me
I've created a mapping but it doesn't "get passed" to moonlight.. it's like I did nothing lol

**Comment by Barina** [comment]
So I've managed to make it work. (SDL mapping)
I added the environment variable myself to my ~/.profile, rebooted and now it seems to be working well! only 2 controllers with the correct mapping :) 
Thanks for the help!
