### ISSUE TITLE
Multiple steam controllers?

### ISSUE THREAD

**Issue by neuromancer** [kozec/sc-controller#73]
Hi,

I have two steam controllers but sc-controller only detects one (the first one?). I'm not sure how two controllers should be handled but steam can easily manage both.

Let me know if you want some testing.

**Comment by kozec** [comment]
Hello.

I have pretty good idea how should it be handled, but coding it with only one controller is next to impossible.

I'm planning to buy another especially for this and #51 once I'll be rich enough, but it's not on top of TODO right now.

**Comment by whatisgravity** [comment]
I can send you enough BTC to buy a controller from Steam, email me at whatisgravity@tuta.io

**Comment by ulgens** [comment]
Hey, what's the latest status about this?

**Comment by kozec** [comment]
> Hey, what's the latest status about this?

```
29/08/2016 07:55 PM

Hello kozec
We're preparing your items to ship.
Tracking information has been created and is attached below. The tracking numbers may not be active until your packages have been transferred to the shipping carrier for delivery.
		
	Steam Controller 	

```

With big thanks to @whatisgravity  :)

**Comment by ulgens** [comment]
Nice, very nice :) I can help for testing in couple of weeks.

**Comment by kozec** [comment]
Adding to that latest status, all commit messages above :)

**Comment by kozec** [comment]
... aaand [released](https://github.com/kozec/sc-controller/releases/tag/v0.3) :)

**Comment by ElectricPrism** [comment]
Wonderful!
