### ISSUE TITLE
Cannot Select RB/LB Settings When RB/LB is set to Mouse Wheel Up or Down 

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#75]
Tested with both stable and git versions. If you set the RB/LB buttons to mouse wheel up or mouse wheel down, they will no longer be clickable from the main configuration window. The only workaround is to right click > clear and then will it work again.

**Comment by kozec** [comment]
Fixed by 71d88bea511a1840bf16d26498d84d9526cf7649
