### ISSUE TITLE
7 Shows As "Wheel UP" When Bound

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#76]
Throughout the UI, if you bind 7 to something, it will show up as "Wheel UP" instead. It still sends the correct key and the actual binding text shows as "button(Keys.KEY_7)", it just ends up labelled wrong.

**Comment by kozec** [comment]
Sounds like there is good chance that Keys.KEY_7 and Rels.REL_WHEEL have same numeric value...
