### ISSUE TITLE
OSD Menu Settings Partially Broken

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#77]
Tested with git and latest stable, OSD menus seem to be broken when they are bound to a button.

2. Selecting the "Confirm selection by releasing button" setting seems to cause menus to not work at all
3. Menus don't respect control option - they are always controlled by joystick.
4. When a touchpad is set to menu, enabling the click "Require click" option leads to the menu not appearing when clicking

**Comment by kozec** [comment]
That last one is kinda by-design, because when touchpad is set to menu, clicking with it is used as confirmation. How would it work if menu would be displayed only after clicking?
