### ISSUE TITLE
Setting all up.

### ISSUE THREAD

**Issue by MeDeVILe** [kozec/sc-controller#79]
I know silly but I have problem to set all up.

How to open keyboard?
How to setup action to left pad pressed?

I was trying everything and don't have idea.

**Comment by kozec** [comment]
:D That reminds me that I should create some wiki or tutorial...

- Keyboard: You can set "Special Action" -> "Display On Screen Keyboard" to some button.
By default, you can also open on-screen menu by pressing Steam button and select "Display Keyboard" option

- Pressed pad: Click on left-side of left-bottom button in main window.

**Comment by MeDeVILe** [comment]
Ok sorry I just figured it out. 

For those who had same problem:

When you setup there is difference when you click on:

![big](https://cloud.githubusercontent.com/assets/6697190/18047641/290fe35a-6dde-11e6-9afd-a19af7f85e89.png)
or on only this part:
![small](https://cloud.githubusercontent.com/assets/6697190/18047652/38178592-6dde-11e6-94db-82e85143733b.png)

**Comment by kozec** [comment]
There is supposed to be visual clue when you are hovering over that part, but it's not there. I'll check where did it gone.

At least it works for both pads.

**Comment by MeDeVILe** [comment]
Visual clue is showing when hovering but only if pressed action is already set up.

**Comment by MeDeVILe** [comment]
It's the fastest closed issue in my life! This dev is the best :D

**Comment by kozec** [comment]
That would sound better if you wouldn't close it yourself :P

**Comment by MeDeVILe** [comment]
Yeah maby but still this issue was a reminder to create wiki page 😀

**Comment by kozec** [comment]
And now it's fixed twice 8-)
