### ISSUE TITLE
[question] Is there a way to easily share setups with others?

### ISSUE THREAD

**Issue by MeDeVILe** [kozec/sc-controller#80]
That would be great. It would be faster to set all up with just small changes to for example kodi, Firefox etc. I know i can import but where to look for setups?

**Comment by kozec** [comment]
I can probably add "export" option as well, but you can as well just send file from `~/.config/scc/profiles` and let other person to copy it in same location.

**Comment by kozec** [comment]
... also, there is this almost documented [profile examples directory](https://github.com/kozec/sc-controller/tree/master/profile_examples).

**Comment by MeDeVILe** [comment]
So you can change label to question and close it ;) 
Will you add some of samples if people will send it to commit changes? It would be easier to have all in one place.

**Comment by kozec** [comment]
> Will you add some of samples if people will send it to commit changes?

Yeah, why not :)

**Comment by MeDeVILe** [comment]
I found this site and it's great. It's collecting sc profiles from steam.
http://www.steamcontrollerdb.com/

**Comment by kozec** [comment]
You can _import_ profile from there and SC-Controller even set itself as handler for their client format, since there is no client on Linux.

But exporting is a problem. SC-Controller can do more than Steam vdf format allows to store.


By the way, I'm working on exporting SCC "native" profiles, but I realized that it's kinda unsafe thing :(
You could make profile with something like `rm -rf ~`  bound to button and send it to someone.

**Comment by CreamyCookie** [comment]
@kozec Maybe you could display some warning message and mention the commands it contains before a config is used for the first time (e.g. if imported), given that it contains commands.

**Comment by kozec** [comment]
So, this is now pronounced done in git and available in next release.

You can export profile from menu and import it from same menu, with drag&drop or by double-clicking it.
And if someone tries to import profile with shell-calling stuff, [big scary window appears.](https://cloud.githubusercontent.com/assets/1282500/23750094/a5b89fb2-04cb-11e7-8aa6-03477288862b.png)
