### ISSUE TITLE
tray icon?

### ISSUE THREAD

**Issue by LiamDawe** [kozec/sc-controller#82]
I can't remember if you have one on other desktops, but on Ubuntu Mate there is no tray icon.

If none exists, any plans to add one? Would be useful for quickly turning emulation on and off without the app actually open.

**Comment by kozec** [comment]
Nope, there is no tray icon yet. Frankly, [tray icons became rather problematic](https://github.com/syncthing/syncthing-gtk/issues/297) after all nonsense that first Ubuntu, then Gnome and now KDE is pulling around them, but I'll try to add something simple :D

**Comment by kozec** [comment]
So, I pretty-much copy pasted "tray" icon from ST-GTK and it pretty-much works. I just need what will it do with Unity.
