### ISSUE TITLE
Mapping buttons or keystrokes to gyros.

### ISSUE THREAD

**Issue by linuxcustom** [kozec/sc-controller#83]
I was wondering if it was possible to use the gyros to activate buttons or keystrokes on the keyboard. I remember it being possible when using the controller setup menu in the steam client but could not seem to find any way of doing it in sc-controller.

**Comment by kozec** [comment]
Currently not. It wouldn't be big problem allowing it to use same output options as stick is, but gyro doesn't have any "neutral" position, so actually using such setup would be rather awkward.

I believe that Steam has same problem, because I've just tried to set DPAD -> WSAD on gyro sensor there and I was not able to find position where it would stop spamming random keypresses :D

But I'm open to any suggestions.

**Comment by linuxcustom** [comment]
Yeah I definitely remember button spamming being an issue when setting buttons on the gyro.  If I remember correctly I had to set in the steam client how far you had to tilt the controller before it would activate an action.  Then again I usually would just set one button on the gyro and use that as a way to reload or melee in a game to "simulate" realism.

**Comment by kozec** [comment]
So, basically, "if I rotate controller usb-side-up, press 'R' and hold it until I rotate it back"?

I'm not sure how less spammy it would be, but I can add it at least as experimental feature.

**Comment by linuxcustom** [comment]
Yeah pretty much like that.  In games that I played even if the game was spamming the R button you would still only see the character reload once since most games wont let you reload when your weapons ammo is full.  The best use I've had using the gyros as buttons though is using just the left and right gyro actions to activate left and right character leaning in games. I had it set where you had to tilt the controller quite a bit before it would even activate the keystroke.  But I would greatly appreciate any work you attempted on this feature as long as it not too much trouble for you to implement.

**Comment by kozec** [comment]
Are you able to test git version?

I've added `tilt` action that acts as less spammy version of that dpad thing in Steam. There is no gui yet, but it is usable in current git version using custom action.

If you set gyro to:
```
tilt(
  button(KEY_D),
  button(KEY_U),
  button(KEY_L),
  button(KEY_R)
)
```
... SCC should press keys those buttons depending on controller rotation.
First two are executed when front side of controller faces down and up, respectively. Last two are executed when controller is tilted to side.

**Comment by linuxcustom** [comment]
I may be doing something wrong but after I mapped the buttons to the gyro and tested it, every game I tried acted as if the gyro was rapidly tapping the button.  For instance if I mapped the crouch button then tilted the gyro thus activating the crouch button, the character would rapidly crouch and un-crouch till the gyro was tilted back to its neutral position.

However in the steam client when I did the same thing in their controller mapping screen my character would crouch and stay down till I tilted the gyro back to its neutral position.  It acted like it just pressed and held that key down rather than tapping it.

Opening a notepad and viewing the output showed that the same key was acting differently in both scenarios.  Other than that its definitely working.

**Comment by kozec** [comment]
Great, that's exactly what it is _not_ supposed to do :D

Can I ask what game are you testing in?

**Comment by kozec** [comment]
I have to admit, I'm not proud about that one :(

But I'm testing it on GZDoom right now and it works as I would expect with above fix.

**Comment by linuxcustom** [comment]
In answer to your previous questions I was using gzdoom, Hexen 2, and RBDoom3BFG for testing the controllers gyro.  As for "notepad" I was using notepadqq which is a port of notepad++ for linux.

With the newly committed fix the controller now acts perfectly. I could not find any immediate issues during my initial testing.  All that is needed now is a GUI interface for it and it looks complete.  By the way excellent work!

**Comment by kozec** [comment]
This is mainly sanity check for me, but on scale from 1 to 10, how understandable is this? :)

![tilt](https://cloud.githubusercontent.com/assets/1282500/18313224/e1ae4b1e-750d-11e6-8c92-472fd2476f71.png)

**Comment by linuxcustom** [comment]
Looks good and pretty understandable to me.  Anyone who enters the gyro sub menus and sees that shouldn't be confused at what they're looking at, otherwise this would probably be the least of their concerns.  I'd give it a 10!
