### ISSUE TITLE
Activating the gyro with trigger soft pull

### ISSUE THREAD

**Issue by CreamyCookie** [kozec/sc-controller#86]
It would be great, if one could use the trigger soft pull (analog) as the gyro activate button. 

When I use the trigger as the enable button it seems to only activate, when it was pressed down completely (you hear a little click).

One use for that is allowing the player to soft pull the trigger to activate iron sights and the gyro for aiming.

**Comment by kozec** [comment]
Well, it's not impossible, but expressing in in configuration may be problem. I'll think about less-hacky way to do it.

**Comment by Patola** [comment]
Is the possible fix for this related to #208?

**Comment by Patola** [comment]
A fix for this could well be general enough that could be used for the trackpads too; the steam controller configuration in Steam allows one to use arbitrarily-defined "rings" (outer ring and inner ring) in the touchpad for different controls.

**Comment by Patola** [comment]
![Joystick controller configuration and the outer ring](https://user-images.githubusercontent.com/2991620/30514615-27c563c8-9aef-11e7-9501-0c8dfa645fa1.png)
![Additional settings](https://user-images.githubusercontent.com/2991620/30514618-38d4e846-9aef-11e7-9d64-f1ac71cadafe.png)

**Comment by kozec** [comment]
> Is the possible fix for this related to 208?

Yes, both is internally controlled by same code. Gyro (de)activation button is effectively modeshift with one empty mode.

> A fix for this could well be general enough that could be used for the joystick too; the steam controller configuration in Steam allows one to use two defined "rings"

SC-Controller has rings bindings as well, but combining them with modeshift is not really that straightforward, without making it into some kind of config-file-only option. I can't really imagine how it should be configured right now.

**Comment by Patola** [comment]
I have downloaded the code and I am trying to figure it out. Isn't it possible to simply break up trigger (or outer/inner ring) into two specific "buttons"? Soft_trigger and hard_trigger, if one condition has to check for just trigger it would check for either soft or hard trigger. Maybe one option asks whether pressing x_trigger also activates (sets) the other, so they are unified. That could be valid for inner and outer rings also.

**Comment by kozec** [comment]
> I have downloaded the code and I am trying to figure it out. Isn't it possible to simply break up trigger (or outer/inner ring) into two specific "buttons"? Soft_trigger and hard_trigger, if one condition has to check for just trigger it would check for either soft or hard trigger.

Yes, but it wouldn't be configurable in that case - you wouldn't be able to set where soft ends and hard begins. Plus, it would mean doing even more math in input handling, what's never good thing.

**Comment by kozec** [comment]
_(it definitely did _not_ took me year to implement this. It was little more than that :)_
