### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by MeDeVILe** [kozec/sc-controller#87]
While import some profiles I get this error
![okno bez tytulu_002](https://cloud.githubusercontent.com/assets/6697190/18331983/2b960e92-7563-11e6-8c74-2e24587dcf74.png)

Error is occurring when button is referring to unknown action or non existing key.
I found out that when I delete key binding which is causing  an error import will work perfectly. 

Could you add auto option to delete or hush these entry? Neither ignoring nor 'Try to fix' option doesn't seem to be working.

**Comment by kozec** [comment]
Would it be possible to copy-paste all that, including "profile dump" bellow here or to pastebin?

**Comment by MeDeVILe** [comment]
http://pastebin.com/arFqCB9k
and it's after import for example:
http://www.steamcontrollerdb.com/config/download_custom/409

**Comment by kozec** [comment]
Ok, this problem may not be really solvable.

That profile uses "game_actions", where game communicates with Steam. I would need to emulate SteamAPI to handle that and that's only step away from cracking Steam altogether :D

**Comment by MeDeVILe** [comment]
Just when importing let it delete those fragments. It's usually 1 or 2 and after I edited file profile is working perfectly

**Comment by kozec** [comment]
Yeah, that may work at least partially. I'll test it.
