### ISSUE TITLE
Can't map menu button to itself

### ISSUE THREAD

**Issue by DaVince** [kozec/sc-controller#88]
I want to be able to map the Steam button in the middle to function the way it normally would, rather than open the OSD menu. This is because apps like RetroArch are able to make use of this button. (As a workaround, I've currently mapped it to F1, which opens RetroArch's menu too.) However, the control mapper doesn't let me select the Menu button as an option - it's not even displayed in the graphic.

If this is not how it works, then sorry for the bother. (Maybe it can still be mapped as an extra controller button?)

**Comment by kozec** [comment]
Yeah, that graphics is based on x360 pad, because that's what's emulated.

But you should be able to use custom action and set `button(Keys.BTN_MODE)` there, that's [official](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h#L395) name of that button.

**Comment by DaVince** [comment]
Thank you very much! Is it possible for the "press a key" prompt to also
recognize it as such? Also, doesn't the XBox have the big XBox button in
the middle anyway?

Op 14 sep. 2016 10:34 schreef "kozec" <notifications@github.com>:

**Comment by kozec** [comment]
> Also, doesn't the XBox have the big XBox button in the middle anyway?

In all seriousness, I dunno :D I mean, yeah, it's there, but I'm not sure if it is a button and if it generates any  input.

> Thank you very much! Is it possible for the "press a key" prompt to also
recognize it as such?

I think I'll just add it to that image so user can click on it.

**Comment by DaVince** [comment]
> In all seriousness, I dunno :D I mean, yeah, it's there, but I'm not sure if it is a button and if it generates any input.

It definitely is! The XBox uses it to go into its system menu, and even Steam recognizes the button to go into the Big Picture overlay. In any case, it's a solved issue now, thank you very much! :D
