### ISSUE TITLE
Automically stop/start driver based on Steam process running?

### ISSUE THREAD

**Issue by parkerlreed** [kozec/sc-controller#89]
The controller is detected fine when plugged in while Steam is running. Could this maybe lead to leaving the scc-daemon running and when Steam is launched just hand off control from the scc-daemon?

Idea came after seeing this thread. https://www.reddit.com/r/SteamController/comments/53nkau/support_wireless_lizard_mode_on_ubuntu/

**Comment by kozec** [comment]
That sounds like same problem as #62. I'm not 100% sure if detecting Steam is possible, but it may work as option to turn off emulation in autoswitcher.

**Comment by parkerlreed** [comment]
I'm sure python has something built-in in for this but just an example

````
if pgrep "steam" > /dev/null; then
    sc-controller pause; 
else     
    sc-controller start; 
fi
````

Some kind of process check that maybe runs once every 5 seconds (Could be an option in settings if you want this feature at all)

**Comment by kozec** [comment]
There is already code that checks for active window (not process) to allow automatic profile switching.

**Comment by parkerlreed** [comment]
From my understanding that wouldn't hand access of the Steam Controller over to Steam though. Doesn't the daemon claim exclusive access?

**Comment by kozec** [comment]
> From my understanding that wouldn't hand access of the Steam Controller over to Steam though.

Nope, but that's not biggest problem. I can make option to turn daemon off, but I don't know how to start it back after Steam exits.

**Comment by kozec** [comment]
So, with autoswitcher rule set like this...

![steam-restart](https://cloud.githubusercontent.com/assets/1282500/18767315/b51f4360-811e-11e6-95c4-731575ff8498.png)

... scc-daemon will restart itself when Steam is activated and then, after (or rather if) Steam releases controller device, it will grab it back again.

**Comment by parkerlreed** [comment]
:D sweet.

**Comment by xavierh** [comment]
Thank you. Thank you. Thank you
