### ISSUE TITLE
Repo not updated?

### ISSUE THREAD

**Issue by azizLIGHT** [kozec/sc-controller#9]
I'm using the repo for Ubuntu 14.04 and the last update is from 12:37 on April 25. There's been several fixes here on github that are not packaged yet in the repo. When will that update happen?

**Comment by kozec** [comment]
I need to test those changes before calling them a release :)

**Comment by azizLIGHT** [comment]
Ah ok! I'm a little too excited for this haha

**Comment by kozec** [comment]
[Here you are](https://build.opensuse.org/package/binaries/home:kozec/sc-controller?arch=i586&repository=xUbuntu_15.10)
