### ISSUE TITLE
Daemon error + no input

### ISSUE THREAD

**Issue by richese** [kozec/sc-controller#92]
Hi,
my controller stopped generating input events. I can see that data are received in Input Test Mode but nothing else happens. The only thing that works are menus.

System: Arch Linux x86_64
sc-controller version: 7a23c6d

This error happens when I turn on controller with wireless dongle. It does not happen when connected by wire (still no input).
```
> scc-daemon /home/luck/.config/scc/profiles/Desktop.sccprofile debug 
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f75ad8698d0>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f75ad805f90>
D Mapper        Gamepad:  <scc.uinput.Gamepad object at 0x7f75ad879750>
D SCCDaemon     Created control socket /home/luck/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
D USB           USB device added: 28de:1142
D AS  Mapper        Creating virtual devices
D AS  Mapper        Keyboard: <scc.uinput.Dummy object at 0x7f97522efdd0>
D AS  Mapper        Mouse:    <scc.uinput.Dummy object at 0x7f97522efe50>
D AS  Mapper        Gamepad:  <scc.uinput.Dummy object at 0x7f97522efe90>
D AS  AutoSwitcher  Parsed 1 autoswitcher conditions
D AS  AutoSwitcher  AutoSwitcher started
D AS  AutoSwitcher  Connected to daemon, version 0.2.17
I SCCDaemon     Registered scc-autoswitch-daemon
D AS  AutoSwitcher  Enabled: False
D AS  AutoSwitcher  Daemon reported profile change: /home/luck/.config/scc/profiles/Desktop.sccprofile
D OSD DaemonCtrlr   Connected to daemon, version 0.2.17
D OSD DaemonCtrlr   Daemon reported profile change: /home/luck/.config/scc/profiles/Desktop.sccprofile
D OSD DaemonCtrlr   Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
E USB           Failed to handle recieved data
E USB           'NoneType' object has no attribute 'input'
E USB           Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/drivers/usb.py", line 73, in callback_wrapper
    callback(endpoint, data)
  File "/usr/lib/python2.7/site-packages/scc/drivers/sc_dongle.py", line 128, in _on_input
    self._controllers[endpoint].input(tup)
  File "/usr/lib/python2.7/site-packages/scc/drivers/sc_dongle.py", line 182, in input
    self.mapper.input(self, time.time(), old_state, idata)
AttributeError: 'NoneType' object has no attribute 'input'

D SCDongle      Got wireless SC with serial FC54726708
D SCCDaemon     Assigned default_mapper to <SCWireless scFC54726708>
D SCCDaemon     Controller added: <SCWireless scFC54726708>
D AS  AutoSwitcher  Enabled: True
D AS  AutoSwitcher  Daemon reported profile change: /home/luck/.config/scc/profiles/Desktop.sccprofile
D OSD DaemonCtrlr   Daemon reported profile change: /home/luck/.config/scc/profiles/Desktop.sccprofile
D AS  AutoSwitcher  Window switched: 20971570
```

**Comment by kozec** [comment]
That looks like your controller starts to send data before it's fully registered. Does that happens always or was it one-time thing?

**Comment by kozec** [comment]
... and does it work after above fix?

**Comment by richese** [comment]
I am sure it didn't happen every time but it was pretty frequent.
The fix seems to work as I don't see it anymore.

But I guess something else got broken in my system since I still have no input and even Steam has trouble getting access to /dev/uinput. 
When I start Steam after system restart both mouse and joystick emulation works with steam driver. Then when I close Steam and start it again all I get is `Couldn't initialize virtual gamepad: Couldn't open /dev/uinput for writing`.

**Comment by kozec** [comment]
What gives you `ls -l /dev/uinput` ?

Also, from that steps, does that happens when restarting Steam while SCC is not involved?

**Comment by richese** [comment]
So I tried a a few combinations running **only either** Steam or scc-daemon
after restart.

With udev rules from sc-controller I get 
`crw-------+ 1 root root 10, 223 sep 28 19:56 /dev/uinput` and no input
from SCC and only mouse/keyboard from Steam.

With rules from arch steam package
```
cat /usr/lib/udev/rules.d/80-steam-controller-permission.rules
#USB devices 
SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0660", TAG+="uaccess"
KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess"
```
I get `crw-rw----+ 1 root root 10, 223 sep 28 19:52 /dev/uinput` after
reboot. This changes  to
`crw-------+ 1 root root 10, 223 sep 28 19:56 /dev/uinput` after
starting SCC or Steam. No input in SCC, works in Steam but stops working
after restarting Steam.

This was probably caused by a package/kernel update but I can't tell which since I didn't use the controller for a while.

**Comment by kozec** [comment]
Weird thing is that it's not so different from [what SCC uses](https://github.com/kozec/sc-controller/blob/master/scripts/90-sc-controller.rules). Maybe try that one and see if it helps.

**Comment by richese** [comment]
Sorry for the delay.

>Also, just to be sure what part doesn't works, is there no input, but input test mode shows that buttons are pressed?

Yes thats exactly what's happening.

I also tried to install SCC to fresh installation of Arch and got the same result. Actually there was even more problems that broke even the GUI. 
![2016-10-01-121306_930x438_scrot](https://cloud.githubusercontent.com/assets/8769724/19013570/c025ff4e-87d4-11e6-9f1b-b839b59d088b.png)

```
Traceback (most recent call last):
  File "/home/luck/git/sc-controller/scc/gui/app.py", line 687, in do_startup
    self.setup_widgets()
  File "/home/luck/git/sc-controller/scc/gui/app.py", line 98, in setup_widgets
    ps.set_profile(self.load_profile_selection())
  File "/home/luck/git/sc-controller/scc/gui/profile_switcher.py", line 95, in set_profile
    if name.endswith(".mod"): name = name[0:-4]
AttributeError: 'NoneType' object has no attribute 'endswith'
```
`load_profile_selection()` returns None if there is no "current_profile" in config but `profile_switcher()` can't handle such input. Also, "current_profile" does not seem to be saved to config file.

```
Traceback (most recent call last):
  File "/home/luck/git/sc-controller/scc/gui/controller_widget.py", line 70, in on_cursor_enter
    self.app.hilight(self.name)
  File "/home/luck/git/sc-controller/scc/gui/app.py", line 170, in hilight
    self._update_background()
  File "/home/luck/git/sc-controller/scc/gui/app.py", line 178, in _update_background
    self.background.hilight(h)
AttributeError: 'NoneType' object has no attribute 'hilight'
```

```
Traceback (most recent call last):
  File "/home/luck/git/sc-controller/scc/gui/userdata_manager.py", line 101, in _on_user_data_loaded
    data[i] = pdir, pdir.enumerate_children_finish(res)
GLib.Error: g-io-error-quark: Error opening directory '/home/luck/.config/scc/controller-icons': Adresár alebo súbor neexistuje (1)
```

**Comment by kozec** [comment]
> The only working solution I found to missing input is to chmod 666 /dev/uinput

I've got message on Reddit from guy with same problem on Anthergos, so I'm 80% sure that Arch broken something. I have install ISO downloaded, but I didn't get to actually installing and testing it yet :(

**Comment by kozec** [comment]
Ok, so I have it reproduced, but I'm really not sure why `TAG+="uaccess"` is suddenly ignored on Arch. 

Most obvious solution would be to change it to `MODE="0666"`, but that would allow any program on same machine to simulate inputs, what doesn't sounds like best idea...

**Comment by kozec** [comment]
Quick question, @richese, does `sudo modprobe uinput` before starting scc solve your problem?

It looks like this _really_ important module is not loaded on Arch by default :D

**Comment by richese** [comment]
@kozec 
Yes, that seemed to be the problem. I added a rule for uinput to /etc/modules-load.d/ and it started working again.

Thanks for the help.

**Comment by kozec** [comment]
Great. I added nice, red message just in case there are more of those.
