### ISSUE TITLE
More than 2 joysticks/4axii

### ISSUE THREAD

**Issue by tealmill** [kozec/sc-controller#93]
Hello. I would like to, simply, instead of binding the two pads, analog stick and shoulder analogs to instead present themselves as 8 axii analog axii on 4 joysticks, for instance without the DPad being limited to it's digital positions, but without ovewriting another control. It would obviously no longer simulate the X-Box 360 controller, but there's games that allow one bind the axii as the device provides them, so that should matter as long as it's the case. Is it possible to achieve that now?

**Comment by kozec** [comment]
Not right now, at least not without some patching.

Option to change what controller is emulated is in TODO, but biggest problem there is that I'm not sure how to approach that from UI perspective. Adding it as config-file only setting should be simple.

**Comment by kozec** [comment]
There also seems to be limit on how many buttons & axes can be added before kernel stops recognizing device as gamepad.

This is best I could do:

![screen](https://cloud.githubusercontent.com/assets/1282500/18967012/e4daedb0-8683-11e6-8c22-52d7df230242.png)

**Comment by tealmill** [comment]
Alright, again, just adding option "misc. joystick 0", "misc. joystick 1"... would do, but if you don't wanna bother with that, I for one can handle some config file editing. And again, all I wanted is to be able to pull all the axii of the steam controller as raw ones, it can't really provide more than uh, 10 or 11, counting the gyro? So 21 should be mighty fine.

**Comment by kozec** [comment]
> Alright, again, just adding option "misc. joystick 0", "misc. joystick 1"... would do, but if you don't wanna bother with that, I for one can handle some config file editing.

I'm not sure if I understand right here.

**Comment by kozec** [comment]
So, anyway, I merged what I tried to do back then. Run it once, then close both application and daemon (disable emulation from menu) and edit `~/.config/scc/config.json`

You should see node looking like this there:
```
"output": {
        "axes": [
                [-32768, 32767], [-32768, 32767], [-32768, 32767], [-32768, 32767],
                [0, 255], [0, 255], [-1, 1], [-1, 1]
        ], 
        "buttons": 20, 
        "name": "Microsoft X-Box 360 pad", 
        "product": "0x028e", 
        "vendor": "0x045e"
    }, 
```

Numbers like `[-32768, 32767]` are minimum and maximum of axis range, rest should be clear.

Also make backup, because if that config has wrong format, it's automatically overwritten with default one.
