### ISSUE TITLE
Undo / Redo buttons not visible on dark themes

### ISSUE THREAD

**Issue by mulark** [kozec/sc-controller#96]
![screenshot_20161004_223229](https://cloud.githubusercontent.com/assets/20687438/19101133/90b46844-8a82-11e6-9028-709192967cab.png)
Image attached. KDE plasma

**Comment by kozec** [comment]
Those icons are provided by same theme, I'm not sure if I can change them in any way...

What theme are you using?

**Comment by mulark** [comment]
Here's some more info: maia theme.
I was playing around in glade and managed to get this far: 
![screenshot_20161005_082205](https://cloud.githubusercontent.com/assets/20687438/19117071/f8c477b0-8ad4-11e6-8942-b1ee3c814392.png)
~~However, this is pretty much a hack at this point, and will be an issue on lighter themes.~~ Disregard at this point, better solution below.

The theme (maia) I am using provides icons (edit-undo, edit-redo, etc.) that assume they will be used on white/light backgrounds, as only the title bars are darkly colored. However, the maia-dark theme icons are intended for dark background use. To change which icons are used for gtk applications on kde, install the kde-gtk-config package. Then, browse to System Settings -> GNOME Application Style (GTK) -> Icon themes, and simply select a more suitable theme. Hopefully this helps someone in the future.
