### ISSUE TITLE
uinput kernel module not loaded

### ISSUE THREAD

**Issue by azizLIGHT** [kozec/sc-controller#97]
Ever since I updated sc-controller, I've been getting this error about uinput kernel module not being loaded. However, I can see that the buttons and keys for my particular profile are still working for the most part. One thing that has changed since the update is that the left stick is now controlling my mouse somehow, even though I am using the same profile before/after the update. It still moves my left stick as per my profile, but also moves my mouse now too. FYI, this is version 0.3.0.1 on Ubuntu 14.04 LTS x64 on 3.13.0-88-generic. 

Do I really need to load this uinput kernel module if everything is working OK with the exception of the Left Stick moving the mouse? How can I stop LS from moving mouse around while still allowing LS to move LS?

**Comment by joekm** [comment]
I saw this problem as well after updating to .301.  By way of background, I'm running Debian on Pine64 (arm) SBC.  So I installed by running the python scripts.  Version .270 worked very well except that virtual keyboard response is a bit "wonky".  After updating, I started to get the "uninput not enabled" message.  Going through your posting, looks like that was a recent addition.  Reverting back to .27, it works if I launch it via run.sh but the sc-controller, I still get the "uinput not enabled" message.  This leads me to believe that I didn't fully uninstall .301.  

Perhaps if there were instructions to completely purge the installation, I could try version .301 again and see what happens. Then again, I did notice you left a comment in your source code indicating some uncertainty regarding where you put the check for uinput.

All the above being said though, thank you for making this.  I actually have this set up in my home office streaming Pandora while I work and use the steam controller to operate it from across the room.  It's actually a pretty slick way to interacti with SBCs :)

**Comment by kozec** [comment]
Ok, so first, left stick controlling sounds like [one particularly weird Xorg "feature"](https://wiki.archlinux.org/index.php/Gamepad#Disable_Joystick_From_Controlling_Mouse). Does it happens always, or only if stick is set to emulate stick on virtual gamepad?

Message about missing uinput is completely harmless, so if gamepad and keyboard emulation works, you can safely ignore it. But I'm still curious why would it be displayed. Can you both, please, post output of following commands for me?

```
$ lsmod |grep uinput
$ grep uinput /proc/modules
$ grep uinput /lib/modules/$(uname -r)/modules.builtin
```

1st and 2nd checks if uinput is loaded using modprobe and last if it's built-in to kernel.

**Comment by azizLIGHT** [comment]
The LS controlling mouse happens only when I select map LS to LS under "Joystick or Mouse" Action Type and "Left Stick" Output in the options. It doesn't happen when I selected "Right Stick" there, nor for any other options in the Output dropdown. Other default profiles like the Xbox Controller ones also move the mouse with LS.

Here is my profile I use

> {
>     "buttons": {
>         "A": {
>             "action": "button(Keys.BTN_GAMEPAD)"
>         }, 
>         "B": {
>             "action": "button(Keys.BTN_EAST)"
>         }, 
>         "BACK": {
>             "action": "button(Keys.BTN_SELECT)"
>         }, 
>         "C": {
>             "actions": [{
>                 "action": "button(Keys.KEY_T)"
>             }, {
>                 "action": "sleep(0.500)"
>             }, {
>                 "action": "button(Keys.KEY_G)"
>             }, {
>                 "action": "button(Keys.KEY_L)"
>             }, {
>                 "action": "button(Keys.KEY_H)"
>             }, {
>                 "action": "button(Keys.KEY_F)"
>             }, {
>                 "action": "button(Keys.KEY_ENTER)"
>             }], 
>             "doubleclick": {}, 
>             "hold": {
>                 "action": "button(Keys.KEY_2); button(Keys.KEY_EQUAL)", 
>                 "name": "Go To Level 2"
>             }, 
>             "name": "GLHF"
>         }, 
>         "LB": {
>             "action": "button(Keys.BTN_TL)"
>         }, 
>         "LGRIP": {
>             "doubleclick": {}, 
>             "hold": {
>                 "action": "button(Keys.KEY_PREVIOUSSONG)", 
>                 "name": "Prev Song"
>             }
>         }, 
>         "RB": {
>             "action": "button(Keys.BTN_TR)"
>         }, 
>         "RGRIP": {
>             "doubleclick": {}, 
>             "hold": {
>                 "action": "button(Keys.KEY_NEXTSONG)", 
>                 "name": "Next Song"
>             }
>         }, 
>         "RPAD": {
>             "action": "button(Keys.BTN_THUMBR)"
>         }, 
>         "START": {
>             "action": "button(Keys.BTN_START)"
>         }, 
>         "STICK": {
>             "action": "button(Keys.BTN_THUMBL)"
>         }, 
>         "X": {
>             "action": "button(Keys.BTN_NORTH)"
>         }, 
>         "Y": {
>             "action": "button(Keys.BTN_WEST)"
>         }
>     }, 
>     "gyro": {}, 
>     "menus": {}, 
>     "pad_left": {
>         "click": true, 
>         "dpad": [{
>             "action": "hatup(Axes.ABS_HAT0Y, 0, 32767)"
>         }, {
>             "action": "hatdown(Axes.ABS_HAT0Y, 0, -32767)"
>         }, {
>             "action": "hatleft(Axes.ABS_HAT0X, 0, 32767)"
>         }, {
>             "action": "hatright(Axes.ABS_HAT0X, 0, -32767)"
>         }]
>     }, 
>     "pad_right": {
>         "X": {
>             "action": "axis(Axes.ABS_RX)"
>         }, 
>         "Y": {
>             "action": "axis(Axes.ABS_RY)"
>         }, 
>         "deadzone": {
>             "lower": 0.0, 
>             "upper": 30138.0
>         }, 
>         "feedback": ["RIGHT", 256], 
>         "sensitivity": [1.3, 1.3, 1.0]
>     }, 
>     "stick": {
>         "X": {
>             "action": "axis(Axes.ABS_X)"
>         }, 
>         "Y": {
>             "action": "raxis(Axes.ABS_Y)"
>         }
>     }, 
>     "trigger_left": {
>         "action": "axis(Axes.ABS_Z)"
>     }, 
>     "trigger_right": {
>         "action": "axis(Axes.ABS_RZ)"
>     }, 
>     "version": 1.2
> }

For uinput, I have no output for "lsmod |grep uinput" and "grep uinput /proc/modules"
The third command "grep uinput /lib/modules/$(uname -r)/modules.builtin" gives:

> kernel/drivers/input/misc/uinput.ko

**Comment by joekm** [comment]
In my case, if I get the message, the controller does not work.  Running the commands you asked yields the following:

debian@pine64:~$ lsmod |grep uinput
debian@pine64:~$ grep uinput /proc/modules
debian@pine64:~$ grep uinput /lib/modules/$(uname -r)/modules.builtin
kernel/drivers/input/misc/uinput.ko
debian@pine64:~$

**Comment by kozec** [comment]
@azizLIGHT, ok, now im 99% sure you have that joystick-controls-mouse option enabled. Try if that [wiki page helps](https://wiki.archlinux.org/index.php/Gamepad#Disable_Joystick_From_Controlling_Mouse) :)

@joekm
> In my case, if I get the message, the controller does not work. Running the commands you asked yields the following:

And does last version work if you call `modprobe uinput` before starting sc-controller?

**Comment by richese** [comment]
@azizLIGHT 
The rule that @kozec mentioned should work, but if you do not want Xorg server to process input from any joysticks you can remove `xf86-input-joystick` package. This is Xorgs driver for joystick input which was most likely installed as part of 'xorg' package group that also installs drivers for all types of input devices and video cards.

**Comment by joekm** [comment]
"...And does last version work if you call modprobe uinput before starting sc-controller?"

Thought about that myself.  No, unfortunately, it doesn't.  Also, whenever I try to use sc-controller now, the light turns off on the steam controller and I can't restart it until I reboot the computer.  (otherwise I get a "USB busy" message or somthing along those lines.

**Comment by kozec** [comment]
> otherwise I get a "USB busy" message or somthing along those lines.

In that case, try running `ps ax|grep scc` if there is any forgotten instance of scc-daemon.

Frankly, how things are getting worse and worse for you is mistery for me, SCC is not complicated enough to break like that :D

You mentioned that you installed SCC without package manager.
Try removing _everything_ scc-related and installing it again:
- remove `/usr/lib/python2.7/site-packages/scc` and `/usr/lib/python2.7/site-packages/sccontroller-*.egg-info` (/usr/lib/python2.7 is your $PYTHONPATH)
- remove `/usr/share/scc/`
- re**name** ~/.config/scc
- probably even `build` directory from where SCC's `setup.py` is located

and then run python2 setup.py install

**Comment by joekm** [comment]
It's no so much getting worse. I just neglected to metion the controller hang first time around.  I did kinda suspect that maybe I was installling alongside the earlier version.  Perhaps your code runs a check for those files and moves on if it finds them without checking against latest version?  

Let me try the steps above and I'll get back ASAP.

**Comment by joekm** [comment]
Interesting.... 'echo $PYTHONPATH returns nothing.  It appears that it should be '/usr/lib/python2.7:/usr/local/lib/python2.7'  None of your files installed there, however. The following files are in /usr/local/bin

debian@pine64:/usr/local/bin$ ls
oldsc       sc-controller     scc-osd-menu
scc-daemon  scc-osd-keyboard  scc-osd-message

I manually set $PYTHONPATH and will try reinstall...

OK, re-installing after manually setting $PYTHONPATH seems to have worked.  I still got the uinput message, but the steam controller was working.  I've added the PYTHONPATH to my .profile file and am going to restart and try sc-controller.

**Comment by joekm** [comment]
OK, sc-controller works.  Still get the "uinput" message, but the controller works.  Unrelated to this project, adding the following to my .profile did not set the $PYTHONPATH env variable...

# set PYTHONPATH
PYTHONPATH="/usr/lib/python2.7:/usr/local/lib/python2.7"
export PYTHONPATH

I guess I can try putting it in my .bashrc, but I kinda think that shoulda worked.....worse comes to worst though, I'll launch it with a little shell script that checks to see if $PYTHONPATH is set.

**Comment by joekm** [comment]
^^^^no idea what made the above text big^^^^^^

**Comment by azizLIGHT** [comment]
I got the LS to stop moving the mouse with the xorg.conf section about inputclass

As for the uinput message, controller still works as configured even if its complaining about uinput

**Comment by joekm** [comment]
Current Status:

On a fresh boot, launching with "sc-controller", it gives the "uinput messge" and the controller fails to start.  However, if I un-check "Emulation Enabled" in the drop down menu (left hand side) and then re-enable it, it will work. This is a pretty repeatable behavior.

if I launch with run.sh, it yields the same behavior as above.

**Comment by kozec** [comment]
Fixed in [v0.3.0.2](https://github.com/kozec/sc-controller/releases/tag/v0.3.0.2)

**Comment by kozec** [comment]
@joekm, please, try upgrading to above version and then running _just_ scc-daemon with 

```
$ scc-daemon debug
```

and check if it reports anything interesting.

**Comment by joekm** [comment]
Output of scc-daemon debug looks pretty clean....

debian@pine64:~/sc-controller-0.3.0.3$ scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7fa2dabf10>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7fa2d3cb10>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7fa2d50450>
D SCCDaemon     Created control socket /home/debian/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0.0
D USB           USB device added: 28de:1142
D OSD DaemonCtrlr   Connected to daemon, version 0.3
D OSD DaemonCtrlr   Daemon reported profile change: /home/debian/.config/scc/profiles/Desktop.sccprofile
D OSD DaemonCtrlr   Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon

**Comment by kozec** [comment]
Except there is stuff like
```
D SCDongle      Got wireless SC with serial XYABC
D SCCDaemon     Assigned default_mapper to <SCWireless XYABC>
D SCCDaemon     Controller added: <SCWireless XYABC>
```
missing...

Question, is there any way to get system you are using in QEMU or any emulator? Because as it stands, I can't really think of any reason why should controller be registered only after daemon is restarted.
